### ISSUE TITLE
Is it possible to have multiple ContentNegotiation, separate per module?

### ISSUE THREAD

**Issue by magillus** [ktorio/ktor#1002]
### Ktor Version
1.1.2

When trying to install ContentNegotiation inside additional (not main) module:
```
install(ContentNegotiation) {
        register(ContentType.Application.Xml, MyContentConverter()) {

        }
    }
```
I have this error:
```
Caused by: io.ktor.application.DuplicateApplicationFeatureException: Conflicting application feature is already installed with the same key as `ContentNegotiation`
```
however I would like that part of the routes could by default use different content negotiation.
some API require to have XML.

The per route can be defined with help of `contentType`:
```
routing {
        contentType(ContentType.Application.Xml){
            get("/myxml/api"){
                
            }
            
        }
```
Is there way to have that configured per module, how the ContentNegotiation happens?

That would help to have modules as separate dependencies to be reused on different Ktor applications.

**Comment by magillus** [comment]
hmm.. I found that `contentType(ContentType.Application.Xml){` is not working as I expected

**Comment by magillus** [comment]
however it is still possible to define content type with:
```
call.respondText(MyXmlObjMapper.writeValueAsString(respBody), contentType = ContentType.Application.Xml)
```

**Comment by magillus** [comment]
maybe option is to have the `contentType` into `respond` method signature?:
```
call.respond(respBody**_, contentType=ContentType.Application.Xml_**)?
```

**Comment by magillus** [comment]
After digging into ContentNegotiation code I found out that when adding `Accept` HTTP header to a Json or Xml it would return the content in that type, 
if that is not defined it will use first in list of registered converted matching the `*/*` type

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-657">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Hi, since 2.0.0 it's possible to install different `ContentNegotiation` plugins for separate routes

**Comment by Ndemco** [comment]
> Hi, since 2.0.0 it's possible to install different `ContentNegotiation` plugins for separate routes

Could you explain or provide a link on how to do this? I've looked everywhere and scoured the codebase and can't find it.

**Comment by perracolabs** [comment]
@magillus Not sure if this will help you, but you can install a `ContentNavitation` within a routing scope. This has helped me to solve an issue where a third-party library also installed its own `ContentNavitation` plugin, and consequently my module raised a `DuplicatePluginException` when installing mine.
 
```kotlin
fun Application.routingModule() {

    routing {

        // The ContentNegotiation plugin is set at the routing level rather than
        // at the application level to prevent potential conflicts that could arise
        // if other libraries also attempt to install their own ContentNegotiation plugin,
        // which would result in a DuplicatePluginException.
        install(ContentNegotiation) {
            json(Json {
                prettyPrint = true 
                encodeDefaults = true
                ignoreUnknownKeys = false
            })
        }

        // Define your routes routes ....
        // ......
    }
}

```

In addition, you can also have multiple `ContentNegotiations` within your own module as long as are defined within separate scopes. In the next example a `ContentNegotiation` is set for a group of endpoints, and a second one for a concrete endpoint:

```Kotlin
fun Application.routingModule() {
    // Example having a ContentNegotiation for a group of routes.
    routing {
        install(ContentNegotiation) {
            json()
        }
        route("/") {
            get("a") { call.respond("Hello World A") }
            get("b") { call.respond("Hello World B") }
        }
    }

    // Example having a ContentNegotiation for a specific route.
    routing {
        route("/") {
            install(ContentNegotiation) {
                json()
            }
            get("c") { call.respond("Hello World C") }
        }
    }
}
```
