### ISSUE TITLE
Set decompression for client

### ISSUE THREAD

**Issue by YGromyk** [ktorio/ktor#1005]
I faced with gzip-decompression and learned, that there is no possibility to set decompression for client. I've searched in documentations and couldn't find this. For servers it can be done using [**'Enable HTTP Compression Facilities'**](https://ktor.io/servers/features/compression.html).

> Ktor Version 1.0.0
> Client, Apache
>  1.8

**Comment by e5l** [comment]
Compression would be available with next release: https://github.com/ktorio/ktor/pull/1008

**Comment by e5l** [comment]
Merged in `master`
