### ISSUE TITLE
Ktor client catch ConnectException without printing stacktrace

### ISSUE THREAD

**Issue by Tammo0987** [ktorio/ktor#1006]
### Ktor Version 
1.1.3

### Ktor Engine Used
Apache Client

### JVM Version, Operating System and Relevant Context
Java 11, Runtime Environment 18.9 (build 11+28), Windows 10

I want to catch the java.net.ConnectException, when i send a http request without printing the stacktrace. Actually i can catch it, but the stacktrace though is printed. How can i prevent it?

**Comment by e5l** [comment]
Hi @Tammo0987, thanks for the report.
Could you reproduce it with `1.2.0-alpha-1`?

**Comment by Tammo0987** [comment]
Yes, also in the 1.2.0-alpha-1 version is the caught exception printed. Also in the 1.2.0-alpha-2 version.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-655">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
Cannot reproduce it with Ktor 1.5.3
