### ISSUE TITLE
Content payloads of GET requests are inaccessible

### ISSUE THREAD

**Issue by fluidsonic** [ktorio/ktor#1012]
*ktor-server-netty 1.1.3*

The following code makes it impossible to use `GET` requests with a content payload:
https://github.com/ktorio/ktor/blob/d4e1a7caaa031fb466beb1cc102192cc88623bfe/ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1Handler.kt#L46-L48

The HTTP specification does not limit content payloads to specific HTTP methods, so `GET` request can have one as well.

Many HTTP clients support payloads for `GET` requests and Ktor should not make the assumption that `GET` request never contain one.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-653">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
Fixed by https://github.com/scope-demo/ktor/commit/6a4a78e1a243360521bcbbb3cd403b73cccd8346
