### ISSUE TITLE
[Question] Close the client and response ?

### ISSUE THREAD

**Issue by davidasync** [ktorio/ktor#1017]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Apache

### Feedback
When performing this code

`val response = client.get<HttpResponse>("https://en.wikipedia.org/wiki/Main_Page")`

Should I close the response and client ?

**Comment by cy6erGn0m** [comment]
Yes, you should.

**Comment by cy6erGn0m** [comment]
@e5l most likely we need to mention this detail about closing a response instance here: https://ktor.io/clients/http-client/calls/responses.html

**Comment by davidasync** [comment]
Waw that's pretty fast response. thanks
