### ISSUE TITLE
404 link in documentation

### ISSUE THREAD

**Issue by LouisCAD** [ktorio/ktor#1020]
This [404 link](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/src/io/ktor/client/request/builders.kt) is referenced from [this page](https://ktor.io/clients/http-client/calls/requests.html) under the text "HttpClient build extension methods".

**Comment by e5l** [comment]
Fixed here `https://github.com/ktorio/ktorio.github.io/commit/20b820aa010cb7cccfd9f77315808e483e1732a3`
