### ISSUE TITLE
404 links in MPP clients doc

### ISSUE THREAD

**Issue by LouisCAD** [ktorio/ktor#1021]
On [this page](https://ktor.io/clients/http-client/multiplatform.html), the last two links ["the iOS tasks"](https://github.com/ktorio/ktor-samples/blob/master/mpp/client-mpp/ios/build.gradle) and ["the Android ones"](https://github.com/ktorio/ktor-samples/blob/master/mpp/client-mpp/android/build.gradle) point to 404 pages.

**Comment by e5l** [comment]
Hi @LouisCAD, thanks for the report.

Fixed here https://github.com/ktorio/ktorio.github.io/commit/290242b52f271d70ec09792ad762adf2a28a1604
