### ISSUE TITLE
adding io.ktor:ktor-client-json breaks the build

### ISSUE THREAD

**Issue by ninrod** [ktorio/ktor#1023]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
server: netty
client: default

### JVM Version, Operating System and Relevant Context
java --version:
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

### Feedback

I'm trying to Install the json feature for the httpclient (I'm using the default one). 

So I added this line to my build.gradle:

```groovy
compile("io.ktor:ktor-client-json:1.1.3")
```

this brings in a cross-dependency which is called:

    org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.10.0

This dependency is not being found anywhere. All the other dependencies are being found as expected. 

When I try to gradle build my project, after adding that line, I get this error: 

```sh
backend ➜ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ninrod/code/sources/jwt/backend/build.gradle' line: 96

* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all files for configuration ':compile'.
   > Could not find org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.10.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/0.10.0/kotlinx-serialization-runtime-common-0.10.0.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/0.10.0/kotlinx-serialization-runtime-common-0.10.0.jar
       - https://kotlin.bintray.com/ktor/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/0.10.0/kotlinx-serialization-runtime-common-0.10.0.pom
       - https://kotlin.bintray.com/ktor/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/0.10.0/kotlinx-serialization-runtime-common-0.10.0.jar
     Required by:
         project : > io.ktor:ktor-client-json:1.1.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

```

If I take out that line, the project builds just fine, but I can't use the json feature for the http client.

For completeness, here's the full setup I'm using: https://github.com/ninrod/exposed-ktor

**Comment by cy6erGn0m** [comment]
This can be workarounded by adding the repository kotlinx: `maven { url "https://kotlin.bintray.com/kotlinx" }`

**Comment by cy6erGn0m** [comment]
Until we have serialization published to maven central we have to add notice about it here: https://ktor.io/clients/http-client/features/json-feature.html#kotlinx-serialization

**Comment by cy6erGn0m** [comment]
Cc @e5l

**Comment by ninrod** [comment]
@cy6erGn0m. yes, that is a valid workaround for my issue, thank you.

**Comment by e5l** [comment]
Fixed here: https://github.com/ktorio/ktorio.github.io/commit/ea8faf58db74015e7d320edd60880ef3c139fdc6
