### ISSUE TITLE
ktor-plugin UI improvement

### ISSUE THREAD

**Issue by spudro228** [ktorio/ktor#1025]
Can you mark that CIO/Apache/Jetty http client depends of HttpClient Engine?
Maybe add indent?

As a newbie I was really confused

![image](https://user-images.githubusercontent.com/20732536/54587717-fa9da880-4a31-11e9-8e2d-019f9389e2d5.png)

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-649">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
The old plugin is deprecated, we will fix this problem in the new plugin
