### ISSUE TITLE
IntelliJ ktor plugin: priority of HTML elements are too high in completion (and they are not applicable)

### ISSUE THREAD

**Issue by slavam2605** [ktorio/ktor#1026]
### Ktor Version
1.1.3

### JVM Version, Operating System and Relevant Context
JVM 8, Windows 10

### Feedback
When I want to respond with HTML I struggle with the following problem.
Consider the following code and caret position:
```
class MyData(val text: String, val id: Int)
...
val data = MyData(...)
call.respondHtml {
    body {
        div { +data.<caret> }
    }
}
```
I want to see in completion `text` and `id`. But I get all extension functions from `HTML` receiver:
![image](https://user-images.githubusercontent.com/8738347/54590648-9da5f080-4a39-11e9-8662-94f1df25c10a.png)
And properties of `MyData` below all of them. Moreover, those elements from `HTML` receiver are even not applicable, because the receiver is wrong:
![image](https://user-images.githubusercontent.com/8738347/54590744-d5ad3380-4a39-11e9-82a6-9a8e12615101.png)

So I want those elements not to be in the completion list in such case.

**Comment by e5l** [comment]
Hi @slavam2605, thanks for the report.
It looks like a kotlin-plugin issue. Could you file it here https://youtrack.jetbrains.com ?

**Comment by dmitrievanthony** [comment]
Hi @slavam2605, @e5l. I checked this scenario on the fresh version and it seems to be fixed already. I have the following completion suggestions:

<img width="656" alt="Screenshot 2020-01-17 at 11 47 33" src="https://user-images.githubusercontent.com/1028969/72597762-7d77e400-391f-11ea-94e7-6c0efbfb74f5.png">

**Comment by e5l** [comment]
Thanks @dmitrievanthony, closed
