### ISSUE TITLE
@location : Support more than one path

### ISSUE THREAD

**Issue by schleinzer** [ktorio/ktor#103]
I'd love to be able to declare several different paths to the very same location/data class using the `@location` annotation.

This would enable me to support URLs in different languages.

Example:

```kotlin
@location("/sign-up", "/registrieren") // two paths instead of one here
data class SignUpRequest(val email: String = "", val password: String = "", val name: String = "", val error: String = "")
```

**Comment by cy6erGn0m** [comment]
This design leads to a question: which url should be used in location to URL rending ?

**Comment by schleinzer** [comment]
Oh, yes, that's a good point.

The overal issue for me is the wish to support I18Ned URLs. So I will have a language id whenever I'd have to render a URL. For me, actually an index would suffice. That is, when requesting rendering of a URL, an additional Int parameter could be used to select which path to return.

**Comment by orangy** [comment]
It's an interesting use case, I never thought about it. How do you choose which URL to generate into HTML? Accept-Language? Custom subdomain like `de.example.com`? Parameter `?lang=de`?

**Comment by schleinzer** [comment]
As I am quite new to ktor (and loving it so far), could you explain in a little more detail as to when links are rendered by it? (Currently, I chose to use hard-coded ones...) Would love to help with this issue!

Thanks!

**Comment by orangy** [comment]
Sorry, missed the last question somehow. Is the question still relevant? :)

**Comment by schleinzer** [comment]
Thanks for getting back to the issue :-)

Well, for my projects I coded a custom solution, while I still think the I18N issue is relevant - but not sure if that's really something to be handled by core ktor...

So, you might close the issue at your discretion :-)

**Comment by orangy** [comment]
Can you share the main idea of your solution?

**Comment by schleinzer** [comment]
Sure! But it's rather hacky and very naive, only showing the idea :-)

Imagine you need two routes for a "forgot password" link, one English, one German:

`val lostPasswordRoute = Routes("/lost-password", "/kennwort-vergessen", autoAppendLng = false)`

That's nothing more than a list of urls, one for each language.

The `Routes` class looks like this:

```kotlin
class Routes(val routes: Map<Lng, String>) {

    constructor(vararg urls: String, autoAppendLng: Boolean = false) : this(Lng.values().associateBy({ it }) { urls[it.ordinal].run { if (autoAppendLng) "/${it.name}/$this" else this } })
    constructor(vararg routes: Pair<Lng, String>) : this(routes.toMap())

    operator fun get(lng: Lng) = routes[lng]!!

    fun alternateLinks(skip: Lng): String {
        return Lng.values().filterNot { it==skip }.joinToString(separator = "\n") {
            """<link rel="alternate" href="http://example.com${this[it]}" hreflang="$it" />"""
        }
    }
}
```

`Lng` is just an enum, with `en` and `de` (or any other languages to be supported)

Finally, to use the routes, I do

```kotlin
get(lostPasswordRoute) { ... }

post(lostPasswordRoute) { ... }
```

which are defined as

```kotlin
val lngAttributeKey = AttributeKey<Lng>("lng")
val routeAttributeKey = AttributeKey<Routes>("route")
fun Route.get(routes: Routes, body: PipelineInterceptor<Unit>) {
    routes.routes.forEach { route(HttpMethod.Get, it.value) { handle({ _ -> call.attributes.put(lngAttributeKey, call.user?.lng ?: it.key);call.attributes.put(routeAttributeKey, routes) }); handle(body) } }
}

fun Route.post(routes: Routes, body: PipelineInterceptor<Unit>) {
    routes.routes.forEach { route(HttpMethod.Post, it.value) { handle({ _ -> call.attributes.put(lngAttributeKey, call.user?.lng ?: it.key) }); handle(body) } }
}
```

I hope this makes any sense :-) ?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-830">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
