### ISSUE TITLE
Problem with websockets when deploying to a jetty server as a war

### ISSUE THREAD

**Issue by gdesantos** [ktorio/ktor#1032]
### Ktor Version

1.1.3

### Ktor Engine Used(client or server and name)

Jetty

### JVM Version, Operating System and Relevant Context

Ubuntu 18

### Feedback

Hi.
I am having problems with websockets and jetty.
Everythings works fine when execute my app as stand-alone, but when i pack the app in a war, and deploy it to an external jetty i am having problems with websockets connection.
When i open a websockets conneciton i get the following exception:

`21-Mar 08:10:55.349 ERROR - 101 Switching Protocols: GET - /api-sample/ws
java.lang.ClassCastException: org.eclipse.jetty.server.HttpConnection cannot be cast to org.eclipse.jetty.io.Connection
	at io.ktor.server.jetty.internal.JettyUpgradeImpl$performUpgrade$2.invokeSuspend(JettyUpgradeImpl.kt:25)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

I have been inspecting the code, and the problem seems to be in this file:

https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/internal/JettyUpgradeImpl.kt

In the line 25:

`val connection = servletRequest.getAttribute(HttpConnection::class.qualifiedName) as Connection`

Tries to do a cast that fails , because the connection is an HttpConnection.

**Comment by gdesantos** [comment]
Any workaround would be appreciated until the bug is solved :)
Thanks in advance for the awesome work!

**Comment by gdesantos** [comment]
No workaround avaliable?

**Comment by cy6erGn0m** [comment]
It looks like it is something about classloaders since `HttpConnection` implements `Connection` interface. When running jetty embedded server there are no custom classloaders except hot-reload classloader. 

Most likely you have packaged jetty inside of war but only ktor-server-jetty should be packed without jetty modules.

**Comment by cy6erGn0m** [comment]
Unfortunately we can't make these jetty modules _provided_ because of embedded mode. Adding two different modules doesn't look perfect as well.

**Comment by gdesantos** [comment]
Thank you for your answer.
I will check if i can solve the problem adjusting the dependences

Regards

**Comment by wooky** [comment]
If anyone in the future encounters this issue, here's what I did:

First, when packaging your WAR, exclude all the Jetty JARs. In my case, I added the exclusion `WEB-INF/lib/*-9.4.24.v20191120.jar, WEB-INF/lib/javax.*.jar`.

Next, create `src/main/webapp/WEB-INF/jetty-web.xml` with the contents:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
    <Call name="addServerClass">
        <Arg>-org.eclipse.jetty.</Arg>
    </Call>
</Configure>
```
This will allow the classloader to load all (and I do mean all) Jetty JARs. Afterwards your websockets servlets should work.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-645">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
