### ISSUE TITLE
Can not log MDC with exceptions

### ISSUE THREAD

**Issue by Colins-Git** [ktorio/ktor#1033]
### Feedback

I am using the CallId and Call Logging features to get a ID with each log entry via MDC. 
I set it up like:

    private fun newRequestId(): String = UUID.randomUUID().toString()

    install(CallId) {
        retrieveFromHeader(HttpHeaders.XRequestId)

        generate { newRequestId() }

        verify { it.isNotEmpty() }
    }

    // This uses use the logger to log every call (request/response)
    install(CallLogging) {
        level = Level.DEBUG
        callIdMdc("request-id")
    }

For normal logs and call logs it works, but when there is an exception it does not log the MDC data. So when i go to do a search for the request-id i wont find the related exception. 
{"thread":"nettyCallPool-4-1","level":"DEBUG","loggerName":"com.ea.cls.testprj.service.stats.ProviderStatsMappingService","message":"mapping response for EntityId(statCategoryId=test) ","endOfBatch":false,"loggerFqcn":"org.apache.logging.log4j.kotlin.KotlinLogger","instant":{"epochSecond":1553209881,"nanoOfSecond":629335400},"threadId":34,"threadPriority":10,**"request-id":"903bfd30-0036-4867-961c-0f16b88f7e12"**}

{"thread":"nettyCallPool-4-1","level":"ERROR","loggerName":"ktor.application","message":"Unhandled: GET - /v1/context/abc/platform/android/test","thrown":{"commonElementCount":0,"localizedMessage":"bad","message":"bad","name":"com.ea.cls.testprj.exception.testprjException","extendedStackTrace":...,"location":"?","version":"?"}]},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1553209881,"nanoOfSecond":634360800},"threadId":34,"threadPriority":10,**"request-id":"${ctx:request-id}"**}

I am assuming because the errors are logged in DefaultEnginePipeline.kt which is after the MDC context has been torn down in the CallLogging feature. 

I added this as a workaround to log the error with MDC, but it results in duplicate logging. 

    intercept(ApplicationCallPipeline.Features) {
        try {
            proceed()
        } catch (e: Throwable) {
            val status = call.response.status() ?: "Unhandled"
            logger.error("Exception at: $status: ${call.request.toLogString()}", e)
            throw  e
        }
    }

**Comment by cy6erGn0m** [comment]
Fixed in 1.2.0-rc2
