### ISSUE TITLE
Binary content support in tests

### ISSUE THREAD

**Issue by MOZGIII** [ktorio/ktor#1034]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Test engine

### JVM Version, Operating System and Relevant Context
`Linux`, `OpenJDK 8`

### Feedback

I have a server that I need to test, it returns binary response.
This is a simplified sample test code:

```kotlin   
val goldenResult = testResourceLoader.load("/golden_result.bin")
withTestApplication(Application::module) {
    with(handleRequest(HttpMethod.Post, "/")) {
        response.status().shouldBe(HttpStatusCode.OK)
        response.content.shouldBe(goldenResult)
    }
}
```

Here the second assertion fails, and the reason is that despite the application code is correct (I can perform an actual request and compare the results manually), the value stored at `response.content` is not the expected result.
I dumped the value of `response.content`, and it's mangled. I suppose it's because my content is binary, and the `response.content` is a `String`.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-644">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
You can use `byteContent` property to get body of a response as a binary:
```kt
@Test
fun test() {
    withApplication {
        application.routing {
            get("/") {
                call.respondBytes { byteArrayOf(1, 2, 3) }
            }
        }
        handleRequest(true) {}.let { call ->
            assertEquals(HttpStatusCode.OK, call.response.status())
            assertTrue(byteArrayOf(1, 2, 3).contentEquals(call.response.byteContent))
        }
    }
}
```
