### ISSUE TITLE
Failed resolution of: Lio/ktor/client/HttpClientJvmKt

### ISSUE THREAD

**Issue by philmitchell** [ktorio/ktor#1039]
### Ktor Version
1.1.3
### Ktor Engine Used(client or server and name)
mpp clients
### JVM Version, Operating System and Relevant Context
Android/iOS mpp project. For Android, target is a jarfile consumed in a separate app. On iOS, it's a framework.
### Feedback

I have a kotlin multiplatform project targeting Android and iOS and recently integrated ktor so that the shared library can load web resources. It's working on iOS, but on Android I get this error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/HttpClientJvmKt`

I am coming from the iOS world, so may be doing something dumb. The documentation is confusing on several fronts:

1. The [Ktor mpp client docs](https://ktor.io/clients/http-client/multiplatform.html) state that a shared lib should use `ktor-client-core` but the `mpp-client` sample uses `ktor-client-android`.

2. The [Kotlin mpp docs](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#android-support) direct us to use `com.android.library` plugin with the `android` preset, but the IntelliJ project wizard generates a gradle file using the `jvm` preset for the shared mobile library case.

(Probably neither of these issues affects the fact that at runtime `HttpClient` isn't resolving. However, we really need a sample ktor project for the common situation of a shared mobile library -- not just a sample of two apps.)

The gist of my `build.gradle is:
```
apply plugin: 'kotlin-multiplatform'
apply plugin: 'kotlinx-serialization'

repositories {
    google()
    jcenter()
    maven { url "https://kotlin.bintray.com/kotlinx" }
}

kotlin {
    targets {
        ... iOS targets ...

        fromPreset(presets.jvm, 'android')
    }

    sourceSets {
        commonMain.dependencies {
            implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
            implementation "io.ktor:ktor-client-core:$ktor_version"
            implementation "io.ktor:ktor-client-json:$ktor_version"
            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
        }

        androidMain.dependencies {
            implementation 'org.jetbrains.kotlin:kotlin-stdlib'
            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
            implementation "io.ktor:ktor-client-core:$ktor_version"
            // implementation "io.ktor:ktor-client-core-jvm:$ktor_version"
            // implementation "io.ktor:ktor-client-android:$ktor_version"
            // implementation "io.ktor:ktor-client-okhttp:$ktor_version"
            implementation "io.ktor:ktor-client-json-jvm:$ktor_version"
        }

        ... iOS dependencies ...

        ... test dependencies ...
    }
}
```

**Comment by philmitchell** [comment]
SOLUTION: I needed to repeat a bunch of `ktor` and `kotlinx` dependencies in the Android app (and then exclude a bunch of `META-INF` files using `packagingOptions` clause. 

Obviously, this is a novice mistake, but I hope the documentation issues mentioned above can be worked out. Thanks!

**Comment by s6joui** [comment]
For those looking for a more precise solution, here is what we added to the `build.gradle` file

```
android {
    packagingOptions {
        exclude 'META-INF/kotlinx-io.kotlin_module'
        exclude 'META-INF/atomicfu.kotlin_module'
        exclude 'META-INF/kotlinx-coroutines-io.kotlin_module'
        exclude 'META-INF/kotlinx-coroutines-core.kotlin_module'
    }
}

dependencies {
    implementation "io.ktor:ktor-client-android:$ktor_version"
    implementation "io.ktor:ktor-utils-jvm:$ktor_version"
    implementation "io.ktor:ktor-client-logging-jvm:$ktor_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serializer_version"
}
```

**Comment by tudorppp** [comment]
> For those looking for a more precise solution, here is what we added to the `build.gradle` file
> 
> ```
> android {
>     packagingOptions {
>         exclude 'META-INF/kotlinx-io.kotlin_module'
>         exclude 'META-INF/atomicfu.kotlin_module'
>         exclude 'META-INF/kotlinx-coroutines-io.kotlin_module'
>         exclude 'META-INF/kotlinx-coroutines-core.kotlin_module'
>     }
> }
> 
> dependencies {
>     implementation "io.ktor:ktor-client-android:$ktor_version"
>     implementation "io.ktor:ktor-utils-jvm:$ktor_version"
>     implementation "io.ktor:ktor-client-logging-jvm:$ktor_version"
>     implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serializer_version"
> }
> ```

You literally saved my life! yes, indeed. you need to declare these dependencies ( not all of them, but I think the ones you also have in your KMM project ) in your ANDROID project! not in the KMP library.

**Comment by raphael-dario** [comment]
@philmitchell  Hi. I ran into the same problem, generating a project structure for a KMM library from Android Studio, and following the guide.
On the Android app module, I need to add these dependencies:
```
    implementation("io.ktor:ktor-client-android:$ktorVersion")
    implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
```
Is there a way to embed those dependencies in the kmm compiled AAR? on iOS I didn't need to add anything else.

I don't see any reason why the android compiled library should not embed the ktor dependencies, or maybe that's how it's supposed to work?
