### ISSUE TITLE
How do you download a file using KtorClient?

### ISSUE THREAD

**Issue by lamba92** [ktorio/ktor#1054]
Say you have served the files from Ktor server with:
```
static {
    files("someFolder")
}
```
How do you retrieve one using the client and how to listen to the status?

**Comment by e5l** [comment]
Hi @lamba92.
You could check the sample here: https://ktor.io/samples/other/client-tools.html

**Comment by lamba92** [comment]
Great :) A bit cumbersome in my opinion. Now how do you track the status of the download?

**Comment by e5l** [comment]
You could replace `call.response.content.copyAndClose` with a chunk-by-chunk copy for loop and add the counter.

**Comment by e5l** [comment]
Closed. Please reopen if the problem is active.

**Comment by mbunderline76** [comment]
> Hi @lamba92. You could check the sample here: https://ktor.io/samples/other/client-tools.html

there is no sample that downloads file with ktor client !
