### ISSUE TITLE
Double contentLength in request [android httpClient]

### ISSUE THREAD

**Issue by jershell** [ktorio/ktor#1060]
### Ktor Version
1.1.2
### Ktor Engine Used(client or server and name)
HttpClient
```
implementation "io.ktor:ktor-client-android:$ktor_version"
```
```
val client = HttpClient()

        val call = client.call {
            body = TextContent(query, ContentType.Application.Json)
            url.takeFrom(apiUrl)
            method = HttpMethod.Post
            header("Accept", ContentType.Application.Json)
        }
```
```
```
### JVM Version, Operating System and Relevant Context
android 4.2 - reproduced
android 8.1 - not reproduced

### Feedback
wireshark

![image](https://user-images.githubusercontent.com/1238301/55636734-2e1b5980-57cc-11e9-813b-6ed59600623b.png)

**Comment by e5l** [comment]
Hi, @jershell. Thanks for the report. It looks like the `Android` specific problem. Could you reproduce it with the `okhttp` client engine?

**Comment by jershell** [comment]
@e5l
If i use ktor-okhttp (engine based on OkHttp) - reproduced
if i use only okhttp client - not reproduced
wireshark
![image](https://user-images.githubusercontent.com/1238301/55655198-325f6b00-57fc-11e9-9d4a-f4897cdad8db.png)

**Comment by jershell** [comment]
i`m not sure

https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-android/jvm/src/io/ktor/client/engine/android/AndroidClientEngine.kt

![image](https://user-images.githubusercontent.com/1238301/55660527-90497e00-580f-11e9-88c5-4bf29f9c16bb.png)

The addRequestProperty() not overwrite existing values. Therefore the setRequestProperty() will better

**Comment by jershell** [comment]
Is there any news of this trouble?
