### ISSUE TITLE
[Question] Ability to use effective low level serialization/deserialization

### ISSUE THREAD

**Issue by imanushin** [ktorio/ktor#1067]
### Ktor Version
1.1.3

### Ktor Engine Used
client, default engine

### JVM Version, Operating System and Relevant Context
Java 11

### Feedback
Could you please help, do you have ability to have stream-like serialization/deserialization (line in Spring Flux)?

How it can work for get response parsing (just example):
* Ktor client does connection and start receiving binary data
* Low level client creates ReceiveChannel<java.nio.ByteBuffer>
* Serializer (json, protobuf - this does not matter) receives Channel and start observing it
* After each block receiving, Deserializer constructs part of object
* After final block receiving, Deserializer does final object building and return the result

Pros of this method:
* Deserializer works directly with Byte Buffer (instead array/string allocations). So: **less memory is needed**
* Deserialization is started before whole response is received. It means that you don't need to hold whole response buffer in the operating memory. So: **less memory is needed, response can be processed faster**
* The same schema can be adopted for serialization purpose

Cons:
* This method is not compatible with popular libraries. Just Spring has the same concept ([see details here](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#codecs)).
* This method is more complex for coding than existing ones

**Comment by e5l** [comment]
Hi @imanushin, thanks for the report. We don’t support such thing for now. 
Can you tell me if you have an idea?

**Comment by imanushin** [comment]
@e5l, I think we can close this topic, because:
* Looks line noone (even Spring, [see proof](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/codec/json/AbstractJackson2Encoder.java#L130)) does not do serialization/deserialization on fly. All implementations collect buffer and does operation with prepared stream.
* Theoretically serializers can operate with ```ByteReadChannel``` directly. In this case they can:
   * Subscribe on this channel
   * On new portion of data receive: construct part of object 
   * If end of channel received - return constructed object

**Comment by e5l** [comment]
Thanks for the investigation. It probably could be the solution(complex but still valid), but we should setup the benchmarks before any optimization :) 

Closed. Please reopen if any status updates.
