### ISSUE TITLE
[Feature] Add ability to read attributes set on a HttpRequestBuilder

### ISSUE THREAD

**Issue by Ribesg** [ktorio/ktor#1068]
This issue is a **feature request** for the ktor **client** version **1.1.3**.

Currently there is no way to get attributes set on a `HttpRequestBuilder`.
We can only set attributes on the builder by passing a function that will be executed to populate the `Attributes` instance in `HttpRequestBuilder.build()`.

There is no way to retrieve the attributes set this way, as they're not stored in a retrievable data structure, but rather wrapped inside a bunch of nested functions.

We can't just call `.build()` on the builder and then get the attributes because of the `HeadersBuilder` which can only be called once for some reason.

**Comment by e5l** [comment]
Merged in master. Available in `1.2.0-rc`
