### ISSUE TITLE
Ktor Client renders cookie colon symbol (e.g. ':') to %3A

### ISSUE THREAD

**Issue by imanushin** [ktorio/ktor#1069]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
default

### JVM Version, Operating System and Relevant Context
11, win 7

### Feedback
Ktor client escaped colon symbol (and several else). As a result: in some cases client breaks cookie.

**Precondition:**
* Django Python server
* Ktor client with ```HttpCookies``` feature

**Steps to reproduce:**
* Ktor client does application request (for example: ```GET /api/users```)
* Django server answers: 401 Unauthenticated + some cookie (for anonymous user)
* Ktor client does request with authentication like ```POST /api/login``` with custom headers
* Django server returned anonymous cookie (the same from previous step) and new cookie, delimited by colon. Header ```SetCookie``` example: ```myServer=somePreviousCookie:newCookie```
* Ktor client repeats application request (from example: ```GET /api/users```) with cookie above

**Expected result**
Ktor client attaches the following Cookie header: ```myServer=somePreviousCookie:newCookie```

**Actual result:**
Ktor client executes ```renderClientCookies```, so value will be like this: ```myServer=somePreviousCookie%3AnewCookie```. E.g. symbol ```:``` is replaced to ```%3A```

**Workaround**
Write cookie header manually for such web sites

Also: from my point of view it will be useful if ```HttpCookies``` feature will have simple ability to patch cookie value.

**Comment by e5l** [comment]
Hi @imanushin, thanks for the report. 

Probably we could relax escaping rules and follow: https://stackoverflow.com/questions/1969232/allowed-characters-in-cookies
