### ISSUE TITLE
"Create New Project" not working in IntelliJ 2019.1 when Ktor plugin enabled.

### ISSUE THREAD

**Issue by mumsbistro** [ktorio/ktor#1071]

**Comment by e5l** [comment]
Relates to: https://github.com/ktorio/ktor-init-tools/pull/10

**Comment by poloynikov** [comment]
Same problam, i unistall and install 1.1.3 and it is all fine :)

**Comment by alfianyusufabdullah** [comment]
> Same problam, i unistall and install 1.1.3 and it is all fine :)

This is work for me to :+1:

**Comment by cy6erGn0m** [comment]
Fixed in 1.1.4.1
