### ISSUE TITLE
Setup subdomain 

### ISSUE THREAD

**Issue by mancj** [ktorio/ktor#1077]
### Ktor Version
1.1.3
### Ktor Engine Used(client or server and name)
ktor-server-netty
### JVM Version, Operating System and Relevant Context
JDK 10, Mac OS

I have setup subdomain `api.example.com`, and now i want my application to handle only this URL. What i need to do to setup ktor for this purpose? I'm new to server development, so im sorry if my question is too stupid :))

**Comment by cy6erGn0m** [comment]
Use `host` route builder

```
routing {
    host("api.example.com") {
        // REST
    }
    host("example.com") {
        // web
    }
}
```

**Comment by cy6erGn0m** [comment]
Please note that for servlet containers it is required to configure a servlet container itself. 

Tomcat:
- https://tomcat.apache.org/tomcat-9.0-doc/virtual-hosting-howto.html
- https://wiki.apache.org/tomcat/TomcatDevelopmentVirtualHosts

Jetty:
- https://www.eclipse.org/jetty/documentation/9.4.x/configuring-virtual-hosts.html
