### ISSUE TITLE
How to hook into HttpRequestPipeline Pipeline for tracing

### ISSUE THREAD

**Issue by ssp** [ktorio/ktor#1087]
### Ktor Version
1.1.

### Ktor Engine Used(client or server and name)
Apache client

### JVM Version, Operating System and Relevant Context
1.8

### Feedback
I wanted to create a ktor http client that supports tracing (using opencensus). To do that I have to insert headers with the current span ID into every request and gather the request’s result to hand to the tracing library.

My impression is that I should intercept some pipeline to do that. Opening my span before the http request starts and closing it when the request is done. I tried out all pipeline phases I found for HttpRequestPipeline/HttpSendPipeline but I could not find a single place to intercept where I can run my code at the required times (as far as i could see I’d want to run before and after the HttpSend feature runs but I couldn’t figure out how to do that inside the same phase [later phases don’t seem to be executed on failing requests]).

Any hint on how to achieve this or whether this should be done in a different way is appreciated.

Thanks!

**Comment by e5l** [comment]
Hi @ssp, thanks for the report.

The best approach to intercept request and response is `HttpSend` feature itself. You could look at the example in `HttpRedirect` feature:
https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt

**Comment by ssp** [comment]
Thanks a lot for this hint @e5l ! I wasn’t aware I can intercept the HttpSend feature at all. This feels like the right thing to do.

I gave it a try and it turned out that it does not have the desired effect: my interceptor’s code is only run after the http request has finished (meaning I do get the result, but do not get timing information). Looking at the code suggests that interceptors in HttpSend are called only after the execute call has finished and I do not get the opportunity to do before/proceed()/after processing as I can in a pipeline.
