### ISSUE TITLE
Incorrect URL encoding for some characters

### ISSUE THREAD

**Issue by Vantuz** [ktorio/ktor#1094]
### Ktor Version

1.1.5

### Ktor Engine Used(client or server and name)

- ktor-server-netty
- ktor-client-apache

### JVM Version, Operating System and Relevant Context

OpenJDK 1.8.0_191, Ubuntu 16.04

### Feedback

```kotlin
val kek = URLBuilder("https://upload.wikimedia.org/wikipedia/commons/9/9c/University_of_Illinois_at_Urbana–Champaign_logo.svg")
println(kek.encodedPath)
// /wikipedia/commons/9/9c/University_of_Illinois_at_Urbana%13Champaign_logo.svg
// expected: /wikipedia/commons/9/9c/University_of_Illinois_at_Urbana%E2%80%93Champaign_logo.svg

val client = HttpClient(Apache)
val imageResp = client.call("https://upload.wikimedia.org/wikipedia/commons/9/9c/University_of_Illinois_at_Urbana–Champaign_logo.svg").response
println(imageResp.status) // 404 Not Found, expected: 200 OK
```

**Comment by Vantuz** [comment]
Seems that it needs to be fixed here: https://github.com/ktorio/ktor/blob/master/ktor-http/common/src/io/ktor/http/Codecs.kt#L78

```kotlin
append(current.toByte().percentEncode())
```

This works incorrectly for 2-byte characters like ['EN DASH' (U+2013)](https://www.fileformat.info/info/unicode/char/2013/index.htm)

**Comment by e5l** [comment]
Hi, @Vantuz. Thanks for the report

lgtm. Could you make PR? :)

**Comment by Vantuz** [comment]
@e5l I made a [PR](https://github.com/ktorio/ktor/pull/1097) with my fix for this issue. Could you review it? This bug affects my team's production code, so I would really like to resolve this as soon as possible, if it is ok with you. BTW, is there a snapshot repository with builds containing the latest changes? Our team would like to use it while stable build containing fix for this issue is being prepared

**Comment by e5l** [comment]
Merged

**Comment by Vantuz** [comment]
@e5l can you tell when will this get to master?

**Comment by e5l** [comment]
With `1.2.0`
