### ISSUE TITLE
CIO Server Engine fails for requests with more than 32 headers

### ISSUE THREAD

**Issue by supertote** [ktorio/ktor#1095]
### Ktor Version
1.1.5
### Ktor Engine Used(client or server and name)
CIO server
### JVM Version, Operating System and Relevant Context
1.8.0_131
### Feedback
When using the CIO server engine, requests with more than 32 headers are rejected with error 400 and no further diagnostic.
I used the debugger to further track the cause of this error and found that during header parsing an exception is thrown:
> kotlin.NotImplementedError: An operation is not implemented: Implement headers overflow

This is due to the following declaration in file HttpHeaderMap.kt:

> package io.ktor.http.cio
> 
> import io.ktor.http.cio.internals.*
> import io.ktor.util.*
> import kotlinx.io.pool.*
> 
> 
> private const val EXPECTED_HEADERS_QTY = 32
> 
which effectively limits the number of headers to 32.
This error does not appear with the Jetty engine.

**Comment by HeyLey** [comment]
+1

**Comment by cab404** [comment]
Upped the limit to 64 in #1481 :D

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-626">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in 1.5.2

**Comment by vvvv11221121** [comment]
Increasing the allowed number of headers from 32 to 64 is NOT really a fix!!!
Lots of enterprise clients are unable to work because of this limit. 
This has to be restructured so that map can dynamically grow to the required size as headers are added.
