### ISSUE TITLE
How do I use `skipWhen` with `SessionAuthenticationProvider`?

### ISSUE THREAD

**Issue by evanbennett** [ktorio/ktor#1098]
### Ktor Version
1.1.5
### Ktor Engine Used(client or server and name)
Netty server
### JVM Version, Operating System and Relevant Context
OpenJDK 11.0.2+9, Windows 10
### Feedback
I have been trying to work out how to use the Authentication providers. I have been unable to work out how to use `skipWhen` with the `SessionAuthenticationProvider`.

The other providers have a `fun Authentication.Configuration.???(name: String? = null, configure: ???AuthenticationProvider.() -> Unit)` extension function, but this one has `inline fun <reified T : Any> Authentication.Configuration.session(name: String? = null, configure: SessionAuthenticationProvider.Configuration<T>.() -> Unit)`. Note the `.Configuration` after `SessionAuthenticationProvider`.

Am I missing something, or is this functionality not available for `SessionAuthenticationProvider`?

**Comment by cy6erGn0m** [comment]
Yes, it looks like `skipWhen` is missing for session auth provider

**Comment by cy6erGn0m** [comment]
Available in 1.2.0-rc2

**Comment by evanbennett** [comment]
Thanks.
