### ISSUE TITLE
What redirect URL the OAuth feature uses?

### ISSUE THREAD

**Issue by lamba92** [ktorio/ktor#1099]
I mean, i made it work but I've not specified anywhere the redirect uri for the authorization token. How can it even work? 
I've used the example on the documentation

**Comment by cy6erGn0m** [comment]
It should be `urlProvider` specified but it is likely that the feature may handle any url under authenticate route. So it probably works because you have redirect url specified in OAuth server.

**Comment by lamba92** [comment]
Could you elaborate?

**Comment by Wicpar** [comment]
The urlProvider generates the redirect once authorize has been called, and appends the code/state as query. In my case i have set it to a callback that extracts them and sends a message to retry the request with the code and state.

with redirectUrl = ```http://localhost/callback```

calling protected endpoint `http://localhost/endpoint` does
```http://localhost/oauth/authorize?[...]```
does `HTTP 302` with location
```http://localhost/callback?code=<code>&state=<state>```
and on my side the callback does:
```{retry: true, code: <code>, state: <state>}```
and the client retries the request with the parameters
```http://localhost/endpoint?code=<code>&state=<state>```

**Comment by Stexxe** [comment]
@lamba92 do you still have a problem with a redirect URL?

**Comment by lamba92** [comment]
Unfortunately I do not work on that project anymore and I remember very little about it!
