### ISSUE TITLE
Cannot debug ktor call

### ISSUE THREAD

**Issue by spyro2000** [ktorio/ktor#1103]
### Kotlin-Version

1.3

### Kotlin-Plugin

v1.3.31-release-I2019.1-1

### IntelliJ-Version

2019.1.1

### Ktor Version

1.1.4.1

### Ktor Engine Used(client or server and name)

Netty

### JVM Version, Operating System and Relevant Context

JVM 1.8, Windows 10 x64 Pro

### Feedback

I just started a simple Ktor app and set a breakpoint. But it seems I cannot debug or evaluate the interesting items:

![image](https://user-images.githubusercontent.com/8479925/57286939-b1271c80-70b6-11e9-89fc-20dd2ff1b4fa.png)

Seems like the Kotlin Debugger just has no idea what is going on and totally messes up the Scope?

If I am not able to debug my code and evaluate expressions (like inspecting the headers of the request or something) this is an instant no-go for me :(

Is there any special setting needed to make this work?

Thank you!

**Comment by cy6erGn0m** [comment]
This is kotlin debugger [issue KT-31361](https://youtrack.jetbrains.com/issue/KT-31361).

**Comment by cy6erGn0m** [comment]
Fixed in 1.2.2 with kotlin 1.3.40
