### ISSUE TITLE
CIO client fails and won't recover

### ISSUE THREAD

**Issue by akleiman** [ktorio/ktor#1106]
### Ktor Version
1.1.2 and 1.1.4
### Ktor Engine Used(client or server and name)
CIO Client
### JVM Version, Operating System and Relevant Context
JVM 8.0.202-amzn and 11.0.2-zulufx
OS Linux Ubuntu 19.04 Kernel 5.0.0-13 Generic
### Feedback
I've added a gist with sample code that reproduces the usecase 100% of the time:
https://gist.github.com/akleiman/260e20757705b4c89e198c9a314f9531
The number of iterations vary; sometimes it's 6, sometimes it's 12 or 18, but it never finishes executing.

After the exception occurs the client is for all intents and purposes dead, it won't do anything but throw `JobCancellationException`. I haven't been able to nail down what the problem is, but there seems to be some problem when negotiating TLS that the client can't recover from.

This originally occurred within a running Ktor server but I was able to isolate it to the sample code.

When I'm able to place a breakpoint, the underlying cause is: `kotlinx.coroutines.channels.ClosedReceiveChannelException: EOF: one byte required`, but it doesn't seem entirely deterministic -- I've seen it happen in multiple methods of `io/ktor/network/tls/Parser.kt`

**Comment by e5l** [comment]
Hi @akleiman, thanks for the report.
The issue should be fixed in `1.2.0-rc`. Could you check it?

**Comment by akleiman** [comment]
I've run my test a few times and so far haven't been able to reproduce, looking good.

**Comment by akleiman** [comment]
Is there an in-progress changelist for 1.2.0?

**Comment by e5l** [comment]
Awesome. We fixed some issues with the same report.
Closed.

**Comment by akleiman** [comment]
Actually, testing this solution out some more, the problem with the endpoint not recovering was solved, but something seems to be slowing down the client calls. Sometimes the CIO client takes over 30s to respond, and multi-second responses are common, even beyond the 3s connect timeout. 

I swapped out the engine for Apache client and didn't see any of these issues; not sure if this is a regression, or if there's more behind this problem.
Apache client: 
```val http = HttpClient(Apache) {

        expectSuccess = true

        engine {

            connectTimeout = 3000
            connectionRequestTimeout = 500

            customizeClient {
                setMaxConnTotal(500) // Maximum number of socket connections.
                setMaxConnPerRoute(1000) // Maximum number of requests for a specific endpoint route.
            }
        }
    }```

CIO client:
```val http = HttpClient(CIO) {

        expectSuccess = true

        engine {
            endpoint.apply {
                maxConnectionsPerRoute = 500
                maxConnectionsCount = 1000
                connectTimeout = 3000
                connectRetryAttempts = 1
            }
        }
    }```

Not sure if this is worth reopening this issue or opening a new one. Using `1.2.0-rc` for both clients.
