### ISSUE TITLE
KotlinxSerializer not found in 1.2.0-rc

### ISSUE THREAD

**Issue by brewin** [ktorio/ktor#1109]
### Ktor Version
1.2.0-rc, 1.2.0-rc2
### Ktor Engine Used(client or server and name)
Android client
### Feedback
I see that `KotlinxSerializer` was moved to `ktor-client-serialization`. But even after adding that, the `io.ktor.client.features.json.serializer` package is unresolved.

**Comment by brewin** [comment]
Never mind. It's in `ktor-client-serialization-jvm`.

**Comment by TWiStErRob** [comment]
Can we reopen this? It needs work!

1. https://ktor.io/clients/http-client/features/json-feature.html references `ktor-client-json-jvm` which is not enough to use KotlinxSerializer
2. ktor-client-serialization is published for each new build (I'm using `1.2.1-1.3.40-eap-67`), even though it's empty

**Comment by ShoMasegi** [comment]
@TWiStErRob 

```
dependencies {
....
    implementasion "io."io.ktor:ktor-client-serialization-jvm:$versions.ktor"
....
}
```
https://ktor.io/clients/http-client/features/json-feature.html is wrong.

**Comment by TWiStErRob** [comment]
Yep, found it, thanks!

@e5l @cy6erGn0m I really wonder now why ktor-client-serialization artifact exists without any classes?

**Comment by diklimchuk** [comment]
For multiplatform projects you can use
```
dependencies {
          ....
    implementation "io.ktor:ktor-client-serialization:$versions.ktor"
          ....
}
```
Dit it for me
