### ISSUE TITLE
Websocket feature does not fully clean itself up on client close

### ISSUE THREAD

**Issue by serebit** [ktorio/ktor#1110]
### Ktor Version
1.2.0-rc, and previous versions as well.
### Ktor Engine Used(client or server and name)
CIO client
### JVM Version, Operating System and Relevant Context
OpenJDK 1.8.0_192 on Solus (Linux distribution)
### Feedback
One of my projects, which uses Ktor's websockets, has a feature wherein sockets are opened and closed periodically. When a signal is received, the HttpClient that runs the sockets is closed, and all resources managed by the program itself are released. Despite this, the program does not exit. When the coroutines are dumped post-resource-release (using the coroutines debug utility), the trace contains several coroutines with no origin in any of my code, and some with an origin in my code and which originate from a `wss` call. Some are suspended, some are active, and it takes several minutes for all of the coroutines to stop and for the program to finally exit. Here is the full coroutines dump after all resources are cleaned up: https://hastebin.com/xevakaqulo

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-625">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
