### ISSUE TITLE
Active websockets should send close frame on SIGINT

### ISSUE THREAD

**Issue by serebit** [ktorio/ktor#1111]
### Ktor Version
1.2.0-rc
### Ktor Engine Used(client or server and name)
CIO (client)
### JVM Version, Operating System and Relevant Context
1.8.0_192 on Solus (Linux distribution)
### Feedback
When an exit signal is received on a JVM process using Ktor websockets, any active websockets silently terminate, and the remote server is left waiting for a response that will never come. Ideally, Ktor should send close frames on any active websockets before fully exiting, or should be configurable to allow it to do so.

**Comment by cy6erGn0m** [comment]
Stopping server should cause close frames to be sent for all sessions. So it should be something like this

```kotlin
val server = embeddedServer(Jetty/Netty, ...) { ... }
Runtime.getRuntime().addShutdownHook ( ... {
    server.stop(...)
})
server.start(wait = true)
```

I am not sure that we should do it by default...

**Comment by serebit** [comment]
I was mostly referring to clients. Shutdown hooks work well enough for JVM, but by my understanding, websockets will have implementations in kotlin/native in the future. Kotlin/native has no way to add a non-static and capturing shutdown hook like Kotlin/JVM does, so this method of sending close frames on exit isn’t possible in common code. Even if it isn’t the default, I think that adding a common way to enable sending close frames on process exit would go a long way.

**Comment by cy6erGn0m** [comment]
Well, mpp shutdown hooks is a special subject for something like kotlinx.os (doesn't exist yet). Perhaps we can introduce a temporary helper in ktor

**Comment by serebit** [comment]
That would be greatly appreciated, if you’re willing to implement such a feature (even if temporarily).

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-624">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
