### ISSUE TITLE
documentation for https://ktor.io/clients/http-client/calls/requests.html#shortcut-methods

### ISSUE THREAD

**Issue by bjonnh** [ktorio/ktor#1113]
The link to:
https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/src/io/ktor/client/request/builders.kt

In section "The get, post, put, delete, patch, head and options methods"
returns 404.

**Comment by e5l** [comment]
The link fixed in `1.2.0` and will be updated with the release

**Comment by e5l** [comment]
Fixed.
