### ISSUE TITLE
CIO client pausing for long time (30s) during requests

### ISSUE THREAD

**Issue by akleiman** [ktorio/ktor#1115]
### Ktor Version
1.2.0-rc
### Ktor Engine Used(client or server and name)
CIO Client (and Apache engine for comparison)
### JVM Version, Operating System and Relevant Context
JVM 8.0.202-amzn and 11.0.2-zulufx
OS Linux Ubuntu 19.04 Kernel 5.0.0-13 Generic
### Feedback

Further testing out `1.2.0-rc` to see if it had really solved #1106, I came upon a possible regression: using the same [test code](https://gist.github.com/akleiman/260e20757705b4c89e198c9a314f9531) would have the client seemingly pause, sometimes for over 30s (and often for more than 5s) while executing a request. To make sure that this wasn't an issue with the endpoint I swapped in the Apache engine and it ran smoothly (other non-Ktor clients also ran without large delays).

Apache client: 
```
val http = HttpClient(Apache) {

        expectSuccess = true

        engine {

            connectTimeout = 3000
            connectionRequestTimeout = 500

            customizeClient {
                setMaxConnTotal(500) // Maximum number of socket connections.
                setMaxConnPerRoute(1000) // Maximum number of requests for a specific endpoint route.
            }
        }
    }
```

CIO client:
```
val http = HttpClient(CIO) {

        expectSuccess = true

        engine {
            endpoint.apply {
                maxConnectionsPerRoute = 500
                maxConnectionsCount = 1000
                connectTimeout = 3000
                connectRetryAttempts = 1
            }
        }
    }
```

I tested a `withTimeout {}` block to simulate Apache client's `connectionRequestTimeout`, but that just made the CIO client fail almost every single execution.

_Originally posted by @akleiman in https://github.com/ktorio/ktor/issues/1106#issuecomment-491001514_

**Comment by akleiman** [comment]
I tested this out on 1.2.1, it seems to be fixed. Do you have any idea what might have caused/fixed it?

**Comment by e5l** [comment]
The issue was related to https and random utilization. We used blocking random utilization.

Thanks for the testing. Closed
