### ISSUE TITLE
how to get responsed message from server while get BadResponseStatusException

### ISSUE THREAD

**Issue by creatxrgithub** [ktorio/ktor#1117]
### server has response message even if status code > 300

```
{
    "errcode": "M_NOT_JSON",
    "error": "Content not JSON."
}

```
i try the codes below:

```
       try {
            result = client.post<String>(HOME_SERVER_URI + API_POST_LOGIN) {
                body = req
            }
        } catch (e: BadResponseStatusException) {
            println(e.statusCode)
            println(e.response)
            println(e.message)
            println(result)
            println("aaaaaaaaaaaaaaaaaaaaaaaaaaaa")
        }
```
i cannot get the response message.

if i use curl command in terminal window , i could get it.

**Comment by SergioIgreja** [comment]
Did you find a solution for this? I also have information in the body of a failed request that I want to return to a user.

**Comment by creatxrgithub** [comment]
@SergioIgreja

just add "expectSuccess = false" options

read code above
