### ISSUE TITLE
java.lang.BootstrapMethodError when using ktor-client-okhttp 1.2.0-rc2

### ISSUE THREAD

**Issue by LiewJunTung** [ktorio/ktor#1118]
### Ktor Version
1.2.0-rc2

### Ktor Engine Used(client or server and name)
Client Okhttp

### JVM Version, Operating System and Relevant Context
Kotlin 1.3.31
Multiplatform
Android

### Feedback
java.lang.BootstrapMethodError: Exception from call site #4 bootstrap method

#### Gradle import
<img width="874" alt="Screenshot 2019-05-13 at 10 09 27 AM" src="https://user-images.githubusercontent.com/4220976/57592060-3b63fa80-7567-11e9-8e72-11dd526e975a.png">

#### Code
<img width="710" alt="Screenshot 2019-05-13 at 10 06 59 AM" src="https://user-images.githubusercontent.com/4220976/57591994-ddcfae00-7566-11e9-944a-65edd5acdee4.png">

#### Error 
<img width="885" alt="Screenshot 2019-05-13 at 10 07 37 AM" src="https://user-images.githubusercontent.com/4220976/57592017-f770f580-7566-11e9-99a8-8cc061ffcc3a.png">

**Comment by cy6erGn0m** [comment]
This is not ktor-related issue. Since okhttp 3.13.0 requires java8 to be enabled in the android build. See  https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3130 and https://github.com/square/okhttp/issues/4597
