### ISSUE TITLE
Publish on Maven Central

### ISSUE THREAD

**Issue by giflw** [ktorio/ktor#112]
Hi.

There are plans to publish on Maven Central? There are limitations on my organization to reach other maven repositories.

Regards

**Comment by orangy** [comment]
Most likely when it reaches 1.0

**Comment by orangy** [comment]
It's now available through jcenter, too.

**Comment by luengnat** [comment]
@orangy is there a problem with jcenter setting?

http://jcenter.bintray.com/io/ktor/ktor-http

said "The requested path was not found."
