### ISSUE TITLE
Raw sockets with ios

### ISSUE THREAD

**Issue by aaajiekc** [ktorio/ktor#1121]
### Ktor Version
1.1.4
### Ktor Engine Used(client or server and name)
Sockets
### Feedback
I am trying to move the general logic of using upd sockets (android, ios) to kotlin/native project.
I added "io.ktor:ktor-network:1.1.4" dependency to commonMain but I can't use sockets in common code. At the same time, I can see sockets in jvmMain. I tried different versions and different packages(-tls, -metadata etc), all without results.

Do I understand correctly that using 'ktor-network' is only possible for an android project at the moment? Or am I missing something... 
Thank you!

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-622">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Raw socket is supported in iOS since 1.4.0
