### ISSUE TITLE
The beginning character of endodedPath field(Url class) is wrong when relative path

### ISSUE THREAD

**Issue by doyaaaaaken** [ktorio/ktor#1123]
### Ktor Version

1.1.3

### Ktor Engine Used(client or server and name)

server (Netty)

### JVM Version, Operating System and Relevant Context

java 1.8.0_201
MacOS 10.14.4

### Feedback

When I set relative path to Url class constructor, the beggining slash is toggled like below.
```
Url(“/hoge“).encodedPath=“hoge”
Url(“hoge“).encodedPath=“/hoge”
```

I think the beggining slash is retained like below.
```
Url(“/hoge“).encodedPath=“/hoge”
Url(“hoge“).encodedPath=“hoge”
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-621">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
