### ISSUE TITLE
Option to set custom timeout for request

### ISSUE THREAD

**Issue by WaffleLapkin** [ktorio/ktor#1134]
### Ktor Version
`1.2.0`

### Ktor Engine Used(client or server and name)
`CIO` client

### Feedback
Is it possible to set a custom timeout for _request_, not _client_? Something like
```kotlin
client.call("url", timeout = 20) { ... }
```
For now, I see only feature to set timeout for client: 
```kotlin
HttpClient(CIO) {
    engine { requestTimeout = 20 }
}
```

### My use case
I want to use the same client for long polling and common requests.

**Comment by rocketraman** [comment]
Yes, this is sorely needed. A workaround for now appears to be to set a very high client timeout, and then use `withTimeout` on all calls to specify a lower value. This is not very elegant though.

**Comment by martinbonnin** [comment]
@rocketraman Is it possible to set a high timeout in a mpp way ? I've seen platform specific solution such as:

```
val client = HttpClient(Apache) {
    engine {
        /**
         * Max time between TCP packets - default 10 seconds.
         */
        socketTimeout = 10_000
}
```

But I'd really like to keep my code platform agnostic as much as possible

**Comment by e5l** [comment]
Sure! It'll be possible to do with the `HttpTimeout` feature.

**Comment by rocketraman** [comment]
> Sure! It'll be possible to do with the `HttpTimeout` feature.

Being a feature, that will presumably not allow per-request timeout specs. Will using `withTimeout` at the coroutine level then be the preferred approach for specifying per-request timeouts?

**Comment by e5l** [comment]
> not allow per-request timeout

Not extact. The feature would add the extensions to the request builder.

**Comment by vandzi** [comment]
Is there any plan when this feature will be implemented? We have single ktor client instance and we need shorter timeout than 10seconds for some requests. Currently we use `withTimeout` at coroutine level but it works only in android and **not in iOS** which prevents use to use it in production.

**Comment by enleur** [comment]
Since 1.3.1 you can use [HttpTimeout](https://github.com/ktorio/ktor/commit/4644d060756f33a8190af6ae2971e2937817608e#diff-e1a82fe21813d09565dea2ecb0f77d77) feature 

https://ktor.io/clients/http-client/features/timeout.html

**Comment by AndroidPat** [comment]
Why is this not supported on iOS?

**Comment by alwyn** [comment]
I'm amazed at how many people read this request wrong.  The requirement is to set the timeout at a per request level, with different requests having different timeouts.  Using HttpTimeout is not a solution for this requirement.

**Comment by e5l** [comment]
Hey @alwyn, could you check if the `timeout` extension on the `HttpRequestBuilder` fits the use-case?https://api.ktor.io/ktor-client/ktor-client-core/io.ktor.client.request/-http-request-builder/index.html?query=class%20HttpRequestBuilder%20:%20HttpMessageBuilder#1159668160%2FFunctions%2F-1897681819

**Comment by alwyn** [comment]
Hey @e5l , it looks like it will work.  Sorry Leonid, I didn't know about this feature...

**Comment by e5l** [comment]
No problem! Thank you for bumping. We also have some docs around https://ktor.io/docs/client-timeout.html#configure_plugin :)

**Comment by alwyn** [comment]
So in my application I send async requests to 2 different urls and each has different timeout requirements.  Would I need to use 2 different client instances to make sure the timeout configurations don't fall over one another?

**Comment by rocketraman** [comment]
> Would I need to use 2 different client instances to make sure the timeout configurations don't fall over one another?

No because you can set it in the **request** builder.

**Comment by tomasjablonskis** [comment]
I have CIO and OkHttp Http engines configured with HttpTimeout plugin installed with some default values. It seems that timeout { ... } block in request builder does not override those engine HttpTimeout plugin values in KMP project. Is there a way to keep global HttpTimeout plugin installed with some predefined values and override them on per-request basis?
