### ISSUE TITLE
LockNative produces segmentation fault

### ISSUE THREAD

**Issue by arkivanov** [ktorio/ktor#1135]
### Ktor Version
1.2.0

### Ktor Engine Used(client or server and name)
None

### JVM Version, Operating System and Relevant Context
openjdk version "1.8.0_152-release"
Ubuntu 18.10

### Feedback
I was interested in ktor's implementation of [LockNative.kt](https://github.com/ktorio/ktor/blob/master/ktor-utils/posix/src/io/ktor/util/LockNative.kt) because I wanted to find a way how we can create native locks without manually freeing them every time. I copied `utils.def` and `LockNative.kt` into a test project and it suddenly does not work. It fails with segmentation fault error on `ktor_mutex_create(mutex)` call. Further investigations shown that `mutex.mutex` pointer is null.

**Comment by arkivanov** [comment]
Added a few comments to the commit. Just in case.

**Comment by e5l** [comment]
Thanks for the notice!
