### ISSUE TITLE
Allow modification of response during client "receive" interception

### ISSUE THREAD

**Issue by gregorbg** [ktorio/ktor#1139]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Client, Apache

### JVM Version, Operating System and Relevant Context
OpenJDK 11.0.3, Ubuntu 18.04
Communicating with an external enterprise-grade server

### Feedback
The remote server that our customer uses to provide services returns the `Expires` cookie in a wrong, non-standard date format. We do not have the power to convince them to change this behaviour.

It would be nice if we can intercept the "wrong" cookie and fix the formatting ourselves, so that https://github.com/ktorio/ktor/blob/68eef1948ce4c8c11dae794588f8d063afb67d0b/ktor-http/common/src/io/ktor/http/DateUtils.kt#L20 doesn't blow up.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-617">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
Fixed by https://github.com/ktorio/ktor/pull/2522. The fix will be released in version 2.0.0.
