### ISSUE TITLE
Client cache invalid date length

### ISSUE THREAD

**Issue by Thomas-Vos** [ktorio/ktor#1145]
### Ktor Version
1.2.0

### Feedback
https://github.com/ktorio/ktor/blob/5bc0448cf2c367a58284eec7bc4aa91d8c2a60de/ktor-http/common/src/io/ktor/http/DateUtils.kt#L9-L22
This code throws an exception when the date header is not the correct length. I understand why this is done, but some devices return an invalid date format. For example, the [Philips Hue bridge](http://meethue.com) returns these headers:
```
access-control-allow-credentials: true
access-control-allow-headers: Content-Type
access-control-allow-methods: POST, GET, OPTIONS, PUT, DELETE, HEAD
access-control-allow-origin: *
access-control-max-age: 3600
connection: close
content-type: application/json
date: Wed, 22 May 2019 14:26:57 GMT
expires: Mon, 1 Aug 2011 09:00:00 GMT
server: nginx
```
As you can see, the expires header misses a leading zero before the 1. This is something I cannot fix, because this is not my device. Enabling the newly introduced Ktor client cache makes it impossible for me to make requests to this device.

Could the code above be changed to also accept this expires header? I don't know if this is an issue with only the Philips Hue bridge or if more servers/devices have this.

**Comment by Thomas-Vos** [comment]
Another minor issue which is related to the new client cache: The [DisabledCacheStorage](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/common/src/io/ktor/client/features/cache/storage/DisabledChacheStorage.kt) class has a typo in the file name. (DisabledChacheStorage > DisabledCacheStorage)

**Comment by e5l** [comment]
Fix in `master`
