### ISSUE TITLE
Investigate Jetty EndpointReader idleTimeout.

### ISSUE THREAD

**Issue by e5l** [ktorio/ktor#1152]
### Ktor Version
1.2.1

### Ktor Engine Used(client or server and name)
Jetty

### Feedback
https://github.com/ktorio/ktor/blob/315e32a2374c724eebe3766c53d94645eb2f4237/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/internal/EndPointChannels.kt#L63

https://github.com/ktorio/ktor/blob/315e32a2374c724eebe3766c53d94645eb2f4237/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/internal/JettyUpgradeImpl.kt#L32

**Comment by morj** [comment]
Amazing

**Comment by cy6erGn0m** [comment]
I can fix it and make Jetty know about an upgrade but it looks like it makes no big difference except for few invocations that do nothing special.
