### ISSUE TITLE
NaN when path parameter is String

### ISSUE THREAD

**Issue by gmatyszczak** [ktorio/ktor#1155]
### Ktor Version
1.2.0

### Ktor Engine Used(client or server and name)
Netty

### JVM Version, Operating System and Relevant Context
1.8, MacOS

I have this simple code to retrieve path parameter, but when I'm trying to access e.g. `/category/test` I'm getting `NaN` as an `id`. Is it possible to pass String as a path parameter?

`routing { get("/category/{id}") { val id = call.parameters["id"] } }`

**Comment by cy6erGn0m** [comment]
`call.parameters["id"]` returns `String?`, isn't it? How do you get Double?

**Comment by gmatyszczak** [comment]
I'm getting `"NaN"`, which is String

**Comment by cy6erGn0m** [comment]
I can't reproduce it. Are you sure that the actual url is `/category/test` ?

**Comment by gmatyszczak** [comment]
Sorry, my mistake, that was frontend problem 😄
