### ISSUE TITLE
Multiple matching paths do not choose higher quality path (component with more static values) when the lower quality one is authenticated

### ISSUE THREAD

**Issue by rocketraman** [ktorio/ktor#1158]
### Ktor Version

1.1.3

### Ktor Engine Used(client or server and name)

Jetty server

### JVM Version, Operating System and Relevant Context

JDK 11, Linux 5.0

### Feedback

Given the following code:

```
import io.ktor.application.call
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.routing
import io.ktor.server.engine.embeddedServer
import io.ktor.server.jetty.Jetty

fun main() {
  val server = embeddedServer(Jetty, port = 9010) {
    routing {
      get("/foo:{bar}/{baz}") {
        call.respondText("Received route1 bar=${call.parameters["bar"]}, baz=${call.parameters["baz"]}")
      }
      get("/{bar}/{baz}") {
        call.respondText("Received route2 bar=${call.parameters["bar"]}, baz=${call.parameters["baz"]}")
      }
    }
  }
  server.start(wait = true)
}
```

The first route has a static component beginning with `/foo:` whereas the second route is all dynamic parameters. The first route is therefore of higher quality for matching purposes.

With this call:

```
http get :9010/foo:a/b
```

the result is as expected: `Received route1 bar=a, baz=b`

However, when changing the code to wrap the second route in an `authenticate` block like this:

```
    routing {
      get("/foo:{bar}/{baz}") {
        call.respondText("Received route1 bar=${call.parameters["bar"]}, baz=${call.parameters["baz"]}")
      }
      authenticate {
        get("/{bar}/{baz}") {
          call.respondText("Received route2 bar=${call.parameters["bar"]}, baz=${call.parameters["baz"]}")
        }
      }
    }
```

I would expect the routing decision to be the same, but:

```
http get :9010/foo:a/b
```

now attempts to execute the lower quality authenticated path:

HTTP/1.1 401 Unauthorized

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-613">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
