### ISSUE TITLE
Pipeline phase references in Authentication.Feature should not be private

### ISSUE THREAD

**Issue by mechkg** [ktorio/ktor#1160]
### Ktor Version

1.2.0

### Feedback

`Authentication.Feature.authenticationPhase` and `Authentication.Feature.challengePhase` are currently private which prevents client code from referencing those phases. It is therefore impossible to insert a pipeline phase after the authentication phase if it depends on the authentication mechanism, for instance needs to access the principal information decoded from JWT.

It is possible to use `addPhase` and assume that the authentication phases have been properly added earlier as a workaround, but that is very fragile.

**Comment by giylmi** [comment]
Facing this too.

**Comment by ichaki5748** [comment]
+1

**Comment by VeselyJan92** [comment]
>  It is therefore impossible to insert a pipeline phase after the authentication phase if it depends on the authentication mechanism, for instance needs to access the principal information decoded from JWT.

I am developing role based authentication and this could come handy.
