### ISSUE TITLE
CallLogging: ApplicationStopPreparing, ApplicationStopping, ApplicationStopped not being sent

### ISSUE THREAD

**Issue by camhashemi** [ktorio/ktor#1164]
### Ktor Version
1.2.1

### Ktor Engine Used(client or server and name)
Netty, Jetty

### JVM Version, Operating System and Relevant Context
1.8, mac mojave

### Feedback

Steps to reproduce:
1. Create a new Ktor Netty or Jetty project using the Intellij plugin
2. Enable the CallLogging feature
3. Start the server (notice that 'Application started' is logged)
4. Stop the server

5 expected. 'Application stopping', 'Application stopped' are logged
5 actual. no logs appear

This is the simplest example of the larger issue that subscribing to these events doesn't work either, because they are never sent.

 
<img width="909" alt="Screen Shot 2019-06-01 at 9 54 22 AM" src="https://user-images.githubusercontent.com/8929238/58745634-72854780-8453-11e9-94ab-5bf866064387.png">

**Comment by cy6erGn0m** [comment]
sigint are not handled by ktor by default. If you are using embededServer function to start app, use java's shutdown hook to stop the server instance.

**Comment by camhashemi** [comment]
Thank you. Do you know if this is anywhere in the documentation? https://ktor.io/servers/index.html

**Comment by wyaeld** [comment]
Can confirm this now works nicely in 1.2.4.  Elegant solution @cy6erGn0m
