### ISSUE TITLE
Basic Auth passwords cannot contain $

### ISSUE THREAD

**Issue by nilsmagnus** [ktorio/ktor#1166]
### Ktor Version
1.2.1

### Ktor Engine Used(client or server and name)
server, netty

### JVM Version, Operating System and Relevant Context
11.0.2-open

### Feedback
When using basic-auth, the password cannot contain dollar-sign,$. The parsed password is cropped to the characters before the dollar-sign. Eg: "pass$word" is parsed as "pass".

**Comment by cy6erGn0m** [comment]
I can't reproduce it. Could you please describe it what exactly are you doing?

**Comment by nilsmagnus** [comment]
Sorry, I used bash with curl and double quotes around the password. So this issue is invalid.
