### ISSUE TITLE
Missing ktor-client-websocket 1.2.1 in Maven central

### ISSUE THREAD

**Issue by jschneider** [ktorio/ktor#1171]
All other client libs have been updated to 1.2.1 But ktor-client-websocket is missing:

https://repo.maven.apache.org/maven2/io/ktor/ktor-client-websocket/

Is this by accident? Or did I miss something?

**Comment by jschneider** [comment]
Ok. I see - you have renamed it to "ktor-client-websocket*s*"...

**Comment by SelfishLucho** [comment]
In case someone bumped in to this I just tried with 1.1.3 and it's _**io.ktor:ktor-client-websocket**_ (turned back to singular?) which conflicts with the doc, not sure you should reopen this or not.
