### ISSUE TITLE
How can I configure https connector in Jetty?

### ISSUE THREAD

**Issue by sskki** [ktorio/ktor#1182]
### Ktor Version
1.2.1
### Ktor Engine Used(client or server and name)
Jetty
### JVM Version, Operating System and Relevant Context
java version "1.8.0_201"
OS: Ubuntu 18.04
### Feedback
I'm trying to use server side client certificate in Jetty as the code below. But I failed because the Jetty server uses sslConnector in applicationEngineEnvironment(), ignoring httpsConnector defined in embeddedServer().

```kotlin

import io.ktor.application.*
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.jetty.*
import java.io.*
import java.security.KeyStore
import org.eclipse.jetty.server.ServerConnector
import org.eclipse.jetty.util.ssl.SslContextFactory

fun main() {
    val keyStore = KeyStore.getInstance(KeyStore.getDefaultType())
    val environment = applicationEngineEnvironment {
        module { module() }
        connector {
            host = "127.0.0.1"
            port = 8080
        }

        keyStore.load(File("build/keystore.jks").inputStream(), "changeit".toCharArray())

        sslConnector(
            keyStore, "keystore", { "changeit".toCharArray() }, { "changeit".toCharArray() }
        ) {
            host = "127.0.0.1"
            port = 8443
        }
    }

    embeddedServer(Jetty, environment) {
        configureServer = {
            val sslContextFactory = SslContextFactory().apply {
                this.keyStore = keyStore
                setKeyStorePassword("changeit")
                setKeyManagerPassword("changeit")
                this.trustStore = keyStore
                setTrustStorePassword("changeit")
                wantClientAuth = true
            }
            val httpsConnector = ServerConnector(this, sslContextFactory).apply {
                port = 8443
            }
            this.addConnector(httpsConnector)
        }
    }.start(wait = true)
}

fun Application.module(testing: Boolean = false) {
    routing {
        get("/") {
            call.respondText("HELLO WORLD!", contentType = ContentType.Text.Plain)
        }
    }
}

```

Deleting connectors  in applicationEngineEnvironment() results in only an inaccessible server. It seems that org.eclipse.jetty.server.Server.connectors is overwitten by applicationEngineEnvironment() after the configuration by embeddedServer().

[The release notes](https://github.com/ktorio/ktor/releases/tag/1.2.0) says client certificates support was added, but it seems to be "Ktor client" client certificates support.

Is there any way to use customized https connector in Jetty? I need this for client certificate and limiting weak SSL cipher suite in "Ktor server."

**Comment by cy6erGn0m** [comment]
Why `sslConnector` in the evironment doesn't fit? One usually shouldn't use `configureServer` for that purpose. I don't see any specific options configured via jetty's api that is not covered by `sslConnector` function...

**Comment by sskki** [comment]
> One usually shouldn't use configureServer for that purpose. 

I see, but I couldn't read it from [Configuring the Server](https://ktor.io/servers/configuration.html).

> I don't see any specific options configured via jetty's api that is not covered by sslConnector function.

I can't find any argument to define trustStore in either [`sslConnector`](https://api.ktor.io/1.2.1/io.ktor.server.engine/ssl-connector.html) or  [`EngineSSLConnectorBuilder`](https://api.ktor.io/1.2.1/io.ktor.server.engine/-engine-s-s-l-connector-builder/index.html).
I also can't find  any argument to [limit cipher suite](https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html#tls-and-ssl-versions).
Aren't they Jetty's api not covered by `sslConnector` function?

**Comment by sskki** [comment]
I've identified the cause.
In [JettyApplicationEngineBase.kt](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngineBase.kt) 
```kotlin
    protected val server: Server = Server().apply {
        configuration.configureServer(this)
        initializeServer(environment)
    }
```
`initializeServer(environment)` overwrite my connectors settings in `configuration.configureServer(this)`.
Is it better putting `initializeServer(environment)` before `configuration.configureServer(this)`, or does it cause any other problems?
My problem might also be solved by a change in [ServerInitializer.kt](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/ServerInitializer.kt). That is: 
```kotlin
connectors = environment.connectors.map { ktorConnector -> ... }.toTypedArray()
```
to
```kotlin
environment.connectors.map { ktorConnector -> ... }.forEach{ this.addConnector(it) }
```

**Comment by weickmanna** [comment]
Wow @sskki . This explains a lot.

I tried to configure the embedded Jetty server to use https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/server/ForwardedRequestCustomizer.html 

No wonder it didn't work ^ ^

**Comment by sskki** [comment]
Thank you @cy6erGn0m for accepting the pull request #1233 .
I found my customized httpsConnector enabled on [ktor 1.2.3-rc](https://github.com/ktorio/ktor/releases/tag/1.2.3-rc).
I'll try client certificate from now.

**Comment by sskki** [comment]
I finally succeeded client certification in Ktor server.
I needed `needClientAuth = true` besides `wantClientAuth = true`.
Thank you @cy6erGn0m again, and I expect this would also help @weickmanna.
I'll close this issue.
