### ISSUE TITLE
Part of URL after hash sign (#) is removed during the request

### ISSUE THREAD

**Issue by dtolstyi** [ktorio/ktor#1185]
### Ktor Version
1.2.0-rc

### Ktor Engine Used(client or server and name)
ktor-client-apache:1.2.0-rc

### JVM Version, Operating System and Relevant Context
Oracle JDK 8, Open JDK 11

### Feedback
When trying to open an URL with `#` sign in URL the part after hash is completely removed

Example:
```
val response = client.call("https://google.com#test") {
        method = HttpMethod.Get
}.response
```

Actual request is going to be made to `https://google.com` page instead of `https://google.com#test`.

**Comment by Prototik** [comment]
Fragment part (everything after `#`) assumed to be client-side only, it never should be submitted to the server.

**Comment by e5l** [comment]
Hi @dtolstyi, the client shouldn't send the fragment part of URL as mentioned.

**Comment by dtolstyi** [comment]
OK. Thank you for information @Prototik and @e5l.  I don't know how it's being done in Chrome and FireFox but they do send this part.
Anyway, if you say that it shouldn't I believe you.
Thank you!

**Comment by Prototik** [comment]
They never send this part. It requests page with fragment and process fragment at client-side later (via js or just by using anchors). In general server doesn't know anything about fragments, you should do your stuff by yourself.

**Comment by dtolstyi** [comment]
Might be. Thank you @Prototik for your explanation!
