### ISSUE TITLE
Upgrade Netty to 4.1.30+

### ISSUE THREAD

**Issue by delta-bravo** [ktorio/ktor#1190]
### Description

When running the ktor app in Java 11 runtime getting `java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled` excdeptions. This appears to be fixed in Netty 4.1.30+  
https://github.com/netty/netty/issues/8318

Could Netty be upgraded within Ktor please?

**Comment by cy6erGn0m** [comment]
Done in 9d68537a360a51a7ae85eacef0fd2bcc9f4ee1e7
