### ISSUE TITLE
'followRedirects' not respected by okHttp client

### ISSUE THREAD

**Issue by guenhter** [ktorio/ktor#1195]
### Ktor Version
1.2.1

### Ktor Engine Used(client or server and name)
okHttp Client

Gradle:
`io.ktor:ktor-client-okhttp:1.2.1`

### JVM Version, Operating System and Relevant Context
jdk-11.0.2

### Feedback

When a client is created like this
```
HttpClient {
        followRedirects = false
    }
```

the `followRedirects` is not respected when using okHttp as Implementaton. When using Apache, this works as expected.

**Comment by e5l** [comment]
Fixed in `master`.
