### ISSUE TITLE
Non-blocking HTTP with this library?

### ISSUE THREAD

**Issue by Mygod** [ktorio/ktor#1197]
### Ktor Version

1.2.2

### Ktor Engine Used(client or server and name)

client CIO or Apache

### JVM Version, Operating System and Relevant Context

Android 9

### Feedback

I am trying to do non-blocking IO (testing via doing network on main thread on Android and see where NetworkOnMainThreadException occurs), however, both CIO and Apache seems to fail in doing DNS resolving.

Is it possible or planned to implement completely non-blocking HTTP requests?

#### CIO

In CIO, the main thread attempts to resolve DNS at io.ktor.client.engine.cio.Endpoint.<init>(Endpoint.kt:29).
I don't think there is any way to get around that.

#### Apache

Similar thing happens to Apache. I found that there is a way to customize DnsResolver like such:

```
HttpClient(Apache) {
    engine {
        customizeClient {
            setConnectionManager(PoolingNHttpClientConnectionManager(
                    DefaultConnectingIOReactor(IOReactorConfig.DEFAULT),
                    null
            ) { InetAddress.getAllByName(it) })
        }
    }
}
```

Unfortunately, apache DnsResolver does not support suspend/async calls, so sadly I cannot take advantage of [new nonblocking API provided by Android API 29](https://developer.android.com/reference/kotlin/android/net/DnsResolver.html).

**Comment by e5l** [comment]
Hi, @Mygod. Thanks for the question. 
We have no async DNS right now. I made the separate issue for that: https://github.com/ktorio/ktor/issues/1924
