### ISSUE TITLE
Raw sockets problem

### ISSUE THREAD

**Issue by asimaranov** [ktorio/ktor#1198]
### Ktor 1.1.2, Windows 10

I have a strange exception using the raw sockets. How can I avoid it?
![photo_2019-06-24_14-19-11](https://user-images.githubusercontent.com/25568730/60015013-0fba5100-968b-11e9-908c-7d9df06d63ea.jpg)

**Comment by e5l** [comment]
Hi @asimaranov, thanks for the report.
Could you check it on ktor `1.2.2` and provide the code sample?

**Comment by cy6erGn0m** [comment]
Are you sure that you are not writing to a channel from different threads concurrently?

**Comment by asimaranov** [comment]
> Are you sure that you are not writing to a channel from different threads concurrently?

Thank you. The problem was that the keep-alive packets were being sent asynchronously in the background
