### ISSUE TITLE
Url(…) doesn't parse non-HTTP-like URL strings correctly

### ISSUE THREAD

**Issue by fluidsonic** [ktorio/ktor#1204]
`Url` is [supposed to](https://kotlinlang.slack.com/archives/C0A974TJ9/p1561553541222200?thread_ts=1561546449.221000&cid=C0A974TJ9) not just support HTTP-like URLs but [any kind of URLs](https://tools.ietf.org/html/rfc1738).

However the string parser seems to properly support only HTTP-like URLs:

### Example
```kotlin
Url("mailto:marc@knaup.io").toString()
Url("file:///var/www").toString()
```

### Expected
```kotlin
"mailto:marc@knaup.io"
"file:///var/www"
```

### Actual
```kotlin
"mailto://localhost/marc@knaup.io"
"file://var/www"
```

Ktor 1.2.2

**Comment by karthikbhat013** [comment]
Hey, can I pick this up? Thanks.

**Comment by karthikbhat13** [comment]
Hey, I have rebased the changes on master. Let me know if I need to do anything more.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-604">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
