### ISSUE TITLE
Would you please provide a complete sample

### ISSUE THREAD

**Issue by qiuzhanghua** [ktorio/ktor#1207]
### Ktor Version
1.2
### Ktor Engine Used(client or server and name)
Server
### JVM Version, Operating System and Relevant Context
JDK 1.8
### Feedback

Just like PetStore, blog etc.

I find all knowledge points, but I can't find a sample using Session, authenticate, template etc.

**Comment by e5l** [comment]
Hi @qiuzhanghua, thanks for the question. Here we have the samples you're looking for https://github.com/ktorio/ktor-samples/tree/master/feature
