### ISSUE TITLE
HttpResponse.readText() fails for non-2xx HTTP status

### ISSUE THREAD

**Issue by stuebingerb** [ktorio/ktor#1217]
### Ktor Version
1.2.2

### Ktor Engine Used(client or server and name)
Apache Client

### JVM Version, Operating System and Relevant Context
jdk1.8.0_172, Windows

### Feedback
`HttpResponse.readText()` fails in 1.2.2 (probably since 1.2.0) for requests that return a non-2xx HTTP reponse.

I don't know whether this is intentional, but since it used to work in 1.1.5 and I haven't seen any corresponding notice, this might be an unwanted regression.

See the following sample:

```
import io.ktor.client.HttpClient
import io.ktor.client.engine.apache.Apache
import io.ktor.client.request.get
import io.ktor.client.response.HttpResponse
import io.ktor.client.response.readText
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    val client = HttpClient(Apache)
    val response200 = client.get<HttpResponse>("https://httpstat.us/200")
    println(response200.readText())
    // v1.2.2: Prints: "200 OK"
    // v1.1.5: Prints: "200 OK"

    val response400 = client.get<HttpResponse>("https://httpstat.us/400")
    println(response400.readText())
    // v1.2.2: Throws exception: "Exception in thread "main" io.ktor.client.features.ClientRequestException: Client request(https://httpstat.us/400) invalid: 400 Bad Request"
    // v1.1.5: Prints "400 Bad Request"
}
```

**Comment by cy6erGn0m** [comment]
This is as designed. See https://ktor.io/clients/http-client/features/response-validation.html

**Comment by stuebingerb** [comment]
Okay. So is there a built-in way to get the payload of a failed request as text other than using `readBytes()` and fiddling with the correct charset yourself?

**Comment by MyrionSC** [comment]
It says so in the linked documentation but just to be needlessly redundant for the next people that arrive here. The HttpClient `expectSuccess` flag set to false stops the exceptions being thrown on http failures.

```
val client = HttpClient() {
    expectSuccess = false
}
```

**Comment by wkornewald** [comment]
Why is the response status code validated only when accessing the body? The status is invalid even before that already.

**Comment by e5l** [comment]
Cause it's important only when you processing body: `get<MyDataClass>` usually only make sense only when you have `2xx` status, and `get<HttpResponse>` will not fail in any case.

**Comment by wkornewald** [comment]
This inconsistency has caused bugs on our side. If I activate response validation then I expect validation to always happen. We often use `get<HttpResponse>` because we only need to inspect the etag or other headers, but not the body. In all of those cases we never caught bad response status codes because we expected Ktor to consistently do it like it's doing it for all other `get()` calls. Really, this is very confusing. If I enable validation then I expect it to always be active.

**Comment by e5l** [comment]
Yep, that looks like we're missing the valid use case. Could you file an issue about that? I will take a look

**Comment by wkornewald** [comment]
Yes, sure: https://youtrack.jetbrains.com/issue/KTOR-1412
