### ISSUE TITLE
Easy way to set content type in tests

### ISSUE THREAD

**Issue by sksamuel** [ktorio/ktor#1220]
When writing a test case using the testkit it would be great if there was a quick way to set the content type of the body rather than `addHeader("Content-Type", "application/json")`

**Comment by e5l** [comment]
Hi @sksamuel, thanks for the report. Could you provide a sample how would it looks?

**Comment by sksamuel** [comment]
```
handleRequest(...) { 
  setBody("json", ContentTypes.application/json)
  // or
  setBody("json")
  setContentType(ContentTypes.application.json)
}.apply {

}
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-598">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
