### ISSUE TITLE
Can not find module ktor-ktor-http in npm.

### ISSUE THREAD

**Issue by 1renhaO** [ktorio/ktor#1224]
First I would very appreciate for the ktor framework, but I have a little problem of my usage.  I compile the kotlin code to JS. but in the generated JS code it  contain this ```require("ktor-ktor-http")``` code. So I searched ```ktor-ktor-http``` in the npm repositories, but unfortunately I can not find it in the the npm repositories. So, did I missed something?

this is my generated JS code 

```

function (root, factory) {
  if (typeof define === 'function' && define.amd)
    define(['exports', 'kotlin', 'kotlinx-coroutines-core', 'ktor-ktor-client-core', 'ktor-ktor-http'], factory);
  else if (typeof exports === 'object')
    factory(module.exports, require('kotlin'), require('kotlinx-coroutines-core'), require('ktor-ktor-client-core'), require('ktor-ktor-http'));
  else {
    if (typeof kotlin === 'undefined') {
      throw new Error("Error loading module 'kb-mutiplatform'. Its dependency 'kotlin' was not found. Please, check whether 'kotlin' is loaded prior to 'kb-mutiplatform'.");
    }
    if (typeof this['kotlinx-coroutines-core'] === 'undefined') {
      throw new Error("Error loading module 'kb-mutiplatform'. Its dependency 'kotlinx-coroutines-core' was not found. Please, check whether 'kotlinx-coroutines-core' is loaded prior to 'kb-mutiplatform'.");
    }
    if (typeof this['ktor-ktor-client-core'] === 'undefined') {
      throw new Error("Error loading module 'kb-mutiplatform'. Its dependency 'ktor-ktor-client-core' was not found. Please, check whether 'ktor-ktor-client-core' is loaded prior to 'kb-mutiplatform'.");
    }
    if (typeof this['ktor-ktor-http'] === 'undefined') {
      throw new Error("Error loading module 'kb-mutiplatform'. Its dependency 'ktor-ktor-http' was not found. Please, check whether 'ktor-ktor-http' is loaded prior to 'kb-mutiplatform'.");
    }
    root['kb-mutiplatform'] = factory(typeof this['kb-mutiplatform'] === 'undefined' ? {} : this['kb-mutiplatform'], kotlin, this['kotlinx-coroutines-core'], this['ktor-ktor-client-core'], this['ktor-ktor-http']);
  }

```

this is my build.gradle

```

plugins {
    id 'kotlin-multiplatform' version '1.3.40'
}
repositories {
    maven {
        url 'http://maven.aliyun.com/nexus/content/groups/public/'
    }
    maven {
        url 'http://maven.aliyun.com/nexus/content/repositories/jcenter'
    }
    mavenLocal()
    mavenCentral()

    maven { url 'https://plugins.gradle.org/m2/' }
    maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
    jcenter()
}
group 'com.example'
version '0.0.1'

apply plugin: 'maven-publish'

kotlin {
    jvm()
    js {
        compilations.main.kotlinOptions.moduleKind = 'umd'
    }
    // For ARM, should be changed to iosArm32 or iosArm64
    // For Linux, should be changed to e.g. linuxX64
    // For MacOS, should be changed to e.g. macosX64
    // For Windows, should be changed to e.g. mingwX64
//    macosX64("macos")
    iosX64("ios") {
        binaries {
            framework()
        }
    }
    sourceSets {
        commonMain {
            dependencies {
                implementation ("io.ktor:ktor-client-core:$ktor_version")
                implementation kotlin('stdlib-common')
            }
        }
        commonTest {
            dependencies {
                implementation kotlin('test-common')
                implementation kotlin('test-annotations-common')
            }
        }
        jvmMain {
            dependencies {
                implementation ("io.ktor:ktor-client-android:$ktor_version")
                implementation kotlin('stdlib-jdk8')
            }
        }
        jvmTest {
            dependencies {
                implementation kotlin('test')
                implementation kotlin('test-junit')
            }
        }
        jsMain {
            dependencies {
                implementation kotlin('stdlib-js')
                implementation "io.ktor:ktor-client-js:$ktor_version"
            }
        }
        jsTest {
            dependencies {
                implementation kotlin('test-js')
            }
        }
        iosMain {
            dependencies {
                implementation ("io.ktor:ktor-client-ios:$ktor_version")
            }
        }
        iosTest {
        }
    }
}

```

this is my kotlin code 

```


class LoginApi {
    private val client = HttpClient()

    fun login(param: LoginReq, callback: (String) -> Unit) {
        GlobalScope.apply {
            launch(ApplicationDispatcher) {
                val result: String = client.post {
                    url("http://10.76.34.177:3000/user/login")
                    parameter("userName", param.userName)
                    parameter("passWord", param.passWord)
                }

                callback(result)
            }
        }
    }
}

```

I'm very newly in kotlin, So I will very appreciate of you reply.

**Comment by Reedyuk** [comment]
I am also getting the same error, i don't think you are doing anything wrong, i just think the dependancy doesn't exist or is not generated for some reason.

**Comment by e5l** [comment]
Hi @Reedyuk, thanks for the report.
There are no ktor modules in npm, could you try adding them as gradle dependencies for now?

**Comment by Reedyuk** [comment]
Do you mean the sub dependancies of the Ktor library?

**Comment by e5l** [comment]
Yes. Could you check the `build.gradle` configuration from: https://github.com/ktorio/ktor-samples/tree/master/mpp/fullstack-mpp ?

**Comment by 1renhaO** [comment]
@Reedyuk @e5l 
 I found these dependancies in my ```build``` directory. 

![屏幕快照 2019-07-16 上午9 14 45](https://user-images.githubusercontent.com/19664590/61258942-89d18780-a7aa-11e9-8c54-f0daf8d223a4.png)
 
  But I wondering whether I have to copy the build files to my Javascript project manually?  I think it's not a good way to use it, because once I change the Kotlin source code, I have to copy the build files to my Javascript project again and again. So, please give me some advises to solve it.
  At last, my english is not good, thanks for you patient.

**Comment by Reedyuk** [comment]
hmm, i dont have the JS folder with packages in my build directory. 
This is what it looks like:

<img width="345" alt="Screenshot 2019-07-16 at 08 30 59" src="https://user-images.githubusercontent.com/3853006/61274730-46741a80-a7a4-11e9-81d2-1854abe73cf0.png">

**Comment by 1renhaO** [comment]
my kotlin version
![image](https://user-images.githubusercontent.com/19664590/61343125-4137ce00-a87f-11e9-8e38-aef48bae9a79.png)

my gradle version 
![image](https://user-images.githubusercontent.com/19664590/61341941-0f246d00-a87b-11e9-984d-ba66879bba7a.png)

I just run ```jsMainClasses``` task and get the build things. (by the way, I use idea as the IDE and my project is based on the  kotlin ```Multiplatform Library``` boilerplate which provide by idea)
![image](https://user-images.githubusercontent.com/19664590/61342882-5bbd7780-a87e-11e9-8c46-63faf6176b4e.png)
![image](https://user-images.githubusercontent.com/19664590/61343285-cc18c880-a87f-11e9-823c-0a8f06d90874.png)

and also you can check the difference of ```build.gradle``` between us.

**Comment by e5l** [comment]
If you configure test runner with `browser()` or `node()` in the `build.gradle`(like in fullstack sample), the gradle plugin will copy dependencies for you.

**Comment by Reedyuk** [comment]
node() i have not seen this, do you have an example? i cant find this in the fullstack sample(it uses browser).
I tried the syntax but it cannot find it.
I need it to be node and not browser as i am exporting as a nodejs package which i host internally.

**Comment by tiendv-teko** [comment]
@Reedyuk  Did you find the solution on how to use the compiled JS module in a nodejs project ?
I got the same result but couldn't use the module

**Comment by Reedyuk** [comment]
No, unfortunately not.

**Comment by emanguy** [comment]
For anyone searching this thread, I got the dependencies to show up the same way @1renhaO did by adding the Ktor bintray repository to my gradle dependencies. I'll also post my JS compilation config here for reference.

(note: I'm using the Kotlin Gradle DSL)
dependencies block:
``` kotlin
repositories {
    mavenCentral()
    jcenter()
    maven("https://kotlin.bintray.com/ktor")
}
```

JS compilation configuration:
``` kotlin
kotlin {
val ktorVersion = "1.2.3"
// Config for other targets...

    js {
        nodejs()
        @Suppress("UNUSED_VARIABLE")
        val main by compilations.getting {
            dependencies {
                implementation(kotlin("stdlib-js"))
                implementation("io.ktor:ktor-client-js:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization-js:$ktorVersion")
            }
        }
    }
    // Other irrelevant config...
}
```

When I run the `gradle jsJar` task it creates the necessary files under `build/js/node_modules` for the dependencies and `build/js/packages/[PROJECT NAME]/` for the actual library. Hope this helps someone else!

**Comment by theromis** [comment]
I'm facing same problem.

My graddle:
```graddle
group 'com.lonje'
version '0.0.1'

kotlin {
    android()
    js("browser") {
        compilations.main.kotlinOptions.moduleKind = 'umd'
        browser {
        }
    }
....
    sourceSets {
        commonMain {
            dependencies {
                implementation "org.jetbrains.kotlin:kotlin-stdlib-common:$kotlinVersion"
                implementation "io.ktor:ktor-client-core:$ktorVersion"
                implementation "io.ktor:ktor-client-websockets:$ktorVersion"
                implementation "io.ktor:ktor-client-json:$ktorVersion"
                implementation "io.ktor:ktor-client-serialization:$ktorVersion"
                implementation "io.ktor:ktor-client-logging:$ktorVersion"
                implementation "org.jetbrains.kotlin:kotlin-serialization:$kotlinVersion"
            }
        }
        browserMain {
            dependencies {
                implementation "io.ktor:ktor-client-js:$ktorVersion"
                implementation "io.ktor:ktor-client-serialization-js:$ktorVersion"
            }
        }
    }
}
```

After running: `./gradlew browserJar`
can see:
```
build/js/node_modules/ktor-ktor-client-core
build/js/node_modules/ktor-ktor-client-js
build/js/node_modules/ktor-ktor-client-json
build/js/node_modules/ktor-ktor-client-serialization
build/js/node_modules/ktor-ktor-http
build/js/node_modules/ktor-ktor-http-cio
build/js/node_modules/ktor-ktor-io
build/js/node_modules/ktor-ktor-utils
```
from here I'm lost, working on angular 10 project, for now just copying everything manually to angular `node_modules`
but I hope exists more clear way of using module
can somebody share experience in it?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-595">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Ktor is not published in npm right now, will be fixed with: https://youtrack.jetbrains.com/issue/KTOR-2399
