### ISSUE TITLE
Feature request - Challenge Builder Function for DigestAuth

### ISSUE THREAD

**Issue by sethchhim** [ktorio/ktor#1229]
**Subsystem**
Server, ktor-auth

**Is your feature request related to a problem? Please describe.**
Request support for [challenge builder function](https://github.com/ktorio/ktor/commit/6638ea7abbecd71af0d70633a2f406587bd4a8fd) to `DigestAuth`

**Describe the solution you'd like**
Same as `JWTAuthChallengeFunction` but for `DigestAuth`

**Motivation to include to ktor**
My project uses DigestAuth and I hope to use this feature. Thank you for any consideration.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-591">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by sethchhim** [comment]
@oleg-larshin Ok, thanks for the update.
