### ISSUE TITLE
LogLevel.None freeze the client

### ISSUE THREAD

**Issue by opensource21** [ktorio/ktor#1230]
**Ktor Version and Engine Used (client or server and name)**
1.1.3 client, additional ktor modules included logging 

**Describe the bug**
If you add Logging with LogLevel.None the client didn't answer.
**To Reproduce**
run tests in [test-project](https://github.com/opensource21/ktor-bug1230)
**Expected behavior**
all test a green

**Comment by e5l** [comment]
Hi @opensource21, thanks for the report.
There are some fixes since `1.1.3` in logging, could you recheck it with `1.2.2`?

**Comment by e5l** [comment]
I checked :) The fix in `1.2.2` is working.
