### ISSUE TITLE
Jackson serialization feature for Android below 7.0

### ISSUE THREAD

**Issue by TrueShirshov** [ktorio/ktor#1238]
**Ktor Version and Engine Used (client or server and name)**
1.2.2, Client, Android

**Describe the bug**
Jackson serialization feature not working on Android versions below 7.0, application fails with exception because dependency "io.ktor:ktor-client-jackson:1.2.2" uses "com.fasterxml.jackson.module:jackson-module-kotlin:2.9.8", while only 2.9.6 works on old Android versions. It's known issue of jackson-module-kotlin:
https://github.com/FasterXML/jackson-module-kotlin/issues/176

Is it even supposed to work on old Android versions (e.g. 5.0 and 6.0)? May this issue be fixed somehow in future versions?
Currently I resorted to write my own serialization feature that uses 2.9.6, but obviously it's not a good solution in general.

**Comment by cy6erGn0m** [comment]
Please note that using outdated jackson may cause security vulnerabilities. So we definitely aren't going to downgrade. For older android use gson or kotlinx serialization. Also note that jackson may be too heavy (kbytes) fot android.

**Comment by TrueShirshov** [comment]
> For older android use gson or kotlinx serialization.

Unfortunately there is "@JsonFormat(shape = JsonFormat.Shape.ARRAY)" annotation only available in Jackson that I have to use to deserialize some objects from server side. I've searched for alternatives but found nothing.
Ok, thanks, looks like the only possibility is to fix the bug in jackson-module-kotlin itself.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-588">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
I'm sorry, but we're not going to support the old version of Jackson explicitly. Please consider to forcing old dependency version with your build tool
