### ISSUE TITLE
Support logging configuration - enhancement

### ISSUE THREAD

**Issue by emrul** [ktorio/ktor#124]
It would be great to be able to configure logging directly in the application.conf instead of maintaining a separate logback.xml configuration file

For example, [Dropwizard](http://www.dropwizard.io/0.7.1/docs/manual/configuration.html#logging) offers this.

It allows therefore to configure all aspects of application configuration from one config file.

**Comment by orangy** [comment]
It's not possible to configure slf4j without having access to specific logger implementation, like logback. I wouldn't require specific implementation just for this. If you have any ideas about how we can implement this, please share.

**Comment by orangy** [comment]
One option would be to have a `logback` feature, that would both bring the dependency and read configuration when the feature is installed.

**Comment by saem** [comment]
When I was messing around trying to create a framework, and using dropwizard as inspiration, I ran into this fairly early. I believe the only thing really required for this is to ensure that there is very early bootstrapping of any logging feature, such that you can guarantee no calls to log prior it setting up.

Alternatively, something I didn't explore was, create a proxy logger that captures everything until the "real" logger shows up, and all the calls are forwarded to it. Wasn't sure hope to deal with time stamps, and other issues.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-827">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
There is a logback.xml file for that. I'm not sure why do we need different approach to configure that
