### ISSUE TITLE
No way to match // in a URL

### ISSUE THREAD

**Issue by sksamuel** [ktorio/ktor#1241]
Currently, if you try to match
`http://localhost:8080/http://foo.com/image.url`

Then both {...} and * fail. The {...} will capture but by changing the path to `http:foo.com/image.url`

This kind of path matching is very useful for endpoints that accept other urls.

I could use a query parameter but I am attempting to write a drop in replacement for an existing service.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-587">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
I am able to match that URI with both `{...}` and `*` using Ktor 1.6.0.
