### ISSUE TITLE
ktor-client: Proxy support

### ISSUE THREAD

**Issue by evgfilim1** [ktorio/ktor#1245]
I'm developing an application with Kotlin and ktor (as client), but haven't found anything about working with any kind of proxy, especially SOCKS one.

**Comment by e5l** [comment]
Hi @evgfilim1, thanks for the report. What client engine do you use?

**Comment by evgfilim1** [comment]
Apache

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-585">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
The proxy support is implemented since `1.4.0`
