### ISSUE TITLE
IosClientEngine URLSession access

### ISSUE THREAD

**Issue by jpulik** [ktorio/ktor#1248]
**Ktor version**
1.2.2

**Ktor Engine used**
IosClientEngine

**Motivation and proposed Solution**
We need to be able to implement URLSession delegate methods (used by IosClientEngine) in our custom code to achieve required functionality. Eg  overriding didReceiveChallenge to deal with certificates stuff. Ideal solution would be to be able to set custom URLSession object or be able to override all URLSession delegate methods on top of some IosClientEngine delegate.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-583">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
