### ISSUE TITLE
Cookies are not set if 302 is received

### ISSUE THREAD

**Issue by gabin8** [ktorio/ktor#1254]
**Ktor Version and Engine Used (client or server and name)**
1.2.2 , OkHttp Client

**Bug description**
The bug #843 is not fixed so I've opened a new ticket.
I have a script in php with following content:
```
<?
		if (array_key_exists('TestCookie1', $_COOKIE)) {
		  print("<pre><b>COOKIES ARE SET !</b><br/>".print_r($_COOKIE,true)."</pre>");
		}
		else
		{
		   setcookie("TestCookie1", 100000 + rand(100, 500) + ".");
		   setcookie("TestCookie2", 200000 + rand(100, 500) + ".");
		   $actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
		   header('Location: '.$actual_link, true, 302);
		   exit;
		}
?>
```
The scripts sets cookie and redirects to the same page. Okhttp client gives me an error:
sources.kts:34 java.net.ProtocolException: Too many follow-up requests: 21

The configuration of OkHttp client:
```
val client = HttpClient(OkHttp) {
    engine {
        config {
            followRedirects(true)
            followSslRedirects(true)

        }
    }
    install(HttpCookies) {
        storage = AcceptAllCookiesStorage()
    }
}
```
Android client and CIO work fine.
The configuration of CIO client:
```
val client = HttpClient(CIO).config {
    install(HttpCookies) {
        storage = AcceptAllCookiesStorage()
    }
}
```
Android client:
```
val client = HttpClient(Android) {
    install(HttpCookies) {
        storage = AcceptAllCookiesStorage()
    }
}
```
**Expected behavior**
Expecting to get result like this:
```
sources.kts:42 content : <pre><b>COOKIES ARE SET !</b><br/>Array
(
    [TRACKID] => 0fc21533e2cef66df1412ff2169726a2
    [TestCookie1] => 100333
    [TestCookie2] => 200222
)
</pre>
```
**Actual result**
sources.kts:34 java.net.ProtocolException: Too many follow-up requests: 21

Related issue:
https://github.com/ktorio/ktor/issues/843

**Comment by e5l** [comment]
Hi @gabin8, the ktor can't handle redirect cookies if it doesn't know about the redirect.

You enabled `okhttp` redirect here:
```kotlin
            followRedirects(true)
            followSslRedirects(true)
```
so ktor doesn't receive the request with cookies at all.

Could you check it with disabled `okhttp` redirect?

**Comment by gabin8** [comment]
removing **config** flags resolved the issue. Thank you
