### ISSUE TITLE
Handling route not found

### ISSUE THREAD

**Issue by marioalvial** [ktorio/ktor#1264]
**Ktor Version and Engine Used (client or server and name)**
1.2.2, netty

**Describe the bug**
I need to set a custom response when the requested route is not found. But there's no documentation on how to capture route not found exception or something.

**Comment by cy6erGn0m** [comment]
The first way is to specify status page https://ktor.io/servers/features/status-pages.html#status

The other way is to intercept the fallback pipeline phase https://ktor.io/advanced/pipeline#ApplicationCallPipeline

**Comment by marioalvial** [comment]
Intercepting the fallback pipeline works for me. Thanks
