### ISSUE TITLE
Make Ktor exceptions recoverable for kotlinx.coroutines

### ISSUE THREAD

**Issue by qwwdfsad** [ktorio/ktor#1268]
**Is your feature request related to a problem? Please describe.**

Ktor exposes a lot of specific exceptions in its public API for the sake of diagnostics.
Often these exceptions have some state (e.g. `responseCode` field) thus [cannot be copied](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#stacktrace-recovery-machinery) by `kotlinx.coroutines` machinery as is.
It means that debugging code that throws such exceptions is not as pleasant experience as it could be (the example from [debugging.md](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#stacktrace-recovery-machinery) shows how stacktrace recovery affects the user)

**Describe the solution you'd like**

Manually implement `CopyableThrowable` in all Ktor exceptions.

**Motivation to include to ktor**

Improve debugging and diagnostics when working with Ktor, coroutines and exceptions

**Comment by e5l** [comment]
Fix in `master`
