### ISSUE TITLE
Error:Kotlin: [Internal Error] java.lang.LinkageError: loader constraint violation: loader (instance of org/jetbrains/kotlin/cli/jvm/plugins/PluginURLClassLoader$SelfThenParentURLClassLoader) previously initiated loading for a different type with name "kotlin/sequences/Sequence"

### ISSUE THREAD

**Issue by Arthur-Kamau** [ktorio/ktor#1271]
**Ktor Version and Engine Used (client or server and name)**

Ktor version 1.2.3
Server Engine Netty
Server Templating Html DSL & freemaker
Client Apache Http Client Engine & Http Client Engine 
java version  openjdk version "1.8.0_222"
Linux ubuntu version 16.04 

**Describe the bug**
After creating a project in https://start.ktor.io.
The project does not run.

**To Reproduce**
Create a project and run the project.

**Expected behavior**
After creating a ktor project it should run.
 The project created Github Repo [link](https://github.com/Arthur-Kamau/Slick)

**Screenshots**
Screenshot of error stacktrace.

![image 1](https://user-images.githubusercontent.com/30284230/62681061-6e305a00-b9c1-11e9-911b-55c849251370.png)

![image 2](https://user-images.githubusercontent.com/30284230/62681071-75effe80-b9c1-11e9-8ce3-dda6777c16b0.png)

**Comment by MistRay** [comment]
I've also met the same situation.

**Comment by Arthur-Kamau** [comment]
Feedback on the above  bug would be much appreciated.

**Comment by MahmoodAliL** [comment]
I have also met the same situation.
Any update?

**Comment by ShradhaSangtani** [comment]
It got fixed by updating the kotlin version in intellij

**Comment by wellybean** [comment]
Updating the Kotlin version on IntelliJ also worked for me

**Comment by sammynjihia** [comment]
@Arthur-Kamau Try updating the version of the Kotlin plugin in your Idea

**Comment by Puneethraj** [comment]
Updating kotlin version solved the issue for me too
