### ISSUE TITLE
crypto is unavailable on IE 11

### ISSUE THREAD

**Issue by dhakehurst** [ktorio/ktor#1283]
**Ktor Version and Engine Used (client or server and name)**
1.2.2

**Describe the bug**
in ktor-utils there is a line

`private val crypto: Crypto = if (PlatformUtils.IS_NODE) js("require('crypto')") else js("crypto")`

this does not work on IE 11, because 'crypto' is undefined.

I that the line should be changed to something like,

`private val crypto: Crypto = if (PlatformUtils.IS_NODE) js("require('crypto')") else js("(crypto ? crypto : msCrypto)")`

**To Reproduce**
use IE 11

SCRIPT5009: 'crypto' is undefined

**Comment by e5l** [comment]
Hi @dhakehurst, thanks for the report. 
We'll fix it in the next release.

**Comment by chadmorrow** [comment]
I'm still running into this problem with Ktor version 1.3.1.

**Comment by e5l** [comment]
Hi @chadmorrow, could you try `1.3.2` and file a new issue with the report?
