### ISSUE TITLE
KTOR client CIO engine sends bad "Host" http header (includes port number)

### ISSUE THREAD

**Issue by Evyy** [ktorio/ktor#1294]
**Ktor Version and Engine Used (client or server and name)**
1.2.2, client, CIO

**Describe the bug**
ktor client with CIO engine sends port number in host header. `Host: test.com:80`

This has caused 2 problems so far

1) the external service had routing rules based on host. `test.com` routed correctly, `test.com:443` did not route and sent 404s. All other major http clients (browser, curl, python, okhttp, etc) do not append the port to the host header (and worked correctly).

2) aws s3 pre-signed urls. the host in the header did not match the host that was signed in the presigned url, caused aws signatures to not match and request to be refused.

**To Reproduce**

```kotlin
val client = HttpClient(CIO)
client.get("http://test.com")
```
**Expected:**
```
GET  HTTP/1.1
Host: test.com
....
```
**Actual:**
```
GET  HTTP/1.1
Host: test.com:80
....
```

**To Fix**
change this line
https://github.com/ktorio/ktor/blob/0e4a6f24e40c756a35913d466036f0dc59519cc1/ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/utils.kt#L31

to
```kt
        builder.headerLine("Host", url.host)
```

**Comment by Bluexin** [comment]
See [ietf](https://tools.ietf.org/html/rfc7230#section-5.4) on the Host header :
> Host = uri-host [ ":" port ] ;

Port is optional, but part of the spec.

It follows the http URI scheme, defined in [section 2.7.1](https://tools.ietf.org/html/rfc7230#section-2.7.1) :
> If the port subcomponent is empty or not given, TCP port 80 (the reserved port for WWW services) is the default.

Maybe we can just have it not specify default ports ?
