### ISSUE TITLE
RequestQueueLimit and other Netty configuration strange behavior

### ISSUE THREAD

**Issue by vellrya** [ktorio/ktor#1298]
**Ktor Version and Engine Used (client or server and name)**
Ktor 1.2.3 + Netty

**Describe the bug**
Hello, maybe this is not a bug, and I just don’t understand how this should work, but in my opinion there may be a mistake.

I create a server with this code (imagine that debugPlay does some work for +-200 ms):
```
fun main() {
val env = applicationEngineEnvironment {
        // Public API
        connector {
            port = 1717
        }
        module {
            mainGet()
        }
    }
    embeddedServer(Netty, environment = env, configure = {
        connectionGroupSize = 1
        workerGroupSize = 1
        callGroupSize = 1
        runningLimit = 1
        requestQueueLimit = 1
    }).start(true)
}
}

fun Application.mainGet() {
    install(CallLogging)
    routing {
        get("/api/checkThis") {
            call.respond(TextContent("""{"msg": "unaccessable when server process old queue request"}""", ContentType.Application.Json))
        }
        get("/api/debugPlay") {
            Thread.sleep(200)
            println("debugPlay")
            call.respond(TextContent(JSONObject().put("sign", "123").toString(), ContentType.Application.Json))
            return@get
       }
    }
}

```

I set all available configure options to 1 to demonstrate the problem.
So, I expect that the queue can save no more than one request. Next, I send 1000 requests from another application simultaneously and close it without waiting for an answer.

However, Ktor continues to respond to requests for a long time, despite the fact that only one request should remain in the queue. Here is the log:
```
debugPlay
[nioEventLoopGroup-4-1] INFO Application - 200 OK: GET - /api/debugPlay, cancelled
debugPlay
[nioEventLoopGroup-4-1] INFO Application - 200 OK: GET - /api/debugPlay, cancelled
debugPlay
[nioEventLoopGroup-4-1] INFO Application - 200 OK: GET - /api/debugPlay, cancelled
debugPlay
[nioEventLoopGroup-4-1] INFO Application - 200 OK: GET - /api/debugPlay, cancelled
debugPlay
[nioEventLoopGroup-4-1] INFO Application - 200 OK: GET - /api/debugPlay, cancelled
...
```

If I do not install Netty options and just use the standard configuration, then the server stops responding to other requests (to another route), and continues to process old ones that have already been canceled. Thus, it is very easy to make a ddos ​​attack by sending a lot of requests to which the server will respond, while ignoring new requests from real users. Can you help: is saving old requests in the queue an error (since I set a limit of 1 request), or I just don’t understand why it is so right? And how to optimally configure ktor so as not to become an easy target for a ddos attack?)

**Comment by cy6erGn0m** [comment]
`requestQueueLimit` is for HTTP pipelining only, it only affects requests in a single socket connection.

The other thing is that there is no way to cancel request processing until response transmitting failure due to broken connection and there is no way to detect connection loss/reset before attempting to transmit a response.

And the third thing is that `Thread.sleep` is blocking operation that always holds a thread while number of threads in the pool is always limited. So since no cancellation could be detected during sleep, all threads will be blocked and this is very common issue, not just ktor.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-568">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
