### ISSUE TITLE
1.3.50 wrong publishing

### ISSUE THREAD

**Issue by IgorKey** [ktorio/ktor#1299]
For my native project Im using your dependencies kotlinx-io and kotlinx and ktor-utils-native.
As I see from commits, you recently update them to support 1.3.50 kotlin.
But they were compiled with older version of KN compiler.

The abi versions don't match. Expected '[14]', found '9'
w: The compiler versions don't match either. Expected '[]', found '1.3.1-release-11173'

so, why? and how u use them for fully multiproject ktor?

**Comment by IgorKey** [comment]
Oh, my bad. You have not publish 1.3.50 yet.. Sorry. Waiting )

**Comment by Thomas-Vos** [comment]
Version `1.2.3-1.3.50-eap-5` works fine for me with Kotlin 1.3.50.

**Comment by IgorKey** [comment]
Yeah. EAP of course works.
