### ISSUE TITLE
Create some API Docs

### ISSUE THREAD

**Issue by StokeMasterJack** [ktorio/ktor#130]
Is there any api docs for ktor? Something analogous to this:

https://tomcat.apache.org/tomcat-5.5-doc/servletapi/

For example, in the servlet api i can do this on an http post:

val x:String = request.getParameter("x")

It took me an hour to find something similar in ktor:

val map = call.request.receive<ValuesMap>()
val token = map["token"]

**Comment by HudsonAfonso** [comment]
+1

**Comment by soywiz** [comment]
In the meantime I have added these documentation pages that include most of the public request/reponse API:
* http://ktor.io/servers/requests.html
* http://ktor.io/servers/responses.html

And for routing this was already there:
* http://ktor.io/features/routing.html

**Comment by soywiz** [comment]
API documentation is live: https://api.ktor.io/0.9.4/
