### ISSUE TITLE
TestApplicationEngine.hookRequests loses old handler's state

### ISSUE THREAD

**Issue by LoneEngineer** [ktorio/ktor#1300]
Ktor-1.2.3 (ktor-server-test-host-1.2.3.jar)

** Description **
Seems like a bug:
```
@KtorExperimentalAPI`
    fun hookRequests(
        processRequest: TestApplicationRequest.(setup: TestApplicationRequest.() -> Unit) -> Unit,
        processResponse: TestApplicationCall.() -> Unit,
        block: () -> Unit
    ) {
        val oldProcessRequest = processRequest    /// <<<----------------------- HERE
        val oldProcessResponse = processResponse  /// <<<----------------------- HERE
        this.processRequest = {
            oldProcessRequest {
                processRequest(it)
            }
        }
```
there is a clash in names between this.processRequest and function's argument processRequest and it resolved to function's argument. So instead preserving old request processor (and restore later) new processor is stored.
I found this behavior with using cookieSession {} extention:

```
  cookiesSession { some requests here }
  handleRequest(...).apply { <<<--- still contains cookies
  }

```

**Expected behavior**
I expected that 'hookRequest' will restore original set of processors (without cookie handling).

**Comment by LoneEngineer** [comment]
Just curios, why issue is not marked as 'closed' ?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-567">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
