### ISSUE TITLE
[Question][JEP 353] Do you have plans to support new JDK socket API ?

### ISSUE THREAD

**Issue by imanushin** [ktorio/ktor#1308]
**Subsystem**
Client and server

**Question**
JDK 13 (is in development state now) has new feature - modernized Socket API. Please [check details here](https://openjdk.java.net/jeps/353). It shall be faster, memory optimized and so on. Do you have any plans to use this API in CIO Engine (if course it should be runtime check, because ktor also works at the older JDKs)?

**Motivation to include to ktor**
Looks like new API will be optimized better than older one. Also probably in future only new Socket API will be improved (e.g. system interoperability changes, etc.).

Therefore (probably) it is better to start looking on it, to have ability of performance boost by using ktor API.

**Comment by cy6erGn0m** [comment]
As far as I can see there is no new API proposed by the JEP but the underlying implementation replacement with improvements for performance reasons (especially for project loom), am I right?

**Comment by imanushin** [comment]
@cy6erGn0m , I rechecked - you are right. Java API is still unchanged, only internal implementation was touched. So, closing issue.
