### ISSUE TITLE
BasicAuth 1.1.5 and Auth 1.2.4 differences

### ISSUE THREAD

**Issue by wyaeld** [ktorio/ktor#1312]
**Ktor Version and Engine Used (client or server and name)**
1.1.5 client auth vs 1.2.4

**Describe the bug**
The behaviour of this
```
val client = HttpClient() {
    install(Auth) {
        basic {
            username = "username"
            password = "password"
        }
    }
}
```
is not equivalent to this
```
val client = HttpClient() {
    install(BasicAuth) {
        username = "username"
        password = "password"
    }
}
```

in a key way.  The former in 1.2.4 is making a request with no authorization header, receiving a 401 and then resending a request with the header.
The latter in 1.1.5 is sending all requests out with the authorization header.

In my case I'm dealing with a slow 3rd party endpoint and the newer behaviour is causing problems.  Is there a way I'm not seeing to configure Auth to always send the authorization with all requests?  I understand the initial request without auth is common enough in browser workflows, but I don't think its something I should have to do with a programmatic httpclient.

**Comment by e5l** [comment]
Hi @wyaeld, thanks for the report.
Could you try using `sendWithoutRequest` option https://api.ktor.io/1.2.3/io.ktor.client.features.auth/-auth-provider/send-without-request.html ?

**Comment by wyaeld** [comment]
@e5l confirming this fixes it.  Thankyou for assistance.

**Comment by e5l** [comment]
Thanks for the feedback! Closed
