### ISSUE TITLE
1.2.4 client-cio publish issue

### ISSUE THREAD

**Issue by wyaeld** [ktorio/ktor#1313]
Most of the 1.2.4 artifacts are downloading fine, but the client-cio is throwing a 401 error on bintray.

`https://kotlin.bintray.com/ktor/io/ktor/ktor-client-cio/1.2.4/ktor-client-cio-1.2.4.jar`

**Comment by e5l** [comment]
Hi @wyaeld, thanks for the report.
It looks like the repositories section is wrong in the `build.gradle`. Could you try to remove `https://kotlin.bintray.com` and keep `jcenter()`?

**Comment by wyaeld** [comment]
Updated to bintray, jar comes down, but imports don't resolve.

When I opened up the downloaded jar, it just has a bunch of kotlin metadata files in it, no class files.  I compared to a couple of the other client feature files, and it doesn't seem right.

The client-auth sources file seems normal, everything is there.  I ran an `rm -rf` on all my io.ktor files in the gradle cache, so everything is fresh from jcenter

**Comment by wyaeld** [comment]
Bit of a further look.  The 1.2.3 and 1.2.4 ktor-client-auth jars on bintray are 6KB and only have metadata files.  The 1.1.5 is 24KB and has the expected class files.  Did something go wrong with packaging?

**Comment by cy6erGn0m** [comment]
These are "common" (multiplatform) jars, in JVM-only projects you usually need "-jvm" suffix

**Comment by wyaeld** [comment]
yep, looks like changing to -jvm fixed it.
I'm not sure whether the instructions make this clear enough, I think the https://ktor.io/clients/http-client/features/auth.html appears about the same since the first version when I started using it, and I wasn't aware that from 1.1.5 to 1.2 it had become a multiplatform library.
But appreciate the help guys.

**Comment by e5l** [comment]
Awesome. Should be fixed by https://github.com/ktorio/ktorio.github.io/pull/215 
Closed
