### ISSUE TITLE
URL Encoding broken since 1.2.0-rc2

### ISSUE THREAD

**Issue by Nohus** [ktorio/ktor#1314]
**Ktor Version and Engine Used (client or server and name)**
Works up to `1.2.0-rc`
Broken since `1.2.0-rc2`

**Describe the bug**
My software is making requests to an API and was working fine, after updating ktor some requests started failing. After lengthy debugging I have found the exact version that broke it, seen above. From this version, URLs started being encoded incorrectly. Further investigating what changed in that update, I have found issue #1094. With some testing I can confirm that the PR that "fixed" that issue broke the encoding. I have isolated it to the `encodeURLPath()` function.

**To Reproduce**
Run `"ü".encodeURLPath()` on `ktor 1.2.0-rc2`, it incorrectly outputs `%C3%BC`.

**Expected behavior**
Run `"ü".encodeURLPath()` on `ktor 1.2.0-rc`, it correctly outputs `%FC`.

As I understand the issue ticket's author was happy with changing this behavior, but it also broke my working code. This is blocking me from updating the library version to `1.2.0`.

I am not arguing which output is correct, it seems both are correct depending on which service is our code talking to, so both should be available.

**Comment by cy6erGn0m** [comment]
Nowadays, URL should be encoded in UTF-8 so `ü` is `0xc3 0xbc` while 0xfc is in ISO-8859-1 that was not correct.

**Comment by cy6erGn0m** [comment]
What is your use-case? Why do you need old encoding and what is broken?

**Comment by Nohus** [comment]
I agree the changed encoding is more modern. But there exist services which use the old one, and ktor should be able to talk to them. I am using the ktor client to talk with a web service which expects the encoding used up to `ktor 1.2.0-rc`. I have no control over that service, so I cannot change the expected encoding.

**Comment by Nohus** [comment]
In JavaScript, `escape("ü")` also produces `%FC`. This may be a legacy encoding, but it's established, and on the web we unfortunately cannot choose what the remote service expects.

**Comment by cy6erGn0m** [comment]
Note that JavaScript's `escape` is deprecated as well (due to many reasons).

**Comment by Nohus** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape
MDN states it's not deprecated, but says "in the absence of legacy usage would be removed". It isn't however deprecated, because it's still (unfortunately) required in many applications.

**Comment by cy6erGn0m** [comment]
So the question is: do we need a way to specify any character encoding (by parameters) or ISO is enough (not clear how it should be represented). 

On JVM the workaround is to use `java.net.URLEncoder.encode(text, charset)`

**Comment by cy6erGn0m** [comment]
Also, note that JavaScript's `escape` is not related to URL/URI percent encoding, it just looks similar but it is completely different because it encodes "long characters" as four-digit HEX number.

**Comment by Nohus** [comment]
I am not sure of the ktor internals, but in my use case the encoding has to be used in the body of POST requests (URL's I request never contain special characters anyway). It seems impossible to choose the encoding with all the nice form DSL's, so I had to construct the `x-www-form-urlencoded` body myself, using ktor's `encodeURLPath()` extension method on the values. Since `1.2.0-rc2` I cannot even encode the values manually. The best solution would be to enable the choice of encoding, something like:

`val request = client.request {
    method = HttpMethod.Post
    encoding = ...
    body = MultiPartFormDataContent(formData {
        append("key", "value")
    })
}`

**Comment by Nohus** [comment]
You are right, JavaScript `escape` might not be a good example, but was just something I found while debugging my issue.

**Comment by Nohus** [comment]
Currently I have to sadly use string manipulation:
`val data = params.map { "${it.key}=${it.value.encodeURLPath()}" }.joinToString("&")`
Otherwise I couldn't encode the values like I need (and with `1.2.0-rc` even that doesn't work).

**Comment by Nohus** [comment]
This issue still stands, I had to switch to making requests with Fuel instead Ktor. Would love to go back to having my service be Ktor-only.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-562">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
I checked the API and see no good ways to support legacy URL encoding along with the correct one. We also can't fix the default one to use a deprecated version.
