### ISSUE TITLE
Setting Content-Length Header manually when using call.respondOutputStream

### ISSUE THREAD

**Issue by greatjack1** [ktorio/ktor#1316]
I am trying to set the Content-Length header when using call.RespondOutputStream, however I get an error "io.ktor.http.UnsafeHeaderException: Header Content-Length is controlled by the engine and cannot be set explicitly".

The issue is that there is no way for the engine to set the header itself since the stream does not provide its size.

So first of all is there a way for me to bypass this somehow in the current release and set the header myself manually?

2. Can we add the ability to set the Content-Length header which would override whatever the engine chooses in a future release?

**Comment by greatjack1** [comment]
Any update on this, still need a solution

**Comment by realdadfish** [comment]
Yep, stumbled upon this as well. I need to pass through data from a server-to-server request to a client and have no way to inform the client on the total download size.

**Comment by andreas-mausch** [comment]
Same problem here.

I was able to work it around like this:

```kotlin
class MyOutputStreamContent(
  private val body: suspend OutputStream.() -> Unit,
  override val contentType: ContentType,
  override val status: HttpStatusCode? = null,
  override val contentLength: Long? = null
) : OutgoingContent.WriteChannelContent() {

  override suspend fun writeTo(channel: ByteWriteChannel) {
    channel.toOutputStream().use { it.body() }
  }
}
```

Sample call (`it` is an InputStream here):

```kotlin
    call.respond(MyOutputStreamContent({ it.copyTo(this) },
        filesystem.contentType(resource), OK, 75))
```

The only change to the original OutputStreamContent is the `override val contentLength`.

This is ugly of course, and it seems like it should be fixable in a one-liner.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-560">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
