### ISSUE TITLE
Optional Parameters not working when serving static files

### ISSUE THREAD

**Issue by d3xter** [ktorio/ktor#132]
embeddedServer(Netty, 3001) {
        routing {
            get("/test/{id?}") {
                it.respond("Test")
            }
        }
    }.start(wait = true)

Requesting `localhost:3001/test`, `localhost:3001/test/` or `localhost:3001/test/1234` works fine.

After static files are served with

            static("/") {
                files(File("web/public"))
            }

a 404 is returned on the first two URLs, only providing id as in the last URL works.

Inside `web/public` there are just two folders `css` and `js`

**Comment by orangy** [comment]
I see… I think we need to revisit routing scoring. The reason here is that both variants – static files and optional (missing) parameter routes has less-than-100% score, because both didn't match exactly. Whichever wins is hard to tell (can't check it right now), but it can't be deterministic enough. E.g. what if user requests `/test/foo/bar` – it matches static files so it should be there. One way is to put static files into another (virtual) directory, i.e. use `static("/public")`

**Comment by d3xter** [comment]
IMHO I'd do it like the following:

First try to find a real file that matches the path.
If none exist, then try to match any dynamic path.

Thats how Joomla does it.

For now I'll just serve both folders with `static("/css")`

**Comment by xnpeng** [comment]
It's critical issue I think. Before introduce static folder, I can write : 
```
@location("/login") class Login(val userId:String,val password:String)
fun Route.loginHandler(){
    get<Login>{
        call.respond(FreeMarkerTamplate("login.ftl",mapOf(...),""))
    }
    post<Login>{
        ...
    }
}
```
we can do get and post request to url "/login". 
When set static folder ``` static("public"){files(".")} ```, the request for "/login" return 404 error.
But , after I change the location class , the request turns right.
``` 
@location("/login") class Signin
@location("/login") class Login(val userId:String,val password:String)
fun Route.loginHandler(){
    get<Sigin>{
        call.respond(FreeMarkerTamplate("login.ftl",mapOf(...),""))
    }

    post<Login>{
        ...
    }
}
```
That means I will rewrite all location class. *Location class for get and post cannot be the same.*

**Comment by cy6erGn0m** [comment]
The first issue is fixed.

**Comment by cy6erGn0m** [comment]
The second issue is not relevant to static content at all. GET /login does return 404 because `Login` class has two _required_ parameters so it should be separated or both userId and password need to be optional with default arguments.
