### ISSUE TITLE
Ktor artifacts in Jcenter cannot be found by Gradle if + is used for the version

### ISSUE THREAD

**Issue by serebit** [ktorio/ktor#1322]
**Describe the bug**
Gradle cannot correctly resolve Ktor dependencies when a version of `+` is provided. This is likely because the Jcenter path for Ktor artifacts does not match the group ID of `io.ktor`, as https://jcenter.bintray.com/io/ktor/ only shows `ktor-utils`, despite all the Ktor artifacts residing in that path (as shown by Gradle with the `--info` flag). This also makes almost all Ktor artifacts incompatible with @ben-manes's Gradle dependency version plugin.

**To Reproduce**
Create a simple Gradle project, add any Ktor dependency besides `ktor-utils`, and specify `+` for the version.

**Expected behavior**
The latest version should be pulled from Jcenter and used for the build.

**Comment by ben-manes** [comment]
Can you try adding Maven Central to your repository listing? JCenter is very annoying by proxying point versions, but not dynamic ranges. This can lead to showing no version or stale versions (as only subset cached). Consider JCenter as a proxy cache and not a source of truth, as its sadly a step backwards from Maven Central.

**Comment by serebit** [comment]
This works with Maven Central, but is still a result of a misconfigured Jcenter repository, and should be fixed.

**Comment by ben-manes** [comment]
For Caffeine, I had taken "ownership" of the JCenter repository to see the stats. Later someone at JCenter asked if they could take it back, since I was still publishing to Central as my workflow. It seems by taking ownership to see metrics, it silently cuts off the proxying and other features by assuming you publish through them (optionally back into Central). If you don't, then their repository handling is busted and it causes weird issues. Maybe something like that happened for ktor?

**Comment by serebit** [comment]
Could be something similar. What's interesting is that Jcenter doesn't show ktor's files in the directory `io/ktor`, including Maven metadata, but when you go directly to the paths of the artifacts, it still allows you to download them directly. For the record, this is also the only project that I've seen this happen with—all other dependencies in my projects that use Jcenter resolve just fine using your plugin and the `+` version.

**Comment by ben-manes** [comment]
Yes, its because they proxy point versions through to Maven Central, making it appear to be hosted directly by them. It doesn't act like a normal repository, or even a sane Artifactory setup. At this point it's a good cache as a fallback repository, but best to always include Central for accuracy.

**Comment by cy6erGn0m** [comment]
Most likely it is something with jcenter link, not ktor itself. We are going to contact support.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-558">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
