### ISSUE TITLE
Kotlin Multiplatform cannot assemble Xcode framework ktor-client-ios 1.2.3

### ISSUE THREAD

**Issue by Stalker11** [ktorio/ktor#1330]
**Ktor Version and Engine Used (client ios)**
io.ktor:ktor-client-core-ios:1.2.3

**Describe the bug**
I work with Kotlin Multiplatform project (Android/IOS). When I assemble Android version it works fine, but when I try to assemble Xcode Framework using task `packForXcode` I have next gradle exception: 

**To Reproduce**

<img width="1042" alt="snapshot 1" src="https://user-images.githubusercontent.com/15062516/64560823-f81d6b00-d351-11e9-9891-59539c50e4f0.png">
<img width="1042" alt="snapshot2" src="https://user-images.githubusercontent.com/15062516/64560851-053a5a00-d352-11e9-8413-e270ff3803c2.png">
<img width="916" alt="snapshot5" src="https://user-images.githubusercontent.com/15062516/64561566-c1485480-d353-11e9-8cfc-2badde43b98b.png">

>ext.kotlin_version = '1.3.50'
>classpath 'com.android.tools.build:gradle:3.5.0'

I have tried to use previous version `io.ktor:ktor-client-core-ios:1.0.0`, but it has problems too:
<img width="1302" alt="snapshot3" src="https://user-images.githubusercontent.com/15062516/64561232-ebe5dd80-d352-11e9-811d-f4e1f87c155a.png">

**Expected behavior**
How I can compile `SharedCode` module to Xcode Framework?

**Comment by e5l** [comment]
Hi @Stalker11, thanks for the report. The artifact `ktor-client-json-ios` was renamed to `ktor-client-json-native` in ktor `1.0`. Could you try it with the new name?

**Comment by Stalker11** [comment]
Hi @e5l unfortunately it didn't help. I have replaced `ios` to `native` in gradle implementations, but I have another error.
<img width="1281" alt="snapshot1" src="https://user-images.githubusercontent.com/15062516/64636855-3e82d080-d40b-11e9-9795-be96a82fa05d.png">
<img width="934" alt="snapshot2" src="https://user-images.githubusercontent.com/15062516/64636872-480c3880-d40b-11e9-8f1a-3d2efdee7a19.png">

**Comment by e5l** [comment]
Ktor `1.2.3` is not compatible with `1.3.50`. Consider using `1.2.4`.

**Comment by Stalker11** [comment]
After updating to version 1.2.4 project was assembled. Thanks a lot.

**Comment by e5l** [comment]
Closed
