### ISSUE TITLE
No way to disable "No ktor.deployment.watch patterns specified" logs

### ISSUE THREAD

**Issue by glasser** [ktorio/ktor#1334]
**Ktor Version and Engine Used (client or server and name)**
Any server

**Describe the bug**
embeddedServer, withTestApplication, etc all use ApplicationEngineEnvironmentBuilder which always creates a ApplicationEngineEnvironmentReloading.  There is no way to tell it "really, I don't want you to reload, I'm aware you have that neat feature but I don't want you to log on startup".

There should be a way to disable reloading.  Additionally, that should probably be the default for withTestApplication.

**Comment by pambrose** [comment]
To remove the warning from your log, add this to your logback.xml file:
```
    <logger name="ktor.application" level="WARN"/>
```

**Comment by glasser** [comment]
I realize that works as a workaround, but there are other INFO logs on the same logger (like "Responding at ..." that are useful for us. I get that you want to advertise the hot reload feature but it's not useful for all ways of using ktor and we should be able to say "I get that hot reloads exist but I don't need to be reminded about them every time".

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-555">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
