### ISSUE TITLE
Reading one byte at a time of a multipart file item's stream reads the first byte every time

### ISSUE THREAD

**Issue by marshallpierce** [ktorio/ktor#1347]
**Ktor Version and Engine Used (client or server and name)**
1.2.4 server, both with NettyEngine (running for real) and the test host. It also happens in 1.3.0-beta-1.

**Describe the bug**
Instead of iterating across the data as you would expect, calling `read()` `n` times just gets the first byte `n` times instead of the first `n` bytes.

**To Reproduce**
- Clone https://bitbucket.org/marshallpierce/ktor-streamprovider-read-repro/src/master/
- `./gradlew check`

**Expected behavior**
The `InputStream` returned from `streamProvider` should follow the contract of `InputStream`.

**Comment by thumannw** [comment]
@marshallpierce: Perfect issue description/data. Should be fixed with PR #1633.

**Comment by thumannw** [comment]
@e5l: please close
