### ISSUE TITLE
Ktor artifacts in Jcenter since 0.9.5-alpha-3-eap13 were removed

### ISSUE THREAD

**Issue by Urugvai** [ktorio/ktor#1349]
**Describe the bug**
Maybe it's expected behaviour but artifacts older 0.9.5-alpha-3-eap13 are absent in https://jcenter.bintray.com/io/ktor/. In the same time they are present in https://kotlin.bintray.com/ktor/io but not all (e.g. ktor-client-cio-1.2.4.jar is absent)

**To Reproduce**
Compare 
https://jcenter.bintray.com/io/ktor/ktor-server-netty/
https://kotlin.bintray.com/ktor/io/ktor/ktor-server-netty/
and
https://jcenter.bintray.com/io/ktor/ktor-server-jetty/
https://kotlin.bintray.com/ktor/io/ktor/ktor-server-jetty/

**Comment by cy6erGn0m** [comment]
This is a bintray issue we are aware of, bintray support is already working on this. As a workarkund, please switch to the maven cemtral (switch or add as the first repo)

**Comment by cy6erGn0m** [comment]
jcenter seems to be fixed
