### ISSUE TITLE
Add an option to disable URL Encoding

### ISSUE THREAD

**Issue by uharaqo** [ktorio/ktor#1351]
**Subsystem**
ktor-client, ktor-http/common

**Is your feature request related to a problem? Please describe.**
ktor-client cannot be used for URLs which are not supported by the URL Encoding format. 

I failed to replace an HTTP client with ktor-client just because we needed to call a URL like `/api?k1=v1;k1=v2` (non-encoded `;` instead of `%3B`). As far as I checked, there's no way to bypass URL Encoding in ktor-client.

In other libraries, typically we can set parameters just like a simple `Map<String, List<String>>`. I agree that it's better to always use a sanitized request object, but it would be too strict not to have an option to disable encoding.

**Describe the solution you'd like**
I opened [a PR to add an option to bypass the URL Encoding](https://github.com/ktorio/ktor/pull/1352) when building a URL.

**Motivation to include to ktor**
I believe that users of ktor-client shouldn't be blocked by the implementation of a server URL because they might not have control over it.

(Please let me know if there's an option to resolve the above problem.)

**Comment by kevincianfarini** [comment]
I agree. In order for me to use ktor-client, I need URL encoding to have an option to be disabled. I would much rather use ktor over retrofit for my use case.

**Comment by kevincianfarini** [comment]
This is my use case for needed this, as commented on the PR. 


> 
> > The only question here: why do we disable escaping at all? The format you mentioned is not URL parameters at all so the only you need is to specify raw query string without parameters. Disabling escaping for sure will lead to security issues and strange bugs.
> 
> My personal use case is that the [bittorrent protocal specifies that data encoded in the URL must be in binary format when making announce calls](https://wiki.theory.org/index.php/BitTorrentSpecification#Tracker_Request_Parameters). It's a binary protocall after all.
> 
> > Note that all binary data in the URL (particularly info_hash and peer_id) must be properly escaped. This means any byte not in the set 0-9, a-z, A-Z, '.', '-', '_' and '~', must be encoded using the "%nn" format, where nn is the hexadecimal value of the byte. (See [RFC1738](http://www.faqs.org/rfcs/rfc1738.html) for details.)
> 
> > For a 20-byte hash of \x12\x34\x56\x78\x9a\xbc\xde\xf1\x23\x45\x67\x89\xab\xcd\xef\x12\x34\x56\x78\x9a.
> 
> > The right encoded form is %124Vx%9A%BC%DE%F1%23Eg%89%AB%CD%EF%124Vx%9A
> 
> So, when I make the following request
> 
> ```kotlin
>         val response = client.get<ByteArray>(announceUrl) {
>             url {
>                 parameters.append("uploaded", uploaded.toString())
>                 parameters.append("downloaded", downloaded.toString())
>                 parameters.append("compact", if (acceptCompact) "1" else "0")
>                 parameters.append(
>                         "info_hash",
>                         infoHash.chunked(2).joinToString("") { "%$it" }
>                 )
>                 parameters.append("peer_id", peerId)
>                 parameters.append("port", port.toString())
>                 parameters.append("left", "${torrentSize - downloaded}")
>             }
>         }
> ```
> 
> I expect that the `%` characters I put in the URl have a way to avoid being encoded. I expect my call to look something like this
> 
> ```
> GET /announce?info_hash=%65%14%5e%d4%d7%45%cf%c9%3f%5f%fe%34%92%e9%cd%e5%4b%55%7d%9f&peer_id=-CR0001-012345678901&uploaded=0&downloaded=0&left= 2082816000&port=6889&compact=1 HTTP/1.1
> Host: torrent.ubuntu.com
> Accept: */*
> Cache-Control: no-cache
> Host: torrent.ubuntu.com
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> cache-control: no-cache
> ```
> 
> but instead I get this.
> 
> ```
> https://torrent.ubuntu.com/announce?uploaded=0&downloaded=0&compact=1&info_hash=%2565%2514%255e%25d4%25d7%2545%25cf%25c9%253f%255f%25fe%2534%2592%25e9%25cd%25e5%254b%2555%257d%259f&peer_id=-CR0001-012345678901&port=0&left=2082816000
> ```
> 
> notice here that the `%` have been encoded. I see no way around this without having a way to disable URL encoding.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-553">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Merged
