### ISSUE TITLE
Receive function not calling initializer blocks

### ISSUE THREAD

**Issue by IronMania-ras** [ktorio/ktor#1353]
**Ktor Version and Engine Used (client or server and name)**
I used Ktor version 1.2.4

**Describe the bug**
When receiving a message and calling 

> call.receive()

The initializer blocks are not called. I use this for validation.

**Expected behavior**
The initializer blocks of my class are called

**Comment by Benjozork** [comment]
We cannot help with one line of code. Please provide a more complete example.

**Comment by cy6erGn0m** [comment]
What serializer do you use? For example, Gson creates instances without calling a constructor.

**Comment by cy6erGn0m** [comment]
However, using [kotlinx.serialziation](https://github.com/Kotlin/kotlinx.serialization) may help to eliminate this limitation since it always instantiates using constructors without black magic.

**Comment by IronMania-ras** [comment]
Yes the problem was using the wrong serializer. I used gson serializer and will now switch to kotlinx.serialization
Thanks @cy6erGn0m

**Comment by cy6erGn0m** [comment]
@IronMania-ras thanks for update! What do you think we can do/improve to avoid confusion here?

**Comment by IronMania-ras** [comment]
@cy6erGn0m I think more it was my own stupidity :-)
it is written in the documentation that `call.receive<>()` uses content negotiation so I could have come to that solution earlier.
