### ISSUE TITLE
Ktor does not work with latest R8 version (using Android Studio 3.6.0-alpha12)

### ISSUE THREAD

**Issue by Thomas-Vos** [ktorio/ktor#1354]
**Ktor Version and Engine Used (client or server and name)**
- io.ktor:ktor-client-android:1.2.4
- io.ktor:ktor-client-okhttp:1.2.4

**Describe the bug**
A call to client.get never returns when R8 is enabled. This started since Android Studio 3.6.0 canaries.

**To Reproduce**
1. Open [this sample project](https://github.com/ktorio/ktor/files/3639885/KtorR8Bug.zip) (requires Android Studio 3.6 canary 12)
2. Run the app (R8 is enabled for debug apk)
3. The app should crash with a message "This code is never reached" in MainActivity. However that does not happen. Disabling R8 "fixes" the issue.

**Expected behavior**
I expect Ktor not to deadlock when calling client.get.

**Comment by Thomas-Vos** [comment]
I am not sure if this is an R8 or Ktor issue, so I reported it to R8 as well: https://issuetracker.google.com/issues/141416122

**Comment by christofferqa** [comment]
This happens due to missing Proguard configuration rules in kotlinx.coroutines.

Adding the following rule as suggested in https://github.com/Kotlin/kotlinx.coroutines/issues/1564 solves the issue.
```
-keepclassmembers class kotlinx.** {
    volatile <fields>;
}
```

**Comment by cy6erGn0m** [comment]
@christofferqa I would say you also need to do the same with `io.ktor.**` classes

**Comment by christofferqa** [comment]
@cy6erGn0m I am not aware of the reflection performed by `io.ktor.**` - maybe one of the developers of ktor can comment on that. Unless the ktor library is also performing some reflection, I do not see why that rule should be needed for `io.ktor.**` classes, though.

**Comment by cy6erGn0m** [comment]
It's not about reflection, it's because of java's `Atomic*Updater` .

**Comment by christofferqa** [comment]
Any update on this? As mentioned previously this should be a one line fix.

Also, please note that `Atomic*Updater` _is_ reflection, as mentioned in the very first line of the docs, https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicReferenceFieldUpdater.html.

**Comment by cy6erGn0m** [comment]
I believe this should work with 1.2.5: both kotlinx-io and ktor have required rules in the jars.

**Comment by clhols** [comment]
I faced a similar issue with ktor 1.3.0-beta-1, where I couldn't enable "proguard-android-optimize" as it would make the ktor client hang on requests.

And indeed adding the following rule fixes the issue:
`-keepclassmembers class io.ktor.** {
    volatile <fields>;
}`

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-552">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Here is the tutorial on how to write the configuration: https://ktor.io/docs/proguard.html
