### ISSUE TITLE
GET request without body (EmptyContent) results in error on iOS 13

### ISSUE THREAD

**Issue by alekseychugaev** [ktorio/ktor#1365]
**Ktor Version and Engine Used (client or server and name)**
ktor_version=1.3.0-beta-1
kotlin_version=1.3.50
implementation "io.ktor:ktor-client-ios:$ktor_version"
implementation "io.ktor:ktor-client-core-native:$ktor_version"
implementation "io.ktor:ktor-client-json-native:$ktor_version"
implementation "io.ktor:ktor-client-serialization-native:$ktor_version"

**Describe the bug**
When sending a GET request without any body, the resulting request still contains body as `{}`.
My request:
```
client.get<MyResponse>("$apiEndpoint/summary?v=1") {
    contentType(ContentType.Application.Json)
}
...
```
Logs:
```
REQUEST: http://0.0.0.0:8080/summary?v=1
METHOD: HttpMethod(value=GET)
COMMON HEADERS
-> User-Agent: timezone=Australia/Melbourne;
-> Authorization: d0460e3b-8ef7-4cd5-bf03-f02feb109ace
-> Accept: application/json
-> Accept-Charset: UTF-8
CONTENT HEADERS
BODY Content-Type: application/json
BODY START
{}
BODY END
```
Looks like iOS 13 does not allow body content for GET requests, so as a result the client fails with error: 
```
GET method must not have a body
finished with error [-1103] Error Domain=NSURLErrorDomain Code=-1103 "resource exceeds maximum size"
```
Another way to reproduce:
```
val unitJson = KotlinxSerializer().write(Unit)
println("$unitJson")
```

**Expected behavior**
When request body for a GET request is specified as `var body: Any = EmptyContent` the actual body sent by ktor should be empty.

From what I can see the body is created here:
https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-features/ktor-client-json/common/src/io/ktor/client/features/json/JsonFeature.kt#L100
It tries to serialize a Unit object.

**Comment by cy6erGn0m** [comment]
In terms of json, an empty content is `{}` so I see no error here.

**Comment by alekseychugaev** [comment]
Removing content-type from request worked, thanks for your help.

**Comment by cy6erGn0m** [comment]
Didn't you mean Accept instead of Content-Type?

**Comment by alekseychugaev** [comment]
I think it was just a copy/paste of a post request I had. It worked fine with Xcode 10.x (so I didn't notice it), but started failing after upgrading to Xcode 11.

**Comment by e5l** [comment]
The issue fixed with https://github.com/ktorio/ktor/commit/0aea4267fac7e95882002c4e9c5d6a5653d1f8ec
Closed
