### ISSUE TITLE
Caching on ContentType.Image.Any does not send back Cache-Control headers for JPEG images

### ISSUE THREAD

**Issue by janvladimirmostert** [ktorio/ktor#1366]
KtorVersion=1.1.3
Engine=Netty (ServerSide)

When installing the CachingHeader, shall i call it plugin, and trying to match all images, none of the images come back with Cache-Control headers.
When i change `ContentType.Image.Any` to `ContentType.Image.JPEG, JPEG images come back with the correct `Cache-Control` headers which means `Any` is not matching images correctly.

I've posted sample code on StackOverflow with screenshots of the missing headers:
https://stackoverflow.com/questions/57978856/respond-with-cache-headers-for-images-in-ktor

TLDR, this works (for JPEG only):
```
install(CachingHeaders) {
    options { outgoingContent ->
        when (outgoingContent.contentType?.withoutParameters()) {
            ContentType.Image.JPEG -> CachingOptions(
                cacheControl = CacheControl.MaxAge(
                mustRevalidate = false,
                maxAgeSeconds = 30 * 24 * 60 * 60,
                visibility = CacheControl.Visibility.Public)
            )
            else -> null
        }
    }
}
```

This does not work:

```
install(CachingHeaders) {
    options { outgoingContent ->
        when (outgoingContent.contentType?.withoutParameters()) {
            ContentType.Image.ANY -> CachingOptions(
                cacheControl = CacheControl.MaxAge(
                mustRevalidate = false,
                maxAgeSeconds = 30 * 24 * 60 * 60,
                visibility = CacheControl.Visibility.Public)
            )
            else -> null
        }
    }
}
```

**Comment by cy6erGn0m** [comment]
When operator does `equals()` check while Any correspond do "*" that is not equal to any other string than "*" itself. Instead, use `ContentType.match`

**Comment by janvladimirmostert** [comment]
I was under the impression that a lot more was happening under the covers than just an equal check, changing to match fixes the issue for me

```
	install(CachingHeaders) {
		options { outgoingContent ->
			if (outgoingContent.contentType?.withoutParameters()?.match(ContentType.Image.Any) == true) {
				CachingOptions(
					cacheControl = CacheControl.MaxAge(
						mustRevalidate = false,
						maxAgeSeconds = 6 * 30 * 24 * 60 * 60,
						visibility = CacheControl.Visibility.Public
					)
				)
			} else {
				null
			}
		}
	}
```
