### ISSUE TITLE
How to handle exception and get response

### ISSUE THREAD

**Issue by Platun0v** [ktorio/ktor#1371]
I'm making simle request to the server, and server can send just json response or json response and 409 error. And in both situations I need to get response. I tryed to make something like this:
```
try {
    val response = client.submitForm<Response>(url, params) {
        standardRequestParameters(url)
    }
 } catch (cause: ClientRequestException) {
    println("Error")
 }
```
But it doesn't work. Can you help me?

**Comment by cy6erGn0m** [comment]
See https://ktor.io/clients/http-client/features/response-validation.html for the explanation why it doesn't work

**Comment by Platun0v** [comment]
Thanks! Now it works :)
