### ISSUE TITLE
ktor-client-curl project is difficult to develop/test

### ISSUE THREAD

**Issue by JLLeitschuh** [ktorio/ktor#1372]
There are a few issues I've run into running and adding new tests to the `CurlNativeTests`.

 1. Adding a new test that fails does not give you the full stack trace of the failure, only the class name for the failure. This make it impossible to determine why your test has failed.
 2. It's impossible to configure the `:ktor-client:ktor-client-curl:posixTest` or even figure out what type it is because when executing the task from the command line, Gradle can't find it. However the task can be executed in IJ for some weird reason. This means that it's impossible to figure out what task needs to be configured in order to potentially fix the above issue.
 3. Adding print statements to the `CurlNativeTests` produces no output in the Gradle console log.

**Comment by cy6erGn0m** [comment]
1. Run the corresponding kexe file directly for debugging, use lldb if necessary. For example, curl test kexe could be here: `ktor-client/ktor-client-curl/build/bin/linuxX64/debugTest/test.kexe`
2. Depending on you platform, run `......:linuxX64Test` or `macosX64Test`
3. This is very common Gradle _feature_, run with `-i` option

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-548">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
