### ISSUE TITLE
start.ktor.io Gradle build uber JAR

### ISSUE THREAD

**Issue by saturnism** [ktorio/ktor#1381]
**Is your feature request related to a problem? Please describe.**

start.ktor.io Maven generator already produces a pom.xml that will build an uber JAR. Uber JAR is helps deploy/run the app easily.

**Describe the solution you'd like**
When generating for Gradle tool, also produce the uber JAR.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-547">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Hey, here is a guide on the website: https://ktor.io/docs/fatjar.html
