### ISSUE TITLE
Ktor fails to parse date in cookie header

### ISSUE THREAD

**Issue by varahash** [ktorio/ktor#1382]
**Ktor Version and Engine Used (client or server and name)**
1.2.5 and 1.3.0-beta-1, client

**Describe the bug**
Ktor unable parse date when it contains two digits year format. In particular request failed with following exception:
```
    java.lang.IllegalStateException: Failed to parse date: Sat, 03-Jan-70 00:00:00 GMT
        at io.ktor.http.DateUtilsKt.fromHttpToGmtDate(DateUtils.kt:37)
        at io.ktor.http.CookieKt.parseServerSetCookieHeader(Cookie.kt:78)
        at io.ktor.http.HttpMessagePropertiesKt.setCookie(HttpMessageProperties.kt:96)
        at io.ktor.client.features.cookies.HttpCookies$Companion$install$2.invokeSuspend(HttpCookies.kt:73)
        at io.ktor.client.features.cookies.HttpCookies$Companion$install$2.invoke(Unknown Source:14)
```

**Expected behavior**
Ktor must support two digit year format. You can look at okhttp implementation:
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/dates.kt

**Comment by cy6erGn0m** [comment]
This is quite old USENET/UUCP date format specified by RFC850. Nowadays, nobody knows what USENET is. No HTTP server should generate dates in this format since it **violates** the HTTP specification. 

However, we could support this format for backward compatibility with some ancient services. The question is: what are these services and why they still do like that?

**Comment by varahash** [comment]
Actually there is official [RFC6265](https://tools.ietf.org/html/rfc6265) document which defines the HTTP Cookie and Set-Cookie header fields. According to this section https://tools.ietf.org/html/rfc6265#section-5.1.1, the date format is very flexible:
```
   cookie-date     = *delimiter date-token-list *delimiter
   date-token-list = date-token *( 1*delimiter date-token )
   date-token      = 1*non-delimiter

   delimiter       = %x09 / %x20-2F / %x3B-40 / %x5B-60 / %x7B-7E
   non-delimiter   = %x00-08 / %x0A-1F / DIGIT / ":" / ALPHA / %x7F-FF
   non-digit       = %x00-2F / %x3A-FF

   day-of-month    = 1*2DIGIT ( non-digit *OCTET )
   month           = ( "jan" / "feb" / "mar" / "apr" /
                       "may" / "jun" / "jul" / "aug" /
                       "sep" / "oct" / "nov" / "dec" ) *OCTET
   year            = 2*4DIGIT ( non-digit *OCTET )
   time            = hms-time ( non-digit *OCTET )
   hms-time        = time-field ":" time-field ":" time-field
   time-field      = 1*2DIGIT
```
I think Ktor should either compliant to this RFC6265 or provide customization point where end user can setup custom date formats/parser.

**Comment by cy6erGn0m** [comment]
I see where the confusion comes from: MDN says completely different!

> The maximum lifetime of the cookie as an HTTP-date timestamp. See [Date](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date) for the required formatting.

While `Date` header is HTTP-date with only one particular date format ending with GMT suffix. 

MDN seems to be wrong here and we probably did just like it is specified in MDN rather than RFC :(
