### ISSUE TITLE
Ktor Client Digest Auth Missing "qop" and "end" tokens in "response" parameter. Not RFC2617 Compliant

### ISSUE THREAD

**Issue by runt9** [ktorio/ktor#1385]
**Ktor Version and Engine Used (client or server and name)**
ktor-client-auth 1.2.5

**Describe the bug**
```
val client = HttpClient(Apache) {
    install(Auth) {
        digest {
            username = "user"
            password = "pass"
            realm = "realm"
       }
   }
}
```

Using this code does not properly handle Digest authentication. The reason why is located [right here](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt#L86). The non-null qop should include the qop and the end variable in the token.

If you take a look at the [RFC 2617 here](https://tools.ietf.org/html/rfc2617#section-3.2.2.1), the request-digest states the following:

```
If the "qop" value is "auth" or "auth-int":

      request-digest  = <"> < KD ( H(A1),     unq(nonce-value)
                                          ":" nc-value
                                          ":" unq(cnonce-value)
                                          ":" unq(qop-value)
                                          ":" H(A2)
                                  ) <">
```

Notice the qop-value and H(A2) there. That's what's missing. Interestingly enough, it's implemented correctly in the [ktor server side code](https://github.com/petertulala/ktor/blob/master/ktor-features/ktor-auth/src/io/ktor/auth/DigestAuth.kt#L156)

It's a simple enough fix and I've already forked and will work on a PR for this, but my VM is running out of memory trying to build the project so it may take a bit. But it really should be as simple as doing the following diff:

```
diff --git a/ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt b/ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt
index 6ed33248f..1a12248dc 100644
--- a/ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt
+++ b/ktor-client/ktor-client-features/ktor-client-auth/common/src/io/ktor/client/features/auth/providers/DigestAuthProvider.kt
@@ -83,7 +83,7 @@ class DigestAuthProvider(
 
         val start = hex(credential)
         val end = hex(makeDigest("$methodName:${url.encodedPath}"))
-        val tokenSequence = if (actualQop == null) listOf(start, nonce, end) else listOf(start, nonce, nonceCount, clientNonce)
+        val tokenSequence = if (actualQop == null) listOf(start, nonce, end) else listOf(start, nonce, nonceCount, clientNonce, actualQop, end)
         val token = makeDigest(tokenSequence.joinToString(":"))
 
         val auth = HttpAuthHeader.Parameterized(AuthScheme.Digest, linkedMapOf<String, String>().apply {
```

**Comment by cy6erGn0m** [comment]
Thank you for your investigation and detailed explanation

**Comment by HolzmanoLagrene** [comment]
Hi @runt9 
We are currently dealing with similar issues. Have you managed to digest authentication to run with your fixes? We tried to implement your solution, but so far couldn't get it to work.
Cheers!

**Comment by runt9** [comment]
Hello @HolzmanoLagrene 

Even with making this fix, my digest authentication is still not working correctly. I've yet to deduce why, so unfortunately the total fix for digest auth is not just what I mentioned in my original post. I'm going to keep investigating and see if I can pin down the whole problem. If/when I do, I'll be sure to open a Pull Request for the full fix.

**Comment by cyrillhalter** [comment]
Hi all,

@HolzmanoLagrene worked on this for a bit and managed to fix the problem. @runt9 your solution was absolutely correct but in addition to fixing the digest response, the nonceCount and qop also had to be added to the authentication header. 

Cheers!

**Comment by e5l** [comment]
Merged.
