### ISSUE TITLE
Unexpected Behavior for call.receiveOrNull

### ISSUE THREAD

**Issue by jkratz55** [ktorio/ktor#1389]
**Ktor Version and Engine Used (client or server and name)**

```
ext.kotlin_version = '1.3.50'
ext.ktor_version = '1.2.4'

mainClassName = "io.ktor.server.netty.EngineMain"

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile "io.ktor:ktor-server-netty:$ktor_version"
    compile "ch.qos.logback:logback-classic:$logback_version"
    compile "io.ktor:ktor-server-core:$ktor_version"
    compile "io.ktor:ktor-jackson:$ktor_version"
    compile "io.ktor:ktor-locations:$ktor_version"
    compile "io.ktor:ktor-metrics:$ktor_version"
    testCompile "io.ktor:ktor-server-tests:$ktor_version"
}
```

**Describe the bug**

According to the documentation for call.recieveOrNull if the content cannot be transformed to the requested type it should return null. But what I am observing is if the JSON payload doesn't match the expected request I get `com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException`. If the request body is empty I get `com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input.` 

Based on the documentation my expectation is that if deserialization failed it should return a null but instead an exception is being thrown which causes the server to return HTTP 500. In this case, HTTP 400 should be the appropriate response as it was a bad request. 

```
Receives content for this request.
Params:
    type - instance of KClass specifying type to be received.
Returns:
    instance of T received from this call, or null if content cannot be transformed to the requested type.
```

**To Reproduce**

Sample code provided below

1. Send POST /encrypt with empty JSON body
2. Send POST /encrypt with JSON body doesn't match the expected format

```
package io.jkratz

import io.ktor.application.*
import io.ktor.response.*
import io.ktor.request.*
import io.ktor.routing.*
import io.ktor.http.*
import com.fasterxml.jackson.databind.*
import io.ktor.jackson.*
import io.ktor.features.*
import io.ktor.locations.*
import org.slf4j.event.*

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@Suppress("unused") // Referenced in application.conf
@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    install(ContentNegotiation) {
        jackson {
            enable(SerializationFeature.INDENT_OUTPUT)
        }
    }

    install(Locations) {
    }

    install(CallLogging) {
        level = Level.INFO
        filter { call -> call.request.path().startsWith("/") }
    }

    install(DataConversion)

    routing {

        get("/ping") {
            call.respond(HttpStatusCode.OK)
        }

        post("/encrypt") {
            val payload = call.receiveOrNull(EncryptDecryptResquest::class)
            payload ?: call.respond(HttpStatusCode.BadRequest)
            payload?.let {
                call.respond(HttpStatusCode.OK, EncryptDecryptResponse(payload.message))
            }
        }
    }
}

data class EncryptDecryptResquest(val message: String, val algorithm: String)
data class EncryptDecryptResponse(val message: String)
```

**Expected behavior**
As the document states an instance of T received from this call should be returned, or null if content cannot be transformed to the requested type.

There should be a graceful way to handle deserializing request payloads, so if there are other ways to handle this I'd be open to hearing about it. I expect to have a way to attempt deserialization gracefully, and if it fails to return an appropriate HTTP status.

**Comment by cy6erGn0m** [comment]
Unfortunately, the documentation is not clear enough here: it returns `null` if _negotiation_ failed and no transformation actually applied. So one can retry after `null` returned.

However, in your case you have a broken content or configuration that causes deserializer to fail and the body is partially consumed so there is no way to retry. So for sure we are not able to return `null` in this case.

The reason why we produce 500 instead of 400 is that there are different kinds of errors (Jackson, IO and some potential infrastructure errors) that not easy to distinguish. Perhaps, we could wrap all `JsonMappingException` to `BadRequestException` so it will cause 400 page instead of 400.

**Comment by jkratz55** [comment]
Thanks for the quick feedback.

I've created an extension method to wrap the handler code. Is there any sort of best practices documented around receiving data from a request in Ktor? I think this would useful to highlight.

```
fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@Suppress("unused") // Referenced in application.conf
@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    install(ContentNegotiation) {
        jackson {
            enable(SerializationFeature.INDENT_OUTPUT)
        }
    }

    install(Locations) {
    }

    install(CallLogging) {
        level = Level.INFO
        filter { call -> call.request.path().startsWith("/") }
    }

    install(DataConversion)

    routing {

        get("/ping") {
            call.respond(HttpStatusCode.OK)
        }

        post("/encrypt") {
            try {
                val payload = call.receiveOrNull(EncryptDecryptResquest::class)
                payload ?: call.respond(HttpStatusCode.BadRequest)
                payload?.let {
                    call.respond(HttpStatusCode.OK, EncryptDecryptResponse(payload.message))
                }
            } catch (e: IOException) {
                call.respond(HttpStatusCode.BadRequest, "Bad Request")
            }
        }

        post("/decrypt") {
            errorAware {
                val payload = call.receive<EncryptDecryptResquest>()
                call.respond(HttpStatusCode.OK, EncryptDecryptResponse(message = payload.message))
            }
        }
    }
}

data class EncryptDecryptResquest(val message: String, val algorithm: String)
data class EncryptDecryptResponse(val message: String)

private suspend fun PipelineContext<*, ApplicationCall>.errorAware(block: suspend  () -> Unit) {
    return try {
        block()
    } catch (e: Exception) {
        when (e) {
            is IOException -> call.respond(HttpStatusCode.BadRequest, "Bad request")
            else -> call.respond(HttpStatusCode.InternalServerError, "Application has encountered an unexpected exception while processing your request")
        }
    }
}
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-545">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
