### ISSUE TITLE
Sudden clusters of Channel failed logs

### ISSUE THREAD

**Issue by brezinajn** [ktorio/ktor#1391]
**Ktor Version and Engine Used (client or server and name)**
versions: 1.2.4, 1.2.5
modules: server-netty, jackson, auth, locations

**Describe the bug**
In seemingly random intervals I'm seeing batches of logs `/route-name, channel failed`. I've tracked the source of the log to [here].(https://github.com/ktorio/ktor/blob/424d1d2cfaa3281302c60af9500f738c8c2fc846/ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/DefaultEnginePipeline.kt#L103)
I'm unable to reproduce the behavior on my local machine. That makes me belive it might happen due to high load. Since the message does not offer much insight to what is happening, I'm unable to properly analyse the problem.

**To Reproduce**
Not sure

**Expected behavior**
Clear message what is happening.

**Screenshots**

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-544">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
