### ISSUE TITLE
Inconsistent behaviour of Headers::getAll(String)

### ISSUE THREAD

**Issue by Koriit** [ktorio/ktor#1397]
**Ktor Version and Engine Used (client or server and name)**
ktor-server-core:1.2.5
ktor-server-netty:1.2.5
ktor-server-cio:1.2.5

**Describe the bug**
There is an inconsistency in `Headers::getAll(String)`(actually `StringValues::getAll(String)`). The KDoc says:

> Gets all values associated with the [name], **or null if the name is not present**

The problem is that for both CIO and Netty engines it is never null. Even if **name** was not present empty collection is returned.

For Netty this behaviour is defined in `io.netty.handler.codec.HeadersUtils::getAllAsString`.
For CIO in `io.ktor.http.cio.HttpHeadersMap::getAll`

**Expected behavior**
I would expect this function to actually work as its own KDoc says.

**Comment by Koriit** [comment]
Actually returning null if name is not present would be nice to have.

**Comment by Koriit** [comment]
I guess this was fixed with #1399 ? If I am correct, this was included in 1.3.0 release?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-542">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Yep
