### ISSUE TITLE
Ability to use browser cookie storage

### ISSUE THREAD

**Issue by DaanVandenBosch** [ktorio/ktor#1403]
**Subsystem**
ktor-client-js

**Is your feature request related to a problem? Please describe.**
I need to be able to store cookies between sessions in a browser.

**Describe the solution you'd like**
A cookie store that uses the browser's cookie storage. Possibly by simply adding `credentials: "include"` to the fetch request.

**Motivation to include to ktor**
A common requirement in web applications is to use the browser's cookie storage (so e.g. authentication cookies can be preserved between sessions). By default the client seems to use an in-memory cookie store and there seems to only be a constant cookie store alternative.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-539">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
