### ISSUE TITLE
Documentation for deployment

### ISSUE THREAD

**Issue by rakshakhegde** [ktorio/ktor#141]
https://github.com/Kotlin/ktor/wiki/Application-Hosting#deploying-the-hosted-application is incomplete. How to use `application.conf` file?

**Comment by johdah** [comment]
I agree, and it would be helpful to get more on how to run it in docker, as a fat jar or something similar.

**Comment by WangChangQin** [comment]
I want to know how to run it in Tomcat +1

**Comment by HudsonAfonso** [comment]
I want to know how to run it in Tomcat +1

**Comment by frendyxzc** [comment]
And how to run it in Resin...

**Comment by thomasnield** [comment]
Here's an article on deploying it to Heroku. Haven't tried this yet but going to this weekend. I'll see if I can contribute on that front... 

https://jkutner.github.io/2017/04/10/kotlin-heroku-ktor.html

**Comment by soywiz** [comment]
I have covered fat jars, war files, jetty, tomcat, docker, nginx, proguard, heroku and google app engine:
https://ktor.io/servers/deploy.html

Feel free to open new issues if you find that the explanations are not clear or you want to see how to integrate with other engines/providers.
