### ISSUE TITLE
Unable to mark css rule as !important using CSS DSL

### ISSUE THREAD

**Issue by alexvas** [ktorio/ktor#1416]
Ktor website contains an example of [css dsl usage](https://ktor.io/samples/other/css-dsl.html).
I'm using the [latest library version](https://bintray.com/kotlin/kotlin-js-wrappers/kotlin-css-jvm/1.0.0-pre.86-kotlin-1.3.50) available and unable to write `!important` directive, like:

```css
background: white !important;
```
Is there anything I missing or CSS DSL is just not ready for production?

**Comment by cy6erGn0m** [comment]
Most likely the library is incomplete.

Could you please reopen it against the library instead https://github.com/JetBrains/kotlin-wrappers ?

**Comment by alexvas** [comment]
resolved:

> If you really need `!important`, you can always do `put("background", "white !important")`.
