### ISSUE TITLE
Ping/Pong is not working or isn't implemented correctly(in server side), and in client side there is no option to configure it either.

### ISSUE THREAD

**Issue by Animeshz** [ktorio/ktor#1418]
**Ktor Version and Engine Used (client or server and name)**
1.2.5, client&server, websockets

**Describe the bug**
There is an option of pingInterval in configuration of WebSocket (server side), but it doesn't seems to do anything buffering client and server side none of them seem to receive pings

**To Reproduce**
Steps to reproduce the behavior: Write the following and run
***Serverside:***
```kotlin
install(WebSockets) {
	pingPeriod = Duration.ofSeconds(30)
	timeout = Duration.ofSeconds(15)
}

routing {
	webSocket("ws") {
		for(frame in incoming)
		{
			if(frame is Frame.Ping)
			{
				println(frame)
				println("ping recieved")
			}
		}
	}
}
```
***Clientside:***
```kotlin
val client = HttpClient(CIO) {
	install(WebSockets)
}

client.ws(
	method = HttpMethod.Get,
	host = "127.0.0.1",
	port = 80,
	path = "/ws"
) {
	for (frame in incoming)
	{
		when (frame)
		{
			is Frame.Ping ->
			{
				println("ping received")
			}
		}
	}
}
```

**Expected behavior**
It was expected to receive ping frames and println of ping recieved should be printed in console every 30 seconds

**Comment by e5l** [comment]
Hi @Animeshz, `DefaultWebSocketSession` filter ping and pong messages. If you want to receive it consider using `RawWebSocketSession`.

**Comment by Animeshz** [comment]
@e5l how to use one any example?

**Comment by fouady** [comment]
> Hi @Animeshz, `DefaultWebSocketSession` filter ping and pong messages. If you want to receive it consider using `RawWebSocketSession`.

Does this mean that the documentation here is not correct? 
https://api.ktor.io/1.2.6/io.ktor.http.cio.websocket/-default-web-socket-session/index.html

**Comment by dmitrievanthony** [comment]
Hi @Animeshz, @fouady.

Well, firstly the main idea. You can use a WebSocket with `DefaultWebSocketSession` writing code like the following:

```
// Client.
client.ws("ws://localhost/socket") { ... }

// Server.
webSocket("socket") { ... }
```

In this case, as it said in the documentation WebSocket session does ping-pong processing. It means that server and client exchange ping-pong messages automatically without your's interaction and in case of timeout closes the connection. It's done automatically, so ping-pong frames are not propagated to your code.

On the other hand, you can use a WebSocket with `RawWebSocketSession` that does not do all these things automatically and delegates it to your code. To use this approach your code should look like:

```
// Client.
client.webSocketRaw("ws://localhost/socket") { ... }

// Server.
webSocketRaw("socket") { ... }
```

In this scenario, you need to manually send ping and respond to them with a pong message:

```
webSocketRaw("ws") {
    for (frame in incoming) {
        if (frame is Frame.Ping) {
            send(Frame.Pong(frame.buffer))
        }
    }
}
```

I hope it will help you. @e5l , please correct me if I'm wrong.

**Comment by fouady** [comment]
@dmitrievanthony Thanks a lot. This makes it much clearer. The lack of propagation of the Ping Pong frames is what caused this confusion. Thanks for the explanation.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-535">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
