### ISSUE TITLE
hex() accepts invalid HEX strings

### ISSUE THREAD

**Issue by pvasin2** [ktorio/ktor#1422]
Result of `hex(hex("1234鼠"))` is "1234". The expected result is an exception.

**Comment by e5l** [comment]
Hi @pvasin2, thanks for the report. This is `ExperimentalApi` and we probably should note behavour in the docs

**Comment by pvasin2** [comment]
@e5l Why not check length and keep API public?

**Comment by e5l** [comment]
It won't cover all edge cases and has unexpected behavior.
On the other side full `Charset` support costs a lot in our use cases.

**Comment by e5l** [comment]
We actually can make different methods for that, but it doesn't look like the HTTP client-server stuff and probably should be in other libraries. 

Closed until we have the use cases.
