### ISSUE TITLE
Is there a a way to read application.conf variables without application context?

### ISSUE THREAD

**Issue by AdityaAnand1** [ktorio/ktor#1448]
E.g:

```environment.config.property("ktor.keys.aws_access_key_id").getString()```

can only be done inside `fun Application.module()`. What about the use case where the variables are needed outside of the application context? Say, some periodic jobs (crons).

**Comment by AdityaAnand1** [comment]
Can there be a way to leverage `System.getEnv()` and sort of seed the environment variables with application conf's contents at server startup?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-523">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
I'm not sure that we're going to support using config outside of the application. Consider reading the configuration file with an external tool instead.
