### ISSUE TITLE
Kotlin 1.3.60 Update

### ISSUE THREAD

**Issue by hfhbd** [ktorio/ktor#1450]
Release a new Version/Beta with Kotlin Version 1.3.60

Kotlin Native needs the same ABI Versions.

ktor-client-serialization.klib: The abi versions don't match. Expected '[17]', found '14'

**Comment by IgorKey** [comment]
Guuuyyys, the official release was 3 days ago, I really need some features from 1.3.60 for native side. I can't find even EAP version with 1.3.60 support. How long will update take?

**Comment by LifeIsStrange** [comment]
I'm not using Kotlin native but Kotlin JVM, can I safely update to 1.3.60 or might I hit ktor bugs ?

**Comment by ewaldhorn** [comment]
I'm running 1.3.60 with KTor on Android and it's working perfectly.  My Native project is broken on the iOS side, but it compiles perfectly for Android, so I think you should be safe.

**Comment by e5l** [comment]
Ktor: 1.2.6 release with 1.3.60 support.

**Comment by LifeIsStrange** [comment]
@e5l the release miss the latest update tag and a changelog.
Github still believe the latest stable release is the 1.3.50

![Screenshot_20191123_012504_com kiwibrowser browser](https://user-images.githubusercontent.com/12934716/69469280-49a19780-0d90-11ea-9b55-3919d7e2fa93.jpg)
