### ISSUE TITLE
Expose some of the NSURLSessionDelegate's callbacks

### ISSUE THREAD

**Issue by matteomatassoni** [ktorio/ktor#1453]
**Subsystem**
iOS Client

**Is your feature request related to a problem? Please describe.**
handling authentication challenges (certificate pinning, ...).

**Describe the solution you'd like**
Expose some of the `NSURLSessionDelegate`'s callbacks. At least: `URLSession:didReceiveChallenge:completionHandler:`.

**Motivation to include to ktor**
To handle authentication challenge, certificate pinning, ...

**Comment by e5l** [comment]
Callback exposed in `master`. It will be available in next minor release.
