### ISSUE TITLE
Client MPP Socket Support

### ISSUE THREAD

**Issue by LookLotsOfPeople** [ktorio/ktor#1454]
**Subsystem**
Common Client

**Is your feature request related to a problem? Please describe.**
https://github.com/ktorio/ktor/issues/1121

**Describe the solution you'd like**
Has there been any development on the common support for sockets? The issue above was added to 1.3.0 milestone, but this has not been added to the patch notes nor is in the beta.

**Motivation to include to ktor**
Client sockets will help communicate with the raw sockets from server as well as external APIs which use sockets for voice or audio.

**Comment by e5l** [comment]
Hi @LookLotsOfPeople, WIP: https://github.com/ktorio/ktor/tree/e5l/cio-common

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-521">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Native socket support was introduced in `1.4.0`
