### ISSUE TITLE
CIO client half-closes the TCP connection after the request send

### ISSUE THREAD

**Issue by rocketraman** [ktorio/ktor#1456]
**Subsystem**
Client, CIO

**Is your feature request related to a problem? Please describe.**
It is to some extent. I had an issue with an outbound proxy when using the CIO client. Upon investigation of the packet dump, I saw that the CIO client half-closes the TCP connection immediately after the request is sent. Upon further research, it appears there is debate in the HTTP community about whether this is "legal" or not for HTTP clients to do, but consensus that for best compatibility its probably not a good idea [1].

[1] See https://github.com/httpwg/http-core/issues/22.

**Describe the solution you'd like**
Do not half-close client connections once the request has been sent. Leave the connection open until after the response has been received.

**Motivation to include to ktor**
As per the linked discussion above in the HTTP WG, it is odd for HTTP clients to do this, and the WG recommends that clients do not do it.

**Comment by dmitrievanthony** [comment]
Hi @rocketraman,

I've just merged fix that allows avoiding TCP half-closes (see https://github.com/ktorio/ktor/pull/1489), so it will be included in `1.3.0`.
