### ISSUE TITLE
R8 issue with 1.3.0-beta-2

### ISSUE THREAD

**Issue by clhols** [ktorio/ktor#1459]
**Ktor Version and Engine Used (client or server and name)**
Ktor client 1.3.0-beta-2 and Kotlin 1.3.60.

**Describe the bug**
Build fails when doing a release build with R8 enabled.

**To Reproduce**
1. Android build with R8 enabled of https://github.com/clhols/drchannels
2. Build fails with:
```
> Task :androidApp:minifyTvReleaseWithR8 FAILED
/Users/clhols/.gradle/caches/transforms-2/files-2.1/eb2868bc900946520016992f2bc02591/rules/lib/META-INF/proguard/ktor.pro:11:7: R8: Expected [!]interface|@interface|class|enum
```

**Expected behavior**
Build should succeed.

**Comment by e5l** [comment]
Fixed in `master`
