### ISSUE TITLE
Ktor scaffolder needs to be updated

### ISSUE THREAD

**Issue by LifeIsStrange** [ktorio/ktor#1463]
I used the intellij plugin version of https://start.ktor.io/#
The default gradlew use a very old version of gradle (4.10).
And Kotlin version 1.2.60 !!

Moreover, the build if broken on modern gradle due to use of deprecated gradle commands.

**Comment by e5l** [comment]
Fixed in `master` https://github.com/ktorio/ktor-init-tools
