### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by sah4ez** [ktorio/ktor#147]
Do you have any idea about dockerized ktor?
I can help with docker infrastructure.

**Comment by orangy** [comment]
Could you please elaborate what exactly do you mean?

**Comment by McPringle** [comment]
I don't know what the op means, but I think of creating a docker image which has all the ktor dependencies in it. This way you build only a small own layer on top of this layer which contains only your business code, no libraries. This keeps the image build very fast and small. All the libs which do not change on every build are "extracted" to a separate layer.

**Comment by orangy** [comment]
I think this makes a lot of sense, but not during such rapid evolution of ktor. When we release 1.0, it would be right thing to do.

**Comment by McPringle** [comment]
I agree with @orangy. Maybe you can introduce the milestone "v1.0" (without a date) here on GitHub, so we can assign it to issues like this?

**Comment by orangy** [comment]
I've created a draft to build an image yourself, it's easy. http://ktor.io/drafts/getting-started-docker.html

**Comment by sah4ez** [comment]
Maybe need push image as Official Image with infrastructure and dependences to Docker Hub?
To run a container/service through Docker Hub, without build image on localhost.
For example docker-compose.yml:
```docker
version: '3.0'
  service:
    web:
      image: kotlin/ktor:1.0
      volumes:
       - ./build:/root
```
And to add default system variables to base image.

**Comment by mohammadrafigh** [comment]
I think openjdk:8 image is enough... I'm currently using this in a gradle project w/o any problem.

**Comment by orangy** [comment]
I'm using openjdk:8-jre-alpine, it's much smaller.
I've also prepared a draft for docs: http://ktor.io/drafts/getting-started-docker.html

**Comment by dave08** [comment]
This might be interesting to look into: https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Comment by orangy** [comment]
It's quite easy to do it, as described here http://ktor.io/quickstart/docker.html so I'm closing it.
