### ISSUE TITLE
Exception during authentication 

### ISSUE THREAD

**Issue by stalexxx** [ktorio/ktor#1470]
Ktor 1.2.6, netty

java.lang.NoSuchMethodError exception when using netty engine (works fine with jetty) 

**To Reproduce**
1. Making oauth2 authentication, almost copied from https://github.com/ktorio/ktor-samples/blob/master/feature/auth/src/io/ktor/samples/auth/OAuthLoginApplication.kt
2. get /login/vk (trying auth to vkontake)
3. See error

java.lang.NoSuchMethodError: kotlinx.coroutines.channels.ChannelsKt.receiveOrNull(Lkotlinx/coroutines/channels/ReceiveChannel;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;

[stacktrace.log](https://github.com/ktorio/ktor/files/3916233/stacktrace.log)

**Comment by cy6erGn0m** [comment]
This is not ktor-related, this is something wrong with libraries versioning or kotlin compiler. Are you sure you have correct versions?

**Comment by stalexxx** [comment]
Oh, i am sorry, had old version on courtines(
