### ISSUE TITLE
Invalid authority value for Url

### ISSUE THREAD

**Issue by dtretyakov** [ktorio/ktor#1476]
**Ktor Version and Engine Used (client or server and name)**
Ktor client master.

**Describe the bug**
Currently `Url.authority` is [calсulated improperly](https://github.com/ktorio/ktor/pull/1468#discussion_r354558679) due to appending default port number:
According to the [specification](https://tools.ietf.org/html/rfc3986#section-3.2) authority should be composed as follows:
```
 authority   = [ userinfo "@" ] host [ ":" port ]
```
where port number is optional.

**To Reproduce**

```kt
val url = Url("http://host/path")
assertEquals("host", url.authority)
```

**How to fix**

Write tests and use the same functionality as in `#toString()` method:
https://github.com/ktorio/ktor/blob/master/ktor-http/common/src/io/ktor/http/URLBuilder.kt#L139-L151

**Comment by dtretyakov** [comment]
cc @cy6erGn0m, @e5l

**Comment by e5l** [comment]
Fixed in `master`
