### ISSUE TITLE
HTTP Upgrade Support

### ISSUE THREAD

**Issue by icode** [ktorio/ktor#1479]
I can't found HTTP Upgrade Support API.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism

It's very useful, like for gRPC, custom protocol

**Comment by e5l** [comment]
Hi @icode, thanks for the report. Do you have an idea about API for that feature?

**Comment by icode** [comment]
Like servlet `HttpUpgradeHandler `,  netty https://netty.io/4.1/api/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandler.html .

**Comment by icode** [comment]
Maybe we can get pipeline involved?

**Comment by e5l** [comment]
It looks like we have a special `OutgoingContent` for the upgrade: https://api.ktor.io/1.2.6/io.ktor.http.content/-outgoing-content/-protocol-upgrade/index.html

**Comment by icode** [comment]
I found Websocket use this api, it's same like HttpUpgrade

**Comment by icode** [comment]
Can you write him into the document？

**Comment by e5l** [comment]
@cy6erGn0m
