### ISSUE TITLE
Prevent wrapping exception in `CancellationException`

### ISSUE THREAD

**Issue by e5l** [ktorio/ktor#1482]
**Ktor Version and Engine Used (client or server and name)**

`1.3.0-beta-2`

**Describe the bug**
In async fail client wraps an exception in `CancellationExeption`
After introducing `CompletableJob` it'll be right to fail it instead of canceling `coroutineContext`. 

Sample can be found here: https://github.com/ktorio/ktor/blob/3a9bc56d42281bb4433aef500dc4113c2d02a6da/ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheResponseConsumer.kt#L118

**Comment by dtretyakov** [comment]
@dmitrievanthony will be this fix merged into 1.3.2 release?

**Comment by dmitrievanthony** [comment]
@dtretyakov, I think so. Meanwhile, I'm waiting for review so far, some concerns should be clarified.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-516">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in 1.3.2
