### ISSUE TITLE
Build in feature for Single PAge Applications

### ISSUE THREAD

**Issue by dhakehurst** [ktorio/ktor#1484]
It would be great if there was a built in (ktor) feature for SinglePage Applications

there are third party ones such as 
- https://github.com/lamba92/ktor-spa
- https://github.com/comchangs/ktor-easy-spa

but I would prefer an official ktor supported approach/feature

(a simple static resource is not sufficient, see #749)

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-515">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
