### ISSUE TITLE
CIO request.local.port does not work with Docker mapped ports

### ISSUE THREAD

**Issue by mervyn-mccreight** [ktorio/ktor#1487]
**Ktor Version and Engine Used (client or server and name)**
1.2.6, server, CIO

**Describe the bug**
If you map a port in Docker, ktor with CIO evaluates `request.local.port` to the mapped port (Docker) not the port local to the application (the port that the applications connector is receiving the requests on; in Docker wording - the "exposed port").

I.e. the application gets the mapped port, not the exposed port.

This behaviour makes it impossible to filter requests by port, as you can not know, how "the user" maps the ports.

If you use Netty instead of CIO everything works as expected.

**To Reproduce**
Please see this example project: https://github.com/mervyn-mccreight/cio-port-bug
It showcases the bug.
The [README.md](https://github.com/mervyn-mccreight/cio-port-bug/blob/master/README.md) explains how to reproduce the bug.

**Expected behavior**
`request.local.port` gets evaluated to the port the connector received the request on (as if you are using e.g. `Netty` instead).

**Comment by cy6erGn0m** [comment]
Fixed in 1.3.1
