### ISSUE TITLE
Authentication of session token

### ISSUE THREAD

**Issue by igalratiner** [ktorio/ktor#1495]
**Subsystem**
Server

**Is your feature request related to a problem? Please describe.**
I am using session token authentication in my system. I found no support for session token authentication in Ktor so i have to create a custom interceptor to authenticate the session token + configure the Sessions feature. If there is a better way to authenticate session toke rather than a custom interceptor I'd like to hear about it.

**Describe the solution you'd like**
Add support for session authentication in the Authentication feature.

**Motivation to include to ktor**
This feature will support basically any system using session token authentication

**Comment by cy6erGn0m** [comment]
Doesn't [session authentication](https://api.ktor.io/1.2.6/io.ktor.auth/session.html) work for you? The only you need is to configure [sessions](https://ktor.io/servers/features/sessions.html) to use token, isn't it?

**Comment by igalratiner** [comment]
Thanks! I will check it out by I strongly advise you to update the [https://ktor.io/servers/features/authentication.html](url) page as it's not mentioned there.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-511">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Closed
