### ISSUE TITLE
The ApplicationStopPreparing event is fired several times in withTestApplication

### ISSUE THREAD

**Issue by BorzdeG** [ktorio/ktor#1498]
**Ktor Version and Engine Used (client or server and name)**
version, client/server, additional ktor modules included
version: master branch (

**To Reproduce**
Demo test added to PR: `io.ktor.tests.server.application.ApplicationEventTest`

**Expected behavior**
ApplicationStopPreparing event is fired once

**Comment by cy6erGn0m** [comment]
Fixed in 1.3.0-rc2
