### ISSUE TITLE
Challenge not executed when no JWT token given

### ISSUE THREAD

**Issue by Monchi** [ktorio/ktor#1503]
**Ktor Version and Engine Used (client or server and name)**
server 1.2.6, auth-jwt feature

**Describe the bug**
With jwt authentication, the challenge called when the token is invalid, but not called when no token given.

**To Reproduce**

```kotlin
install(Authentication) {
    jwt {
        verifier(verifier)
        validate { credential ->
            if (credential.payload.audience.contains(jwtAudience)) JWTPrincipal(credential.payload) else null
        }
        challenge { _, _ ->
            this.context.authentication.errors["JWTAuth"]?.let {
                // AuthenticationFailedCause.InvalidCredentials passed when set broken token in header
                // But AuthenticationFailedCause.NoCredentials never passed when no token in header
            }
        }
    }
}
```

**Expected behavior**
All AuthenticationFailedCause passed to challenge including one generated here:
https://github.com/ktorio/ktor/blob/41d9b4802d8381298ab84addac48ed6168828ffb/ktor-features/ktor-auth-jwt/jvm/src/io/ktor/auth/jwt/JWTAuth.kt#L174

**Comment by cy6erGn0m** [comment]
Could you please try it with 1.3.0-rc? I can't reproduce it

**Comment by Monchi** [comment]
Not resolved with 1.3.0-rc. Still challenge does not be executed.

**Comment by cy6erGn0m** [comment]
Still no clue how do I reproduce it. I have added exactly the same in tests and it works

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-508">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Can't reproduce
