### ISSUE TITLE
ktor-client-mock engine is not thread safe

### ISSUE THREAD

**Issue by haneev** [ktorio/ktor#1505]
**Ktor Version and Engine Used (client or server and name)**
Ktor Client 1.2.5 used for all modules:
- ktor-client-core-jvm
- ktor-client-apache
- ktor-client-json-jvm
- ktor-client-jackson

**Describe the bug**
I get a `IndexOutOfBoundsException` or a `Unhandled http://x...` error.

Line 41 of MockEngine.kt gives a IndexOutOfBoundsException, but also line 40 sometimes happens, then I get an `Unhandled http://x...` error. Both errors indicate that there is something wrong with the `invocationCount` and is mutated at different locations. And i can imagine that also the `requestHistory` is not thread safe.

In my test we execute multiple calls on the HttpClient at the same time using coroutines. I therefore suspect that the mock engine is not thread safe, because `invocationCount` is mutated at different locations (line 41/43). When I run my unit tests it will give me this error about 1 in 100. 

https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-mock/common/src/io/ktor/client/engine/mock/MockEngine.kt#L41

Engine is created using the following snippet:

```
val httpClient = HttpClient(MockEngine) {
    engine {
        addHandler {
            respond("{}", HttpStatusCode.OK, headers = headersOf("Content-Type" to listOf(ContentType.Application.Json.toString())))
        }
    }
    install(JsonFeature) {
        serializer = JacksonSerializer()
    }
}
```

**To Reproduce**
The following test can show the behavior.

```
for (i in 0..100) {
    launch { httpClient.get<HttpResponse> { url(request.endpoint) } }
}
```

**Expected behavior**
No crash :P

**Comment by haneev** [comment]
@cy6erGn0m If you agree with my fix in my branch, I can open a PR?

**Comment by cy6erGn0m** [comment]
@haneev Yes, open a PR, please
