### ISSUE TITLE
Support receiving Server Send Events (SSE) for client

### ISSUE THREAD

**Issue by bungoboingo** [ktorio/ktor#1517]
**Subsystem**
Client

**Is your feature request related to a problem? Please describe.**
I am creating a multiplatform library using Ktor for interacting with a restful API that uses SSE to stream events as they occur. Currently I have no way of supporting these events outside of using a separate library for each platform to handle them.

**Describe the solution you'd like**
I would like to be able to receive SSE on the Client side, preferably by collecting them as they are being emitted in a Flow.

**Motivation to include to ktor**
- Ktor already supports SSE on the Server side, it makes sense to support them on Client side as well.
- It will increase the functionality of Ktor to include another common web API.

If I am missing this functionality somewhere in the project please let me know, I was searching for a long time and did not receive a response on Slack.

**Comment by altavir** [comment]
I would like to support this feature and ask for a workaround. It happens that we need to write a client for a platform that uses SSE and I would like to use ktor client for that.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-505">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by juliocesarsantos1020** [comment]
@shanling! Did you manage to develop this? Because I want to learn more about it.
I sent you some messages on Slack also on this topic

**Comment by ErikHellman** [comment]
Any updates on this? I can't find any client side API in Ktor for consuming SSE.

**Comment by brianguertin** [comment]
SSE is pretty straightforward, you can adapt this java parser here for use in your project: https://github.com/aslakhellesoy/eventsource-java/blob/master/src/main/java/com/github/eventsource/client/impl/EventStreamParser.java

**Comment by brianguertin** [comment]
So, as SSE is a very simply protocol, I tried to implement this, but it turns out it's impossible to implement, because most (if not all) of the Ktor client engines buffer the responses. This is fine for streaming file downloads, etc., but to implement SSE it has to be possible to stream the response byte-for-byte, one-by-one.

Ktor itself has an API to read a single byte, so it's possible to write something that LOOKS like it will work, but it won't work properly because most of the client engines won't send you any bytes until they fill an arbitrary buffer (or the connection is closed).

So, this needs to be fixed in all the client engines (or at least engine one per platform) to allow streaming single bytes without filling a buffer first. Once that's done, SSE can be implemented over Ktor either by the user or by Ktor team.

**Comment by Stexxe** [comment]
@brianguertin I am curious, why can't it work with buffering?

**Comment by altavir** [comment]
The actual discussion is in youtrack: https://youtrack.jetbrains.com/issue/KTOR-505

**Comment by SebastianAigner** [comment]
According to [YouTrack](https://youtrack.jetbrains.com/issue/KTOR-505), this issue was fixed on 1 Jun 2023. Can we close it here to save people coming from search engines a click? :)

**Comment by Stexxe** [comment]
Thank you. This issue is fixed in Ktor 3.0.0.

**Comment by ishowshao** [comment]
Version 3.0 has not been released yet, what should I do now?

**Comment by plutonium-239** [comment]
same here, when is 3.0 and what can I use in the meantime? (coming from the issue mentioning this)

**Comment by Stexxe** [comment]
You can use the version `3.0.0-beta-1` for now.

**Comment by ishowshao** [comment]
`val client = HttpClient(CIO)
client.prepareGet(
    urlString = "url",
    block = {
        url {
            parameters.append(name = "key", value = "value")
        }
    }
).execute { httpResponse ->
    val channel: ByteReadChannel = httpResponse.body()
    while (!channel.isClosedForRead) {
        val message = channel.readUTF8Line()
        if (message != null) {
            // message is "data: ..."
        }
    }
}`
