### ISSUE TITLE
android cio  Failed to parse request body: request body length should be specified

### ISSUE THREAD

**Issue by denglongfei** [ktorio/ktor#1518]
**Ktor Version and Engine Used (client or server and name)**
version, client/server, additional ktor modules included
android 
io.ktor:ktor-client-cio:1.3.0-rc

**Describe the bug**
Error occurred
“ Failed to parse request body: request body length should be specified,
            chunked transfer encoding should be used or
            keep-alive should be disabled (connection: close)”

Client code
  var httpClient= HttpClient(CIO) {
            install(JsonFeature) {
                serializer = GsonSerializer()
            }
        }
        val params = baseFormData {
            append("phone", phone)
            append("code", code)
        }
        var baseRepository = httpClient.submitFormWithBinaryData<BaseRes<LoginResponse>>(params) {
            url("$baseUrl/users/phoneLogin")
        }
Debugging found ktor-client-cio-1.3.0-rc-sources.jar! /JvmMain/io/ktor/client/engine/cio/utils.kt:
Val rawResponse = parseResponse (input) did not parse successfully Content-Length
Debug screenshot
![1](https://user-images.githubusercontent.com/41456814/71349136-2d6c6280-25a9-11ea-87f5-062ab7087b09.png)
![2](https://user-images.githubusercontent.com/41456814/71349150-36f5ca80-25a9-11ea-8f8d-ec40110e94e7.png)

**Comment by cy6erGn0m** [comment]
Is there a reproducer?

**Comment by cy6erGn0m** [comment]
What server do you use? Does it produce many response headers?

**Comment by cy6erGn0m** [comment]
If you can debug, can you please try to step over lines in parseResponse and observe how the "builder" changes: are corrupted characters just appended after http status line or correct headers get overwritten somehow?

**Comment by denglongfei** [comment]
>What server do you use? Does it produce many response headers?

The server is also using ktor
Generate response code
   post <Users.PhoneLogin> {
         var request = call.receiveParameters ()
         var result = newSuspendedTransaction {
             userService.phoneLogin (request ["phone"], request ["code"])
         }
         println ("$ result")
         call.respond (result)
     }
Debugging background io.ktor.server.engine.BaseApplicationResponse 80 lines
![2](https://user-images.githubusercontent.com/41456814/71389057-cba60a00-2635-11ea-9abf-15f399268044.png)

**Comment by denglongfei** [comment]
> If you can debug, can you please try to step over lines in parseResponse and observe how the "builder" changes: are corrupted characters just appended after http status line or correct headers get overwritten somehow?
ByteReadChannel in parseResponse cannot view the content
When I switch to OkHttp engine is
  HttpClient (OkHttp) {
         // Install Json serialization
         install (JsonFeature) {
             serializer = GsonSerializer ()
         }
}
Capable of obtaining data correctly
![1](https://user-images.githubusercontent.com/41456814/71389266-a8c82580-2636-11ea-8502-8013d5e6340e.png)

**Comment by cy6erGn0m** [comment]
Tried so much to do but still no clue how do I get it reproduced. Is it reproducible only inside of a device?

**Comment by denglongfei** [comment]
> Tried so much to do but still no clue how do I get it reproduced. Is it reproducible only inside of a device?
Yes, it can only be reproduced internally now

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-504">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in 1.4.0

**Comment by akelix** [comment]
reproduced on 2.3.4
