### ISSUE TITLE
Line-by-line data processing

### ISSUE THREAD

**Issue by imanushin** [ktorio/ktor#1522]
**Subsystem**
Client

**Is your feature request related to a problem? Please describe.**
Our service parses logs from external services (for example - from TeamCity builds). Because of huge content size it is better to avoid loading whole text into the memory.
All content is processed line-by-line independently. Moreover, the 99% of lines are not needed and skipped if length is less than X.

**Describe the solution you'd like**
Support streaming deserializer, which is able to do line-by-line parsing. However, I'd like to have the feature with the following logic:
* New deserializer receives the function ```fun tryParse(line: CharSequence): TResult?```. Null means "line should be dropped". Probably sealed (or inline?) class with multiple options is better here.
* Next user is able to do call like ```val lines : List<TResult> = client.get<TResult>("https://github.com")```. Internally ktor can call ```tryParse``` method for the each line and skip nulls.
* As I said above, the 99% of lines aren't needed, so it is better to avoid allocating unnecessary ```String```s. Instead of this, ```CharSequence``` should wrap special class, which does lazy conversion from ```ByteBuffer``` to ```String```. This can be useful to reduce memory allocations. Otherwise user is able to call ```toString``` immediately to materialize ```CharSequence``` to ```String```

So internal code can be like this:
```
val result = mutableListOf<TResult>();

response.content.use { content ->
     do {
          val nextLine = content.wrapNextLine(); // use IoBuffer.decodeUTF8 here to find end of String and calculate size; for index-based access repeat this with O(N) complexity
          if(nextLine !== null) {
               nextLine.use { line ->
                   val parsingResult = tryParse(line)

                   if(parsingResult !== null) {
                        result.add(parsingResult)
                   }
               }
          }
     }
}
```

**Motivation to include to ktor**
Multiple items:
* This fixes #1242
* This can be useful for the same cases, when stream-like processing is needed. Probably (not sure) this method can be generalized to separate lines not just by end of line, but by other optional delimiters too.
* **Important:** if possible, I'd like to implement this option by myself and put the code into the ktor to remove support from myself (which is egoistic). Therefore question for ktor project owner: are you interesting in this feature?

**Comment by cy6erGn0m** [comment]
This is already available. See how it is done in CIO http parser: https://github.com/ktorio/ktor/blob/94cd62f3cacf499d51c0a7127ca740f09b60debc/ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt#L102

**Comment by imanushin** [comment]
Will  check and close. Thank you!
