### ISSUE TITLE
Incoming request validation

### ISSUE THREAD

**Issue by viartemev** [ktorio/ktor#1524]
**Subsystem**
Server

**Is your feature request related to a problem? Please describe.**
The feature is related to the incoming request validation problem.

**Describe the solution you'd like**
You can find the implementation here: https://github.com/viartemev/ktor-validation-feature

**Motivation to include to ktor**
This is a core feature of all HTTP servers, most of the incoming requests must be validated. This feature provides a simple way for incoming request validation.

If you think that the proposed option suits for Ktor I can create PR and add tests for it.

**Comment by sysmat** [comment]
Any progress on that?

**Comment by viartemev** [comment]
@sysmat you can find my impl of the feature here: https://github.com/viartemev/ktor-validation-feature
I'm not sure about this way of validation, if @cy6erGn0m happy with it, I can create PR.

**Comment by sysmat** [comment]
@viartemev this implementation will be as lib or part of ktor?

**Comment by viartemev** [comment]
@sysmat it could be part of a standard set of features (as part of ktor library) or can be a separate feature that can be added to the project.

**Comment by LookBad** [comment]
@viartemev I did something similar. Look at this: https://gist.github.com/LookBad/9611af5b90f1909eb4f597bb5d9e7737

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-503">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by viartemev** [comment]
@oleg-larshin what is the motivation for moving to YouTrack? Do you have any plans to transfer upvotes?
