### ISSUE TITLE
AttributeKey equality

### ISSUE THREAD

**Issue by viartemev** [ktorio/ktor#1525]
**Ktor Version and Engine Used (client or server and name)**
version 1.3.0-rc, engines: all

**Describe the bug**
Usecase: I'm trying to put custom value to `attributes` (request call) in feature and get it another place. I can't get it back if I know the attribute name. I have to provide an instance of `Attribute`, only in this case it will return the actual key.
```
call.request.call.attributes.put(AttributeKey("name"), 1)
val attribute = call.request.call.attributes.getOrNull(AttributeKey("name")) //attribute is null
```
[Attribute](https://github.com/ktorio/ktor/blob/532d5804f60279a2e629b0df1f720e47463db65e/ktor-utils/common/src/io/ktor/util/Attributes.kt#L12) class doesn't have equals/hashcode, but all the time it used in `Map`'s.

**To Reproduce**
```
@Test
fun twoAttributeKeyWithSameKeyShouldBeEqual() {
    val key = "key"
    assertEquals(AttributeKey<String>(key), AttributeKey<String>(key))
}
```

**Expected behavior**
Was it made on purpose (some element of design)? I checked all Ktor features use one instance for access to attribute map. 
If yes, could you explain the design decision? In this case, it should be documented on ktor.io (I haven't found it on it), it's not obvious.

**Comment by cy6erGn0m** [comment]
One shouldn't instantiate a lot of attribute keys. By design, attribute keys should have identity equality. So use global instances instead.

**Comment by viartemev** [comment]
@cy6erGn0m Yes, I figured it out, but spend on it some time. 
Maybe I could rase PR for docs update with this design info?
