### ISSUE TITLE
Incorrect behavior with multiple Set-Cookie on iOS

### ISSUE THREAD

**Issue by alexgolenkevich** [ktorio/ktor#1528]
Ktor client 1.2.4 + HttpCookies feature

In case server sends several "Set-Cookie" headers in response the only first cookie is stored in the cookie storage on iOS platform.

It seems that the problem is caused by used property [[NSHTTPURLResponse allHeaderFields]](https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1415485-httpshouldhandlecookies?language=objc) which merges all "Set-Cookie" headers into single one.

Here is the log of response on iOS:

>[HTTP] COMMON HEADERS
>[HTTP] -> Content-Type: application/json;charset=UTF-8
>[HTTP] -> P3P: CP="NON DSP COR CURa ADM ADMa OUR STP IDC IND PHY ONL COM STA"
>[HTTP] -> Set-Cookie: JSESSIONID=117B87B55A6E49839738518C8BFC3076; Path=/SSW2010/; HttpOnly, WLPCOOKIE=sswvlc29744; Expires=Tue, 24-Dec-2019 16:46:45 GMT; Path=/SSW2010; Secure; HttpOnly, WLPCOOKIE=sswvlc29744; Expires=Tue, 24-Dec-2019 16:46:45 GMT; Path=/; Secure; HttpOnly, WLPCOOKIE=sswvlc29744; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/SSW2010; Secure; HttpOnly, JSESSIONID=117B87B55A6E49839738518C8BFC3076; Path=/; Secure; HttpOnly, JSESSIONID=117B87B55A6E49839738518C8BFC3076; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/SSW2010/; Secure; HttpOnly, SSWGID=E6870699E54049978BF77534CDA2180A; Expires=Fri, 21-Dec-2029 14:46:45 GMT; Path=/; Secure; HttpOnly
>[HTTP] -> X-XSS-Protection: 1; mode=block
>[HTTP] -> Content-Encoding: gzip
>[HTTP] -> Transfer-Encoding: Identity
>[HTTP] -> Server: Sabre Gateway
>[HTTP] -> Date: Tue, 24 Dec 2019 14:46:45 GMT
>[HTTP] -> X-Cnection: close, close
>[HTTP] -> X-Content-Type-Options: nosniff
>[HTTP] -> X-Frame-Options: DENY
>[HTTP] -> Vary: Accept-Encoding

Here is the log on Android:
>P3P: CP="NON DSP COR CURa ADM ADMa OUR STP IDC IND PHY ONL COM STA"
>Set-Cookie: JSESSIONID=831B5C69567F21AF2067FE8EBBA1BFD2; Path=/SSW2010/; HttpOnly
>Set-Cookie: WLPCOOKIE=sswvlc29744; Expires=Tue, 24-Dec-2019 16:35:20 GMT; Path=/SSW2010; Secure; HttpOnly
>Set-Cookie: WLPCOOKIE=sswvlc29744; Expires=Tue, 24-Dec-2019 16:35:20 GMT; Path=/; Secure; HttpOnly
>Set-Cookie: WLPCOOKIE=sswvlc29744; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/SSW2010; Secure; HttpOnly
>Set-Cookie: JSESSIONID=831B5C69567F21AF2067FE8EBBA1BFD2; Path=/; Secure; HttpOnly
>Set-Cookie: JSESSIONID=831B5C69567F21AF2067FE8EBBA1BFD2; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/SSW2010/; Secure; HttpOnly
>Set-Cookie: SSWGID=4EE3A32595AD427DBB8B911B5E43A766; Expires=Fri, 21-Dec-2029 14:35:20 GMT; Path=/; Secure; HttpOnly
>Vary: Accept-Encoding
>X-Content-Type-Options: nosniff
>X-Frame-Options: DENY
>X-XSS-Protection: 1; mode=block
>Content-Type: application/json;charset=UTF-8
>Transfer-Encoding: chunked
>Server: Sabre Gateway

**Comment by e5l** [comment]
Fixed in `master`
