### ISSUE TITLE
How to handle server disconnection with Raw Socket TCP Connection?

### ISSUE THREAD

**Issue by DakarKaret** [ktorio/ktor#1532]
How to handle server disconnection with Raw Socket TCP Connection?

**Comment by cy6erGn0m** [comment]
Depending on the way it is disconnected, there are only three ways to discover a TCP connection issue (in TCP generally, there is nothing ktor specific here): 
- reading from the socket may fail or return EOF (-1)
- writing to the socket will fail (after a while, probably on write timeout)
- application's ping/pong (if protocol supports)

The first one is not guaranteed and only work well if a peer has disconnected properly and doesn't work in many cases. The second is relatively guaranteed but not every protocol allows to write in any time. 

In ktor all of the ways above available: reading from a channel may fail, writing will fail.
