### ISSUE TITLE
[ktor-client-js] Ktor's User-Agent breaks CORS policy in a browser

### ISSUE THREAD

**Issue by Prototik** [ktorio/ktor#1533]
`ktor-client-core-js` `1.3.0-rc`

I'm using ktor client in a browser to network requests (obviously), but something recently changed and now ktor provides default user-agent in case the developer himself didn't. That ruins in browser. `User-Agent` header marks request as [non-simple](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and browser performs cors-preflight request first, then rejects original request because `User-Agent` not allowed header for that server (and particularly any other server). 

The worst moment I can not override that behavior and delete `User-Agent` header from request as [this check](https://github.com/ktorio/ktor/blob/1b4ab0adf6671efe7b52ec04c44566c7d730551b/ktor-client/ktor-client-core/common/src/io/ktor/client/engine/Utils.kt#L40) performs on later stage inside of engine, so no any workarounds for me :(.

![Screenshot from 2019-12-28 01-01-13](https://user-images.githubusercontent.com/1416030/71525971-3ff9db00-28cc-11ea-9d5f-8bcaac00f9a7.png)
![Screenshot from 2019-12-28 01-00-47](https://user-images.githubusercontent.com/1416030/71525974-41c39e80-28cc-11ea-9ea1-4b4e4f9d26a5.png)

**Comment by cy6erGn0m** [comment]
This is slightly strange: the page you are referring to clearly states that User-Agent is allowed and shouldn't trigger preflight. On the other side, the specification doesn't state that. This is not the first time when I see MDN is not exactly correct.

**Comment by Prototik** [comment]
```
the only headers which are allowed to be manually set are those which the Fetch spec defines as a “CORS-safelisted request-header”, which are:

    Accept
    Accept-Language
    Content-Language
    Content-Type (but note the additional requirements below)
    DPR
    Downlink
    Save-Data
    Viewport-Width
    Width
```
There is no User-Agent in the list. Any other header will trigger preflight too.

**Comment by Prototik** [comment]
Just tested it in chromium - it allows `User-Agent` in that case. Firefox-only issue?

**Comment by Prototik** [comment]
Derp, chromium just ignores ktor's user-agent and sends their own in place. Seems ktor's user-agent completely useless in a browser.

**Comment by e5l** [comment]
Fix in `master`
