### ISSUE TITLE
[ktor-client] Customize HttpCache behavior, serve stale if host is down, ignore max-age

### ISSUE THREAD

**Issue by rrva** [ktorio/ktor#1534]
**Subsystem**

ktor-client http cache

**Is your feature request related to a problem? Please describe.**

Whenever a host is down or a timeout occurs, or if the origin host responds with http 5xx, I want to use contents from the ktor client http cache. 

I tried to customize the behavior by implementing my own io.ktor.client.features.cache.storage.HttpCacheStorage, but the HttpCacheEntry class is so closed for extension that I cannot customize this behavior in my own code.

**Describe the solution you'd like**

Either make the HttpCache configurable so that it can serve requests from the cache even if the origin server responds with http 5xx (or timeout or connection refused). It should also be possible to ignore the cache-control max-age directives of the origin server here and use data past its expire time.

Or, make the HttpCacheEntry class more open for extension/subclassing so that I can implement my own HttpCacheStorage and plug this into the cache.

**Motivation to include to ktor**

This cache behavior is very useful for resilience, the cache can make content available past its expire time when an outage of the origin server occurs. In some scenarios old data is better than no data.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-501">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
