### ISSUE TITLE
Enabling and disabling TSL protocols

### ISSUE THREAD

**Issue by Lundez** [ktorio/ktor#1552]
**Subsystem**
Ssl part of Application.conf or the SslConnector if that is easiest to start with

**Is your feature request related to a problem? Please describe.**
I did a security test of my backend recently and it brought up that I don't support TSL 1.3 (which is supported in Netty; https://stackoverflow.com/questions/53406502/how-to-enable-tlsv1-3-in-netty) and I support TSL 1.0 which is outdated and unsecure.
This feels bad.

**Describe the solution you'd like**
I want to disable TSL 1.0 & enable TSL 1.3 (I _really_ want to disable TSL 1.0)

**Motivation to include to ktor**
Security is always key, the documentation is good for now but this part is not clear & I can't find a way to achieve this. It'd be great to check this boxes :ballot_box_with_check: 

Thanks for an awesome framework!

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-495">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
Only TLSv1.2 and TLSv1.3 protocols are enabled by default using Ktor 1.6.1 and Netty engine.
