### ISSUE TITLE
Ktor raw sockets read channel read nothing right after connection established

### ISSUE THREAD

**Issue by ikyzmin** [ktorio/ktor#1560]
I'm trying to connect to IMAP server with Ktor raw sockets

```   
@KtorExperimentalAPI
    override suspend fun start(host: SocketAddress) {
        socket = aSocket(ActorSelectorManager(Dispatchers.IO)).tcp().connect(host).tls(Dispatchers.IO)
        writeChannel = socket.openWriteChannel()
        readChannel = socket.openReadChannel()
        val handshakeResponse = ByteArray(readChannel.availableForRead)
        readChannel.readAvailable(handshakeResponse)
        val handshake = String(handshakeResponse)
        println(handshake)
    } 
 ```

After this connection I excpect that I'll get IMAP server response like this

```
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE  SPECIAL-USE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
```

And then I send IMAP commands to login to my mailbox

```
  @KtorExperimentalAPI
    override suspend fun command(command: String): String {
        writeChannel.write("$command\r\n".also { print(it) })
        val response = ByteArray(readChannel.availableForRead)
        readChannel.readAvailable(response)
        val responseString = String(response)
        println(responseString)
        return responseString
    }
```

So my output should be like this

```
 * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE  SPECIAL-USE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
S1 LOGIN email pass
S1 OK Logged in
```
But for some reason, the output looks like these commands are executed in parallel threads

```
S1 LOGIN email pass
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE  SPECIAL-USE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
```

And my coroutine is blocked at write/read channels because Ktor use randezvous channels and I can't write to channel until I read output

My main code looks like this
```
 fun run() {
        val store = IMAPStore()
        runBlocking(coroutineContext) {
                //connect with tls (suspend function)
                store.install()
                //send login command (suspend function)
                store.login()
        }
    }
```

I probably don’t quite understand how the connection through tls works and how the channels work. Maybe I'm starting coroutines wrong. 

In this sample code the same logic works perfectly
```
fun main() {
    runBlocking {
        val socket =
            aSocket(ActorSelectorManager(Dispatchers.IO)).tcp().connect(host)
                .tls(Dispatchers.IO)
        val w = socket.openWriteChannel(autoFlush = false)
        val r = socket.openReadChannel()
        r.readUTF8LineTo(System.out)
        w.write("$TAG${tagCounter++} LOGIN email password\r\n")
        r.readUTF8LineTo(System.out)
    }
```
Am i doing something wrong?

**Comment by cy6erGn0m** [comment]
This is absolutely wrong:

```kotlin
readChannel = socket.openReadChannel()
val handshakeResponse = ByteArray(readChannel.availableForRead)
```

The reason why it is not correct is that the network and the TCP stack is running asynchronously. So, most likely `availableForRead` is always 0 because it takes time to transfer and receive bytes and mark them as available. The same here:

```kotlin
writeChannel.write("$command\r\n".also { print(it) })
val response = ByteArray(readChannel.availableForRead)
readChannel.readAvailable(response)
val responseString = String(response)
```

Here it writes a command and after that it always creates a byte array of a "random" size (possibly 0) because sending bytes, processing them on the remote side, receiving answer and so on takes time. But the code doesn't wait for response and simply takes number of bytes available before the response. So we may see empty responses or part of responses. 

The other issue is that channel's buffer is always limited. So if a response is longer that the buffer, you get it truncated because `availableForRead` will be never longer that the buffer size.

**Comment by cy6erGn0m** [comment]
For reading line-delimited text protocol, one should use `readLineUtf8` function.

**Comment by ikyzmin** [comment]
@cy6erGn0m Thanks! After your answer I tried to change read logic to

```
 socket = aSocket(ActorSelectorManager(Dispatchers.IO)).tcp().connect(host).tls(Dispatchers.IO)
        writeChannel = socket.openWriteChannel()
        readChannel = socket.openReadChannel()
        readChannel.readUTF8LineTo(System.out)
        println()
```

and for commands 
```
@KtorExperimentalAPI
    override suspend fun command(command: String): String {
        writeChannel.write("$command\r\n".also { print(it) })
        writeChannel.flush()
        val response = StringBuilder()
        while(readChannel.readUTF8LineTo(response)){
            response.append("\r\n")
            if (readChannel.availableForRead<=0){
                break
            }
        }
        println(response)
        return response.toString()
    }
```
And this is work just like you describe. So if I call readAvailable on Buffer with zero available bytes it will not suspend until something is write to the bufferchannel? But with readUTF8LIneTo will suspend until something is appear in output? 

And is it right way to read multiple lines from output?
```
 while(readChannel.readUTF8LineTo(response)){
            response.append("\r\n")
            if (readChannel.availableForRead<=0){
                break
            }
        }
```

**Comment by cy6erGn0m** [comment]
This is not going to work  due to the same reason. Perhaps, we need to deprecate availableForRead to avoid incorrect usage. There are to few ways to use it correctly

**Comment by ikyzmin** [comment]
@cy6erGn0m ok, I'll figure it out somehow with this. Thank you

**Comment by simaotwx** [comment]
I'm observing that `readLineUtf8` appears buffered and thus reading line-by-line is still delayed due to buffering.
Is there a way to disable buffering or decrease the buffer size?
See: https://stackoverflow.com/questions/76787577/how-to-set-the-read-channel-buffer-size-when-using-readutf8line-in-ktor
