### ISSUE TITLE
withTestApplication with gracePeriod parameter

### ISSUE THREAD

**Issue by OlSom** [ktorio/ktor#1566]
**Subsystem**
Server

**Is your feature request related to a problem? Please describe.**
As far as I can tell there is no version of withApplication / withTestApplication that takes a gracePeriod parameter, which we would like to use in our tests to give the application time to close a connection. 

**Describe the solution you'd like**
Changing the signature of withTestApplication and withApplication to include a `gracePeriod` parameter:
```kotlin
fun <R> withTestApplication(
    gracePeriod: Long = 0L,
    moduleFunction: Application.() -> Unit,
    configure: TestApplicationEngine.Configuration.() -> Unit = {},
    test: TestApplicationEngine.() -> R
): R {
    return withApplication(gracePeriod, createTestEnvironment(), configure) {
        moduleFunction(application)
        test()
    }
}

fun <R> withApplication(
    gracePeriod: Long = 0L,
    environment: ApplicationEngineEnvironment = createTestEnvironment(),
    configure: TestApplicationEngine.Configuration.() -> Unit = {},
    test: TestApplicationEngine.() -> R
): R {
    val engine = TestApplicationEngine(environment, configure)
    engine.start()
    try {
        return engine.test()
    } finally {
        engine.stop(gracePeriod, 0L, TimeUnit.MILLISECONDS)
    }
}
```

**Motivation to include to ktor**
This should be helpful for anyone trying to achieve a graceful shutdown of the application between tests.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-490">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Closed. `withTestApplication` is deprecated in 2.0.0
