### ISSUE TITLE
LocalFileContent no longer available to client applications after upgrading to 1.3.0

### ISSUE THREAD

**Issue by yuforia** [ktorio/ktor#1569]
**Ktor Version and Engine Used (client or server and name)**
This occurred in a client application upgrading from ktor 1.2.6 to 1.3.0.
Modules used: `ktor-client-okhttp`, `ktor-client-core`, `ktor-client-serialization-jvm`.

**Describe the bug**
In order to upload files, `body = LocalFileContent(File("build.gradle"))` was used to specify a body for requests, as suggested by [quick start guide for clients](https://ktor.io/clients/http-client/quick-start/requests.html).
 In `1.2.6`, it could be imported using

> import io.ktor.http.content.LocalFileContent

 but after setting the ktor version to `1.3.0`, this line fails with `Unresolved reference`. And Intellij couldn't suggest any imports for `LocalFileContent`.

I went through some git log and found that in this commit: [Reduce jdk8 dependencies in client ](https://github.com/ktorio/ktor/commit/06077ee8bc6be688af5c393f21f81f57065c085f), the file

> ktor-http/jvm/src/io/ktor/http/content/LocalFileContent.kt

was moved to 

> ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/LocalFileContent.kt

 It seems to suggest that `LocalFileContent` is now only in `ktor-server`.

`LocalFileContent` is still mentioned in [quick start guide for clients](https://ktor.io/clients/http-client/quick-start/requests.html) but not in the guide [Migrating 1.2.4 → 1.3.0](https://ktor.io/quickstart/migration/1.3.0.html). I guess it could also be the docs that need updating.

**Comment by e5l** [comment]
Hi, @yuforia it was deleted because of versions and will be added back in 1.3.1. Consider using the snippet for now:
```kotlin
class LocalFileContent(
    val file: File,
    override val contentType: ContentType = ContentType.defaultForFile(file)
) : OutgoingContent.ReadChannelContent() {

    override val contentLength: Long get() = file.length()

    override fun readFrom(): ByteReadChannel = file.readChannel()

    override fun readFrom(range: LongRange): ByteReadChannel = file.readChannel(range.start, range.endInclusive)
}
```

**Comment by yuforia** [comment]
Thanks!

**Comment by e5l** [comment]
Fix in `master`
