### ISSUE TITLE
Include gson-kotlin library for json parsing with gson

### ISSUE THREAD

**Issue by dszopa** [ktorio/ktor#157]
The [gson-kotlin](https://github.com/sargunv/gson-kotlin) library enforce nullability on Kotlin properties during deserialization by throwing parsing errors if the Kotlin object is created with nullable fields that are marked non nullable. 

Is there any interest in adding this to the default `ktor-gson` feature or making a `ktor-kotlin-gson` feature?

**Comment by orangy** [comment]
That makes sense. However I would wait for proper Content Negotiation feature before doing it.

**Comment by orangy** [comment]
Currently you can easily configure Gson to use that library in the application. And it's not on jcenter/maven, so we can't include it as a transitive dependency

**Comment by orangy** [comment]
I'm closing it for now. When the library is on JCenter, we can reconsider it.
