### ISSUE TITLE
Logging feature with LogLevel.ALL logging form body broken

### ISSUE THREAD

**Issue by bitkid** [ktorio/ktor#1574]
**Ktor Version and Engine Used (client or server and name)**
version, client/server, additional ktor modules included
1.3.0 client engine Apache / 1.3.0 server engine Netty

**Describe the bug**
when i install the logging feature (loglevel=ALL or BODY) and do a client.submitFormWithBinaryData<HttpResponse>() the client fails sending the data.
(the exceptions i see https://gist.github.com/bitkid/f9884fc3d0278a8f4aefab3b8c6f8794)

@e5l suspected in slack:
"It looks like form body doesn’t work well with logging,  consumes the source twice and fail."

**To Reproduce**
1. Write the following
2. Run using browser/curl/etc
3. See error

**Expected behavior**

**Screenshots**

**Comment by e5l** [comment]
Fix in `master`
