### ISSUE TITLE
io.ktor.http.UnsafeHeaderException: Header Content-Type

### ISSUE THREAD

**Issue by dllewellyn** [ktorio/ktor#1575]
**Ktor Version and Engine Used (client or server and name)**
1.3.0, client, okhttp & android

**Describe the bug**
When setting a custom Content-Type header (application/vnd.<company>.schema-v1+json) we encounter UnsafeHeaderException: Header Content-Type cannot be set by the engine explicitly.

**To Reproduce**
(or similar, e.g. client.post(url))
`        client.call(url) {
            header("content-type", "vnd.<company>.schema-v1+json")
            method = HttpMethod.Post
            body = ByteArrayContent(
                """{"emailAddress": "$email"}""".toByteArray(),
                null
            )
        }
`
**Expected behavior**
I would hope for an option to override this behaviour, we need to use this header to interact with a clients API, there's no chance of us changing this from their point of view. 

The issue seems to stem from `UnsafeHeadersArray.asList()` being immutable. The ability to edit this would be ideal, otherwise a flag for 'ignore unsafe headeres' for us to configure

**Comment by cy6erGn0m** [comment]
Simply specify content type parameter of `ByteArrayContent` instead.

**Comment by cy6erGn0m** [comment]
One shouldn't specify that header directly.

**Comment by dllewellyn** [comment]
Great, updated to this and it now works. Thanks for your help
`client.call(url) {
    method = HttpMethod.Post
    body = ByteArrayContent(
        """{"emailAddress": "$email"}""".toByteArray(),
        ContentType("application", "vnd.<company>.schema-v1+json")
    )
}`
