### ISSUE TITLE
Stream request stops after one item received in multiplatform

### ISSUE THREAD

**Issue by tyczj** [ktorio/ktor#1578]
I have a Spring Boot REST controller that has a streaming endpoint that just returns an item every second

```
@RequestMapping(method = [RequestMethod.GET], value = ["/values"], produces = [MediaType.APPLICATION_STREAM_JSON_VALUE])
    fun sayHello(@RequestParam(value = "name") name:String): Flux<Example> {
        return Flux.interval(Duration.ofSeconds(1))
            .map { Example(number = generateNumber()) }
            .share()
    }
```

on the client side I create a streaming get request like this

```
@ImplicitReflectionSerializer
    @ExperimentalCoroutinesApi
    suspend fun getData(){
        client.get<HttpStatement>("http://192.168.7.24:8080/api/v1/values?name=hello").execute{
            val channel = it.receive<ByteReadChannel>()
            val byteArray = ByteArray(it.content.availableForRead)
            channel.readAvailable(byteArray,0,byteArray.size)
            val example = Json.parse<Example>(stringFromUtf8Bytes(byteArray))
        }
    }
```

it all works but it only works for the first item received from the API, after that initial one I dont get anymore items from it. I was expecting a constant stream of data that I can then update the client UI. Is this not the way to accomplish that?

**Comment by cy6erGn0m** [comment]
Why did you expect it to receive upcoming elements? You do only a single read so no more elements could be received

**Comment by cy6erGn0m** [comment]
for reading multiple elements you need a loop

**Comment by tyczj** [comment]
When I read stream I was thinking like observable stream similar to RxJava or something where you have a connection and you get constant updates without having a loop.

When I copy the url into chrome it get a constant stream of data showing/updating in the browser with only making one request and this is what I was expecting here.
