### ISSUE TITLE
Exposing some internal classes could help add features to Ktor Http Client

### ISSUE THREAD

**Issue by speekha** [ktorio/ktor#1583]
**Subsystem**
Http Client

**Is your feature request related to a problem? Please describe.**
I've developed a library to allow mocking http calls for OkHttp. https://github.com/speekha/httpmocker
I was hoping to do the same with Ktor, and as far as I could tell, what looked like the best option would be to develop a new Feature and plug it on the pipelines. Thing is I can't return a HttpResponse without a HttpClientCall, and I can't find a way to do that: I can't inherit from HttpClientCall because of the internal constructor, can't set the response and request inside because of the internal setters, and the DelegatedCall and SavedCall can't be used either since they're internal classes.

**Describe the solution you'd like**
I don't see a way to create a Reponse without exposing a bit more of Ktor API, either by opening the HttpClientCall class and its setters a bit or allowing to extend it (unless there's a more appropriate way to intercept request and serve static responses from disk instead).

**Motivation to include to ktor**
I believe that the possibility to create Features for Ktor is a very interesting way to extend Ktor's possibilities, but it would really benefit from exposing some of the internal classes or API.

**Comment by cy6erGn0m** [comment]
Doesn't ktor's mock client do what you need? https://ktor.io/clients/http-client/testing.html

**Comment by speekha** [comment]
Creating a mock engine was my first idea (very similar to Ktor's mock engine, which seems to answer some use cases). But my approach was a little bit different though: I would like to be able to use the same configuration all the time and not have different engines. Furthermore, my mock interceptor also allows to record scenarios. But maybe what I'm trying to do is not needed.
Anyway, my initial point is that the documentation advises to use standard features as examples for creating custom features, but the standard features themselves (cache, response observer...) benefit from the fact that they're in the same module as Ktor client (and thus have access to internal classes or members). A developer wanting to implement something similar would not have the possibility to do so since the "internal" visibility would restrict what classes they can manipulate or not.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-488">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
