### ISSUE TITLE
Unable to use WebSocket on Android.

### ISSUE THREAD

**Issue by charlag** [ktorio/ktor#1587]
**Ktor Version and Engine Used (client or server and name)**
```groovy
ext.kotlin_version = '1.3.61'
ext.ktor_version = '1.2.3'

commonMain {
    dependencies {
        implementation kotlin('stdlib-common')
        implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
        implementation "io.ktor:ktor-client-core:$ktor_version"
        implementation "io.ktor:ktor-client-json:$ktor_version"
        api "io.ktor:ktor-client-logging:$ktor_version"
        implementation "io.ktor:ktor-client-websockets:$ktor_version"
    }
}

androidMain {
    dependencies {
        implementation kotlin('stdlib')
        api "io.ktor:ktor-client-core:$ktor_version"
        api "io.ktor:ktor-client-android:$ktor_version"
        implementation "io.ktor:ktor-client-serialization-jvm:$ktor_version"
        implementation 'org.jetbrains.kotlin:kotlin-reflect:1.3.61'
        api "io.ktor:ktor-client-logging-jvm:$ktor_version"
        api "io.ktor:ktor-client-logging:$ktor_version"
        implementation "io.ktor:ktor-client-websockets:$ktor_version"
    }
}
```

```kotlin
HttpClient(Android.create()) {
    install(JsonFeature) {
        serializer = platformJsonSerializer()
    }
    install(Logging) {
        logger = Logger.DEFAULT
    }
   install(WebSockets)
}
```

**Describe the bug**
When I try to use websocket with Android app I get one of two errors:
1. With
`httpClient.wss(host = "host.com", path = "events") { ..}` or wss url I get
`java.net.MalformedURLException: unknown protocol: wss`
2. With `httpClient.wss("https://mail.tutanota.com/events") { ..}` I get
`
 io.ktor.client.call.NoTransformationFoundException: No transformation found: class kotlinx.coroutines.io.ByteBufferChannel -> class io.ktor.client.features.websocket.DefaultClientWebSocketSession
`
(server supports upgrades from HTTP, it already works this way in browser)

I imagine it is related to the Android angine being unable to handle WebSocket but I would be nice if you could confirm that. Then I could use it with OkHttp.

(maybe related to #732)

P.S: absolutely rocking set of libraries, thanks for your work.

**Comment by charlag** [comment]
Update: swapping `Android.create()` with `OkHttp.create {  }` doesn't help.
I searched for `ClientWebSocket` impl in the repo and could only find CIO implementation even though the docs say
> Ktor provides a WebSocket client for the following engines: CIO, OkHttp, Js.

Thank you.

**Comment by cy6erGn0m** [comment]
ktor 1.2.3 is quite outdated. We recommend you to upgrade to 1.3.0

**Comment by cy6erGn0m** [comment]
You also generally don't need to invoke `Engine.create()`, use HttpClient's configuration lambda instead

**Comment by cy6erGn0m** [comment]
OkHttp should handle websockets properly, Android shouldn't (since it's a wrapper over `HttpUrlConnection`)

**Comment by charlag** [comment]
Hi
Thanks a lot for the response, especially on the weekend, it's appreciated a lot!
Shame on me for not noticing outdated version. Now I updated it and got useful error message that my path was wrong.
When I fixed the path, I still get transformation message. I tried to print the headers but it doesn't seem like `Upgrade` was sent:

```
D/HTTP: REQUEST: https://mail.tutanota.com/event
    METHOD: HttpMethod(value=GET)
    COMMON HEADERS
D/HTTP: -> Accept: application/json
    -> Accept-Charset: UTF-8
    CONTENT HEADERS
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.charlag.tuta, PID: 20333
    io.ktor.client.call.NoTransformationFoundException: No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class io.ktor.client.features.websocket.DefaultClientWebSocketSession
    with response from https://mail.tutanota.com/event:
    status: 200 OK
    response headers: 
    content-length: 0
    , date: Sat, 25 Jan 2020 10:44:10 GMT
    , referrer-policy: no-referrer
    , strict-transport-security: max-age=63072000; includeSubDomains; preload
    , x-content-type-options: nosniff
    , x-frame-options: DENY
    , x-xss-protection: 1
```
Engine.create is needed because of my abstraction where platform provides engine to the common API code. I will replace it later.

**Comment by charlag** [comment]
Update: using `wss://` url directly worked it seems (at least connection was established). I'm not sure why upgrade wasn't handled with `https://` URL (like it worked in browser).

**Comment by e5l** [comment]
That's because we can't distinguish WebSocket and HTTP at the API level, but the browser has a separate method for WebSocket connect. Probably we should adjust the protocol inside `wss` method.

**Comment by manmeet-trantor** [comment]
Client is closing immediately on Android 7.1.1 however this is working on Android 8.1 ( testing on emulator )
Any idea what is missing
`private val client = HttpClient(CIO) {
        install(WebSockets)
}

 client.ws(
            method = HttpMethod.Get,
            host = "192.168.232.2",
            port = 8080, path = "/ws"
        ) { 
            send(Frame.Text("Ping to webserver"))
            try {
                val frame = incoming.receive()
                when (frame) {
                    is Frame.Text -> Log.i(TAG, "message received: ${frame.readText()}")
                    is Frame.Binary -> println(frame.readBytes())
                }
            } catch (e: ClosedReceiveChannelException) {
                Log.w(TAG, "Failure: ${e.message}")
            } catch (e: Exception) {
                Log.w(TAG, "Failure: ${e.message}")
            }
}`

ktor_version = '1.3.2'

Is this duplicate of #732 
My guess is that this has been fixed with #999 

Any idea what is missing

**Comment by charlag** [comment]
I used OkHttp as a runtime, I'm not sure from which version CIO would work

**Comment by manmeet-trantor** [comment]
Did it work for you or are you still getting some errors as you posted in trailing comments
and which version are you running on ( Android + ktor )

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-487">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by NurseyitTursunkulov** [comment]
@charlag is there any progress?

**Comment by e5l** [comment]
You can use `OkHttp` engine for `Ktor` as workaround

**Comment by NurseyitTursunkulov** [comment]
@e5l how to use it? can you please share code?

**Comment by NurseyitTursunkulov** [comment]
@e5l is it in Ktor or in Android?

**Comment by NurseyitTursunkulov** [comment]
Also I have this problem:
java.net.SocketTimeoutException: failed to connect to ws/64.70.19.33 (port 80)

even though I specified host as 
 host = "http://192.144.444.4"

**Comment by NurseyitTursunkulov** [comment]
` val client = HttpClient(OkHttp) {
                    install(WebSockets)
                }
                try {

                    client.ws(
                        "http://192.168.43.4:8080/chat".asCorrectWebSocketUrl,//64.70.19.33
                    ) {}`

this way it worked

**Comment by cyb3rko** [comment]
Any updates or do you all still use the OkHttp engine as a workaround?

**Comment by chanphiromsok** [comment]
Switch HttpClient engine from HttpClient(Android to CIO) work for me check this https://github.com/philipplackner/OnlineTicTacToe/blob/master/app/build.gradle
