### ISSUE TITLE
Static resources and (caching) headers

### ISSUE THREAD

**Issue by spand** [ktorio/ktor#159]
If I am using `static { resources(String) } ` how do I customize the cache headers? I have some static resources that I would like to cache forever

Maybe `resources` should also take decorating closure a la `fun Route.resources(resourcePackage: String? = null, block: (Resource) -> Resource = { it })` ?

**Comment by orangy** [comment]
That's a very good point. What could be other properties of a response that needs adjusting? If it's just cache headers, it's easier to make a decorating function:
```
static {
   cache(forever) {
     files("/foo")
   }
}
```

**Comment by spand** [comment]
I dont have this need myself but I could imagine `Content-Type` type also.

**Comment by kosiakk** [comment]
I've made a small Feature to set cache headers on all resources and files:

```
class CacheStaticResources(val maxAgeSeconds: Int, val visibility: CacheControlVisibility) {

    class Configuration {
        var maxAgeSeconds = 10 * 60
        var visibility = CacheControlVisibility.PUBLIC
    }

    companion object Feature : ApplicationFeature<ApplicationCallPipeline, Configuration, CacheStaticResources> {
        override val key = AttributeKey<CacheStaticResources>("CacheStaticResources")
        override fun install(pipeline: ApplicationCallPipeline, configure: Configuration.() -> Unit): CacheStaticResources {

            val config = Configuration()
            configure(config)

            val feature = CacheStaticResources(config.maxAgeSeconds, config.visibility)
            
            // Intercept response pipeline and after the content is ready to be served
            // add cacheControl for static RESOURCES
            pipeline.sendPipeline.intercept(ApplicationSendPipeline.Transform) { message: Any ->

                if (HttpHeaders.CacheControl in call.response.headers)
                    return@intercept // Cache header is already present

                when (message) {
                    is ResourceFileContent,
                    is LocalFileContent -> {
                        // Static resources
                        call.response.cacheControl(MaxAge(
                                maxAgeSeconds = feature.maxAgeSeconds,
                                visibility = feature.visibility
                        ))
                    }
                }
            }

            return feature
        }

    }
}
```

Is that something useful?

**Comment by orangy** [comment]
That looks nice, however `ResourceFileContent` & `LocalFileContent` are implementing `Resource` interface and thus has their cache control info with them. Via `FinalContent.headers` it might go into headers being sent and thus overwrite whatever is being sent in the feature. It is all pretty complicated as of now, we need to simplify this part of the system.

**Comment by orangy** [comment]
We refactored this part significantly, so it's now easy to add it. I think we can make it soon.

**Comment by RamenSea** [comment]
I am also having issues delivering pre-gzipped resources as the content type is not properly set.

**Comment by cy6erGn0m** [comment]
`CachingHeaders` features is implemented now. See http://ktor.io/features/caching-headers.html

**Comment by spand** [comment]
So is this fixed in the sense that one can
1. First list all your static resources in a `static { }` block
2. Install `CachingHeaders` and then duplicate all the same paths for setting their headers?

If that is the case then I would not really consider this fixed. Seems to fit the bill for the general case based on content-type but at least in our case this is sub optimal where we have different files of the same type with differing expiry.

**Comment by NorbertSandor** [comment]
> duplicate all the same paths for setting their headers

May I ask how could you achieved this? I see no option to conditionally set caching headers based on the resource's path...

**Comment by NorbertSandor** [comment]
> I was under the impression that you would install the feature under a path but maybe I am mistaken.

No, I don't think so :(
