### ISSUE TITLE
Is there a way to run multiple servers in a single process?

### ISSUE THREAD

**Issue by AdityaAnand1** [ktorio/ktor#1601]
If I simply call `embeddedServer(..).start(wait = true)` twice (say I want to run two servers in same process), then only the first one runs.

Is there a way to run both of them in the same process? Perhaps via some coroutine trick?

**Comment by pvasin2** [comment]
Call `.start(wait = false)` and then wait on the last server or something else, e.g. join a coroutine.

**Comment by cy6erGn0m** [comment]
The other way is to start coroutines or threads.
