### ISSUE TITLE
Undefined Routes

### ISSUE THREAD

**Issue by muth0mi** [ktorio/ktor#1606]
How do I throw status pages for for routes to undefined endpoints?

**Comment by cy6erGn0m** [comment]
https://ktor.io/servers/features/status-pages.html

**Comment by muth0mi** [comment]
Thank you @cy6erGn0m 
I've been able to achieve the same by adding the following code block

   `status(HttpStatusCode.NotFound) {
               call.respond("Undefined Route")
   }`
