### ISSUE TITLE
io.ktor.network.tls.certificates.generateCertificate DNE in 1.3.0

### ISSUE THREAD

**Issue by dustinevan** [ktorio/ktor#1612]
io.ktor.network.tls.certificates.generateCertificate doesn't exist in 1.3.0 but the docs say it does
https://api.ktor.io/1.3.0/io.ktor.network.tls.certificates/index.html

**Comment by defel** [comment]
Hello, can confirm this.

The function `generateCertificate` exists here: https://github.com/ktorio/ktor/blob/master/ktor-network/ktor-network-tls/ktor-network-tls-certificates/jvm/src/io/ktor/network/tls/certificates/Certificates.kt#L28

But it is not possible to import it as described in the docs.

**Comment by DonGiovanni83** [comment]
I encountered the same problem. I can see the `generateCertificate` function in the dependencies src as a public function. However, my IntelliJ can't find it.

**Comment by uglyog** [comment]
All the 1.3.x versions of ktor-network-tls is missing all the classes in the certificates package except CertificateType.

`jar tf ktor-network-tls-1.2.3.jar` shows
```
io/ktor/network/tls/certificates/
io/ktor/network/tls/certificates/KeyStoreBuilder.class
io/ktor/network/tls/certificates/CertificatesKt$writeX509Counterparty$1.class
io/ktor/network/tls/certificates/CertificateInfo.class
io/ktor/network/tls/certificates/CertificatesKt$writeX509Info$1$$special$$inlined$buildPacket$lambda$1$1.class
io/ktor/network/tls/certificates/CertificatesKt$writeAlgorithmIdentifier$1.class
io/ktor/network/tls/certificates/CertificatesKt.class
io/ktor/network/tls/certificates/CertificatesKt$writeX509Info$1$$special$$inlined$buildPacket$lambda$1$1$1.class
io/ktor/network/tls/certificates/CertificatesKt$writeX509Info$1.class
io/ktor/network/tls/certificates/CertificatesKt$writeX509Info$1$$special$$inlined$buildPacket$lambda$1.class
io/ktor/network/tls/certificates/CertificatesKt$writeX509Info$1$$special$$inlined$buildPacket$lambda$1$1$1$1$1.class
io/ktor/network/tls/certificates/CertificatesKt$writeCertificate$1$1.class
io/ktor/network/tls/certificates/Counterparty.class
io/ktor/network/tls/certificates/CertificateType.class
io/ktor/network/tls/certificates/BuildersKt.class
```
while `java tf ktor-network-tls-1.3.2.jar` only shows
```
io/ktor/network/tls/certificates/
io/ktor/network/tls/certificates/CertificateType.class
```

**Comment by uglyog** [comment]
It's been moved to ktor-network-tls-certificates, the documentation at https://ktor.io/servers/self-signed-certificate.html needs to be updated to reflect this.

**Comment by rawatpallavi** [comment]
@uglyog Agreed. For now I am using the dependency as  "io.ktor:ktor-network-tls-certificates:1.3.1"
Could not really find one for 1.3.2 for the ktor-network-tls-certificates..

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-484">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Closed
