### ISSUE TITLE
Bug in move refactoring for ktor plugin in IntellijIDEA

### ISSUE THREAD

**Issue by slavam2605** [ktorio/ktor#1617]
**Ktor Version and Engine Used (client or server and name)**
Intellij IDEA 2019.3.2, Ktor plugin 1.3.0

**Describe the bug**
See **To Reproduce** for details.

**To Reproduce**
1. Create a default project.
2. Change package of `ApplicationKt` file to no package. 
3. Edit `application.conf` appropriately (`modules = [ ApplicationKt.module ]`).
4. Create a package with the name `server`.
5. Move `Application.kt` file to this package.

**Expected behavior**
`modules = [ server.ApplicationKt.module ]` in `application.conf`.

**Actual behavior**
`modules = [ ApplicationKt.server.module ]` in `application.conf`. New package is added to the wrong place.

**Comment by cy6erGn0m** [comment]
What IDE kotlin plugin version do you use? Is it 1.3.61?

**Comment by cy6erGn0m** [comment]
Opened https://youtrack.jetbrains.com/issue/KT-36382 since I believe it is not related to ktor plugin.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-482">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
The plugin is deprecated
