### ISSUE TITLE
kotlinMultiplatform publications miss the gradle metadata

### ISSUE THREAD

**Issue by LouisCAD** [ktorio/ktor#1619]
Checked on releases 1.3.0 and 1.3.1.

Example : https://bintray.com/version/files/kotlin/ktor/ktor/1.3.0?order=asc&sort=name&basePath=io%2Fktor%2Fktor-auth-jwt-kotlinMultiplatform%2F1.3.0&tab=files

This makes these publications plain useless.

**Comment by r4zzz4k** [comment]
Not sure if related or not, but for ktor-client Gradle Metadata (mentioning both native and JVM with JS) is located at `io.ktor:ktor-client-core-native`, not at `io.ktor:ktor-client-core` as one would expect.

**Comment by martinbonnin** [comment]
It's the same situation as `kotlinx.coroutines` where `org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$version` also works for JVM-JS. See https://github.com/Kotlin/kotlinx.coroutines/issues/1096#issuecomment-559781977

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-480">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in `1.4.0`
