### ISSUE TITLE
iOS Client Cookies on 302 Response

### ISSUE THREAD

**Issue by nectar1** [ktorio/ktor#1625]
**Ktor Version and Engine Used (client or server and name)**
1.3.0 iOS client

**Describe the bug**
if you setup cookies storage manually by
`install(HttpCookies) {
    storage = AcceptAllCookiesStorage()
}`
on redirection response (http code 302) cookies doest apply on new request 

I thought that AcceptAllCookiesStorage is default storage, but if I don't setup storage everything works fine.

Android is ok in both cases.

**Comment by e5l** [comment]
Hi @nectar1, the issue is fixed in `1.3.2`
