### ISSUE TITLE
Add the possibility to combine authentications (AND/OR) per route

### ISSUE THREAD

**Issue by kroegerama** [ktorio/ktor#1628]
**Subsystem**
Server

**Is your feature request related to a problem? Please describe.**
I need the possibility to add two different authentications to my routes. I need them both to return a valid principal to allow the route to be called. (Global ApiKey in Header AND token as query parameter for _some_ routes)

**Describe the solution you'd like**
A possible solution was posted in #1191.
The following syntax could be used to allow the AND combinator:
```kotlin
//no authentication
route("/insecure") {

    authenticate("header") {

        //only header auth
        route("/secured") {

            authenticate("token") {

                //header auth AND token auth
                route("/supersecure") {

                }
            }
        }
    }
}
```

The OR combinator would work (as it works now):
```kotlin
//no authentication
route("/insecure") {

    authenticate("header", "token") {

        //header auth OR token auth
        route("/semi_secure") {

            authenticate("supertoken") {
                
                //(header auth OR token auth) AND supertoken auth
                route("/superdupersecure") {

                }
            }

        }
    }
}
```

**Motivation to include to ktor**
I think that many users would benefit from this feature as it provides a better control over the authentications.
E.g. we could have a global basic auth with additional per-route api keys.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-477">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
