### ISSUE TITLE
Expose LocationInfo in ktor locations

### ISSUE THREAD

**Issue by bizarre** [ktorio/ktor#1657]
**Subsystem**
Server

**Is your feature request related to a problem? Please describe.**
We wanted our typed locations to be able to define a permission node / access level. We did this via an additional annotation but then we had to write an interceptor that would get the class annotated with `@Location` **from the request path** and check for ours. The problem is that there doesn't seem to be any public access to the mapping done in Locations. Right now we're using a pretty-narly looking reflection solution that's less than ideal.

**Describe the solution you'd like**
Exposing `io.ktor.locations.Locations$LocationInfo` and an immutable copy of `io.ktor.locations.Locations.info` should be enough.

**Motivation to include to ktor**
I'm sure this could be a beneficial feature to a lot of users, even if it's not implemented in the way described above. It'll allow users to add additional properties to their routes and implement them in interceptors (and elsewhere) without having to do any reflection or map what is already mapped within _ktor.locations_.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-468">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in 1.5.3
