### ISSUE TITLE
call.request.host() returns strange result on localhost

### ISSUE THREAD

**Issue by altavir** [ktorio/ktor#1663]
**Ktor Version and Engine Used (client or server and name)**
Ktor server (CIO) `1.3.1`, plain JS on the client.

**Describe the bug**
In my application I need to modify a requesting host address and send back a request for data.
When called on localhost server, `call.request.host()` returns `0.0.0.0.0.0.0.0` instead of ip4 address, which does not play well with some JS functions. It was working properly on 1.2.3, but is broken after migration.

**Expected behavior**
Don't know, maybe it is by design, but it should be documented in that case.

**Comment by cy6erGn0m** [comment]
This is introduced as per PR #1531

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-466">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed since 1.4.0
