### ISSUE TITLE
Does ktor support androidNative in mpp project ?

### ISSUE THREAD

**Issue by VincentChen1212** [ktorio/ktor#1669]
I have a mpp project with androidNative/iOS/jvm

I want to write HttpClient in common
but I find androidNative can't import HttpClient.
```
implementation("io.ktor:ktor-client-core:$ktor_version")
implementation("io.ktor:ktor-client-curl:$ktor_version")
=> All Error
```

So, does ktor support androidNative ??

Thanks.

**Comment by cy6erGn0m** [comment]
I believe it should be a way. Not sure how to bundle curl properly, @e5l ?

**Comment by ANURAGX** [comment]
Is this still un-supported?
I do have my sdk project, and I'm exporting C wrappers for all platforms except android.

**Comment by ANURAGX** [comment]
Is this still un-supported?
I do have my sdk project, and I'm exporting C wrappers for all platforms except android.

Any near future plans or any alpha support available or any workaround?

**Comment by e5l** [comment]
Hey! We do not currently support it, but it shouldn't be a big issue :)

Could you log an issue for that? We also would be happy to accept the PR

**Comment by e5l** [comment]
@dtretyakov have such experience, maybe he can share insights
