### ISSUE TITLE
Implement Content Negotiation feature

### ISSUE THREAD

**Issue by hhariri** [ktorio/ktor#167]
Currently, if I want to send back a response in JSon, I have to do 

```kotlin
install(GsonSupport)
``` 

This feels like it's coupling a specific implementation of Json encoding with the feature of actually representing a response with a specific content type. 

Considering generalising this support with something more generic such as 

```kotlin
install(AutoContentType)
```

and register different content types with specific serialisers/deserialisers. For instance 

```kotlin
register("application/json", GsonSerialiser)
register("application/xml", XmlSerialiser)
```

and then allow the respond call to specify the content type

```kotlin
call.respond(listOf(myStuff), "application/json")
```

which will be picked up by the correct serialiser.

**Comment by orangy** [comment]
Yes, something like this is planned.

**Comment by McPringle** [comment]
In my opinion the content type should not be specified at the respond call. It should be "hidden" by ktor like it is in JAX-RS, which looks at the `accept` header of the request and sends a corresponding response. There should be no content type hard coded in the business code, ktor could handle this pretty well for me under the hood. _jm2c_

**Comment by orangy** [comment]
@McPringle agree, that's the plan. It should be something like this:
```
install(AutoContent) {
   register(ContentType.Application.Json, GsonConverter)
}

routing { 
   get("/api/user/{id}") {
      val id = call.parameters["id"]
      val user = db.getUser(id)
      call.respond(user)
   }
}
```
(error handling omitted for clarity)

Same for `call.receive<User>()` for POST data.

**Comment by hhariri** [comment]
@McPringle Yes. That's what Wasabi did too. It was using the request sent by the client, be it via accept headers, or via URL/query parameters. But it also allowed for explicit content negotiation, i.e. I want to override what the request is sending or I have no other option. 

See [Content Negotiation on Wasabi](https://github.com/wasabifx/wasabi#content-negotiation) for what I have in mind here...

**Comment by rocketraman** [comment]
> But it also allowed for explicit content negotiation, i.e. I want to override what the request is sending or I have no other option.

This is important. Sometimes clients are not coded correctly and do not send the `Accept` header, or send it with invalid content -- and these clients are not always within our control.

**Comment by orangy** [comment]
It's basically there in 0.9. We need feedback! :)

**Comment by leus** [comment]
Any news on this?

**Comment by orangy** [comment]
@leus it's in master, and released in 0.9.0 (AFAIR), but anyway it's in latest `0.9.1-alpha-9`. We plan to release `0.9.1` pretty soon.

**Comment by leus** [comment]
Some pointers on how to check this out? I have 0.9.1-alpha-9, but I haven't found any documentation or examples on this (I want to be able to serve html or json depending on routing)

**Comment by orangy** [comment]
Could you please give an example of what you need to do?

**Comment by leus** [comment]
@orangy if I have a route (for example, `/v1` or `/api`) I want to use content negotiation there. But I want to still serve some HTML in other areas. I haven't figured this yet, because it seems the examples make content negotiation available for all routes.

**Comment by orangy** [comment]
Content Negotiation works only for data that is not one of the standard types (String, HttpStatusCode, etc), or is not `OutgoingContent`. If you are using template engine (Velocity or Freemarker), kotlinx.html via `respondHtml` content negotiation shouldn't kick in.

**Comment by cy6erGn0m** [comment]
Please see http://ktor.io/features/content-negotiation.html for details.
