### ISSUE TITLE
Support for java.util.UUID parameter in ktor-locations

### ISSUE THREAD

**Issue by orangain** [ktorio/ktor#1673]
**Subsystem**

Server, ktor-locations

**Is your feature request related to a problem? Please describe.**

I don't want to write  a custom converter to convert a string to `java.util.UUID`. Using custom converters makes controllers less reusable and it is less readable especially for new project members.

**Describe the solution you'd like**

Ktor's built-in converter supports converting a string to/from `java.util.UUID`.

**Motivation to include to ktor**

UUID is a globally unique identifier and commonly used in URLs. In particular, UUID v4 is a handy choice when we need an unguessable or scattering identifier. It is convenient if ktor-locations supports it by default. For example, [Spring](https://github.com/spring-projects/spring-framework/blob/v5.2.3.RELEASE/spring-core/src/main/java/org/springframework/core/convert/support/DefaultConversionService.java#L167) and [Django](https://docs.djangoproject.com/en/3.0/topics/http/urls/#path-converters) provide built-in support for UUIDs.

**Comment by cy6erGn0m** [comment]
You may provide a custom [`ConversionService`](https://ktor.io/servers/features/data-conversion.html) and add UUID.

**Comment by orangain** [comment]
@cy6erGn0m I know a custom converter can convert a string to UUID, but what I request here is **built-in** support of `java.util.UUID`. As I wrote above, I believe UUID is worth built-in support as some Web application frameworks do.

If built-in support of UUID is acceptable, I can send a pull request.

**Comment by cy6erGn0m** [comment]
The only disadvantage is that it is JVM only. So you can't use it with ktor client at non-JVM platforms and no future support if server will support non-JVM targets as well

**Comment by orangain** [comment]
@cy6erGn0m Reading #1681 and related issues, I understood what you mean; ktor-locations is now migrating to Kotlin Multiplatform.

So I will close this issue for now. As you say, java.util.UUID is specific to the JVM. I might propose this again seeing how the conversion of BigInteger and BigDecimal is implemented.

**Comment by cy6erGn0m** [comment]
@orangain there is a change to get MPP uuid. Please see https://github.com/cy6erGn0m/kotlinx-uuid preview if still interested
