### ISSUE TITLE
ktor-server-test-host - Exception when reading complex object body using io.ktor.request.recieve 

### ISSUE THREAD

**Issue by yaelsteinberger** [ktorio/ktor#1683]
**Ktor Version and Engine Used (client or server and name)**
- **module:** ktor-server-test-host 
- **ktor version:** 1.2.6

**Describe the bug**
I'm getting a **CannotTransformContentToTypeException** when using `io.ktor.request.recieve` to read the request’s body which contains a complex object (e.g. `call.recieve<Map<String,String>>()`).
No issues when `recieve`'s casting type is Any/Object (e.g. `call.recieve<Any>()`)

**To Reproduce**
1. Write the following:
**Code to test:**
```
import io.ktor.request.receive
import io.ktor.application.ApplicationCall

suspend fun mapBody(call: ApplicationCall): Map<String, String> {
    return call.receive()
}
```

**Test code:**
```
import io.ktor.server.testing.*
import kotlinx.coroutines.runBlocking
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe
import com.fasterxml.jackson.databind.ObjectMapper

object MyTest: Spek({
    describe("Testing Body"){
        val mapper = ObjectMapper()
        val body = mapOf("name" to "George")

        withTestApplication {
            handleRequest(HttpMethod.Post, "/") {
                setBody(mapper.writeValueAsString(body))
            }.let { call ->
                runBlocking{
                    mapBody(call)
                }
            }
        }
    }
})
```

2. Run the test on your development environment (e.g. intelliJ)

3. See error
![image](https://user-images.githubusercontent.com/39768210/75502188-343ea800-5a26-11ea-957a-19e29698d6e8.png)

**Expected behavior**
As the actual http request when I use Insomnia, I expect the `mapBody()` to return:
![image](https://user-images.githubusercontent.com/39768210/75502331-a9aa7880-5a26-11ea-9a6e-ba519557476b.png)

**Additional info and Screenshots**

I've debbuged the issue and looked into the file: `io.ktor.request -> ApplicationReceiveRequest.kt`, where the `recieve` method was implemented:

![image](https://user-images.githubusercontent.com/39768210/75502506-0c9c0f80-5a27-11ea-9487-0b53d6df5a2d.png)

I've changed `myBody()` to return Any/Object reather than a Map, and noticed a difference in the `transformed` value when running the test versus receiving the request from Insomnia:

**- Http request from Insomnia:** 
![image](https://user-images.githubusercontent.com/39768210/75503419-b2e91480-5a29-11ea-9001-091a883b062c.png)

**- Request from Test:**
![image](https://user-images.githubusercontent.com/39768210/75503440-bed4d680-5a29-11ea-8b0a-e8c08da01b5c.png)

When the request arrives from insomnia the `call.recieve<Any>()` recognises the body as a map. However, it's not so with the test call. 
The bodies in the requests are the same in both cases and just to be sure, I've verified their ByteArrays are identical as well (using: `call.request.receiveChannel().toByteArray()`)

I'm fairly new to Kotlin, and not sure what I'm doing wrong. I couldn't find any similar issue around, so, I though it would be worth rasing the issue with you.

Thanks!

**Comment by cy6erGn0m** [comment]
Just curious, is there any specific reason of using old 1.2.6?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-460">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
To make it work you need to install the [ContentNegotiation](https://ktor.io/docs/serialization.html) plugin and add `Content-Type` header with a value `application/json` to a request. Here is the code:
```kt
@Test
fun testLoginSuccessWithTracker(): Unit = withTestApplication {
    val mapper = ObjectMapper()
    val body = mapOf("name" to "George")

    withTestApplication {
        application.install(ContentNegotiation) {
            jackson()
        }

        handleRequest(HttpMethod.Post, "/") {
            addHeader("Content-Type", "application/json")
            setBody(mapper.writeValueAsString(body))
        }.let { call ->
            runBlocking{
                mapBody(call)
            }
        }
    }
}
```
