### ISSUE TITLE
Support more fine grained caching setup with ease

### ISSUE THREAD

**Issue by TWiStErRob** [ktorio/ktor#1688]
**Subsystem**
CachingHeaders feature 1.3.1 and its [docs](https://ktor.io/servers/features/caching-headers.html)

**Is your feature request related to a problem?**
I was trying to set up a cache for an endpoint, but the request has to be conditionally cached depending on whether the user is logged in. i.e.
```kotlin
get<Cinemas.Routes.List> {
	if (call.hasUser) {
		// this cannot be cached, because the user can change cinema's state (favorite it)
		call.respond(repository.getCinemasAuth(userID = call.userId))
	} else {
		// no logged in user, safe to cache for days/weeks since the cinema list barely ever changes
		call.cache(CachingOptions(/* parameters specifically for this response path */))
		call.respond(repository.getActiveCinemas())
	}
}
```

**Describe the solution you'd like**
The implementation of `ApplicationCall.cache()` was really tricky. The documentation only shows how to cache centrally based on content type. No mention of caching by route or code path. Reading the code and debugging for hours I found that the following setup works:
```kotlin
embeddedServer(Netty, port) { // this: Application
	install(CachingHeaders) {
		// default is `options { it.caching }`, see ktorio/ktor#1687
	}
	routing {
		get ... // as above
	}
}
fun ApplicationCall.cache(caching: CachingOption) {
	this.response.pipeline.intercept(ApplicationSendPipeline.Render) {
		// by definition of Render phase, it can be only OutgoingContent here
		// this will be read by the default CachingHeaders.options lambda
		// and put it among the response headers
		(subject as OutgoingContent).caching = caching
	}
}
```

**Motivation to include to ktor**
A function like `call.cache(...)` above or a property `call.caching = ...` would be beneficial to share via in-built extensions, so that users who write Ktor apps can set caching up easily.

It is possible that what's missing is a lambda-bearing overload of `respond(Any)` [similar to `respondText`](https://github.com/ktorio/ktor/issues/1687), where `OutgoingContent` can be amended.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-457">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
