### ISSUE TITLE
Content-type header is missing in Request when using LogLevel.BODY

### ISSUE THREAD

**Issue by audkar** [ktorio/ktor#1690]
**Ktor Version and Engine Used (client or server and name)**
version: `1.3.1`
lib: `ktor-client-cio`
additional modules: `ktor-client-logging-jvm`

**Describe the bug**
Content-type header is missing when `LogLevel.BODY` is set. _(also I am using multi-part body, not sure if relevant)_. Header exists if removing logging or setting `LogLevel.HEADER`.

**To Reproduce**
1. Set logging 
```kotlin
HttpClient {
  install(Logging) {
  logger = Logger.ANDROID
  level = LogLevel.BODY
  }
}
```
2. Do multi-form request
```kotlin
val response = httpClient.post<String> {
  url("http://someurl")
  body = MultiPartFormDataContent(formData {
    append(
          "file",
          "file.txt",
          ContentType.parse("text/plain"),
          contentBytes.size.toLong()
    ) {
      writeFully(contentBytes)
    }
})
```
3. Observe missing `Content-Type: multipart/form-data; <...>` header

**Expected behavior**
`Content-Type: multipart/form-data; <...>` in request exists

**Comment by e5l** [comment]
Hi @audkar, it looks similar to fixed: https://github.com/ktorio/ktor/commit/fb09c374b4d6adaf057ad7c76859c46459c0f725

Could you take a look?

**Comment by audkar** [comment]
Currently I have no access to computer. But just looking at source code I don't think this is same. Unless removing `suspend` fixes some magical problem. In my case header missing from actual request. It isn't just not logged.

**Comment by alistairsykes** [comment]
I am experiencing the same issue with jvm and native too:
`io.ktor:ktor-client-okhttp:1.3.1`
`io.ktor:ktor-client-logging-jvm:1.3.1`
`io.ktor:ktor-client-ios:1.3.1`
`io.ktor:ktor-client-logging-native:1.3.1`

I am also using a multi-part body.

```
client.post<String> {
    url("https://api.example.com/some/example/path")
    accept(ContentType.Application.Json)
    body = MultiPartFormDataContent(formData {
        append("version", "1.0")
        append("locale", "en-GB")
    })
}
```

I used Charles to intercept the traffic.

**LogLevel.HEADERS**
```
POST /some/example/path HTTP/1.1
Accept: application/json;application/json
Accept-Charset: UTF-8
User-Agent: Ktor client
Content-Type: multipart/form-data; boundary=-[SOME HASH]-
Content-Length: ***
Host: api.example.com
Connection: Keep-Alive
Accept-Encoding: gzip




---[SOME HASH]-
Content-Disposition: form-data; name=version
Content-Length: 4

1.0
---[SOME HASH]-
Content-Disposition: form-data; name=locale
Content-Length: 5

en-GB
---[SOME HASH]---
```

**LogLevel.BODY**
```
POST /some/example/path HTTP/1.1
Accept: application/json;application/json
Accept-Charset: UTF-8
User-Agent: Ktor client
Transfer-Encoding: chunked
Host: api.example.com
Connection: Keep-Alive
Accept-Encoding: gzip
```

It looks to me like adding body logging is removing the body from the actual network request.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-456">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
