### ISSUE TITLE
Content-Disposition additional parameters should be inside quotes

### ISSUE THREAD

**Issue by audkar** [ktorio/ktor#1691]
**Ktor Version and Engine Used (client or server and name)**
1.3.1, client

**Describe the bug**
`Content-Disposition` additional parameters should be inside quotes in multi-part Request body.

**To Reproduce**
1. Multi-part request
```kotlin
import io.ktor.client.request.forms.append

<...>
httpClient.post<String> {
      body = MultiPartFormDataContent(formData {
        append(
          "file",
          "file.txt",
          ContentType.parse("text/plain")
        ) {
          writeText("content")
        }
      })
    }
<...>
```
2. Observe part data in Request body: `Content-Disposition: form-data; name=file; filename=file.txt`

**Expected behavior**
Header matching spec: 

> The first parameter in the HTTP context is always form-data. Additional parameters are case-insensitive and have arguments that use quoted-string syntax after the '=' sign. Multiple parameters are separated by a semi-colon (';').

`Content-Disposition: form-data; name="file"; filename="file.txt"`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by cy6erGn0m** [comment]
Note that MDN is not the spec. Looks like a value should be quoted if it doesn't fit in a so called _token_. Need to be investigated more

**Comment by cy6erGn0m** [comment]
For sure, the definition at MDN is not correct at all.  This is not the first time when MDN is not exactly correct or even wrong.

**Comment by audkar** [comment]
But in your posted spec value has types: `token | quoted-string`. `token` has specific format and in case value is not a `token` then it must be `quoted-string`. Best example would be `my file.txt` (filename with space)

**Comment by Myaamori** [comment]
This is a blocking issue for me. The API I'm working with at the moment rejects my requests unless the filename is quoted, claiming that the file extension is incorrect; I assume the server isn't reading the filename correctly due to the missing quotes. I'm considering just adding quotes manually as a workaround, but I'm scared that I'll forget about it when/if Ktor ends up addressing this issue resulting in double quoting.

**Comment by Myaamori** [comment]
For reference, `token` here seems to be defined as

```
       token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
       CHAR           = <any US-ASCII character (octets 0 - 127)>
```

where `1*` seems to mean "one or more". The name of the file in my case contained both `(`, `)`, `[` and `]`, so it was definitely not a valid `token`, meaning it should have been sent as a `quoted-string`.

In general, it seems to me that simply always sending a quoted string is the safest/simplest option? That's what curl does for one.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-455">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in Ktor 1.5.0

**Comment by sonder-joker** [comment]
I still get error at version 1.5.1.
```
---10d6dca55de98752-42e24f08eceb2643cb511ad4d68df6197b6e002ae4639c18ffa0
Content-Disposition: form-data; name=bkn
Content-Length: 10

1528532740
---10d6dca55de98752-42e24f08eceb2643cb511ad4d68df6197b6e002ae4639c18ffa0
Content-Disposition: form-data; name=source
Content-Length: 11

troopNotice
---10d6dca55de98752-42e24f08eceb2643cb511ad4d68df6197b6e002ae4639c18ffa0
Content-Disposition: form-data; name=m
Content-Length: 1

0
---10d6dca55de98752-42e24f08eceb2643cb511ad4d68df6197b6e002ae4639c18ffa0
Content-Disposition: form-data; name=pic_up; file; filename=temp_uploadFile.png
Content-Type: image/png

 PNG
...
```
```
MultiPartFormDataContent(formData {
                        append("qid", groupId)
                        append("bkn", bkn)
                        append("text", announcement.msg.text)
                        append("pinned", announcement.pinned)
                        append(
                            "settings",
                            json.encodeToString(
                                GroupAnnouncementSettings.serializer(),
                                announcement.settings ?: GroupAnnouncementSettings()
                            )
                        )
                        append("format", "json")
                    })
```

**Comment by davidejones88** [comment]
I am getting the same issue.

Working curl body:
```
--------------------------5SSwmw2ypNTZcRAdQZCwv1
Content-Disposition: form-data; name="purpose"
```

ktor faulty body:
```
--------------------------5SSwmw2ypNTZcRAdQZCwv1
Content-Disposition: form-data; name=purpose
```

As a workaround, manually adding the quotes fixes the issue
```
        val multipart = MultiPartFormDataContent(
            formData {
                append("\"purpose\"", purpose)
                append("\"file\"", image,
                    Headers.build {
                    append(HttpHeaders.ContentType, ContentType.Image.PNG.toString())
                    append(HttpHeaders.ContentDisposition, "filename=\"test.png\"")
                })
            },
            boundary = boundary
        )
```

Our current setup
```
ksp = "2.0.20-1.0.24"
ktor = "2.3.12"
ktorfit = "2.1.0"
```
