### ISSUE TITLE
Missing Locations params result in 404 instead of 400

### ISSUE THREAD

**Issue by goodhoko** [ktorio/ktor#1711]
**Ktor Version and Engine Used (client or server and name)**
Server/netty 1.3.0

**Describe the bug**
When an URL for a defined Location is hit but some of the query parameters are missing HTTP404 is returned instead of HTTP400 which makes more sense. See example below.

**To Reproduce**
First we setup a simple application
```kotlin
fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@Location("/user") data class User(val id: Long)

@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    install(Locations)
    routing {
        get<User> {
            call.respondText("User[id: ${id}]")
        }
    }
}
```
Now GETing `localhost/user?id=123` works fine but GETing `localhost/user` returns `HTTP 404` while `HTTP 400` would certainly make more sense.

**Expected behavior**
400 status code when requesting a location with missing parameters.

Or at least a provided ability to override this behaviour manually.

**Comment by goodhoko** [comment]
This issue is similar to https://github.com/ktorio/ktor/issues/155 but that comprises parameters passed in JSON in request body.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-447">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
