### ISSUE TITLE
corsCheckRequestHeaders false

### ISSUE THREAD

**Issue by cnyondy** [ktorio/ktor#1722]
**Ktor Version and Engine Used (client or server and name)**
ktor_version=1.3.1 
server

**Describe the bug**
CORS feature installed in Application
   install(CORS)
    {
        method(HttpMethod.Options)
        header(HttpHeaders.XForwardedProto)
        anyHost()
        allowSameOrigin = false
        allowCredentials = true
        allowNonSimpleContentTypes = true
        maxAgeDuration = 1.toDuration(DurationUnit.DAYS)
    }

The preflight request of some browser contains Access-Control-Request-Headers, but the field-value of it is empty, function corsCheckRequestHeaders will return false, and the browser will get 403 status.

------------------------------
preflight request header
------------------------------
Host: xxx
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: https://xxx
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 QBCore/4.0.1295.400 QQBrowser/9.0.2524.400 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2875.116 Safari/537.36 NetType/WIFI MicroMessenger/7.0.5 WindowsWechat
Access-Control-Request-Headers: 
Accept: */*
Referer: https://xxx
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.5;q=0.4

-------------------------
corsCheckRequestHeaders()
-------------------------

    private fun ApplicationCall.corsCheckRequestHeaders(): Boolean {

        val requestHeaders =
            request.headers.getAll(HttpHeaders.AccessControlRequestHeaders)
                ?.filter { !it.isBlank() } // add this line to fix the issue <<<<<<<<<<<<<<<<<<<<<<<
                ?.flatMap { it.split(",") }
                ?.map {
                    it.trim().toLowerCasePreservingASCIIRules()
                } ?: emptyList()

        return requestHeaders.none { it !in allHeadersSet }
    }

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-445">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
