### ISSUE TITLE
Undefined symbol: _curl_multi_poll when building for macOS using 1.3.2

### ISSUE THREAD

**Issue by joreilly** [ktorio/ktor#1723]
**Ktor Version and Engine Used (client or server and name)**
1.3.2, curl

Getting "Undefined symbol: _curl_multi_poll " when using v1.3.2 of Ktor as part of Kotlin/Native module used in macOS app.  I have added `libcurl` in XCode project.

**Comment by e5l** [comment]
Hi @joreilly, ktor search `curl` installed from brew by default. If you want to use custom version of curl, you should specify it in the `build.gradle` explicitly.

Here is the sample: https://github.com/JetBrains/kotlin-native/tree/master/samples/libcurl

**Comment by joreilly** [comment]
Hi @e5l , I'm probably missing something basic here but the error I'm getting is when building project in XCode....and it's in XCode where I've added `libcurl` dependency as shown in screenshot here (just default one that's available here)

<img width="847" alt="Screenshot 2020-03-16 at 08 00 49" src="https://user-images.githubusercontent.com/6302/76735352-a28ca580-675c-11ea-8912-d26a1596036a.png">

**Comment by e5l** [comment]
Could you list the build log here? It looks like this error was produced by gradle, inside the xcode build

**Comment by joreilly** [comment]
```
Ld /Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Products/Debug/BikeShareMac.app/Contents/MacOS/BikeShareMac normal x86_64 (in target 'BikeShareMac' from project 'BikeShareMac')
    cd /Users/joreilly/dev/github/BikeShare/macOS/BikeShareMac
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Products/Debug -F/Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Products/Debug -F/Users/joreilly/dev/github/BikeShare/macOS/BikeShareMac/Pods/../../../common/build/cocoapods/framework -filelist /Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Intermediates.noindex/BikeShareMac.build/Debug/BikeShareMac.build/Objects-normal/x86_64/BikeShareMac.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Intermediates.noindex/BikeShareMac.build/Debug/BikeShareMac.build/Objects-normal/x86_64/BikeShareMac_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Intermediates.noindex/BikeShareMac.build/Debug/BikeShareMac.build/Objects-normal/x86_64/BikeShareMac.swiftmodule -ObjC -lc++ -framework common -lcurl -lPods-BikeShareMac -Xlinker -dependency_info -Xlinker /Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Intermediates.noindex/BikeShareMac.build/Debug/BikeShareMac.build/Objects-normal/x86_64/BikeShareMac_dependency_info.dat -o /Users/joreilly/Library/Developer/Xcode/DerivedData/BikeShareMac-bjzblqsdmrnbegfbcjtyxltvkbhf/Build/Products/Debug/BikeShareMac.app/Contents/MacOS/BikeShareMac

Undefined symbols for architecture x86_64:
  "_curl_multi_poll", referenced from:
      _libcurl_curl_multi_poll_wrapper49 in common(result.o)
     (maybe you meant: _libcurl_curl_multi_poll_wrapper49, knifunptr_libcurl53_curl_multi_poll )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by joreilly** [comment]
so, the libcurl dependency right now (as per screenshot above) is configured in XCode.  Is it perhaps better to configure this dependency directly in `build.gradle`?

**Comment by e5l** [comment]
Yep, ktor definitely can't hook it up from the Xcode config. :)  I'm also looking for the idea of implementing that.

**Comment by joreilly** [comment]
the thing is that it "generally" works....if I don't include libcurl in XCode then I get ton of other curl undefined symbols....this is only one that's an issue so seems to be issue with version of libcurl being used

**Comment by joreilly** [comment]
Do you have example of how dependency on this can be specified in `build.gradle`?

**Comment by e5l** [comment]
Sure: https://github.com/JetBrains/kotlin-native/blob/c5576ad64e34b7617002ef69867e1d566a47e916/samples/libcurl/build.gradle.kts#L38

Btw the easiest way to setup curl on  the mac is to run `brew install curl` in terminal.

**Comment by joreilly** [comment]
I did run `brew install curl ` but didn't make any difference....possibly not version of libcurl picked up by XCode when it's linking?

**Comment by e5l** [comment]
Definitely, so unfortunatelly the single way to configure libcurl is manual :(

**Comment by joreilly** [comment]
I wasn't able to get any `build.gradle` config to make a difference but what did work was, after updating version I had installed locally,  to add following to XCode "Other Linker Flags"

-L/usr/local/opt/curl/lib

**Comment by martinbonnin** [comment]
I had the same issue when linking a debug Framework (release seems ok). From what I understand, the ktor binaries link dynamically with curl ? Isn't that a bit dangerous in case the curl installed on the client is incompatible with the curl used to compile ktor ? Would it be an option to link curl statically inside ktor (if that makes sense ?) ?
