### ISSUE TITLE
Build failure when using HttpClient with default engine on JS in 1.3.2

### ISSUE THREAD

**Issue by russhwolf** [ktorio/ktor#1724]
**Ktor Version and Engine Used (client or server and name)**
Ktor 1.3.2 with default JsClientEngine and no other modules included

**Describe the bug**
When compiling code that constructs an `HttpClient` on JS via `./gradlew build`, the `jsBrowserProductionWebpack` task fails.

**To Reproduce**
Sample code: https://github.com/russhwolf/KtorDemo1370/pull/1/files
Build output: https://github.com/russhwolf/KtorDemo1370/pull/1/checks?check_run_id=509492952

**Expected behavior**
The build succeeds.

**Comment by russhwolf** [comment]
I now think this is a duplicate of #961.

**Comment by e5l** [comment]
Thanks! Closed as duplicate
