### ISSUE TITLE
Invoking HttpClient on iOS causes build to overload heap space

### ISSUE THREAD

**Issue by russhwolf** [ktorio/ktor#1725]
**Ktor Version and Engine Used (client or server and name)**
Ktor 1.3.2 with default IosClientEngine and no other modules included

**Describe the bug**
When compiling code that constructs an `HttpClient` on iOS via `./gradlew build`, the build sometimes runs out of heap space and fails. I've observed this intermittently on small repro projects, but it's pretty consistent on first build so there might be something cache-related happening. Also happens consistently on a larger project.

**To Reproduce**
Minimal repro: https://github.com/russhwolf/KtorDemo1370/pull/2/files
Build output with failure: https://github.com/russhwolf/KtorDemo1370/pull/2/checks?check_run_id=509645071
Build success when `HttpClient` invokation is removed: https://github.com/russhwolf/KtorDemo1370/pull/3/checks?check_run_id=509667621

Larger project which reproduces the issue consistently: https://github.com/russhwolf/multiplatform-hello/tree/1.3.70
Build output? (it's been running over 5 hours at time of writing and hasn't yet completed): https://github.com/russhwolf/multiplatform-hello/runs/509321417?check_suite_focus=true

**Expected behavior**
The build succeeds.

**Comment by e5l** [comment]
Hi @russhwolf, it looks like kotlin-native update requires lot's of memory to build. @SvyatoslavScherbina.

You can try to add `org.gradle.jvmargs=-Xmx2g` in `gradle.properties` file as workaround.

**Comment by russhwolf** [comment]
Still testing in CI but I can confirm that workaround does the trick for me locally. Should have thought to try that myself. Thanks.

**Comment by russhwolf** [comment]
Confirmed the fix for both projects listed above. Not sure if it's better to close with that workaround or leave it open to track the fact that probably it's using more memory than it should.

**Comment by e5l** [comment]
The issue should be closed here. It's related to kotlin-native.
