### ISSUE TITLE
ContentConverter.convertForSend should receive a KType

### ISSUE THREAD

**Issue by ansman** [ktorio/ktor#1726]
**Subsystem** 
Server - Serialization

**Is your feature request related to a problem? Please describe.**
Just like in #875 it would be great if a `KType` would be passed to `ContentConverter.convertForSend` since it'd be impossible to correctly serialize parameterized types otherwise.

**Describe the solution you'd like**
Not sure how this could be done in a binary compatible way. I suppose changing the context's subject would be binary compatible since it's a generic but it would be a source incompatible change unless the subject is also declared as `out`.

**Motivation to include to ktor**
See the examples in #875. Writing polymorphic types or parameterized types can cause issues unless the expected type is know in advance.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-444">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by unoexperto** [comment]
@oleg-larshin Folks, any update on this ? Without KType we can't use 3rd-party serializers such as Mosi with generic values (e.g. List<String>).
