### ISSUE TITLE
Problem with WebSocket code

### ISSUE THREAD

**Issue by jkleiser** [ktorio/ktor#1730]
**Ktor Version and Engine Used (client or server and name)**
version, client/server, additional ktor modules included

I just generated a demo project including WebSocket by using https://ktor.io/quickstart/generator.html#. I then replaced these lines
```
while (true) {
  val frame = incoming.receive()
  if (frame is Frame.Text) {
    send(Frame.Text("Client said: " + frame.readText()))
  }
}
```
with these
```
for (frame in incoming) {
  when (frame) {
    is Frame.Text -> {
      val text = frame.readText()
      outgoing.send(Frame.Text("YOU SAID: $text"))
      if (text.equals("bye", ignoreCase = true)) {
        close(CloseReason(CloseReason.Codes.NORMAL, "Client said BYE"))
      }
    }
  }
}
```
which worked fine. I found them here: https://ktor.io/servers/features/websockets.html#actor

**Describe the bug**
On the same page, under "Usage as a Channel", I found this line
```
for (frame in incoming.mapNotNull { it as? Frame.Text }) {
```
which, as I understand, should be able to replace the three first lines (before `val text = frame.readText()`). However, in my case it leads to errors. See below.

**To Reproduce**
After replacing the three lines, as described above, and removing the left-over }'s, when I do `./gradlew run`, I get this:
```
> Task :compileKotlin FAILED
e: /Volumes/P3/Kotlin/ktor-demo/src/Application.kt: (95, 36): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline fun <T, R : Any> Array<out ???>.mapNotNull(transform: (???) -> ???): List<???> defined in kotlin.collections
public inline fun <R : Any> CharSequence.mapNotNull(transform: (Char) -> ???): List<???> defined in kotlin.text
public inline fun <T, R : Any> Iterable<???>.mapNotNull(transform: (???) -> ???): List<???> defined in kotlin.collections
public inline fun <K, V, R : Any> Map<out ???, ???>.mapNotNull(transform: (Map.Entry<???, ???>) -> ???): List<???> defined in kotlin.collections
public fun <T, R : Any> Sequence<???>.mapNotNull(transform: (???) -> ???): Sequence<???> defined in kotlin.sequences
e: /Volumes/P3/Kotlin/ktor-demo/src/Application.kt: (95, 49): Unresolved reference: it

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details
```

**Expected behavior**
No compilation errors.

**Comment by jorispz** [comment]
The `mapNotNull` method you try to use needs to be imported first, as it is an extension function on `ReceiveChannel`. So, adding
```
import kotlinx.coroutines.channels.mapNotNull
```
to your imports should fix your issue

**Comment by jkleiser** [comment]
Thanks. That worked. ;-)
