### ISSUE TITLE
insertPhaseBefore and insertPhaseAfter lead to different order

### ISSUE THREAD

**Issue by PeterUlb** [ktorio/ktor#1736]
**Ktor Version and Engine Used (client or server and name)**
1.3.2 server

**Describe the bug**
Using nested Feature's interceptPipeline leads to different results when using insertPhaseBefore and insertPhaseAfter.
Example:
`    customA {
        customB(1) {
            get {
                call.respond("")
            }
        }
    }`

Both added to Child of a Route via
`pipeline.insertPhaseBefore(ApplicationCallPipeline.Features, customA/B)
pipeline.intercept(customA/B)`

Using after:
[Phase('Setup'), Phase('Monitoring'), Phase('Features'), Phase('customB'), Phase('Call'), Phase('Fallback')]
[Phase('Setup'), Phase('Monitoring'), Phase('Features'), Phase('customA'), Phase('Call'), Phase('Fallback')]

Using before
[Phase('Setup'), Phase('Monitoring'), Phase('customA'), Phase('Features'), Phase('Call'), Phase('Fallback')]
[Phase('Setup'), Phase('Monitoring'), Phase('customB'), Phase('Features'), Phase('Call'), Phase('Fallback')]

**Expected behavior**
I would expect that both variants put Phase(customA) first, then Phase(customB) when merging the pipelines.

Upon googling I found the similar issue [here](https://stackoverflow.com/questions/57502789/user-type-restricted-route-feature-wrong-order-of-interceptors).

**Comment by cy6erGn0m** [comment]
Could you please provide more detailed/complete example? Currently, I don't get what exactly wrong here

**Comment by PeterUlb** [comment]
Please check this [gist](https://gist.github.com/PeterUlb/ec98fe4ab495aaa748b4e78b39f354cc).
Console output when I hit the endpoint is
Feature B
Feature A

I would expect 
Feature A
Feature B

It works when using insertPhaseBefore

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-438">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
