### ISSUE TITLE
Clearing Session Cookie in Chrome 80+ with SameSite and Secure 

### ISSUE THREAD

**Issue by mattupstate** [ktorio/ktor#1738]
Ktor Server 1.3.2

I'm currently experience what is explained in this [article](https://www.thinktecture.com/en/identity/samesite/how-to-delete-samesite-cookies/). TLDR: Chrome 80+ won't delete `SameSite` cookies unless the `Secure` and `SameSite` flags are both set. The current `call.sessions.clear<MySession>()` does not set the `Secure` flag or pass extensions through and thus a session will never be cleared for Chrome browsers.

To reproduce:

Setup an app with a `Sessions` config that looks similar to the following, ensuring to set `secure` and the `SameSite` values:

```kotin
install(Sessions) {
    cookie<MySessionObject>("SESSION") {
        cookie.path = "/"
        cookie.secure = true
        cookie.domain = "acme.test"
        cookie.extensions["SameSite"] = "None"
        cookie.maxAgeInSeconds = 2592000
    }
}
```

Setup endpoints to set and clear the session.
Access the endpoint to create the session over HTTPS
Access the endpoint to clear the session over HTTPS

The endpoint to clear the session will return the following Header:

```
set-cookie: SESSION=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Domain=acme.test; Path=/; $x-enc=URI_ENCODING
```

As you can see the `Secure` flag is not set. And you'll have to take my word for it, but Chrome, as explained in the article above, does not delete the cookie.

**Expected behavior**

Ideally, Ktor will pass the `Secure` flag along when clearing the cookie through the `call.sessions.clear` API.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-437">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
