### ISSUE TITLE
Allow registering Servlets to embedded jetty

### ISSUE THREAD

**Issue by jruuttun** [ktorio/ktor#1741]
Using `ktor-server-jetty` (1.3.0-beta-2), I'm afraid there's no way to register other handlers (Servlets) besides [JettyKtorHandler](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngine.kt#L21). I need it to be able to support legacy SOAP-based Web Services, more specifically using [WSServlet](https://www.javadoc.io/doc/com.sun.xml.ws/jaxws-rt/2.3.2/com.sun.xml.ws.jaxws/com/sun/xml/ws/transport/http/servlet/WSServlet.html). This is easy to do in a regular embedded Jetty setup (or in a Servlet container) by using a [WSServletContextListener](https://www.javadoc.io/doc/com.sun.xml.ws/jaxws-rt/2.3.2/com.sun.xml.ws.jaxws/com/sun/xml/ws/transport/http/servlet/WSServletContextListener.html), but in ktor-server-jetty, web.xml is out of the picture and JettyApplicationEngine doesn't allow adding other handlers (or rather, overwrites them), and also cannot be replaced by a modified version because of visibility issues.

Following up on [this SO question](https://stackoverflow.com/questions/53315271/how-to-register-a-servlet-in-ktor) and #270 (maybe others?), I would love this supported, of course unless there are specific reasons not to. I specifically *don't* want to deploy my Ktor application in a proper Servlet container where I'm free to add other Servlets and webapps, but a way to package my Ktor application to a clean microservice-style docker image.

Currently this is preventing me from a full-on switch to Ktor. With some encouragement I might be able to try a PR for this. Any thoughts or suggestions, please?

**Comment by cy6erGn0m** [comment]
What prevents you from making a docker image with a properly configured Servlet container? 

To register a servlet into ktor, one need to write a bridge from ktor's `ApplicationCall` to Servlet API. I don't think that it's that easy to cover all Servlet API properly. On ktor side we can't provide a partial support (this is no go) while the full support is too expensive and seems to be out of focus for now. 

If this is so important to not deploy your ktor app into a container, then you may try to implement such a limited bridge that covers your requirements. At least `HttpServletRequest`, `HttpServletResponse` and `ServletContext` should be implemented on top of `ApplicationCall`.

**Comment by jruuttun** [comment]
Thanks for your quick reply!

> What prevents you from making a docker image with a properly configured Servlet container?

Nothing, really. If this was just one-time problem, I'd probably go this way, or just _not move_ (from a vanilla embedded jetty app) to Ktor for this project. But I'd like to port our "product family" onto Ktor without losing the simplicity of our build (using [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) and embedded Jetty) and 'leanness' of the resulting docker image.

> To register a servlet into ktor, one need to write a bridge from ktor's `ApplicationCall` to Servlet API. I don't think that it's that easy to cover all Servlet API properly. On ktor side we can't provide a partial support (this is no go) while the full support is too expensive and seems to be out of focus for now.

I don't want to register a Servlet into Ktor, but to the underlying Jetty server, just to another path/context (like you'd do when running Ktor and another application in the same standalone container). I think this could be done without writing the bridge you envision; it's just that as I understand, `JettyApplicationEngine` [overwrites](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngine.kt#L21) any registered handlers on startup and registers `JettyKtorHandler` as the only one. This is natural, but I'm suggesting that maybe there's an easy way to let the developer-user add other handlers to the server instance, without adding Servlet API support (or anything, really) to _Ktor's_ actual functionality. Maybe I missed something here? 

Forgot to mention that I really like Ktor!

**Comment by cy6erGn0m** [comment]
You may try [Configuration.configureServer](https://api.ktor.io/1.3.2/io.ktor.server.jetty/-jetty-application-engine-base/-configuration/configure-server.html) to insert a handler.

**Comment by jruuttun** [comment]
That is exactly what I tried to do (sorry, I should have mentioned it), but when `JettyApplicationEngine` is started, it unfortunately overwrites any "handlers" I have previously added in `configureServer`, and I can't find a way to do it after the fact either. I agree that passing a suitable `configureServer` block seems to be the right way, except for the aforementioned issue. So from Ktor's perspective my problem is essentially the same as [here](https://github.com/ktorio/ktor/issues/270#issuecomment-351319284).
Thanks for looking into this!

**Comment by jruuttun** [comment]
My problem would be solved by moving the call to `configuration.configureServer(server)` from  `server` initialization to the beginning of `start()` in `JettyApplicationEngineBase`, so that `configureServer` could add handlers to the `server.handler` chain *after* it has been assigned in `JettyApplicationEngine.start()`. I tried building master with this change and did not seem to break anything. I'll create a PR for your consideration.

**Comment by jruuttun** [comment]
@cy6erGn0m what do you think of my solution? Could I improve it somehow?

**Comment by jruuttun** [comment]
@cy6erGn0m this is still very much an issue for me. Would it be more appropriate to label this a `bug` since the documented approach (that you suggested above) doesn't work?

A possible alternative to #1773 would be to keep the method invocations in place, and change the [handler assignment](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-jetty/jvm/src/io/ktor/server/jetty/JettyApplicationEngine.kt#L21) to accommodate previously assigned handlers. Would you prefer that approach instead?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-436">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
