### ISSUE TITLE
HTTP/2 example does not provide HTTP/2 but still HTTP/1.1

### ISSUE THREAD

**Issue by loxal** [ktorio/ktor#175]
I could not [mvn clean install it](https://github.com/Kotlin/ktor/tree/master/ktor-samples/ktor-samples-ssl-http2), as it reported erros but I followed your instructions [implementing it here](https://github.com/loxal/muctool) but still what I get is `HTTP/1.1` when calling https://muctool.loxal.net/echo which essentially obtains this info from  `call.request.local.version`.

**Comment by cy6erGn0m** [comment]
Which host do you use? Is it jetty or netty? which OS/hw platform?

**Comment by loxal** [comment]
I'm using Jety, and run a single fat JAR using `java -jar fat.jar` on Alpine Linux 64. Still same issue when running using `./gradlew run` on Windows.

**Comment by cy6erGn0m** [comment]
@loxal have you tried http://ktor.io/advanced/http2.html ? Jetty requires alpn-boot with corresponding version (depending on JDK version).

**Comment by loxal** [comment]
@cy6erGn0m Thanks, but I solved both issues, SSL & HTTP2 via an *nginx* reverse proxy.
