### ISSUE TITLE
How to get remote (client) port

### ISSUE THREAD

**Issue by dkrivoruchko** [ktorio/ktor#1754]
I can get client host by `call.request.local.remoteHost` but how to get client port?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-430">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by ztkmkoo** [comment]
Hi, @dkrivoruchko 
Can I get more information bout this issue? I test it on my local but everything works. See https://youtrack.jetbrains.com/issue/KTOR-430
