### ISSUE TITLE
LogLevel.ALL does not print parameters for POST-requests

### ISSUE THREAD

**Issue by hardysim** [ktorio/ktor#1758]
**Ktor Version and Engine Used (client or server and name)**
client 1.3.2

**Describe the bug**
When using `LogLevel.ALL` on a POST-request (via `submitForm()`) it does not print out the parameters in the log.

**To Reproduce**
Do a POST-request via `submitForm()` and add some `Parameters` via `Parameters.build {}` and log with  `LogLevel.ALL`.

The log contains the following lines for the request (but not the actual parameters):

```
HttpClient: METHOD: HttpMethod(value=POST)
[some headers]
HttpClient: BODY Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```

**Expected behavior**
The parameters should be printed to the log (like OkHttp does it).

**Comment by gabin8** [comment]
same as #1729

**Comment by hardysim** [comment]
True. Sorry, I was looking for issues but overlooked this one. Closing.
