### ISSUE TITLE
Cannot assign the CIO HTTP Client's socketTimeout

### ISSUE THREAD

**Issue by dmstocking** [ktorio/ktor#1762]
**Ktor Version and Engine Used (client or server and name)**
1.3.2, CIO HTTP client

**Describe the bug**
The `EndpointConfig` has the `socketTimeout` as a `val` so you cannot assign it. `EndpointConfig` is also final so you can't change it via inheritance.

**To Reproduce**
Try to compile
```
HttpClient(CIO) {
    engine {
        endpoint {
            socketTimeout = 10_000
        }
    }
}
```

**Expected behavior**
I should be able to set the socketTimeout.

**Comment by dmitrievanthony** [comment]
Hi @dmstocking,

Thanks for reporting. Have you tried to use the [Timeout](https://ktor.io/clients/http-client/features/timeout.html) feature?

**Comment by dmitrievanthony** [comment]
Well, I double-checked, the `socketTimeout` is a new field in endpoint configuration introduced to support the Timeout feature, so this does not affect old code. At the same time for the new code, the Timeout feature should be used.

Feel free to reopen the issue if you have any additional questions.

**Comment by dmstocking** [comment]
@dmitrievanthony I am a little confused how the field is needed to support the new Timeout feature if it can't be reassigned. I haven't gotten a chance to go look into this further, but if the Timeout features is really the way to go, why isn't this just removed?

**Comment by dmitrievanthony** [comment]
> @dmitrievanthony I am a little confused how the field is needed to support the new Timeout feature if it can't be reassigned. I haven't gotten a chance to go look into this further, but if the Timeout features is really the way to go, why isn't this just removed?

Well, you are right, this field could be omitted. We'll probably remove it in further releases to avoid confusion. Anyway, this right way to configure timeout now is to use the `Timeout` feature. So, give it a try and let me know if you have any issues with it.

**Comment by dmstocking** [comment]
OK. Will do. Thanks for your time. I will let you know if I find any problems.
