### ISSUE TITLE
Post request shows empty body after upgrading v1.3.2

### ISSUE THREAD

**Issue by minaEweida** [ktorio/ktor#1764]
Ktor Version 1.3.2 - Android

Post request shows empty body

We are sending a post request using Ktor. After upgrading to V1.3.2 to support kotlin 1.3.7, the request body started showing empty and nothing is actually sent in the body. I used the debugger to trace it, I see that it is able to serialize my request object correctly and content type is done correctly with `application/json`, however at some point I see in the logs that it is nullified.

We are using JsonFeature and Logging feature and our event object has it's own serilaizer which I was able to see it successfully serialized inside Ktor client

This is from `KotlinxSerializer.kt`
```
    override fun write(data: Any, contentType: ContentType): OutgoingContent {
        @Suppress("UNCHECKED_CAST")
        val content = json.stringify(buildSerializer(data) as KSerializer<Any>, data)
        return TextContent(content, contentType)
    }
```

It is returning a valid `TextContent(content, contentType)` with correct `contentType` and a valid json string as `content`

This is how I install the features
```
private val httpClient by lazy {
        HttpClient {
            install(Logging) {
                logger = apiLogger
                level = LogLevel.ALL
            }
            install(JsonFeature) {
                serializer = KotlinxSerializer()
            }
        }
    }
```

This is how we do the post request inside the same class

```
    fun fireEvents(event: List<EventRequest>) = blockingGet {
        httpClient.post<Unit>(
            scheme = SCHEME_HTTPS,
            host = baseUrl,
            path = EVENT_API_V1,
            body = event
        ) {
            header(CONTENT_TYPE, APPLICATION_JSON)
            header(API_TOKEN_HEADER, applicationApiToken)
        }
    }
```

In previous version I used to see the body correctly. But now I see the log just `BODY START` and `BODY END`

```I/AppLogger: REQUEST: https://something.com/v1/send
    METHOD: HttpMethod(value=POST)
    COMMON HEADERS
    -> some-key: some-value
    -> Accept: application/json
    -> Accept-Charset: UTF-8
    CONTENT HEADERS
    BODY Content-Type: application/json
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/AppLogger: RESPONSE: 200 OK
    METHOD: HttpMethod(value=POST)
I/AppLogger: FROM: https://something.com/v1/send
    COMMON HEADERS
    -> Connection: keep-alive
    -> Date: Tue, 31 Mar 2020 14:58:04 GMT
    -> Server: nginx/1.14.1
    -> Transfer-Encoding: chunked
    -> X-Android-Received-Millis: 1585666684496
    -> X-Android-Response-Source: NETWORK 200
    -> X-Android-Selected-Protocol: http/1.1
    -> X-Android-Sent-Millis: 1585666684232
I/AppLogger: BODY Content-Type: null
    BODY START
I/AppLogger: BODY END
```

I am not sure if this is normal or not. But can you tell me if I am doing something wrong in my code that I can fix? I checked changelog but I did not see anything that requires my attention in this code snippet I posted.

**Comment by MWingbermuhle** [comment]
I'm having the same issue in my project. Used to see logging before, but with latests version it's gone, I only see the response body, not the request.

**Comment by minaEweida** [comment]
I think it's not only about logging because I don't see the request body actually reaching the endpoint

**Comment by minaEweida** [comment]
@e5l It seems that it's only logging, I tested another post request and it works fine but the request body in the logger is empty

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-426">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Duplicates #1729
