### ISSUE TITLE
Get client certificate information from request

### ISSUE THREAD

**Issue by jorispz** [ktorio/ktor#1767]
**Subsystem**
Server

**Is your feature request related to a problem? Please describe.**
We want to use client-side certificates to authenticate HTTPS requests from connected devices. In our code, we need to get the client certificate information to determine the DN in the certificate.

In a regular servlet, client certificate information can be accessed using `request.getAttribute("javax.servlet.request.X509Certificate")`, which returns the certificate chain.

Our strategy to get this to work in ktor was to run our application as a WAR in a Tomcat instance configured to do client authentication. Unfortunately, request attributes do not seem to be available. (Note that a Spring Boot application deployed under the same Tomcat can access these attributes, so we know Tomcat is configured correctly for TLS.)

**Describe the solution you'd like**
We'd like some way to access servlet request attributes from ktor application code.

**Motivation to include to ktor**
Client certificates are an important part of IoT deployments, where ktor would shine because typically a server needs to manage a lot of concurrent connections. Ktor itself doesn't support client certificate authentication - our solution would be a workaround if only we could access request attributes.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-424">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by jorispz** [comment]
Closed see https://youtrack.jetbrains.com/issue/KTOR-424

**Comment by ydanneg** [comment]
is it possible to get a client certificate using other engines, like Netty?
