### ISSUE TITLE
Feature: Use websockets with serialization

### ISSUE THREAD

**Issue by cromefire** [ktorio/ktor#1768]
**Subsystem**
Server(/Client?):
- ktor-serialization
- ktor-websockets

**Is your feature request related to a problem? Please describe.**
Right now I don't see a good way to combine websockets with serialization.

**Describe the solution you'd like**
In http you can do it like this:
```kotlin
call.respond(SomeSerializableClass())
```

I'd propose something like this:
```kotlin
outgoing.send(
    Frame.Text.fromSerializable(SomeSerializableClass())
)
```
and
```kotlin
textFrame.toSerializable<SomeSerializableClass>()
```

Either in some kind of library or at least somewhere in the documentation.

**Motivation to include to ktor**
Currently there's not a really good way to communicate over websockets via JSON.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-423">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
