### ISSUE TITLE
ktor: client: ios: jsonfeature is ignored 

### ISSUE THREAD

**Issue by petersamokhin** [ktorio/ktor#1770]
**Ktor Version and Engine Used (client or server and name)**
Kotlin/Native `1.3.71`, Multiplatorm, iOS (13.4) app, arm64

**Dependencies**:
commonMain:
```kotlin
io.ktor:ktor-client-core:1.3.2
io.ktor:ktor-client-json:1.3.2
io.ktor:ktor-client-serialization:1.3.2
io.ktor:ktor-client-serialization-native:1.3.2 // (case 1)

org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.20.0
org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:0.20.0 // (case 1)
```

iosMain:
```kotlin
io.ktor:ktor-client-ios:1.3.2`
io.ktor:ktor-client-json-native:1.3.2

io.ktor:ktor-client-serialization-iosarm64:1.3.2 // (case 2)
org.jetbrains.kotlinx:kotlinx-serialization-runtime-iosarm64:0.20.0 // (case 2)
```

**(case 1)** and **(case 2)** are mutually exclusive. The issue can be reproduced in both cases.

**Describe the bug**
The serialization of the request body is not working.

**To Reproduce**
Common module code:
```kotlin
val client = HttpClient(/* `Ios.create()`, in actual code */) {
    install(JsonFeature) {
        serializer = KotlinxSerializer()
        // or the same issue with (or without specifying this):
        // serializer = deaultSerializer()
    }
}

client.post {
    url("...")
    body = SomeDataClass(test = true)
}

/* ... */
@kotlinx.serialization.Serializable
data class SomeDataClass(val test: Boolean)
```

Then you will get an exception:
```
kotlin.IllegalStateException: Fail to send body. Content has type: class com.example.package.DataClass
```

But (ofc) it is working with the manual serialization:
```kotlin
val json = defaultSerializer()
/* ... */
body = json.write(SomeDataClass(test = true))
```

**Comment by dmitrievanthony** [comment]
Hi @petersamokhin, 

Have you tried to specify `contentType(ContentType.Application.Json)`?

**Comment by petersamokhin** [comment]
@dmitrievanthony yes, it works now. So please update the documentation: https://ktor.io/clients/http-client/quick-start/requests.html — need to specify content type is mentioned, but not presented in an example.
