### ISSUE TITLE
Mocking with Kotlin Objects

### ISSUE THREAD

**Issue by geowatson** [ktorio/ktor#1776]
The idea is pretty simple - to add support for passing arbitrary object while calling `respond()` in handler scope. Example:

```kotlin
// basic environment
val client: HttpClient = HttpClient(MockEngine) {
   install(JsonFeature) {
      serializer = GsonSerializer()
   }
   engine {
      addHandler { request ->
         // responding here
      }
   }
}
```

From this:
```kotlin
respond(
   """ {'a': 'b'} """,
   200,
   headersOf("Content-Type", ContentType.Application.Json.toString())
)
```

To this:
```kotlin
data class MyResponse(val a: String)
...
respond(MyResponse(a = 'b'), 200)
respond(MyResponse('b'))  // also true
```

Thus maybe it will look like this (in implementation)
```kotlin
fun MockRequestHandleScope.respond(
    content: Any!,
    status: HttpStatusCode = HttpStatusCode.OK,
    headers: Headers = headersOf()
): HttpResponseData = respondWithJson(content, status, headers)
```

Where `respondWithJson` function uses either JsonFeature serializer or throws exception of encoding object into string.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-421">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Consider using `testApplication` API comming in 2.0.0
