### ISSUE TITLE
Support for Dependency Injection

### ISSUE THREAD

**Issue by halimpuckjava** [ktorio/ktor#1788]
add support for auto dependency injection like spring boot (@autowired)

**Comment by dmitrievanthony** [comment]
Hi @halimpuckjava.

Could you clarify what exactly you mean? Using Spring you can create `HttpClient` as a regular bean and inject it.

**Comment by halimpuckjava** [comment]
hi

i mean use KODEIN support with KTOR

**Comment by MikeMitterer** [comment]
Why not use Koin - it works for me without problems...

**Comment by dmitrievanthony** [comment]
Well, @halimpuckjava,

I mean that any dependency injection framework is a generic framework and using it you could inject any bean you'd like. What kind of specific support you'd like to have from Ktor side?

**Comment by halimpuckjava** [comment]
hi

reactive databases (r2dbc, reactive no-sql) features support in ktor with kodein as dependency injection support

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-416">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
I'm not sure that Ktor should have DI inside. There are lots of Kotlin libraries that make DI

**Comment by dodalovic** [comment]
@e5l Currently, there's no DI working with current Ktor.

**Comment by e5l** [comment]
@dodalovic,[Koin](https://insert-koin.io/docs/reference/koin-ktor/ktor) and [Kodein](https://github.com/Kodein-Framework/Kodein-DI) have Ktor support

**Comment by dodalovic** [comment]
Hi, i was trying to make it work with ktor 2.0, without success

**Comment by e5l** [comment]
Could you log an issue there? I think they add 2.0.0 support in a while.

**Comment by dodalovic** [comment]
https://github.com/InsertKoinIO/koin/issues/1295

There seems to be some hacking around it
