### ISSUE TITLE
Just a question about ios-iosarm64 and ios-iosx64 artifacts

### ISSUE THREAD

**Issue by wellingtoncosta** [ktorio/ktor#1791]
Hi,

I'm planning to use ktor-client in a Kotlin Multiplatform project, building for Android and iOS.

My question is about `ktor-client-ios-iosarm64` and `ktor-client-ios-iosx64` artifacts and how exactly I should use them.

I was seeing a demo project and I noticed these artifacts used as dependencies for [`iosarm64` ](https://github.com/SimonSchubert/Newsout/blob/master/shared/build.gradle#L87) and [`iosx64`](https://github.com/SimonSchubert/Newsout/blob/master/shared/build.gradle#L91) architectures in iOS target, but in ktor examples I just noticed use of `ktor-client-ios` dependency. So, I would like to know what I should use in my project.

**Comment by e5l** [comment]
Hi @wellingtoncosta, you can use `ktor-client-ios`; It should resolve platform dependencies for you.

**Comment by wellingtoncosta** [comment]
Thanks @e5l!!
