### ISSUE TITLE
java.io.EOFException is thrown from Flow.collect when trying to send a Ping

### ISSUE THREAD

**Issue by edenman** [ktorio/ktor#1803]
**Ktor Version and Engine Used (client or server and name)**
Ktor 1.3.2 client, ktor-client-okhttp (on top of ktor-client-core and ktor-client-websockets)

**Describe the bug**
`java.io.EOFException` is thrown from `Flow.collect` when trying to `send` a `Ping` message

**To Reproduce**
1. client.wss with a block like this:
```
{
  incoming.consumeAsFlow()
    .collect { frame ->
      if (frame.isHello) {
        GlobalScope.launch { 
          delay(500L)
          send(Frame.Ping(ByteArray(0)))
        }
      } else {
        // Normal frame processing here.
      }
    }
}
```

**Expected behavior**
Ping is sent, server responds with Pong.

It's entirely possible I'm doing something wrong but I can't see what.  This is reproducible 100% of the time.  Stacktrace:

<img width="989" alt="Screen Shot 2020-04-18 at 1 52 39 PM" src="https://user-images.githubusercontent.com/1063557/79625266-e4ee3b80-817b-11ea-82e2-8afb251b0c7d.png">

**Comment by edenman** [comment]
Well, I guess that sure would do it, huh: https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt#L65

**Comment by edenman** [comment]
I've fixed my issue by using an API level "ping" message so I don't care about this anymore, but I do think it'd be worthwhile to support manually sending ping messages.  Although it looks like OkHttp doesn't want you to do that.  And it only supports setting `pingInterval` when you create the `OkHttpClient` which doesn't work for my usecase because I don't know what the interval should be until I've already opened the websocket 😭

**Comment by dmitrievanthony** [comment]
Hi @edenman,

As far as I know, Ping messages are not supposed to send/receive to/from regular WebSockets. Regular WebSockets handle Pings behind the scene. If you'd like to work with them manually you need to use so-called "raw web sockets". Unfortunately, it seems like OkHttp does not support raw WebSockets either automated pings.

I'm trying to figure out how to eliminate this problems.

**Comment by edenman** [comment]
afaict OkHttp _does_ support automated pings but only via the `pingInterval` setting, which doesn't work for me.  Regardless, not a big deal for me but probably worth addressing this at some point

**Comment by dmitrievanthony** [comment]
Hi @edenman, well the only thing I can recommend you is to try CIO out. Is does support manual Ping/Pong processing using RawWebSockets.

And just to fix the status, speaking about OkHttp I see here several inconveniences. Firstly, when we send a frame we don't get an exception immediately. Send operation is performed asynchronously and we are able to get an exception only when try to send something again. Secondly, OkHttp provides it's own Ping/Pong mechanism which is not properly integrated with Ktor infrastructure so far.

I can nothing to suggest you but try CIO, so I'll close the issue. If you have any ideas or suggestions feel free to reopen it.

**Comment by Animeshz** [comment]
@dmitrievanthony So can it be possible for us to be able to implement the DefaultWebSocketSessionImpl so that we can inherit some of the functionality from it and have a custom implementation for handling the others frames as well (Ping/Pongs)? It seems we can't because kotlin has by default final class declaration, if it does make sense to inherit from Default implementation then kindly make the class open.

**Comment by dragossusi** [comment]
@dmitrievanthony I tried using CIO, but it doesn't work well with android when using HTTPS, it always shows an error about certificate, okhttp works well.

**Comment by techygrrrl** [comment]
> OkHttp provides it's own Ping/Pong mechanism which is not properly integrated with Ktor infrastructure so far.
> 
> I can nothing to suggest you but try CIO, so I'll close the issue. 

I was experiencing the `java.io.EOFException` error too and suspected it could be related to pinging while collecting a flow for an extended period of time. Switching to the CIO engine from the OkHttp engine fixed the issue, thanks!

**Comment by pitoszud** [comment]
I switched to HttpClient(CIO) (ktor client 2.3.8) in android and the java.io.EOFException has gone, but the Pong is not coming through.
`socket?.takeIf { it.isActive }?.incoming?.receiveAsFlow()?.onEach{ frame -> //checking here for Frame.Pong}?.catch{}`
I'm sending an empty byte array, but perhaps the engine expects a specific String as byte array?
`socket?.send(Frame.Ping(ByteArray(0)))`
