### ISSUE TITLE
crypto is undefined in IE11

### ISSUE THREAD

**Issue by chadmorrow** [ktorio/ktor#1814]
**Ktor Version and Engine Used (client or server and name)**

Version 1.3.2

My project uses ktor-client-core and ktor-client-core-js

**Describe the bug**
I have a React web application built with the kotlin-wrappers and ktor as the http client. When loading the application in IE 11, the application fails to load and the console displays an error saying: `crypto is undefined`

This problem happens in IE 11 on both windows 7 and windows 10.

#1283 references this same problem.

**To Reproduce**
1. Start web application. Application will not render because of crypto is undefined.

**Expected behavior**
Application should load and run without javascript exceptions from ktor.

**Screenshots**
![image](https://user-images.githubusercontent.com/15710088/79894963-0d17ad80-83bb-11ea-8653-74e975e38e40.png)

![image](https://user-images.githubusercontent.com/15710088/79895585-f7ef4e80-83bb-11ea-9c03-dd9c5fa45f3c.png)

**Comment by e5l** [comment]
Hi @chadmorrow, thanks for the report. The issue will be fixed in the next release.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-409">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in `1.6.1`
