### ISSUE TITLE
Add a Validation phase to the HttpResponsePipeline

### ISSUE THREAD

**Issue by sgarfinkel** [ktorio/ktor#1817]
**Subsystem**
This is applicable to the client.

**Is your feature request related to a problem? Please describe.**
I'm trying to implement a retry-on-failure feature, which handles exceptions thrown by `HttpCallValidator`. The problem is that the validator handles an ad-hoc pipeline phase that it adds. To intercept this phase, or add a pipeline phase before it, you need to extract that particular phase from the set of registered PipelinePhases.

Since this feature is already on by default, I think it would be beneficial to instead add an explicit phase to the `HttpResponsePipeline` that is first in the set of phases called `Validation` and let the `HttpCallValidator` instead intercept this new phase.

Then exception handlers can be registered as features by either adding their own phases before the `Validation` phase, or by intercepting the `Validation` phase directly.

**Describe the solution you'd like**
See above. Simply add a new phase to the `HttpResponsePipeline` as defined above. Update the `HttpCallValidator` to intercept this new phase instead.

**Motivation to include to ktor**
See description--this would be helpful for adding exception handlers to the pipeline.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-408">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
