### ISSUE TITLE
[Question] Analysis of techempower.com benchmarks results

### ISSUE THREAD

**Issue by dodalovic** [ktorio/ktor#1821]
Hi, I'm very new to ktor, and would like someone from the team help me understand if the results from 

https://www.techempower.com/benchmarks

are meeting expectations with regards to `ktor` project?

**Comment by ssijak** [comment]
I'm also interested in this. Is there a reason why ktor is 4-5x slower than http4k in this benchmarks? I am starting a new project and am choosing between ktor and http4k, I would prefer  ktor because of much larger community and jetbrains backing, but 5x slower speed transfer to server costs so I am not sure.

**Comment by raharrison** [comment]
I would expect Ktor to be faster considering it's a relatively thin library (be interesting what the devs have to say on that), but either way those kinds of benchmarks don't necessarily tell the whole story. There might potentially be some optimization possible on the apps they use to benchmark. Also note that plenty of the other libs are using apps which are very micro-optimized and don't necessarily reflect real-world usage.

> but 5x slower speed transfer to server costs

That's really not going to be the case. - it's much much more complicated than that. If you are operating at a scale where this even becomes an issue then you will have bigger problems to worry about. 5x slower in those benchmarks doesn't mean 5x slower in your specific use case and definitely doesn't mean 5x server costs. You might not even notice any difference at all depending on how much traffic you are actually serving and more importantly what your app actually does (DB bottlenecks etc).

**Comment by dodalovic** [comment]
Let's see if we get some feedback to be able to discuss further

**Comment by raharrison** [comment]
FYI new round of TechEmpower benchmarks just go released.

Ktor ranking/perf seems to have decreased a fair bit again..

**Comment by Danieliessen** [comment]
Well, it is a 32bit(java 1.8 - they still could run it in 64bit but thats strange, this is just what i found on github) test of ktor 1.2.0(released in 19 mar 2019, while the bench was in 2020 05 28), what did you expect.

**Comment by e5l** [comment]
The latest public TFB run is using ktor `1.0.0-beta-*`. We've just updated it to the `1.4.0` there and will follow the results.
Thanks for rising the question.

**Comment by rishavs** [comment]
Why did we close this question without attempting to look into it? This makes me wary of using Ktor for my project.
