### ISSUE TITLE
httpMethod does not affected by X-Http-Method-Override (in opposite to docs)

### ISSUE THREAD

**Issue by LoneEngineer** [ktorio/ktor#1825]
**Ktor Version and Engine Used (client or server and name)**
ktor 1.3.2 (Netty)

**Describe the bug**
https://api.ktor.io/1.3.2/io.ktor.request/http-method.html states:
> Returns request HTTP method possibly overridden via header X-Http-Method-Override

However it doesn't work. httpMethod() returns POST while headers[" X-Http-Method-Override"] returns GET.

**To Reproduce**
Execute POST request with  X-Http-Method-Override: GET header.

**Expected behavior**
Returns 'GET' or documentation is not correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/8122440/80306855-7a1daf80-87ce-11ea-810f-f299a9de885a.png)
![image](https://user-images.githubusercontent.com/8122440/80306861-80ac2700-87ce-11ea-92e2-89d82cf98f11.png)

Is that correct that routing API also ignores X-Http-Method-Override or it's a bug ?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-404">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
