### ISSUE TITLE
URLBuilder to append paths to currently encoded path

### ISSUE THREAD

**Issue by Krizzu** [ktorio/ktor#1826]
**Subsystem**

URLBuilder

**Is your feature request related to a problem? Please describe.**

I want to create a final URL from several paths. Let's say my starting url is `https://example.com/items/` and incoming paths are: `/category/`, `/directory/`, `/product`.

Doing:
```kotlin

val url = URLBuilder("https://example.com/items/").run {
        path("/category/", "/directory/", "/product")
        buildString()
      }
```

I will end up with: `https://example.com//category///directory///product`.
Notice that `/items/` from starting URL is gone and the unnecessary slash duplications.

To preserve the original path, one can use:
```kotlin
 path(encodedPath, "/category/", "/directory/", "/product")
```
but that does not fix the path separator problem (in case where you don't control them).

**Describe the solution you'd like**

Adding a simple function, `appendToPath`, which will handle path extending and separators. 

Exemplary implementation:

```kotlin
fun URLBuilder.appendToPath(vararg components: String) {
  // removes all trailing and leading separators
  val paths = components
    .map { it.replace(Regex("""(^/|/+$)"""), "") }
    .joinToString("/", transform = { it.encodeURLQueryComponent() })

  // make sure that there's a slash separator at the end of current path
  if (!encodedPath.endsWith('/')) {
    encodedPath = "${encodedPath}/"
  }
  this.encodedPath += paths
}
```

**Motivation to include to ktor**

I think this might be a common case (building up URL), so in my opinion, this small helper would be a beneficial addition. I'm more than happy to open up PR.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-403">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Krizzu** [comment]
@oleg-larshin Ktor moves away from GH issues?
