### ISSUE TITLE
Integration with detekt-hint

### ISSUE THREAD

**Issue by Mkohm** [ktorio/ktor#1830]
Hi! 

I am working on a tool for detection of violations on design principles in my master thesis (read more about it https://github.com/Mkohm/detekt-hint), and is looking for an open source project where I can integrate my tool for some feedback and testing. Would you welcome such an integration? It would mean a lot, and I hope it can continue to improve the maintainability of this project. 

It only requires creating a configuration file and a new GitHub action. Please let me know if it is of any interest, and I will create a PR with the required changes.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-401">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
