### ISSUE TITLE
Support Scheduling Tasks? like spring2 and dynamic manager it

### ISSUE THREAD

**Issue by yizems** [ktorio/ktor#1831]

**Comment by dmitrievanthony** [comment]
Hi @yizems, could you please give a bit more details about your idea?

**Comment by yizems** [comment]
Like ThreadPoolTaskScheduler

**Comment by dmitrievanthony** [comment]
Well, I still don't see the connection between task scheduler and HTTP framework like Ktor. Could you give me a clue?
