### ISSUE TITLE
parameterOf() should have a variant that takes in a Map<String, List<String>>

### ISSUE THREAD

**Issue by rock3r** [ktorio/ktor#1833]
**Subsystem**
Server

**Is your feature request related to a problem? Please describe.**
There is currently no way to build a Parameters instance from a Map, even though the internal representation of the values is a map. `Parameters` can only be constructed using:
 * `parametersOf()`
 * `parametersOf(name: String, value: String)`
 * `parametersOf(name: String, values: List<String>)`
 * `parametersOf(vararg pairs: Pair<String, List<String>>)`

`ParametersImpl` is internal and cannot be constructed directly.

**Describe the solution you'd like**
I'd like there to be a `parametersOf(parameters: Map<String, List<String>>)`:

```kotlin
fun parametersOf(vararg parameters: Map<String, List<String>>): Parameters =
    ParametersImpl(parameters)
```

**Motivation to include to ktor**
Seems like it should be there. There are many cases where you're already working with a parameters map, and having to transform that into a list of pairs just to have it retransformed back under the hood seems wasteful.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-399">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
