### ISSUE TITLE
ktor-client-okhttp does not terminate after closing WebSocket, gets stuck in waitForReferencePendingList()

### ISSUE THREAD

**Issue by SebastianAigner** [ktorio/ktor#1839]
**Ktor Version and Engine Used (client or server and name)**
```
implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
implementation("io.ktor:ktor-client-websockets:$ktor_version")
implementation("io.ktor:ktor-client-okhttp:$ktor_version")
```

**Describe the bug**
A program using ktor-client-okhttp does not terminate properly even after closing a WebSocket. Instead, it just hangs at the end of the main method.

**To Reproduce**
Check out the repro repo at https://github.com/SebastianAigner/reproduce-ktor-client-coroutine-issue
Run [`Simplified.kt`](https://github.com/SebastianAigner/reproduce-ktor-client-coroutine-issue/blob/master/src/main/kotlin/Simplified.kt) (or `App.kt`).
Console output is as follows:
```
Entering blocking websocket part...
RECV: PING
Done!
```

At this point, the program gets stuck. Debugger shows that it is stuck in `java.lang.ref.Reference#waitForReferencePendingList`.

**Expected behavior**
The program should terminate after printing "Done!". Note that if you switch out the WebSocket implementations from
```
implementation("io.ktor:ktor-client-okhttp:$ktor_version")
```
to
```
implementation("io.ktor:ktor-client-cio:$ktor_version")
```
The program terminates as expected – which is why this bug seems to be limited to the okhttp implementation.

**Comment by e5l** [comment]
Hi @SebastianAigner, thanks for the report. I'm investigating the problem.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-396">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
