### ISSUE TITLE
metrics prometheus better documentation

### ISSUE THREAD

**Issue by sysmat** [ktorio/ktor#1842]
**Subsystem**
Server - metrics

**Is your feature request related to a problem? Please describe.**
https://ktor.io/servers/features/metrics-micrometer.html

* I'm new to ktor and trying to have prometheus metrics, I do it in java app servers with simpleclient_servlet very easy
* I read install MicrometerMetrics, PrometheusMeterRegistry -> in doc missing dependency 
* There is no doc where the metrics are exposed(URI)
* There is no doc if metrics need auth and which type of auth
* There is no doc should I need a route which expose metrics 

**Describe the solution you'd like**
* More clear docs or working sample

**Motivation to include to ktor**
Monitoring of app is very important and prometheus is very popular

**Comment by colymore** [comment]
Finally did you integrate prometheus? I've the same doubts.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-394">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by devsnice** [comment]
hey, when are planning to it? this docs is really confusing

**Comment by hhariri** [comment]
@devsnice Thanks. We'll get it updated.

**Comment by hhariri** [comment]
@devsnice Just as an update - we have this resolved but we need to publish the new docs. Unfortunately it won't be published in 1.4.3 as the whole doc structure has been revamped. Please keep an eye out on our [blog](https://blog.jetbrains.com/ktor) and [Twitter](https://twitter.com/jetbrainsktor) for updates around new docs. Thanks.
