### ISSUE TITLE
Handle pipeline cancel / error

### ISSUE THREAD

**Issue by AleksandrGilmanov** [ktorio/ktor#1843]
**Subsystem**
HttpClientFeature pipeline

**Is your feature request related to a problem? Please describe.**
It would be useful to be able do some work like logging or write metrics when something went wrong and pipeline was closed due unhandled exception in pipeline interceptor.
For example: we want to add "HttpClientFeature" which gives ability to log time to get response from the server and counts errors, group it by some parameters (i.e. host, path, response code if exists and so on).

I've found that "DefaultResponseValidation" throws "ResponseException" on status code >= 400 and it cancels pipeline. So if we want to log duration of this request we need to disable it. Anyway, it looks like any unhandled exception interrupts pipeline and we can't find out that request/response already finished.

**Describe the solution you'd like**
It wound be great to add Pipeline phases which will be called after the end of pipeline and on it's cancel.

**Motivation to include to ktor**
I hope that it would be helpful to create new HttpClientFeature's which has state and should be finished after the end of the pipeline regardless of whether it finished with success or error.

**Comment by e5l** [comment]
Hi @AleksandrGilmanov, thanks for the report.
The request lifetime is not limited to the pipeline execution. You can observe the request lifetime using `executionContext`(https://api.ktor.io/1.3.2/io.ktor.client.request/-http-request-builder/execution-context.html) in `request` or `requestBuilder`.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-393">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
