### ISSUE TITLE
Question: how to change Connection header?

### ISSUE THREAD

**Issue by CommanderTvis** [ktorio/ktor#1844]
Ktor sets `Connection` to `keep-alive` by default. How can I change it to `close` without duplication? 

```kotlin
call.response.header(name = HttpHeaders.Connection, value = "close")
```

produces double `Connection` header...

**Comment by proton72** [comment]
The same with `Host` header in case of CIO engine

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-392">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
Because of https://github.com/ktorio/ktor/pull/1943 you can now just append a `Connection` header with any value you like:
```kt
routing {
    get("/") {
        call.response.header("Connection", "close")
        call.respondText { "hello" }
    }
}
```
