### ISSUE TITLE
ConditionalHeaders feature doesn't set required headers on 304

### ISSUE THREAD

**Issue by sachindshinde** [ktorio/ktor#1849]
**Ktor Version and Engine Used (client or server and name)**

group ID: `io.ktor`
artifact ID: `ktor-server-core`
version: `1.2.6` (but it would appear it's also on master)

**Describe the bug**

[RFC 7232](https://tools.ietf.org/html/rfc7232#section-4.1) states the following regarding `304 Not Modified`:
> The server generating a 304 response MUST generate any of the following header fields that would have been sent in a 200 (OK) response to the same request: Cache-Control, Content-Location, Date, ETag, Expires, and Vary.

Looking at the `ConditionalHeader`'s [interceptor code](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-core/jvm/src/io/ktor/features/ConditionalHeaders.kt#L37) currently on master
```kotlin
    internal suspend fun interceptor(context: PipelineContext<Any, ApplicationCall>, message: Any) {
        val call = context.call

        val versions = if (message is OutgoingContent) versionsFor(message) else emptyList()

        val checkResult = checkVersions(call, versions)
        if (checkResult != VersionCheckResult.OK) {
            val response = HttpStatusCodeContent(checkResult.statusCode)
            context.proceedWith(response)
            return
        }

        if (versions.isNotEmpty()) {
            val headers = Headers.build {
                versions.forEach { it.appendHeadersTo(this) }
            }

            val responseHeaders = call.response.headers
            headers.forEach { name, values ->
                values.forEach { responseHeaders.append(name, it) }
            }
        }
    }
```
you'll notice the following when returning 304:
1. The `ETag` header is not appended.
2. Any extension properties set in the old `OutgoingContent` object are not forwarded to the new `HttpStatusCodeContent` object. This means that ktor features like `CachingHeaders`, which stores a `CachingOptions` object in the `OutgoingContent` as an extension property, will not detect their property in `HttpStatusCodeContent`. This particularly means the `Cache-Control` header will not be set, depending on the order the interceptors for `CachingHeaders` and `ConditionalHeaders` are run.

**Comment by dmitrievanthony** [comment]
Hi @sachindshinde,

Thanks for reporting! I prepared the fix, it's currently on review.

**Comment by sachindshinde** [comment]
Hi @dmitrievanthony ,

Thanks for the quick PR! It fixes the `ETag` issue, but I don't believe it fixes the caching issue related to `CachingHeaders`. To do that, we'd have to carry over `CachingHeaders`'s extension property on `OutgoingContent` to the new `HttpStatusCodeContent`.
