### ISSUE TITLE
Automatically configure KotlinxSerializer to consume @Serializable classes

### ISSUE THREAD

**Issue by kuuuurt** [ktorio/ktor#1851]
**Subsystem**
Client (Multiplatform, Android, iOS)
- io.ktor:ktor-client-core:1.3.2
- io.ktor:ktor-client-serialization:1.3.2
- io.ktor:ktor-client-json:1.3.2

**Is your feature request related to a problem? Please describe.**
Is there a way where Ktor could consume all classes annotated with `@Serializable`? I'm trying to achieve a single `HttpClient` for my whole application. Currently, I'm creating an instance per request and configure the serializer on each request.

Here's my helper function for creating an `HttpClient`
```kotlin
fun createHttpClient(
    config: KotlinxSerializer.() -> Unit = {}
) = HttpClient(httpClientEngine) {
    ...
    install(JsonFeature) {
        serializer = KotlinxSerializer(Json(jsonConfig)).apply {
            config(this)
        }
    }
    ...
}
```

and I use it like this:

```kotlin
suspend fun firstRequest() {
    createHttpClient {
        typeOf<FirstRequestResponse>()
    }.get<FirstRequestResponse>("url-to-first-request")
}

suspend fun secondRequest() {
    createHttpClient {
        typeOf<SecondRequestResponse>()
    }.get<SecondRequestResponse>("url-to-second-request")
}
```

I was hoping we could create just use one instance to use lesser resources but I'm not sure.

I also tried creating a single instance

```kotlin
val httpClient = HttpClient(...) {
    ...
    install(JsonFeature) {
        serializer = KotlinxSerializer(Json(jsonConfig)).apply {
            typeOf<FirstRequestResponse>()
            typeOf<SecondRequestResponse>()
        }
    }
    ...
}
suspend fun firstRequest() {
    httpClient.get<FirstRequestResponse>("url-to-first-request")
}

suspend fun secondRequest() {
    httpClient.get<SecondRequestResponse>("url-to-second-request")
}
```

But if the requests are in another module, I won't be able to register them here so I just resorted to the helper function.

**Describe the solution you'd like**
I think it'd be nice if we just put `serializer = KotlinxSerializer(Json(jsonConfig))` and it automatically consumes/registers all classes with `@Serializable` annotations. Much like how Retrofit uses `addConverterFactory` and all Moshi/Gson/etc. will be serialized.

But **does it matter if I use a single instance vs an instance per request?** If it doesn't I can stick to my current implementation.

**Motivation to include to ktor**
I think this could reduce a lot boilerplate in registering the response classes.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-389">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Dominaezzz** [comment]
I think this has been fixed now.

**Comment by e5l** [comment]
Thanks for the notice, closed
