### ISSUE TITLE
WebSockets do not throw expected ClosedReceiveChannelException when using suspended iteration

### ISSUE THREAD

**Issue by SebastianAigner** [ktorio/ktor#1857]
**Ktor Version and Engine Used (client or server and name)**
Ktor server 1.3.2 with Netty

**Describe the bug**

**To Reproduce**
Try running the example from https://ktor.io/servers/features/websockets.html#faq :

```kotlin
webSocket("/echo") {
    println("onConnect")
    try {
        for (frame in incoming){
            val text = (frame as Frame.Text).readText()
            println("onMessage")
            // received += text
            outgoing.send(Frame.Text(text))
        }
    } catch (e: ClosedReceiveChannelException) {
        println("onClose ${closeReason.await()}")
    } catch (e: Throwable) {
        println("onError ${closeReason.await()}")
        e.printStackTrace()
    }
}
```

The example text explicitly states:
> In this sample, the infinite loop is only exited with an exception is risen: either a ClosedReceiveChannelException or another exception.

However, I can terminate the connection from the client side without ever hitting `onClose` or `onError`.

It seems to work properly when I use a `while(true)` loop with `incoming.receive()`, giving me an `onClose CloseReason(reason=CLOSED_ABNORMALLY, message=Connection was closed without close frame)` and a `ClosedReceiveChannelException`.

**Expected behavior**
The infinite loop is only exited with an exception is risen: either a `ClosedReceiveChannelException` or another exception.

**Comment by e5l** [comment]
Hi @SebastianAigner, thanks for the report.
The behavior with `incoming` `in` operator is expected: the channel was closed normally and operator shouldn't throw. It looks like the documentation mistake.

By the way, have `null` in `closeReason` is really confusing. So I file the separate issue for that: https://youtrack.jetbrains.com/issue/KTOR-17.

**Comment by nassian** [comment]
> Hi @SebastianAigner, thanks for the report.
> The behavior with `incoming` `in` operator is expected: the channel was closed normally and operator shouldn't throw. It looks like the documentation mistake.
> 
> By the way, have `null` in `closeReason` is really confusing. So I file the separate issue for that: https://youtrack.jetbrains.com/issue/KTOR-17.

Then, how does the server know if the channel is closed normally and the client is not connected to the server anymore? So we can remove this terminated connection from the list of connections.

**Comment by ziglee** [comment]
Just passing by to tell that the doc hasn't changed and I got the same confusion as the creator of this issue.
