### ISSUE TITLE
Strings are not decoded when received as application/json

### ISSUE THREAD

**Issue by Legion2** [ktorio/ktor#1861]
**Ktor Version and Engine Used (client or server and name)**
io.ktor:ktor-client:1.3.2
io.ktor:ktor-client-cio:1.3.2
io.ktor:ktor-client-json:1.3.2
io.ktor:ktor-client-gson:1.3.2

**Describe the bug**
When requesting a simple string (e.g. `foo`) from a ASP.NET Core Web-API the server returns the simple string encoded as Json string (`"foo"`) with mime type `application/json`.
The ktor client does not use the configured serializer (e.g. `GsonSerializer`) to deserialize the response body, but rather directly return the string `"foo"` with the quotes to the requesting code. This is a bigger problem when the simple string contains character which must be encoded in json strings like `"` or LF. Then the string in the HTTP response look like `"\"\n"` and ktor returns the string `"\"\n"` (this is a string with length 6) but it should be a string with two characters, the first character a `\` and the second a LF.

**To Reproduce**
1. Write the following
```kotlin
client = HttpClient {
  install(JsonFeature) {
    serializer = GsonSerializer()
  }
}
val simpleString = client.get<String>(someUrl)
println(simpleString)
```
2. The server at `someUrl` must respond with a HTTP response like following:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8

"foo\"\n"
```
3. See `"foo\"\n"` printed as output

**Expected behavior**
only `foo"` should be printed (two line breaks)

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-385">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
