### ISSUE TITLE
Request may not include Host parameter

### ISSUE THREAD

**Issue by zuevmaxim** [ktorio/ktor#1863]
**Ktor Version and Engine Used (client or server and name)**
io.ktor:ktor-server-cio:1.3.2

**Describe the bug**
Request must include Host parameter(see https://tools.ietf.org/html/rfc2616#section-14.23)

**To Reproduce**
Run code:
```
import io.ktor.http.cio.parseRequest
import io.ktor.utils.io.ByteReadChannel
import kotlinx.coroutines.runBlocking

fun main() {
    test(
        """
        GET / HTTP/1.1
        

        """.trimIndent()
    )
}

fun test(http: String) {
    val request = runBlocking { parseRequest(ByteReadChannel(http)) }!!
    println("method=${request.method};uri={${request.uri}};headers=[${request.headers}]")
}

```

**Expected behavior**
An error expected - exception or null result.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-383">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
