### ISSUE TITLE
Content Negotiation: Gson: Should be able to return 400 for badly formatted request.

### ISSUE THREAD

**Issue by lgwillmore** [ktorio/ktor#1874]
**Ktor Version and Engine Used 1.3.2**
Additionally using `ktor-gson` plugin.

**Describe the bug**
gson converter returns a 500 status request if the gson is badly formatted. I think it should be a 400.

**To Reproduce**
1. Add content negotiation plugin. Use the gson converter
2. Call your endpoint with badly formatted json
3. Get a 500 status

**Expected behavior**
Should be a 400 status.

gson converter should catch the `JsonSyntaxException` and throw a `BadRequestException`

**Comment by lgwillmore** [comment]
I have used status pages to handle this - so maybe the intent is for status pages to be the way that gson parsing errors are handled?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-373">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
