### ISSUE TITLE
Ktor should resolve trailing slash as a different URL 

### ISSUE THREAD

**Issue by gzoritchak** [ktorio/ktor#1876]
From the beginning to Ktor 1.3.2.

Ktor makes no difference between URLs ending with a trailing slash or not. 

The following code will produce an error because two handlers are trying to respond to the incoming request.

  ```
  @Test fun `routing trailing slash`() = withTestApplication {
        application.routing {
            get("foo") {
                println("server processing /foo")
                call.respondText("/foo")
            }
            get("foo/") {
                println("server procession /foo/")
                call.respondText("/foo/")
            }
        }

        on ("making /foo request") {
            val result = handleRequest {
                uri = "/foo"
                method = HttpMethod.Get
            }
            it("should be handled") {
                assertTrue(result.requestHandled)
            }
            it("should have /foo as a response") {
                assertEquals("/foo", result.response.content)
            }
        }
    }


//produces
server processing /foo
server procession /foo/
Response has already been sent
io.ktor.server.engine.BaseApplicationResponse$ResponseAlreadySentException: Response has already been sent
```

This error has an impact on SEO because Google respects the difference between `/foo` and `/foo/` that may produce different results.

It is also a problem when you want to use a first-level path parameter like `"/{user}/"` coupled with static content serving. Browsers can send requests to get a favicon file. These requests don't have any trailing slash, but still, Ktor will route them to the `"/{user}/"` handler instead of serving the file.

**Expected behavior**
A router "/{user}/" should not handle a "/favicon.png" request. 

Because it is a modification of behavior, users should activate this correction by configuration.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-372">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
