### ISSUE TITLE
No Pagination options available in the default api

### ISSUE THREAD

**Issue by VasuBhaskar** [ktorio/ktor#1877]
**Subsystem**
Client/Server, particular relevant ktor module(s) if applicable.

**Is your feature request related to a problem? Please describe.**
It would be nice to have options to generate rest style pagination headers which can be sent as response headers.

**Describe the solution you'd like**
Example :

Input : page = 1 and per_page=2
Assume total count fetched from DB is 7
Headers expected : </test_domain/v1/page=2&per_page=5>;next,</test_domain/v1?page=2&per_page=5>;last

Given TotalCount fetched , page number and the page size requested, a list of pagination headers will be returned.

In short Add extension functions to this file https://github.com/ktorio/ktor/blob/dffd440acee1649f4aea37c9065f1e0b1dfbe6b8/ktor-http/common/src/io/ktor/http/URLUtils.kt

I have the solution and tests written. I will be more than happy to raise a PR .

**Motivation to include to ktor**
An explanation, why do you believe that the feature you'd like to see is important for other users as well and why it should be delivered with ktor.

Springboot has options for generating pagination headers as below . It would be nice for Ktor to have inbuilt options too.

https://www.baeldung.com/rest-api-pagination-in-spring

**Comment by mahramane** [comment]
Yes.
I also think this feature is necessary for any framework.
