### ISSUE TITLE
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

### ISSUE THREAD

**Issue by apkelly** [ktorio/ktor#1878]
**Subsystem**
ktor server websockets

**Is your feature request related to a problem? Please describe.**
Currently the only way to specify the supported protocols for my server is to iterate through a list and create a websocket for each protocol version.

```
getSupportedProtocols().forEach { protocol ->
  webSocket("/", protocol) {
    val handler = WebSocketHandlerFactory.getHandler(protocol)
    handler?.let {
      // handler will process incoming Frames
    }
  }
}
```
But this means I need to register Routes for _all_ my protocol versions. However, for the scenario I'm working in, I know I'll only need to support a single client at any given time, I just don't know what protocol version that client will be using.

**Describe the solution you'd like**
I'd like to be able to only register a Route once i know a client is connected with a protocol version I support.

```
webSocket("/") {
  call.request.headers[HttpHeaders.SecWebSocketProtocol]?.let { protocol ->  
    val handler = WebSocketHandlerFactory.getHandler(protocol)  
    handler?.let {  
      // handler will process incoming Frames  
    }
  }
}
```

However, in this scenario I get the following error on the client `"Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received"`, which seems to imply that because we didn't register an explicit protocol, the connection hasn't been completed.

**Motivation to include to ktor**
Registering 100s of routes seems overkill when I only need 1 (or a few for other people) to be registered at any given time.

**Comment by apkelly** [comment]
I think what I need is a way to specify my own WebsocketProtocolSelector, which is a RouteSelector. I could then check if the header is one that I support and if it is then I accept the Route with a RouteSelectorEvaluation.Constant

**Comment by apkelly** [comment]
I ended up coding this....
```
                route(WS_PATH, HttpMethod.Get) {
                    // Look for the headers to upgrade our http connection to a websocket one.
                    header(HttpHeaders.Connection, "Upgrade") {
                        header(HttpHeaders.Upgrade, "websocket") {

                            // Create a child route that will only process connections for protocol versions we support.
                            val selector = MyProtocolSelector()
                            createChild(selector).apply {

                                handle {
                                    call.respond(WebSocketUpgrade(call, selector.protocol) {
                                        DelegatedWebSocketServerSession(call, this).apply {

                                            // app logic is handled by a lambda here.

                                        }
                                    })
                                }
                            }
                        }
                    }
                }



    class MyProtocolSelector : RouteSelector(RouteSelectorEvaluation.qualityConstant) {
        lateinit var handler: MyWebSocketProtocolHandler
        lateinit var protocol: String

        override fun evaluate(
            context: RoutingResolveContext,
            segmentIndex: Int
        ): RouteSelectorEvaluation {
            context.call.request.headers[HttpHeaders.SecWebSocketProtocol]?.let { protocol ->
                val handler = MyWebSocketHandlerFactory.getHandler(protocol)
                return if (handler != null) {
                    this.handler = handler
                    this.protocol = protocol
                    RouteSelectorEvaluation.Constant
                } else {
                    RouteSelectorEvaluation.Failed
                }
            }
            return RouteSelectorEvaluation.Failed
        }
    }

```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-371">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
