### ISSUE TITLE
Invalid response without error

### ISSUE THREAD

**Issue by zuevmaxim** [ktorio/ktor#1883]
**Ktor Version and Engine Used (client or server and name)**
io.ktor:ktor-server-cio:1.3.2

**Describe the bug**
Strings like "a", "H" are invalid responses(see https://tools.ietf.org/html/rfc2616#section-6)

**To Reproduce**
Run code:
```
import io.ktor.http.cio.parseResponse
import io.ktor.utils.io.ByteReadChannel
import kotlinx.coroutines.runBlocking

fun main() {
    listOf("A", "H", "a")
        .forEach { test(it) }
}

fun test(http: String) {
    val response = runBlocking { parseResponse(ByteReadChannel(http)) }!!
    println("status=${response.status};statusText={${response.statusText}};headers=[${response.headers}];version=${response.version}")
}
```

**Expected behavior**
An error expected - exception or null result.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-369">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by vladf2n** [comment]
Hi, I want to work on this, but first I have a question: Is it possible to the status-line have an empty status-code or empty status-text? (gonna mention @cy6erGn0m here because he is helping me with other issues hehehe)
