### ISSUE TITLE
ktor not closing user connections

### ISSUE THREAD

**Issue by itboy87** [ktorio/ktor#1885]
**Ktor Version and Engine Used (client or server and name)**
1.3.2, Netty server, routes

`ktor_version=1.3.2,
kotlin_version=1.3.70`

```
implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version")
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("ch.qos.logback:logback-classic:$logback_version")
    testImplementation("io.ktor:ktor-server-tests:$ktor_version")
```

**Describe the bug**
I migrated one of my project form php to ktor and deployed it in production for about 5k users. After one day server stopped working and linux file opened limits exceed which was 20k and when i checked with command `ss -ant | grep :8383 | wc -l` connections were 20k+ but i don't have users more than 5k which were not all active. Then i switched my floating ip to old php server and no more request to this server next day when i checked again with command `ss -ant | grep :8383 | wc -l` connections were still 20k+ even no more new request were coming and all connections were in ESTAB state.

So after that i created new project which was empty with ktor, kotlin dsl i mentioned its dependencies above and run that on that server Then i run this command `watch -n 1 'ss -ant | grep {MY_IP}'` on server to filter connections for my ip first it was no connection from my ip on port 8383 then i send single request from postman on `SERVER_IP:8388` which was simple get request and response was from `call.respond("Testing")` and on server terminal it show me connection on 8383 with my ip. In postman request was complete and i got result. Then i closed postman and keep checking when it will close my connection from server. I checked that  after an hour still connection was not closed and when i requested again it was still using that same connection. So it was reusing connection and not closing even after some hours. I'm not sure but may be error with keep alive or http2. I'm not sending any header i request.

I didn't tried any other ktor or kotlin version and I'm not able to reproduce it local.
I'm running jar file generated with shadowjar on linux server with systemd service.

**To Reproduce**
1. create new project with ktor version 1.3.2 and kotlin 1.3.70 with GradleKotlinDsl
```
fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)
@Suppress("unused") // Referenced in application.conf
@kotlin.jvm.JvmOverloads
fun Application.module(testing: Boolean = false) {
    install(Routing) {
        get("/") {
            call.respond("Testing")
        }
    }
}
```

2. create jar file with shadowjar
```
tasks {
    named<ShadowJar>("shadowJar") {
        archiveBaseName.set("shadow")
        mergeServiceFiles()
        manifest {
            attributes(mapOf("Main-Class" to mainClasses))
        }
        transform(com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer::class.java) {
            setPath("META-INF/services")
            include("org.eclipse.jetty.http.HttpFieldPreEncoder")
        }
        archiveFileName.set("example.jar")
    }
}
```

3. upload on ubuntu server and create its systemd service and run with systemctl start example
_service file:_ 
```
[Unit]
Description=example
After=syslog.target

[Service]
User=root
LimitNOFILE=20536
ExecStart=/var/www/example/example-script
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```

_example-script:_
```
#!/bin/sh
cd /var/www/example
java -jar exmaple.jar
```

**Expected behavior**
When user make request to http://SERVER_IP:APP_PORT it should close it after request complete but it keep opened it until we will stop server. Checking with `ss -ant | grep {CLIENT_PUBLIC_IP}`

**Screenshots**
_This is screenshot which i get after an hour when made last request in screenshot last connection with port 8383 that is from my machine and it is still not closed._
<img width="672" alt="Screenshot 2020-05-20 at 9 32 50 PM" src="https://user-images.githubusercontent.com/11086988/82472678-fd86a400-9ae1-11ea-8db6-d1969f98a5ab.png">

**Comment by e5l** [comment]
Hi @itboy87, thanks for the report. Could you tell me how you perform the request?

**Comment by itboy87** [comment]
Hi @e5l thanks for responding. I tried it from postman simple get request with my server ip and ktor app port.

**Comment by itboy87** [comment]
Hi @e5l is there any progress on this?

**Comment by e5l** [comment]
Hi @itboy87, sorry for the delay. Yep, I'm searching for the fix.

**Comment by itboy87** [comment]
Ok thanks @e5l. My ktor containers is hanging after 1 day even resources enough may be due to this issue. Currently containers restarting when hanging with livenessprobe in kubernetes and work again. I will check my code and test things to make sure if that is related to this issue or something else.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-368">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by stevejuma** [comment]
> Ok thanks @e5l. My ktor containers is hanging after 1 day even resources enough may be due to this issue. Currently containers restarting when hanging with livenessprobe in kubernetes and work again. I will check my code and test things to make sure if that is related to this issue or something else.

For anyone experiencing similar issues with ktor containers being restarted by kubernetes due to failures in the liveness probe, we found the culprit to be an issue with Netty. Switching to using Tomcat seemed to resolve our problems.
