### ISSUE TITLE
Custom Host header should override default value in CIO client

### ISSUE THREAD

**Issue by proton72** [ktorio/ktor#1886]
**Ktor Version and Engine Used (client or server and name)**
CIO client 1.3.2

**Describe the bug**
Custom ```Host``` header cause doubling of ```Host``` header in request

**To Reproduce**
1. Add ```header("Host", "my-lovely-host")``` to the request definition
2. Execute request
3. See two headers with the same key in the http request:
```
Host: real-host
Host: my-lovely-host
```
Some of http servers treat that request as incorrect and reply 400, some - take into account only first header.

**Expected behavior**
Custom `Host` header should override original one. This is behavior of apache client, and the issue prevents from the migration Apache -> CIO.

**Comment by e5l** [comment]
Hi @proton72, thanks for the report. The `Host` header is the restricted header, manual control could cause security issues. Could you tell me why you need to customize it?

Otherwise, we're considering to prevent setting it by hand.

**Comment by proton72** [comment]
Hello, @e5l ! We are building a pulling monitoring system, which collects data from different http services in the network. 
Some of the services are dislocated behind the sidecar proxy. That kind of proxy is configired to pass only requests with particular `Host` header (which is reasonable for real world traffic), without any exceptions for `X-Forwarded-Host` or `Forwarded` headers. 
I think, that our case is not the most typical one, but sure, that prevention from altering `Host` would cause more inconvenience than security benefits.

**Comment by e5l** [comment]
Fixed in the branch `e5l/doubling-host`. The fix will be available in the next release!
