### ISSUE TITLE
uninstallFeature function not working properly

### ISSUE THREAD

**Issue by agcom** [ktorio/ktor#1887]
**Ktor Version and Engine Used (client or server and name)**
1.3.2, server/client, CIO engine

**Describe the bug**
I don't see uninstallFeature function, un-intercepting the pipeline.
Tested with *DefaultHeaders* and *CORS*.

**To Reproduce**
Server code,
```kotlin
fun main() {

    embeddedServer(CIO, host = "localhost", port = 8080) {
        
        install(CORS) {
            
            host("AHost.com")
            
        }
        
        install(DefaultHeaders)
        
        uninstallAllFeatures() // This is where uninstallFeature will be called
        
        routing {
            
            get {
                
                call.respond("Hello")
                
            }
            
        }
        
    }.start(wait = true)

}
```
A client code (typically a simple get request),
```kotlin
fun main() = runBlocking {
    
    val client = HttpClient(CIO)
    
    client.get<HttpResponse>(port = 8080) {
        
        header(HttpHeaders.Accept, ContentType.Application.Json)
        header(HttpHeaders.Origin, "http://AHost.com")
        
    }.run {
        
        println(headers)
        
    }
    
}
```

Result,
```
Headers [Vary=[Origin], Access-Control-Allow-Origin=[http://AHost.com], Date=[Fri, 22 May 2020 00:21:53 GMT], Server=[ktor-server-core/1.3.2 ktor-server-core/1.3.2], Content-Length=[5], Content-Type=[text/plain; charset=UTF-8]]
```

**Expected behavior**
Features actually be uninstalled. Meaning they won't intercept the pipeline anymore.

**Comment by zypus** [comment]
Stumbled upon the same issue, regarding _ContentNegotiation_. By first installing _Jackson_  as content negotiator, then uninstalling the ContentNegotiation and adding _kotlinx.serialization_ as new content negotiator. The second install executes without any issues, however still Jackson handles the content negotiation.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-367">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
