### ISSUE TITLE
configureBootstrap hook overwritten by Ktor settings

### ISSUE THREAD

**Issue by carbotaniuman** [ktorio/ktor#1909]
**Subsystem**
ktor-server-netty

**Is your feature request related to a problem? Please describe.**
I'm trying to add some GlobalTrafficShapingHandler to ktor, but I cannot do anything because Ktor overwrites what I am trying to do in the `configureBootstrap` lambda. I cannot set the childHandler or the channelFactory , or even influence what they do in any way. I cannot touch childHandler nor channelFactory (it's set via the `channel()` call).

```
ServerBootstrap().apply {
	configuration.configureBootstrap(this)
	group(connectionEventGroup, workerEventGroup)
	channel(connectionEventGroup.channel.java)
	childHandler(
		NettyChannelInitializer(
			pipeline, environment,
			callEventGroup, engineDispatcherWithShutdown, dispatcherWithShutdown,
			connector,
			configuration.requestQueueLimit,
			configuration.runningLimit,
			configuration.responseWriteTimeoutSeconds,
			configuration.requestReadTimeoutSeconds,
			configuration.httpServerCodec
		)
	)
}
```

**Describe the solution you'd like**
I'd want a way to expose the underlying NettyPipeline, or at least have some way to meaninfully use the `configureBootstrap` hook. I would also take a hook called in `override fun initChannel(ch: SocketChannel) {` as that would let me do the configuration I want.

**Motivation to include to ktor**
Ktor already takes effort to expose this hook, but I've found the things I really want to do with this hook aren't allowed.

**Comment by carbotaniuman** [comment]
I was trying to extend the classes and modify stuff that way, but the Ktor classes are closed and the implementations use internal variables and methods that I cant reach.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-356">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Merged
