### ISSUE TITLE
Reactive Database (R2DBC) Feature Support

### ISSUE THREAD

**Issue by halimpuckjava** [ktorio/ktor#1910]
hi

R2DBC feature support for KTOR

**Comment by e5l** [comment]
Hi @halimpuckjava, thanks for the response.
What kind of support do you want to see in Ktor?

It also would be awesome If you post some of your ideas or code samples for that

**Comment by halimpuckjava** [comment]
hi @e5l 

i use spring kofu, so with r2dbc there is koltin dsl where use can specify your driver & conenction properties  (r2dbcpostgres , ...ect) 

so i suggest to add plugins to support this kind of r2dbc and offer an implementation for DatabaseClient and can inject auto when install plugin for r2dbc 

i hope its now more clean

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-355">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
