### ISSUE TITLE
Ktor IOS Memory Consumption

### ISSUE THREAD

**Issue by BlomeTim** [ktorio/ktor#1918]
**Ktor Version and Engine Used (client or server and name)**
Kotlin: 1.3.72
Ktor: 1.3.2
Engine: Ios
To start a Coroutine we use `dispatch_async(dispatch_get_main_queue())` within our Dispatcher.

**Describe the bug**
Ktor seems to require quite a lot of memory not being released afterwards:

We are trying to write a NSFileProviderExtension based on a Kotlin core.
There we are doing quite a lot of http requests via Ktor.
Sadly we did not find a possibility to stay below Apples overall 15 MB memory limit, yet.
We know using a default UrlSession ist not ideal, so we have already created a Client that uses a Background Session for downloads.
Still adding up memory on each HTTP call, we can not reduce the memory impact enough to stay below that limit.

Ktor seems to consume way more memory than a default NSUrlSession. And does not release all consumed memory afterwards.
For Comparison we implemented almost the same NSUrlSession call in Kotlin and Swift.
When firing 30 requests, the UrlSession itself came back to 23 MB Memory consumption, while Ktor does not go below 44MB afterwards.
Memory consumption can be checked out via memory tab in Xcode.
Is there anything we can do to reach something like the UrlSession memory consumption?

**To Reproduce**
To reproduce, we created a demo project here:
https://github.com/BlomeTim/KtorMemoryConsumptionIOS/tree/master/MPP%20Ktor%20Memory%20Demo/mpp-ios-android-step-008-based-memory-consumption
To keep the mpp project setup simple, we started with https://github.com/kotlin-hands-on/mpp-ios-android/tree/step-008 .

A sample Ktor iOS implementation can be found in actual.kt (https://github.com/BlomeTim/KtorMemoryConsumptionIOS/blob/master/MPP%20Ktor%20Memory%20Demo/mpp-ios-android-step-008-based-memory-consumption/SharedCode/src/iosMain/kotlin/actual.kt).
The counterpart to execute is located in ViewController.swift (https://github.com/BlomeTim/KtorMemoryConsumptionIOS/blob/master/MPP%20Ktor%20Memory%20Demo/mpp-ios-android-step-008-based-memory-consumption/native/KotlinIOS/KotlinIOS/ViewController.swift).

Steps to reproduce the behaviour:
0. Open Project in AndroidStudio &(Terminal @AndroidStudio) ./gradlew packForXcode
2. Open Xcode project 'KotlinIOS'
3. Run on iPhone 11 Simulator and check Memory Tab in Xcode
4. To compare to a NSURLSession written in Kotlin, comment line 28 and uncomment line 30 in ViewController.swift

**Expected behavior**
After performing several http calls via Ktor, we expected, that memory consumption would go back to where it has started.

**Screenshots**
1) Memory consumption using Ktor:
![image](https://user-images.githubusercontent.com/23495474/83516298-17a78580-a4d7-11ea-89ce-f24d3b21f02f.png)
2) Memory consumption using NSURLSession called within Kotlin:
![image](https://user-images.githubusercontent.com/23495474/83516357-2ee67300-a4d7-11ea-934d-b93f09e9a54c.png)
3) Memory consumption using NSURLSession directly called in Swift:
![image](https://user-images.githubusercontent.com/23495474/83516403-46bdf700-a4d7-11ea-8613-a2ea5692dfbc.png)

**Comment by e5l** [comment]
Hi @BlomeTim, thanks for the report. It's a known problem and the fix is clear and was made in `1.3.0`. But unfortunately, we have to roll back the fix due to the kotlin-native issue of calling GC code on the different thread(https://youtrack.jetbrains.com/issue/KT-37225).

It will be fixed in kotlin `1.4`, and we will apply the fix after that!

**Comment by e5l** [comment]
Related: https://github.com/ktorio/ktor/issues/1650
