### ISSUE TITLE
call.respond(Object) cause error

### ISSUE THREAD

**Issue by Alcheorg** [ktorio/ktor#192]
At sample json for example:
`java.lang.IllegalArgumentException: Response pipeline couldn't transform 'class org.jetbrains.ktor.samples.json.Model' to the FinalContent`

//ktor-test-host used

**Comment by cy6erGn0m** [comment]
Are you sure you have Gson feature installed?

**Comment by orangy** [comment]
More likely Accept header is missing `application/json`. It looks like a duplicate of #180

**Comment by mohammadrafigh** [comment]
I have the same problem. @cy6erGn0m Gson is installed, and @orangy application/json is set both for request and response. but the only thing works is that I manually convert to Json like this:
`call.respond(gson.toJson(myObject))`

**Comment by orangy** [comment]
Is it still a problem with 0.9 and its new content negotiation feature?

**Comment by cy6erGn0m** [comment]
Closing it due to no response. Please reopen it if there is still issue.
