### ISSUE TITLE
Support Java HTTP Client

### ISSUE THREAD

**Issue by dtretyakov** [ktorio/ktor#1930]
**Subsystem**
Client, JVM

**Describe the solution you'd like**
In Java 11 was [introduced HTTP Client](https://openjdk.java.net/groups/net/httpclient/intro.html) based on reactive-streams.

**Motivation to include to ktor**
Since more projects are switching to modern Java versions it could be valuable to use built-in [Java HTTP Client](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/package-summary.html) without need to use additional libraries. It supports HTTP/1.1 and HTTP/2 protocol and provides async APIs.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-348">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by dtretyakov** [comment]
Fixed in https://github.com/ktorio/ktor/pull/2187
