### ISSUE TITLE
Failed to build ktor locally: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by BorzdeG** [ktorio/ktor#1931]
**To Reproduce**
1. Clone this repository from the `master` branch
2. Run the `./gradlew clean check` command

**Describe the bug**

[gradle.log](https://github.com/ktorio/ktor/files/4741545/gradle.log)

```
> java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

> sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.15.6
BuildVersion:   19G36e

> uname -a
Darwin XXX 19.6.0 Darwin Kernel Version 19.6.0: Sun May 17 22:15:23 PDT 2020; root:xnu-6153.140.21~10/RELEASE_X86_64 x86_64
```

**Comment by e5l** [comment]
Hi @BorzdeG, thanks for the report.
Could you try running `clean check` with `--no-parallel` flag?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-347">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
