### ISSUE TITLE
StatusPages doesn't catch FreeMarker exceptions

### ISSUE THREAD

**Issue by Masterzach32** [ktorio/ktor#1941]
**Ktor Version and Engine Used (client or server and name)**
1.3.2, Netty server, FreeMarker and StatusPages

**Describe the bug**
If an exception is thrown while generating a html page using FreeMarker (ie. FreeMarker throws a TemplateException), the StatusPages feature does not consume it. I've tried catching Throwable and TemplateException:

```
exception<TemplateException> {
    Rollbar.error("Error generating page: ", it)
    call.respond(FreeMarkerContent(
        "error.ftl",
        mapOf("data" to ErrorData(
            500,
            "Oops! An error occurred while we were generating that page!",
            "Hit the back button on your browser and try again."
        ))
    ))
}

exception<Throwable> {
    Rollbar.error(null, it)
    call.respond(FreeMarkerContent(
        "error.ftl",
        mapOf("data" to ErrorData(
            500,
            "Oops! Something went wrong on our end!",
            it.localizedMessage
        ))
    ))
}
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-343">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
@Masterzach32 I can catch `TemplateNotFoundException` and `ParseException` with StatusPages on Ktor 1.6.0. Please tell me how exactly do you trigger `TemplateException`?
