### ISSUE TITLE
Wrong max-age directive on the Cache-Control header

### ISSUE THREAD

**Issue by bernatpl** [ktorio/ktor#1944]
**Ktor Version and Engine Used (client or server and name)**
ktor-client, version 1.3.2

**Describe the bug**
Using the ktor-client on Android with the OkHttp engine I noticed that using the maxAge() function to set the Cache-Control header had no effect on the caching strategy.
It was caused because using that function the max-age directive key and value are separated with ':' and the OkHttp client expected '=' as a separator.

**Expected behavior**
According to the HTTP standard, the max-age directive of the Cache-Control header must use the '=' symbol instead of ':' to separate the directive key with the value.

**Comment by bernatpl** [comment]
See PR https://github.com/ktorio/ktor/pull/1769 for the fix.

**Comment by e5l** [comment]
Hi @bernatpl, great thanks for the report and fix! 
Merged and closed.
