### ISSUE TITLE
CIO client silently failing on connection closed

### ISSUE THREAD

**Issue by vehovsky** [ktorio/ktor#1948]
**Ktor Version and Engine Used (client or server and name)**
1.3.2, client, CIO

**Describe the bug**
I've encountered issue with CIO client during file download. When server, for whatever reason (in my case due to Jenkins httpKeepAliveTimeout issue: https://issues.jenkins-ci.org/browse/JENKINS-61823) closes connection before sending the whole file, CIO client does not throw any exception and it's very hard to tell what happened.

**To Reproduce**
```
client.request<HttpStatement>(url).execute { response ->
    if (!response.status.isSuccess()) {
        onError(response)
        return@execute
    }
    val channel = response.receive<ByteReadChannel>()
    while (!channel.isClosedForRead) {
        val packet = channel.readRemaining(DEFAULT_BUFFER_SIZE.toLong())
        while (!packet.isEmpty) {
            val bytes = packet.readBytes()
            destination.appendBytes(bytes)
        }
    }
    if (headResponse.contentLength() ?: 0 > 0 && headResponse.contentLength() != destination.length()) {
        throw RuntimeException("[DOWNLOAD FAILURE] '$url'. Expected size of downloaded file '${headResponse.contentLength()}' actual size '${destination.length()}'.")
    }
}
```

**Expected behavior**
On the contrary Apache client behaves nicely and throws:
```org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 113531; received: 15329```

**Comment by Ololoshechkin** [comment]
Am I correct that your RuntimeException ```"[DOWNLOAD FAILURE] '$url'. Expected size of downloaded file '${headResponse.contentLength()}' actual size '${destination.length()}'."``` was also never thrown?
Have you tried to debug that? Does debugger drop in that place of code?

**Comment by vehovsky** [comment]
You are not correct. With CIO client it was thrown. Not with Apache client obviously, ConnectionClosedException was correctly thrown by Apache client.

**Comment by e5l** [comment]
Hi @vehovsky, thanks for the issue and clarification :)
I will investigate the problem.

**Comment by e5l** [comment]
Hey, @vehovsky 
I checked the problem and got different exceptions from all engines. I failed to reproduce the absence of the exception.

Could you post here the request and response headers? It will help to understand the case.

I also will unify the exceptions in that place - it will be the same exception on all engines and platforms.

**Comment by vehovsky** [comment]
I't was happening consistently when downloading build artifacts (100+MB) from Jenkins CI jobs, when downloading multiple (5-10) such files in parallel. My VPN connection to the server wasn't fastest also. On the server side, that interrupted the connection, exception as posted in the [JENKINS-61823](https://issues.jenkins-ci.org/browse/JENKINS-61823) was thrown.

As far as I could tell there was nothing special about the request/response headers, when comparing the successful vs failed headers.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-338">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
