### ISSUE TITLE
[Outdated doc] Ktor quickstart contains outdated reference to version before 1.0

### ISSUE THREAD

**Issue by gabrielgatu** [ktorio/ktor#1950]
**Ktor Version and Engine Used (client or server and name)**
https://ktor.io/quickstart/quickstart/gradle.html#intellij-improve-the-app-with-the-application-object

**Describe the bug**
Ktor is currently at version 1.3.2, but in the quickstart docs it is mentioned that is not yet 1.0. Referenced line is: "Since Ktor is not yet 1.0, we have custom Maven repositories for distributing our early preview artifacts."

**Expected behavior**
Line should be corrected.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-337">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in 1.5.2
