### ISSUE TITLE
Raw headers

### ISSUE THREAD

**Issue by marcincinik** [ktorio/ktor#1955]
**Subsystem**
Client

**Is your feature request related to a problem? Please describe.**
I have to send non-conformant Accept header to a server which interprets accept headers incorrectly.
The server will accept only 'Accept: application/x-json-stream', but KTOR client always posts 'Accept: application/x-json-stream; application/json'

My client:
```kotlin
client.get<HttpStatement> {
     url("xxxxxxxx")
     headers {
         accept(ContentType("application", "x-json-stream"))
         header("Authorization", "Bearer ${jwtToken()}")
     }
}
```

**Describe the solution you'd like**
I want to be able to define raw accept header which is sent as I define it.

**Motivation to include to ktor**
Any non-conformant server / web-service

**Comment by e5l** [comment]
Hey @marcincinik,
you can write a custom feature to do that:

```kotlin
class HeadersRewriteFeature(val rewriter: HeadersBuilder.() -> Unit) {

    companion object : HttpClientFeature<HeadersBuilder, HeadersRewriteFeature> {
        override val key: AttributeKey<HeadersRewriteFeature> = AttributeKey("HeadersRewriteFeature")

        override fun prepare(block: HeadersBuilder.() -> Unit): HeadersRewriteFeature = HeadersRewriteFeature(block)

        override fun install(feature: HeadersRewriteFeature, scope: HttpClient) {
            scope.requestPipeline.intercept(HttpRequestPipeline.Render) {
                feature.rewriter(context.headers)
            }
        }
    }
}
```

And that's how you can use it:
```kotlin
val client = HttpClient {
   install(HeadersRewriteFeature) {
       if (get(HttpHeaders.Accept) == "bad value") {
          set(HttpHeaders.Accept, "good value")
       }
   }
}
````

**Comment by marcincinik** [comment]
Thanks a lot - i’ll check It out and tell you the outcome


W dniu pt., 19.06.2020 o 12:22 Leonid Stashevsky <notifications@github.com>
napisał(a):

**Comment by marcincinik** [comment]
Leonid - a silly follow up question - seems I'm unable to google which jar contains the headers rewrite feature. Which of io.ktor:ktor-client-* should I be looking at ?

**Comment by e5l** [comment]
You don't need to add a new dependency. The feature is written in my response.

**Comment by marcincinik** [comment]
Sorry - I missed it

**Comment by marcincinik** [comment]
Works ! Thank you !

**Comment by e5l** [comment]
Thanks for the fast response!
Closed
