### ISSUE TITLE
Unhandled get freezes with `CIO` server

### ISSUE THREAD

**Issue by e5l** [ktorio/ktor#1962]
**Ktor Version and Engine Used (client or server and name)**
Server `CIO`,  `1.3.2`

**Describe the bug**
If we don't call `call.respond` the server freezes and holds the connection with `CIO` server(without any message)
The `Netty` treats this sample as correct response and respond with status code `Unauthorized`

**To Reproduce**
Make the request with `CIO` server:
```kotlin
get("unauthorized") {
    call.response.status(HttpStatusCode.Unauthorized)
    call.response.header(HttpHeaders.WWWAuthenticate, "Basic realm=\"TestServer\", charset=UTF-8")
}
```
**Expected behavior**
Respond with `5xx Internal server error` or a correct response in that case

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-333">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
