### ISSUE TITLE
HTTP-client auth with Bearer token

### ISSUE THREAD

**Issue by Savrov** [ktorio/ktor#1967]
**Subsystem**
Client/Server, particular relevant ktor module(s) if applicable.
ktor HTTP-client, auth

**Is your feature request related to a problem? Please describe.**
Currently, Ktor HTTP-client supports only 2 types of providers: Basic and Digest. But in a real-life project is a standard to use Bearer token pair - access and refresh. So it will be great to add support of Bearer tokens to multiplatform Ktor's HTTP-client.
So the problem itself can be split into 4 sub-tasks:
1. Persist token pair in a safe place
2. Add them to auth headers
3. In case when the request with access token returns 401, 
3.1. pause all present requests
3.2 refresh it with refresh token.. and so on, regular flow.
3.3 restart interrupted requests from 3.1

**Describe the solution you'd like**
Create BearerAuthConfig, BearerAuthProvider like its Basic and Digest versions. Update Auth class to be able to save, load and refresh tokens. Something like this:
```
fun provide(): HttpClient = HttpClient {
        install(Auth) {
            bearer {
                refresh = TODO("lambda function that get new access token and return a string"),
                revoke = TODO("lambda function that removes tokens")
            }
        }
    }
```

**Motivation to include to ktor**
Add support of Bearer tokens for clients.

**Comment by Ololoshechkin** [comment]
Thanks for the feature request!
What you suggest is actually 2 features:
1. Bearer (jwt) support in HttpClient
2. Automatic token refresh.

The first one should be added as a part of Auth feature and we'll be working on that.
And the second one (token renewal) is currently a bit out of our scope but we'll keep our eye on it in future.

**Comment by Savrov** [comment]
Thank you for a quick response,
I personally think that Bearer support without refresh functionality is pretty useless and un-safe (to make access token work long enough, access token's lifetime should be extended to a week at least. According to my knowledge access token should be valid for 5-10 min). So, will be much better, if these two features will be delivered together.
If there is a way to help you in solving these tasks, please let me know.

**Comment by Ololoshechkin** [comment]
Thank you for offering your help!
We will appreciate if you make a PR with your changes. Please tell if you need any help or guidance from us.

**Comment by Savrov** [comment]
@Ololoshechkin, I don't see a way to add support of token refresh w/o complete rewrite of Auth.kt
As I understand, the whole job must happen inside the `install` function of `Auth` class:
we check if response status is Unauthorized and a current provider is BearerAuthProvider (that must be created)
if this condition was fulfilled, then run a blocking function to load a new token
after token received, continue with the original request

so I see it like this:
```
scope.feature(HttpSend)!!.intercept { origin, context ->
                if (origin.response.status != HttpStatusCode.Unauthorized) return@intercept origin
                if (origin.request.attributes.contains(circuitBreaker)) return@intercept origin

                var call = origin
                val candidateProviders = HashSet(feature.providers).apply { removeAll(feature.alwaysSend) }
                while (call.response.status == HttpStatusCode.Unauthorized) {
                    val headerValue = call.response.headers[HttpHeaders.WWWAuthenticate] ?: return@intercept call
                    val authHeader = parseAuthorizationHeader(headerValue) ?: return@intercept call
                    val provider = candidateProviders.find { it.isApplicable(authHeader) } ?: return@intercept call

                    when(provider) {
                        is BearerAuthProvider -> {
                            // try to refresh token, token should be stored somewhere, so `addRequestHeaders` function can load it and update auth header
                            val token = provider.refreshToken()
                            println("tokens=$token")
                        }
                    }

                    candidateProviders.remove(provider)

                    val request = HttpRequestBuilder()
                    request.takeFromWithExecutionContext(context)
                    provider.addRequestHeaders(request) // load token from a storage, insert auth header
                    request.attributes.put(circuitBreaker, Unit)

                    call = execute(request)
                }
                return@intercept call
            }
```
What do you think about this solution?

**Comment by Ololoshechkin** [comment]
@Savrov ,
Thanks for the solution you provided!
I am mostly fine with it but what would happen if for some reason `call.response.status` would be always `Unauthorized`? I guess it worth limiting the number of attempts to prevent client from being forever frozen.

**Comment by Savrov** [comment]
that's why there is a block:
```
 // if token is null, return 401 response to ask to login with username/pwd
 if (token == null) return@intercept call
```
It should work in a desired way, cause if its not - all other types (digest, basic) will fall to recursion as well. Sadly, I can not test it, cause when I'm running this simple code:
```
suspend fun main(args: Array<String>) {
    val client = HttpClientProvider.provide()
    GlobalScope.launch(Dispatchers.IO) {
        val response: HttpResponse = client.get("https://google.com")
        println("response=$response")
    }.join()
}
```
it fails with an exception

> Exception in thread "DefaultDispatcher-worker-1" org.apache.http.ConnectionClosedException: Connection closed unexpectedly
> 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.closed(HttpAsyncRequestExecutor.java:146)
> 	at org.apache.http.impl.nio.client.InternalIODispatch.onClosed(InternalIODispatch.java:71)
> 	at org.apache.http.impl.nio.client.InternalIODispatch.onClosed(InternalIODispatch.java:39)
> 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100)
> 	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:277)
> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:449)
> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.hardShutdown(AbstractIOReactor.java:590)
> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:305)
> 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
> 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
> 	at java.lang.Thread.run(Thread.java:748)

And this is a problem **only of my local build**, for example, ktor version 1.3.2 has no problems with a provided snippet. 
Yeah, and it fails even w/o Auth feature used. So I suggest it happens due to unrelated error to my "bearer feature". If you have any ideas, I'll be glad to hear one)

**Comment by Savrov** [comment]
Ok, I'm trying to run it via build-in tests, but I don't understand how "mocked" endpoints are defined. I've created a test under `AuthTest.kt` file:
```
 @Test
    fun testUnauthorizedBearerAuth() = clientTests {
        config {
            install(Auth) {
                bearer {
                    refreshTokenFun = { null }
                    loadTokensFun = { null }
                    sendWithoutRequest = true
                }
            }
        }

        test { client ->
            client.get<HttpStatement>("$TEST_SERVER/bearer/unauthorized").execute {
                assertEquals(HttpStatusCode.Unauthorized, it.status)
            }
        }
    }
```
Expectedly, endpoint `$TEST_SERVER/bearer/unauthorized` does not exist, but I don't know how I can create it. I've found a `ktor-auth.api` file, but I have never seen anything like that before. Files with .API extension are unknown to me, I need some information how tests work

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-331">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Released in 1.4.0

**Comment by spauldhaliwal** [comment]
@e5l  I'm on ktor and ktor-auth 1.5.2 and I don't see this feature. Was it removed? Even looking in the source code I don't see it.

**Comment by jeffdgr8** [comment]
@e5l this has not been released yet. [The PR](https://github.com/ktorio/ktor/pull/1991) was merged to the [vbr/bearer-auth](https://github.com/ktorio/ktor/tree/vbr/bearer-auth) branch, pending [finalizing the API](https://github.com/ktorio/ktor/pull/1991#issuecomment-657628167) before releasing.

**Comment by e5l** [comment]
Sorry, didn't notice.

**Comment by miltonwu** [comment]
Hi all,

Do we have any progress for this feature?
I am looking forward to this.

Thanks.

**Comment by e5l** [comment]
Merged in main. Will be available in Ktor 1.6.0

**Comment by Azbesciak** [comment]
Hello, looking at this class
```kotlin
public class BearerTokens(
    public val accessToken: String,
    public val refreshToken: String
)
```

What is the point in `refreshToken` as `String`?

**Comment by bigoloo** [comment]
Assume this scenario, 
if the refresh token is failed I want to get the exception in my other interceptors
what should I do for that purpose

**Comment by Stexxe** [comment]
@bigoloo what do you mean by refresh token is failed?

**Comment by spauldhaliwal** [comment]
Presumably they mean the refresh token was not able to create a new access token, so the user's session has expired. In this scenario, he would like to receive this exception in order to re-authenticate the user from scratch. 

A lot of flows work like this:

1) Authenticate with username and password to receive access token and refresh token.

2) Request data with access token

3) If at any point the access token expires, get a new access token by using the original refresh token.

4) If the refresh token succeeds in retrieving a new access token, continue making further request with the new access token. However, if the refresh token itself has also expired, we would like to catch this particular exception in order to completely restart the authentication process in step 1 (by entering a username and password, for example)

**Comment by e5l** [comment]
@rsinukov could you take a look?

**Comment by rsinukov** [comment]
@spauldhaliwal Isn't how it works now? In case if refresh failed, you will receive 401 response and can handle it by showing login screen, etc.

**Comment by spauldhaliwal** [comment]
> @spauldhaliwal Isn't that how it works now? In case if refresh failed, you will receive 401 response and can handle it by showing login screen, etc. 

I haven't tried it actually. I ended up implementing my own solution a while back, so I was just clarifying what I thought the above comment was trying to describe

(though perhaps I shouldn't have said anything since as I said I haven't actually tried this implementation haha. Sorry!)

**Comment by rsinukov** [comment]
@spauldhaliwal 
No worries, thanks for the clarification!
