### ISSUE TITLE
[JS client] Cannot change redirect policy by followRedirects=false

### ISSUE THREAD

**Issue by kam1sh** [ktorio/ktor#1968]
**Ktor Version and Engine Used (client or server and name)**
Ktor HTTP client 1.3.2 on Kotlin/JS; dependencies: 
```
                implementation("io.ktor:ktor-client-json:$ktorVersion")
                implementation("io.ktor:ktor-client-js:$ktorVersion")
                implementation("io.ktor:ktor-client-json-js:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization-js:$ktorVersion")
```

**Describe the bug**
While debugging the situation with redirects location, I found that if you call something like `println(resp)` where resp is a `HttpResponse` result of a request that returns `HTTP/1.1 302 Found`, string will be `HttpResponse[http://localhost:3000/api/v1/auth/logout, 200 OK]`, where I excected something like `HttpResponse[http://localhost:3000/api/v1/auth/logout, 302 Found]`.

In network tab of browser developer tools response shown as `302 Found` with correct `Location` header, but ktor client shows different results...

**To Reproduce**
1. Take [this repo](https://github.com/kam1sh/kvision-sandbox/tree/ktor-http-issue) for example, change url in `App.kt` to something suitable in your environment (httpbin, for example)
2. Open in browser localhost:3000
3. See string representation of response with 200 OK

**Expected behavior**
302 Found with `Location` header

**Screenshots**
![image](https://user-images.githubusercontent.com/14600211/85710861-5fdd5080-b6ef-11ea-94ab-c6ba4947cd4a.png)

If what, I can try to debug this and fix by myself, but later...

P.S. Thank you for ktor framework and client. They're awesome.

**Comment by kam1sh** [comment]
Wrote a simple test that shows this issue: https://github.com/kam1sh/ktor/commit/3651bbffd2425177cbde1d89a7e0a068551745c2

```kotlin
    @Test
    fun testRedirectResponse() = clientTests {
        config {
            followRedirects = false
        }
        test { client ->
            client.get<HttpStatement>("$TEST_URL_BASE/").execute {
                assertEquals(HttpStatusCode.Found, it.status)
                assertNotNull(it.headers["Location"], "Location header not found.")
                assertTrue(it.toString().endsWith("302 Found]"))
            }
        }
    }

```

Do you have a developer documentation that describes a request/response pipeline? I don't understand where should I look for a root cause...

**Comment by kam1sh** [comment]
Yes! As I understand right now, JS Fetch API has a `redirect = "follow"` parameter by default.

So I have to implement setting redirect = manual if config.followRedirects is false. And that's it.

**Comment by kam1sh** [comment]
Oh. It's hardcoded value...
https://github.com/ktorio/ktor/blob/c2d1a573d4cb7ea1463ce65a36b8ed1834d9e35b/ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/JsUtils.kt#L38

I hope I can propose a different approach.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-326">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
