### ISSUE TITLE
how to set different config file

### ISSUE THREAD

**Issue by P1NG2WIN** [ktorio/ktor#1969]
I have two configs, `application.conf` and `application-dev.conf` with different `deployment` in. How i can programmatically change default ktor config so it will be load `application-dev.conf` instead of `application.conf`?

ktor main class

```
fun main(args: Array<String>): Unit
        = EngineMain.main(args)

@UseExperimental(ExperimentalCoroutinesApi::class, InternalAPI::class, KtorExperimentalAPI::class, ExperimentalTime::class)
@Suppress("unused") // Referenced in application.conf
@JvmOverloads
fun Application.mainModule(testing: Boolean = false) {
    install(DefaultHeaders)
    install(ContentNegotiation) {
        gson { }
    }
    install(CallLogging) {
        logger = LoggerFactory.getLogger("CallLogging")
    }

    val client = HttpClient(CIO) {
        install(JsonFeature) {
            serializer = GsonSerializer() {
                disableHtmlEscaping()
            }
        }
        install(Logging) {
            level = io.ktor.client.features.logging.LogLevel.INFO
        }
    }

    val envType = EnvTypes.from(
        environment.config.property("ktor.environment").getString())


    routing {
        ......
    }
}
```

**Comment by P1NG2WIN** [comment]
Or maybe i can have two deployment cases in application.conf and set which one will be loaded in the code myself

**Comment by Ololoshechkin** [comment]
Thanks for the issue report!
We'll think about the design for the case of multiple configurations. Currently you can either use Gradle task or write a simple script that changes your configuration.

**Comment by P1NG2WIN** [comment]
> you can use Gradle task

Could you tell me more about this? Config that will be used somewhere in the jar?

**Comment by Ololoshechkin** [comment]
No, what you can do is you can just have 2 separate config files (`application-default.conf` and `application-dev.conf` in your case) and you can have 2 gradle tasks, correspondingly: `useApplicationDefaultConf` and `useApplicationDevConf`. Each task just writes content of a corresponding .conf file to the main `application.conf`. You can also do that with bash script.

Yes, it's not the best solution, but at least I hope this will help you for now.
