### ISSUE TITLE
Objections to changing boundary to internal on MultiPartFormDataContent?

### ISSUE THREAD

**Issue by jschneidereit** [ktorio/ktor#1970]
https://github.com/ktorio/ktor/blob/3ce3906c2bfa3c86238d40e9b67006b2b020bdaf/ktor-client/ktor-client-core/common/src/io/ktor/client/request/forms/FormDataContent.kt#L43

I'd like to change this to internal so I can consume the boundary like so:

```kotlin
class MultiPartMixedDataContent(
        parts: List<PartData>
) : MultiPartFormDataContent {
    override val contentType: ContentType = ContentType.MultiPart.Mixed.withParameter("boundary", boundary)
}
```

**Comment by e5l** [comment]
Hi @jschneidereit, thanks for the report.
It's the valid use case and we're absolutely OK to change that.

It would be nice if you make the PR :)

**Comment by jschneidereit** [comment]
@e5l - Change is in progress and it looks like I'd have to make `MultiPartFormDataContent` open, is that acceptable?

**Comment by e5l** [comment]
That's OK

**Comment by jschneidereit** [comment]
Hey @e5l could I get a review on the linked PR? I saw in contributing that there were documentation changes required but am not sure what changes I should make since they'll be picked up by intellisense 🤔

**Comment by cy6erGn0m** [comment]
Using inheritance for extending is generally not the best option and usually causes difficulties due to inheritance and instantiation limitations. I would prefer adding a constructor parameter with the default argument computing by the generate function. So one could simply pass a custom value if required.

**Comment by jschneidereit** [comment]
@cy6erGn0m how about my solution in #2003?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-325">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
