### ISSUE TITLE
qop missing from auth header when using digest auth

### ISSUE THREAD

**Issue by RyanGrif** [ktorio/ktor#1974]
When using the Ktor http client (ktor 1.3.1) with digest auth, calls to a downstream service fail with a 401 status code. This is because the "qop" field isn't included in the authentication header.

The problem is caused by a bug in DigestAuthProvider.addRequestHeaders. This line:

`actualQop?.let { this["qop"] }`

should be

`actualQop?.let { this["qop"] = it }`

**Comment by Ololoshechkin** [comment]
Thanks for the bug report!
Would you like to make a pull request?

**Comment by RyanGrif** [comment]
Yes please. Does someone need to give me permission to contribute?

**Comment by e5l** [comment]
Thanks for the fix, merged and closed
