### ISSUE TITLE
standalone ktor server (eg.: binary linux, or exe windows)

### ISSUE THREAD

**Issue by erlangp** [ktorio/ktor#1976]
**Describe the solution you'd like**
standalone ktor server (eg.: binary linux, or exe windows)

**Comment by e5l** [comment]
Hey @erlangp, could you tell me how you want to use it?

**Comment by erlangp** [comment]
like `./myserverapp` (standalone) :D

**Comment by MaaxGr** [comment]
why not build a jar and than start it with `java -jar <myserver>`? If you like you can than write a simple bash script, that executes the java command

**Comment by erlangp** [comment]
@MaaxGr run without jvm (native).. standalone :)

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-322">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
