### ISSUE TITLE
GSON Support turns List<Long> into List<Double> during deserialization

### ISSUE THREAD

**Issue by andreaskaltenbach** [ktorio/ktor#1981]
**Ktor Version and Engine Used (client or server and name)**
Ktor 1.3.2, server, using ktor-gson for content negotiation

**Describe the bug**
When using Ktor's GSON support for content negotiation, `call.receive` calls for generic collection types accidentally return the wrong collection type.

Example: 
A sample route, expecting a JSON number array as payload. Inside the endpoint implementation, the JSON payload is intended to be deserialized into List\<Long\>. But unfortunately, the result type is List\<Double\>:
```
post("/test") {
  val listOfLongs:List<Long> = call.receive<List<Long>>()
  // listOfLongs is of type java.util.ArrayList<kotlin.Double> !!!
  call.respond(listOfLongs)
}
```

**To Reproduce**
1. Add the sample endpoint to your Ktor application
2. Use Ktor GSON support by setting
 ```
  install(ContentNegotiation) {
    gson {
    }
  }
```
3. Perform a POST /test with payload `[1, 2, 3]`
4. The response payload is `[ 1.0, 2.0, 3.0]` indicating that the deserialized value is of type List\<Double\> instead of List<Long>

**Expected behavior**
It is expected that the return type of `call.receive<List<Long>>()` is List\<Long\> and not List\<Double\>

**Comment by e5l** [comment]
Hi @andreaskaltenbach, it looks like the gson ignored the parameter here. Do you have any ideas on how we can fix this?

**Comment by e5l** [comment]
As a workaround you can try using `kotlinx.serialization` converter

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-320">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
