### ISSUE TITLE
Client for OkHttp 3.12.x

### ISSUE THREAD

**Issue by daugeldauge** [ktorio/ktor#1983]
Hi! We'd like to use ktor with OkHttp in Android app but OkHttp 3.13 and newer supports only Android 5+. We still have to to support Android 4 in our app.

**Subsystem**
ktor-client-okhttp

**Describe the solution you'd like**
Add separate client ktor-client-okhttp312 based on OkHttp 3.12.x branch or downgrade OkHttp dependency in ktor-client-okhttp

**Motivation to include to ktor**
Android 4 share is still significant for apps with large audience. OkHttp 3.12.x is still supported (latest release was about a month ago)

**Comment by e5l** [comment]
Hi @daugeldauge, thanks for the request.
We have no plans to support old `OkHttp` engines, but we have the `Android` engine for such cases.
Could you tell me if it works for you?

**Comment by e5l** [comment]
Closed. Please reopen if it doesn't work for you

**Comment by daugeldauge** [comment]
Sorry for late response.

Yes, I'm aware of `Android` engine. But we don't want to use it for the same reasons we've been using `OkHttp` engine in the first place — we would be susceptible to vendor & OS -specific behavior and bugs.

**Comment by daugeldauge** [comment]
We are going to downgrade OkHttp in our fork of ktor-client-okhttp.

Will pull-request which adds this fork as new ktor-client-okhttp312 module be accepted?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-319">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
