### ISSUE TITLE
Digest auth fails for urls with query params

### ISSUE THREAD

**Issue by RyanGrif** [ktorio/ktor#1990]
When using the Ktor http client (ktor 1.3.1) with digest auth, calls to a downstream service fail with a 401 status code when query parameters are included. This is because the uri field does not include the query params.

Changing all places in `DigestAuthProvider.addRequestHeaders` which currently use `url.encodedPath` to use `url.fullPath` instead seems to fix this problem (at least for the API I'm calling).

I can raise PR for this if someone agrees agrees this is the correct fix?

**Comment by e5l** [comment]
Hey @RyanGrif, thanks for the report. 
It looks like the right direction. Could you make the PR? :)

**Comment by e5l** [comment]
Merged. Closed. Thanks for the PR
