### ISSUE TITLE
PartialContent need responed content length  when respcode = 206

### ISSUE THREAD

**Issue by yizems** [ktorio/ktor#1995]
now just range

![image](https://user-images.githubusercontent.com/16949474/87007108-47dbf580-c1f4-11ea-810a-85f3c343e7e8.png)

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-308">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
