### ISSUE TITLE
How to use ContentEncoding?

### ISSUE THREAD

**Issue by Recognized** [ktorio/ktor#1996]
I setup client like here: 
```
HttpClient {
    ContentEncoding()
}
```
But I still cannot read request (using `call.content`) with `Accept-Encoding: gzip`, I don't see normal text, just some binary data. What do I need to do to read decoded text through ByteReadChannel?

**Comment by e5l** [comment]
Hi @Recognized, thanks for the report.

Could you try?
```kotlin
ContentEncoding {
    gzip()
}
```

**Comment by Recognized** [comment]
Hello @e5l ! Yes, that is what I did. I will attach repro project soon

**Comment by Recognized** [comment]
Here is example. https://github.com/Recognized/ktor-encoding-example/blob/master/src/main/kotlin/Main.kt . Shortly, when accessing `call.content` content is not decoded.
```

**Comment by alexbezhan** [comment]
+1, I'm experiencing the same issue
```kotlin
val client = io.ktor.client.HttpClient(Apache) {
    install(ContentEncoding) {
        gzip()
    }
}
val response = client.get<io.ktor.client.statement.HttpResponse>("https://postman-echo.com/gzip")
val bodyString = Buffer.buffer(response.call.response.readBytes())?.toString() // content is not decoded
assertEquals(true, JsonObject(bodyString).getBoolean("gzipped"))
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-307">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by rsinukov** [comment]
Property `content` of `HttpResponse` is a raw response from the server, that is not modified by `HttpResponsePipeline`. To get modified content, please use the `receive` function.
Example
```
        client.get<HttpStatement>(url).execute { response ->
            val content = response.receive<String>()
        }
```
I updated the doc [here](https://github.com/ktorio/ktor/pull/2065) to make it more visible
