### ISSUE TITLE
Thymeleaf   ExpressionObjecs  invalied , ex #httpServletRequest

### ISSUE THREAD

**Issue by yizems** [ktorio/ktor#1997]
```
StandardExpressionObjectFactory.buildObject(
            final IExpressionContext context,
            final String expressionObjectName
)
```

Context is EngineContext, not WebEngineContext, so can't get  `session` , `request`  , `response`  and so on;

how to resolve it?

**Comment by yizems** [comment]
I find an other question: 

OGNL expression `?.` invalid , 

`Caused by: ognl.ExpressionSyntaxException: Malformed OGNL expression: dict?.name` 


I think Thymeleaf  is imperfect on ktor ,  Don't use it

**Comment by e5l** [comment]
Hey, @yizems. Thanks for the report.
Could you file some snippets to give more details about the situation?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-306">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
