### ISSUE TITLE
Is there any way to check connectionState on android device with ktor WebSocket lib? 

### ISSUE THREAD

**Issue by keyvanNorouzi** [ktorio/ktor#2020]
Hi is there any way to check connection state and poor internet connection or socket state-change listener on android?
For example, when I want to notify when the device has no-internet (WIFI is connected but no data) or Check Socket is connected or not?

**Comment by corrado4eyes** [comment]
Hi @keyvanNorouzi , if you want to check on android the reachability of the connection, I suggest you to use the implementation of [NetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback) which have been introduced for android sdk >=24. [Here is a tutorial](https://proandroiddev.com/connectivity-network-internet-state-change-on-android-10-and-above-311fb761925) that shows implementation for android  sdk < 24 and 24+.

**Comment by keyvanNorouzi** [comment]
Hi, I don't mean the reachability of the internet connection.
I want to notify when the socket goes CONNECTION, DISSCONECTED, or CONNECTED

**Comment by 1354092549** [comment]
When you call 'ws', it is CONNECTING.
When you got a WebsocketSession, it is CONNECTED.
When the incoming channel is closed, it is DISCONNECTED and you can use CAUSE to check the reason.

**Comment by gulluchaubey** [comment]
@ArcticLampyrid can you please give a example for the CONNECTING, CONNECTED, DISCONNECTING AND DISCONNECTED from websocket.
