### ISSUE TITLE
Where the statusFiles should be saved?

### ISSUE THREAD

**Issue by hasanOryx** [ktorio/ktor#212]
I added this to my code:

```
    install(StatusPages){
            status(HttpStatusCode.NotFound) {
                 statusFile(HttpStatusCode.NotFound, HttpStatusCode.Unauthorized, filePattern = "error#.html")
           }
    }
```
and saved the statusFiles in path: `resources/statusFiles/404.html` 

tried to test by by routing to `http://localhost:8080/loginx` but did not get the error html file, instead I got the below:

> 

> <H1>404 Not Found</H1><P>Cannot find resource with the requested URI: /loginx</P>

**Comment by chrisjenx** [comment]
@hasanOryx `statusFiles()` does a `resolveResource(path)`. 
So in this instance for you. It would do a lookup in `src/main/resources/error404.html`

**Comment by chrisjenx** [comment]
If you wanted it to look in status files and just use the error code like you have currently put your files, this should do it.
```
statusFile(HttpStatusCode.NotFound, HttpStatusCode.Unauthorized, filePattern = "statusFiles/#.html")
```

**Comment by cy6erGn0m** [comment]
@hasanOryx have you managed this? can we close it?

**Comment by hasanOryx** [comment]
@cy6erGn0m  sorry for delay in feedback, but actually did not work with me, I tried both options

![image](https://user-images.githubusercontent.com/26045838/32186367-f4fbf06a-bdb2-11e7-94a6-d9f11dc850e3.png)

![image](https://user-images.githubusercontent.com/26045838/32186397-0738463e-bdb3-11e7-8bbe-4580bb2a9aa3.png)
