### ISSUE TITLE
Metrics Improvements

### ISSUE THREAD

**Issue by triplem** [ktorio/ktor#223]
Right now there are the following metrics available:

```
/ENDPOINT/(method:GET).200 OK
/ENDPOINT/(method:GET).meter
/ENDPOINT/(method:GET).timer
```

I would suggest to refactor these slightly to have the following names, to be able to parse those in an easy and nice way:

```
/method:GET/ENDPOINT/status.200 (so without OK)
/method:GET/ENDPOINT/meter
/method:GET/ENDPOINT/timer
```
This would allow to query for methods vs by endpoint as implemented right now and equals the defined ktor.calls.status metrics.

```
ktor.calls.status.200
```

**Comment by orangy** [comment]
It will be hard to change order of Method/Endpoint, because it matches Routing tables. For status I agree.

**Comment by triplem** [comment]
Adopted. Now using star-imports.

**Comment by triplem** [comment]
I guess after merging, we can close this issue.
