### ISSUE TITLE
contentLength() returns null on Android

### ISSUE THREAD

**Issue by sanchin** [ktorio/ktor#2239]
With Ktor 1.3.2 (I'm unable to check a newer version for now because of compatibility issues with other libs) I'm not getting a Content-Length header in the response from the following code:

```
         val url = URLBuilder().takeFrom(urlResolver.dxApiBaseUrl)
            .apply {
                parameters.append("param", "value")
            }

        httpClient.get<HttpStatement>(url.build()).execute { response ->
            
            val fileSize = response.contentLength() ?: -1
            println(fileSize)
            val channel = response.receive<ByteReadChannel>()
            // ... read the channel
            
        }
```

I've tried both the default client and OkHttp - both don't have the header and response.contentLength() returns null. The same code works on iOS, and I can see the headers when inspecting network traffic. Looks like a problem with parsing.

I've seen multiple issues regarding content-length here, some said it was added twice to requests, some were server-side etc. Was this fixed in 1.4.0? Is there any workaround that would make this work in 1.3.2? I've tried messing around with loglevel as mentioned in https://github.com/ktorio/ktor/issues/1690 to no avail. Also, transfer-encoding is NOT chunked, so it's not related to https://github.com/andrey-vasilyev/ktor/commit/d244d1ffb705e990b94950f108627b5774024b1d

**Comment by e5l** [comment]
Hey @sanchin, could you reopen the issue in YT?
