### ISSUE TITLE
Delegate some request to the servlet container

### ISSUE THREAD

**Issue by ian4hu** [ktorio/ktor#225]
In spring mvc, a `<mvc:default-servlet-handler />` means to delegate some resource request(like static content, JSP content) to a default servlet that built-in the servlet container.

can ktor support bellow to implement the function of `<mvc:default-servlet-handler />`

```kotlin
fun Application.module() {
    install(Routing) {
        get("/") {
            call.respondText("My Example Blog2", ContentType.Text.Html)
        }
        containerDefault("*.html") //delegate all html to the container(tomcat/jetty)
        containerDefault("/jsp/*.jsp") // delegate jsp in jsp to the container
        route("static") {
           containerDefault()
        }
    }
}
```

**Comment by cy6erGn0m** [comment]
This approach is not portable across containers so once you try to run in it netty - it will stop working. Why can't you use `static { }` instead of container delegation?

**Comment by orangy** [comment]
I think everything that is not handled is delegated back to container, no?

**Comment by ian4hu** [comment]
@orangy you are right.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-819">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
It looks like the problem is solved. Closed
