### ISSUE TITLE
Reuse Serialization from Server in Client

### ISSUE THREAD

**Issue by triplem** [ktorio/ktor#236]
On Server Side the Serialization is implemented in the ContentNegotiation Feature and additional Support "Features". To avoid any code duplication, it would be great if the same ContentConverter could be used in the client as well. 
This would IMHO also need a common module which is used in the client as well as the server.

**Comment by triplem** [comment]
I guess other used classes do fall in the same category, like Request, Response and ContentType, Header, ...

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-817">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Duplicates https://youtrack.jetbrains.com/issue/KTOR-1689.
