### ISSUE TITLE
Locations: Create a convention for creating no-value query parameters

### ISSUE THREAD

**Issue by mathiasbn** [ktorio/ktor#24]
If I want a URL to look like this:
`/?novalue`

The best I can come up with is:

```
@Location("/") class SomeLocation private constructor(val novalue:String){
    constructor():this("")
}
```

Which give:
`/?novalue=`

**Comment by orangy** [comment]
How about we instead allow to bind routes to paths like `/foo/bar?param=1` or `/foo/bar?novalue`? It would create a query parameter matching selectors at the end of the route chain.

**Comment by mathiasbn** [comment]
Could you give an example? How would you mark it no value?

**Comment by orangy** [comment]
Something like `@Location("/?novalue&value=1")`

**Comment by mathiasbn** [comment]
Well that could work for some scenarios. It could be annoying if you have 3 possible "novalue", and then need to express 8 different locations. But the again it's difficult to encode everything in the path. "I want novalue with '='", I want with '='", I want absent optionals to be like novalue ....

Perhaps it's just better to remove '=' at empty string? Then it's still dynamic.

This is not the most important issue in the world. It's just the representation of the URLs 

(Sorry for late reply. Was on vacation)

**Comment by e5l** [comment]
Migrated: https://youtrack.jetbrains.com/issue/KTOR-837
