### ISSUE TITLE
Getting dependencies via maven

### ISSUE THREAD

**Issue by awskii** [ktorio/ktor#241]
Hi. I'm new in java world. 
During my try to set up basic web server from Quick Start guide via maven got next error:
`Dependency 'io.ktor:ktor-server-netty:0.4.0 not found`
Changing ktor.version to 0.9.0-alpha-3 leads to new errors..

Building with gradle leads to the same issues.
All was configured in accordance with http://ktor.io/quickstart/index.html
and nothing works.

Kotlin 1.1.51
maven 3.5.2

**Comment by orangy** [comment]
Documentation is currently in transition from 0.4 to 0.9. Sorry for inconvenience, it should be ready next week.

**Comment by awskii** [comment]
so what i should do now?  Changing ktor version to 0.9 was not successful.

**Comment by orangy** [comment]
You can try to use 0.4.0 and replace `io.ktor` with `org.jetbrains.ktor` in dependencies and package names.

**Comment by awskii** [comment]
I tried :) But still not work: cant resolve repo. But seems like valid path is `http://dl.bintray.com/kotlin/ktor/org/jetbrains/ktor/ktor/0.4.0/` but i can do nothing (don't know right way to do it).

**Comment by orangy** [comment]
Try using mvn repository browsing tool: http://mvnrepository.com/artifact/org.jetbrains.ktor/ktor-jetty/0.4.0
I'm really sorry for this mixed state, it's in transition from one structure to another.

**Comment by awskii** [comment]
If the only thing what i should to do (as i understood) - add xml into pom and rebuild - there is no result.

**Comment by orangy** [comment]
It's hard to give specific advices without seeing the source code. You can try to look at some existing projects by searching github. E.g. some random link: https://github.com/wooky/catalog

**Comment by awskii** [comment]
Yeah, thanks, solution in #242 has helped. But now i'm truly interested in error in my case, so i create repo, please, if it's not hard for you, take a glance: https://github.com/awskii/kt-test

**Comment by orangy** [comment]
Well, you added two (ktor-specific) dependencies:
```
 <dependency>
            <groupId>org.jetbrains.ktor</groupId>
            <artifactId>ktor-jetty</artifactId>
            <version>0.4.0</version>
            <scope>test</scope>
  </dependency>
```
This is jetty-based server added to `test` scope, so you could only use it in tests.

The other one is
```
        <dependency>
            <groupId>org.jetbrains.ktor</groupId>
            <artifactId>ktor-server-netty</artifactId>
            <version>${ktor.version}</version>
        </dependency>
```
Which has artifactId from 0.9.0 version (ktor-server-netty), but everything else from 0.4.0, so it couldn't find it.

**Comment by awskii** [comment]
solved with change artifactId from `ktor-server-netty` to `ktor-netty`. Thank you.
