### ISSUE TITLE
Maven POM: some dependencies are in different repository then mentioned in documentation

### ISSUE THREAD

**Issue by thomasweitzel** [ktorio/ktor#244]
While I was switching to `0.9.0` from `0.4.0` (IntelliJ IDEA project) I found that a dependency was not found: `org.jetbrains.kotlinx:kotlin-io-jvm:0.0.6` that is a dependency from `io.ktor:ktor-server-tomcat:0.9.0` and other `io.ktor:ktor-server-...` components (it's a direct dependency from `org.jetbrains.kotlinx:kotlinx-coroutines-io:0.20-alpha-8`).

I found it in a repository that was not shown in the Maven POM on page [Quickstart Maven](http://ktor.io/quickstart/maven.html).

Adding the repository to the POM fixed the problem for me:
```
<repository>
    <id>kotlinx</id>
    <url>http://dl.bintray.com/kotlin/kotlinx</url>
</repository>
```
Edit: the missing repository is correctly shown on the page [Quickstart Gradle](http://ktor.io/quickstart/gradle.html).

**Comment by triplem** [comment]
I added a PR to the documentation. This PR adds the above mentioned repository to the Quickstart Maven Guide.

**Comment by cy6erGn0m** [comment]
Fixed, thanks @triplem
