### ISSUE TITLE
Issues with the hello world sample

### ISSUE THREAD

**Issue by laserallan** [ktorio/ktor#246]
I've tried running the hello world example from here http://ktor.io/quickstart/application.html and I get some strange results.

When using the netty server (as the example does) I get no response:
```
C:\Users\user> & 'C:\Program Files\Git\usr\bin\curl.exe' -L http://localhost:8080/ --connect-timeout 10
curl: (52) Empty reply from server

```
Note that this is a slightly different error compared to try using a port with no server:
```
C:\Users\user> & 'C:\Program Files\Git\usr\bin\curl.exe' -L http://localhost:8081/ --connect-timeout 10
curl: (7) Failed to connect to localhost port 8081: Connection timed out
```
I interpret this as something going on and there is code in the server being hit during the request but it never reaches the route for "/".
I've tried running it with and without firewall and I have tried hosting things on 8080 with other servers to make sure it's not something more fundamentally wrong with my device/setup.

When I try switching to Jetty (i.e import io.ktor.server.jetty.* and replace Netty with Jetty) I get a different response. It reaches the handler for my route to "/" but it gives this error: 
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 insufficient content written</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /. Reason:
<pre>    insufficient content written</pre></p>
</body>
</html>
```

The issue in that case seem to be related to the behavior in PipelineContext.kt:proceed where executeInterceptor seem to be invoked multiple times and BaseApplicationResponse.kt:pipeline throws ResponseAlreadySentException since responded gets set.

Anyone have any ideas of what I might be doing wrong?
I'm on ktor 0.9.0 on kotlin 1.1 running windows 10.

**Comment by aeronite** [comment]
I'm getting the exactly the same problem with ktor 0.9.0, kotlin 1.1 on Linux Mint 17.3

**Comment by triplem** [comment]
I have copied the Final build.gradle from the quickstart, copied the self-hosted application from the quickstart and start the application via IntelliJ Run Command on the Test.kt (that is how I named my application file). 
Everything is working fine. 

How do you start the application? Have you configured anything "specific" to your system?

**Comment by orangy** [comment]
Can you post logs from the server with exceptions?

**Comment by aeronite** [comment]
I had set up the hello world using maven and not gradle, not sure what the issue was however I've swapped to gradle since your documentation is better there and now it works!
BTW - is gradle generally recommened over maven for Kotlin?

**Comment by triplem** [comment]
I guess that this should be fixed by ktorio/ktorio.github.io#20.

**Comment by aeronite** [comment]
awesome, thanks!

**Comment by cy6erGn0m** [comment]
@aeronite could you please confirm that it is fixed now?

**Comment by aeronite** [comment]
Yes, just swapped back to Maven now and everything works.
Many thanks!
