### ISSUE TITLE
Exceptions in WriterContent body are not logged

### ISSUE THREAD

**Issue by fluidsonic** [ktorio/ktor#247]
When an exception occurs within the body of a `WriteContent` response then Ktor simply closes the connection, which leads for example to an `ERR_INCOMPLETE_CHUNKED_ENCODING` error in Chrome.

**Actual behavior:**
Ktor doesn't log the exception anywhere so the developer must guess what has caused the connection abort.

**Expected behavior:**
Ktor should log the exception.

**Comment by cy6erGn0m** [comment]
Fixed in master

**Comment by cy6erGn0m** [comment]
available in 0.9.1-alpha-5
