### ISSUE TITLE
Gradle Ktor Build Fails - Gradle Version Documentation Issue

### ISSUE THREAD

**Issue by amimimor** [ktorio/ktor#248]
IMHO , the issue is a result of *lacking documentation* (or lacking search skills on my behalf)

The issue described below comes from using gradle version <4.0; The issue is *resolved* after an update to gradle 4.3

I think there is no 'build from source' instructions/documentation and there is no mentioning of a minimal gradle version, these could be of use

### Setup:
Fresh ktor clone
Oracle Java 1.8.121
Gradle 3.5
MacOS 10.12.3

### Result:
```
* Where:
Build file '/Users/amitmor/Projects/kotlin/ktor/ktor-server/ktor-server-benchmarks/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'me.champeau.gradle.jmh', version: '0.4.4']
> Failed to apply plugin [id 'me.champeau.gradle.jmh']
   > Could not generate a proxy class for class me.champeau.gradle.JMHPluginExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by cy6erGn0m** [comment]
Gradle wrapper need to be used instead: `./gradlew`

**Comment by amimimor** [comment]
FWIW, a more elegant approach than committing the gradlew script into the repo is to add the  [https://docs.gradle.org/current/userguide/wrapper_plugin.html](gradle wrapper plugin) into the build.gradle file, because the actual script is kind of orthogonal to the content of the repo. And as tagged, it is basically a documentation issue (that took more than a couple of minutes for me to resolve)

**Comment by soywiz** [comment]
This recently added page should address the issue: https://ktor.io/advanced/building-from-source.html
