### ISSUE TITLE
Write typesafe js functions (kotlin2js) directly in ktor html builder.

### ISSUE THREAD

**Issue by up-to-you** [ktorio/ktor#249]
Hi guys! You are doing incredible art !!!
I have your simple backend sample with typesafe html builder :
```
fun main(args: Array<String>) {
    val html = createHTML().html {
            head {
                title {+"XML encoding with Kotlin"}
            }
            body {
                h1 {+"XML encoding with Kotlin"}
                p  {+"this format can be used as an alternative markup to XML"}
                a(href = "http://kotlinlang.org") {+"Kotlin"}
                
                // WORK
                button {
                    onClick = "window.alert(something)"
                }
                // DOESN'T WORK
                div {
                    onClickFunction = {
                        _ -> println("super")
                    }
                }
            }
    }
    embeddedServer(Netty, 8080) {
        routing {
            get("/") {
                call.respondText(html, ContentType.Text.Html)
            }
        }
    }.start(wait = true)
}
```

and i want to ask for this snippet :

```
// DOESN'T WORK
                div {
                    onClickFunction = {
                        _ -> println("super")
                    }
                }
```

Are there any plans to involve typesafe js writing using kotlin on backed (for html builder)?
Or do i missing something ?
The main problem i think, that many backend developers don't want to even touch js, and ktor will be the rescue.

**P.s. i know that there is kotlin2js plugin and i can separate modules for FE and BE, but my purpose is to build html exclusively on backend with some simple js (using kotlin) logic.

**Comment by orangy** [comment]
Thanks for your kind words. Right now it is not possible to mix JVM & JS code in the same source file. Check http://kweb.io/ or https://vaadin.com/
