### ISSUE TITLE
Locations: Support trailing /

### ISSUE THREAD

**Issue by mathiasbn** [ktorio/ktor#25]
At the moment you cannot create hrefs from a location with trailing /:
`/somepath/` as it would end up being `/somepath`

This should of cause also work for nested Locations, so i could do:

```
@location("/somepath/") class SomeLocation{
    @location("/nested/") class Nested
}
```

and get `/somepath/`and `/somepath/nested/`

**Comment by gzoritchak** [comment]
I agree. Having the trailing / or not is considered as two different urls. It could serve (even if it is not recommended) 2 different contents.

I have the same problem as @mathiasbn. An older website I plan to migrate have urls with the trailing /. It would be easier to do the migration with locations managing it.

**Comment by hhariri** [comment]
For follow-ups to this issue, please see https://youtrack.jetbrains.com/issue/KTOR-836

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-836">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
