### ISSUE TITLE
responseChannel() is always setChunked as true

### ISSUE THREAD

**Issue by xxxifan** [ktorio/ktor#250]
Version: 0.9.0
Engine: Netty

I try to write a function to respond a LocalFileContent to download files and I found that the header is returning `Transfer-Encoding=chunked` and no content-length so that I can't get download size to show progress, I trace to here:

NettyHttp1ApplicationResponse chunked = true
```
    override fun responseMessage(chunked: Boolean, last: Boolean): Any {
        val responseMessage = DefaultHttpResponse(protocol, responseStatus, responseHeaders)
        if (chunked) {
            setChunked(responseMessage)
        }
        return responseMessage
    }
```

NettyApplicationResponse
```
    protected final fun sendResponse(chunked: Boolean = true, content: ByteReadChannel) {
        if (!responseMessageSent) {
            responseChannel = content
            responseMessage.complete(responseMessage(chunked, content.isClosedForRead))
            responseMessageSent = true
        }
    }
```

and the responseMessage() method is using a default value 
```
override suspend fun responseChannel(): WriteChannel {
        val channel = ByteChannel()
        sendResponse(content = channel)
        return CIOWriteChannelAdapter(channel)
    }
```

so when it use responseChannel setChunked is always true and I don't know how to disable it. Though LocalFileContent has appended a Content-Length

**Comment by cy6erGn0m** [comment]
This is what Netty does by default. See https://github.com/netty/netty/blob/8618a3351cbecc68562c06c409538b182077f8d9/codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java#L329

Perhaps we have to set up transfer encoding by simply adding header rather than using this utility method.

**Comment by orangy** [comment]
Well, no… https://www.ietf.org/rfc/rfc2616.txt
> Messages MUST NOT include both a Content-Length header field and a non-identity transfer-coding. If the message does include a non-identity transfer-coding, the Content-Length MUST be ignored.

We might need to be able to disable chunked, if specified by user.

**Comment by xxxifan** [comment]
@cy6erGn0m yes, it removed Content-Length if chunked is true, but this method sendResponse() calling in responseChannel() does not specified whether chunked is true or false, so it always is true.

**Comment by e5l** [comment]
Fixed here https://github.com/ktorio/ktor/commit/62541f8c8eebdd482e831e3096b2cafa679dda07
