### ISSUE TITLE
http://ktor.io/samples/index.html

### ISSUE THREAD

**Issue by gedenata** [ktorio/ktor#252]
Please check the web. It's still blink-blink mode. Thanks

**Comment by orangy** [comment]
What does it mean "blink-blink"? Not sure I understand the issue.

**Comment by gedenata** [comment]
When I open that website then scroll down  my screen directly blink

**Comment by soywiz** [comment]
I can't reproduce it. Does this still happens to you? Can you provide more details like: which browser, operating system, resolution are you using? A screenshot or small video reproducing the problem would help too. Thanks!

**Comment by soywiz** [comment]
I was able to reproduce it in pages with a long left column and a short right column. For now I have disabled the javascript for keeping fixed the left column, until a proper layout is working.
