### ISSUE TITLE
ktor-samples-gson/build.gradle -> unresolved reference: gson?

### ISSUE THREAD

**Issue by firstgid** [ktorio/ktor#254]
actually build.gradle contains following dependencies, which doesn't work for me
`dependencies {
    compile project(':ktor-features:ktor-gson')
}`
but I found and added to my dependencies this line`compile "io.ktor:ktor-gson:$ktor_version"` and project works quite well. 
I'm doing something wrong or it's a bug?

**Comment by orangy** [comment]
You replaced module reference with binary reference, which is what should work for standalone project, but is not right for a module in a ktor project itself. Are you trying to build from the sample's folder instead of the ktor root folder?

**Comment by firstgid** [comment]
I tried build from standalone blank project. Today I tried build from root folder and everything works. Thx for help.
