### ISSUE TITLE
Invalid hex byte exception when decoding invalid query string

### ISSUE THREAD

**Issue by rlerch** [ktorio/ktor#2559]
Hello All,

A get request with a malformed query string causes a 500 error with the message 
`invalid hex byte 's%' at index 3 of '/?%s%'`

Steps to reproduce,

- Start a ktor server.
- Navigate to http://localhost:2000/?%s%
- Server than returns 500

Expected Behavior

Server returns 400 Bad Request

**Comment by Stexxe** [comment]
@rlerch unfortunately, I cannot reproduce this error. Could you please share a code snippet and tell me what version of Ktor do you use?

**Comment by Stexxe** [comment]
Thank you for creating the [YT issue](https://youtrack.jetbrains.com/issue/KTOR-2934).
