### ISSUE TITLE
parameters in the builder is not configurable

### ISSUE THREAD

**Issue by fabiel-casas** [ktorio/ktor#2566]
The parameter variable of the builder is not configurable, does this intended?
https://github.com/ktorio/ktor/blob/b519016210d5ced5f63b6da9a3489e3a799903b1/ktor-http/common/src/io/ktor/http/URLBuilder.kt#L32

**Comment by Stexxe** [comment]
That's intended. You are supposed to mutate (append, set, remove) parameters but not change a reference.
So, for example, if you want a URL with fresh new parameters then you can remove all of them at once  and append new ones:
```kt
val builder = URLBuilder() // A builder could've been retrieved from somewhere
builder.parameters.clear()
builder.parameters.append("name", "value")
println(builder.buildString())
```
