### ISSUE TITLE
Locations, POST with parameters ->404

### ISSUE THREAD

**Issue by MaxHogervorst** [ktorio/ktor#258]
i have the following code:

`@location("/test")
data class Test(val id: Int)

fun Route.members() {
    post<Test> { test ->
        call.respond(test)
    }
}`

When I do a post requeest with postman it returns a 404, however if change Test to a class without paramaters it works. Am i passing the parameters wrong in postman?

I've tried form-data x-www and raw with json

**Comment by cy6erGn0m** [comment]
Locations does only work with query parameters but not with post parameters. Since you have `id` specified with no default value then it requires `id` query parameters to be set. The other alternative is to set it in url pattern

```
@location("/test/{id}")
data class Test(val id: Int)
```

To get post parameters use `call.receice<ValuesMap>()` instead
