### ISSUE TITLE
Cookie's path can be controlled for creation, but not for deletion

### ISSUE THREAD

**Issue by thomasweitzel** [ktorio/ktor#259]
In order to delete a cookie you've to use the same path that is stored with the cookie on the client browser. Ktor let us control the path with cookie creation. Here's an example configuration:

    install(Sessions) {
        cookie<MySession>(sessionMarker) {
            cookie.duration = cookieDuration
            cookie.path = "/myWebapp"
            transform(SessionTransportTransformerMessageAuthentication(sessionKey))
        }
    }

On the login page `/myWebapp/page/login`, the cookie is created:

    call.sessions.set(MySession([some arguments]))

The cookie shows the path `/myWebapp` when inspected on the client. The default would be `/myWebapp/page` because that's the path of the login page, but the path is taken from the cookie configuration shown above.

Eventually the user wants to log out via a request to the login page:

    call.sessions.clear<MySession>()

There's no way of controlling the cookie's path here. Because the login page `/myWebapp/page/login` is sending the expired cookie back to the client for another path (its own `/myWebapp/page`), the original cookie is not deleted (`/myWebapp/page` != `/myWebapp`).

**Edit**: I would expect that the call to `clear()` uses the same path that was used for the cookie's creation.

**Comment by noncom** [comment]
I got into this problem too. How are you supposed to work with user sessions implemented via cookies when there is such a problem? I can't get it to work, the pages continue sending outdated session cookies whatever I do, breaking down my websiet. Please help! I would appreciate a workaround while this is still being not fixed.
