### ISSUE TITLE
Ktor works fine in Intellij but not on command line

### ISSUE THREAD

**Issue by precisemath** [ktorio/ktor#2590]
version=1.6.3
Java version=Open JDK 1.8
build tool = gradle

I setup the latest version of Ktor using the plugin in Intellij. It works fine when I run it and debug it in Intellij.
We then built a fat jar and ran it on the command line like this:

`java -jar run.jar`

It even prints this statement on the command line:

`Responding at http://0.0.0.0:8080`

But the server is not accessible via curl or browser or postman.

By downgrading to Ktor 1.5.4, the fat jar works perfectly fine!

**Comment by e5l** [comment]
Hey @precisemath, the issues on GitHub are closed cause they are hard to manage and plan. Please consider reopening this issue on YT: https://github.com/ktorio/ktor/issues/new/choose
