### ISSUE TITLE
Project 'tomcat-war' not found in root project

### ISSUE THREAD

**Issue by amirhossein320** [ktorio/ktor#2596]
Hi,  I receive below error  when  run app grrety tomcat war (**./gradlew :tomcat-war:run**)

```
org.gradle.execution.taskpath.ProjectFinderByTaskPath$ProjectLookupException: Project 'tomcat-war' not found in root project 'ktor-sample'.
```

**application.kt**

```
fun Application.module(testing: Boolean = false) {
    routing {
        get{
            call.respond("Hello World")
        }
    }
}
```

**web.app**
```
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         version="3.0">
   <servlet>
        <display-name>KtorServlet</display-name>
        <servlet-name>KtorServlet</servlet-name>
        <servlet-class>io.ktor.server.servlet.ServletApplicationEngine</servlet-class>
        <init-param>
            <param-name>io.ktor.ktor.config</param-name>
            <param-value>application.conf</param-value>
        </init-param>
        <async-supported>true</async-supported>
    </servlet>
<servlet-mapping>
        <servlet-name>KtorServlet</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>
</web-app>
```

**application.conf**
```
ktor{
    deployment {
        port = 8080
    }
    application{
        modules = [
        com.example.ApplicationKt.module
        ]
    }
}
```

**build.gardle.kts**
```
import java.net.InetAddress.getByName
val ktor_version: String by project
val kotlin_version: String by project
val logback_version: String by project

plugins {
    application
    kotlin("jvm") version "1.5.30"
    id("org.jetbrains.kotlin.plugin.serialization") version "1.5.30"
    id("org.gretty") version "3.0.6"
    id("war")
}
group = "com.example"
version = "0.0.1"

afterEvaluate {
    tasks.getByName("run") {
        dependsOn("appRun")
    }
}
application {
    mainClass.set("com.example.ApplicationKt")
}
gretty {
    servletContainer = "tomcat9"
    contextPath = "/"
    logbackConfigFile = "src/main/resources/logback.xml"
}
repositories {
    mavenCentral()
}
dependencies {
    implementation("io.ktor:ktor-server-core:$ktor_version")
    implementation("io.ktor:ktor-auth:$ktor_version")
    implementation("io.ktor:ktor-auth-jwt:$ktor_version")
    implementation("io.ktor:ktor-server-host-common:$ktor_version")
    implementation("io.ktor:ktor-serialization:$ktor_version")
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("io.ktor:ktor-server-tomcat:$ktor_version")
    implementation("ch.qos.logback:logback-classic:$logback_version")
    testImplementation("io.ktor:ktor-server-tests:$ktor_version")
    testImplementation("org.jetbrains.kotlin:kotlin-test:$kotlin_version")
    implementation("io.ktor:ktor-server-servlet:$ktor_version")
}
```

**Comment by Stexxe** [comment]
@amirhossein320 If you took code from https://github.com/ktorio/ktor-documentation/tree/main/codeSnippets/snippets/tomcat-war then you should have a Gradle subproject named `tomcat-war` to run it this way, otherwise just run it via `./gradlew run`.

**Comment by amirhossein320** [comment]
> @amirhossein320 If you took code from https://github.com/ktorio/ktor-documentation/tree/main/codeSnippets/snippets/tomcat-war then you should have a Gradle subproject named `tomcat-war` to run it this way, otherwise just run it via `./gradlew run`.

**Comment by amirhossein320** [comment]
> @amirhossein320 If you took code from https://github.com/ktorio/ktor-documentation/tree/main/codeSnippets/snippets/tomcat-war then you should have a Gradle subproject named `tomcat-war` to run it this way, otherwise just run it via `./gradlew run`.


I watched it. but i`m begginer and i don`t know how create gardle subproject.
please help me to solve it

**Comment by Stexxe** [comment]
I suggest reading https://docs.gradle.org/current/userguide/multi_project_builds.html but you don't need to have a subproject in this case so just run it via `./gradlew run`.

**Comment by amirhossein320** [comment]
> I suggest reading https://docs.gradle.org/current/userguide/multi_project_builds.html but you don't need to have a subproject in this case so just run it via `./gradlew run`.

thank you i solve the problem of subproject but now i receive the error about not found task run.
in your sample project use groovy gradle but i use gardle and cant convert run task to it

**Comment by Stexxe** [comment]
If you use the `org.gretty` Gradle plugin then you can run your application via `./gradlew tomcatStart`.
