### ISSUE TITLE
Location parameters with invalid kotlin names

### ISSUE THREAD

**Issue by spand** [ktorio/ktor#260]
We have had to modify the `Locations` code in order for it support query parameters with names that are not allowed in Kotlin. It seems this has been considered but it remains unimplemented in the current version.

I propose the following for adding such a feature:
```
@Location
data class SunshineCase(@Name("foo.bar") val fooBar: String)
```
But in order to not duplicate standard parameter names on all locations something like this could be useful to support:
```
interface OpenId {
	@Name("openid.ns") val openIdNs: String
// ... more here
}

@Location
data class PageWithOpenId(override val openIdNs: String, val baz: String) : OpenId
```

I suggest the precedence should then be the following: 
1. `@Name` on the parameter
2. `@Name` on the corresponding property from any super type (maybe error if multiple are found)
3. name of the parameter.

Thoughts?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-813">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
