### ISSUE TITLE
Static content in fat jar

### ISSUE THREAD

**Issue by coolemza** [ktorio/ktor#262]
how to serve static content from fat jar? if im using fat jar to deploy ktor app then my rosources folder zipped into jar and i need to setup static routing to jar, i tried this way like i do with embedded jetty:

static("static") {,
  val resPath = Thread.currentThread().contextClassLoader.getResource("public").toExternalForm().substringAfter("file:")
  staticRootFolder = File(resPath)
  file("rut.css")
}

it works if i debug/run it under Intellij IDEA, but doesnt work in fat jar

Is it possible with ktor? Or may be some workarounds to deploy static contents would be greatly apreciated

**Comment by orangy** [comment]
Sure, use `resource` function instead of `file` if you want to serve embedded resources.

**Comment by coolemza** [comment]
ty, it works
