### ISSUE TITLE
I have the same exception in version 1.6.2.

### ISSUE THREAD

**Issue by zhaolongqing** [ktorio/ktor#2621]
I have the same exception in version 1.6.2.
![image](https://user-images.githubusercontent.com/29787804/135187264-5fa3afd8-97f5-4a1e-a768-178e9e0b9994.png)
![image](https://user-images.githubusercontent.com/29787804/135187320-0d7d58b8-90c4-4820-b4f7-db9c1dadf624.png)

_Originally posted by @zhaolongqing in https://github.com/ktorio/ktor/issues/813#issuecomment-929746276_

**Comment by zhaolongqing** [comment]
Probably, I mybe know why I try catch the exception。Because when I call  same methods "socket.send" in the same time, it report error, when I call one method "socket.send" and until the method complete,I didn't see the error. Is that rigtht?
if rigtht ,can you create a safe thead medthod to wrap "writeStringUtf8 ".

**Comment by e5l** [comment]
Hey @zhaolongqing, the issues on GitHub are closed cause they are hard to manage and plan. Please consider reopen this issue on YT: https://github.com/ktorio/ktor/issues/new/choose
