### ISSUE TITLE
Is it possible to change port base on arguments when using .conf?

### ISSUE THREAD

**Issue by joshuaavalon** [ktorio/ktor#264]
If I use `embeddedServer`, I can 

```kotlin
fun main(args: Array<String>) {
    val config = parseOptions(args)
    embeddedServer(Netty, config.port) {
        routing {
            get("/") {
                call.respondText("My Example Blog", ContentType.Text.Html)
            }
        }
    }.start(wait = true)
}
```

However, is it possible to do with `application.conf`?

```
ktor {
    deployment {
        port = 8080
    }

    application {
        modules = [ blog.BlogAppKt.main ]
    }
}
```

**Comment by thomasweitzel** [comment]
Sure, but this is a how-to question and shouldn't be asked here. Neither should I answer it here ;-). See [Standard Behavior](https://github.com/lightbend/config#standard-behavior) for details.
```
import com.typesafe.config.Config
import com.typesafe.config.ConfigFactory

val config: Config = ConfigFactory.load()
val port: Int = config.getInt("ktor.deployment.port")

embeddedServer(Netty, port) // ...
```

**Comment by joshuaavalon** [comment]
@thomasweitzel I asked here because I cannot found documentation  on ktor.io or found or how to do it in the source code. I will take a look on the article. Thanks.

**Comment by orangy** [comment]
The question is entirely valid and an example is there in `embedded` sample, including custom name and location for the config file.

**Comment by thomasweitzel** [comment]
Oh, then I'm very sorry for writing that! I was probably due to my too narrow interpretation of the word "issues". My fault.

**Comment by orangy** [comment]
No problem, @thomasweitzel :) Issue is, well, when someone has an issue – being it because of lack of documentation, unclear API, bad samples, or bug or missing feature in the system.
