### ISSUE TITLE
Minor tweak to docs

### ISSUE THREAD

**Issue by kgilmer** [ktorio/ktor#267]
I do not see the docs as a project here so just putting the change in the issue.

On page: http://ktor.io/servers/application

From: "Installing interceptor into pipeline is the primary..."
To: "Installing an interceptor into the pipeline is the primary..."

**Comment by goreRatzete** [comment]
Here is the rep: https://github.com/ktorio/ktorio.github.io

**Comment by kgilmer** [comment]
From https://github.com/ktorio/ktor/issues/267

**Comment by kgilmer** [comment]
Opened PR, no need for this issue.
