### ISSUE TITLE
Don't force trustAll on JettyHttp2Backend

### ISSUE THREAD

**Issue by dansanduleac** [ktorio/ktor#272]
https://github.com/ktorio/ktor/blob/0.9.0/ktor-client/ktor-client-jetty/src/io/ktor/client/backend/jetty/JettyHttp2Backend.kt#L23

This should be configurable instead, otherwise this class is unusable in production.

**Comment by e5l** [comment]
done https://github.com/ktorio/ktor/commit/fa975ea016ffc590c419c6a6a0a7cdc3539d4191
