### ISSUE TITLE
Ktor performance improvements

### ISSUE THREAD

**Issue by qwwdfsad** [ktorio/ktor#275]
Out of curiosity I've made small profiling session of ktor via `FullBenchmark.kt`, but added query string and its parsing (to emulate more realistic workload).

CPU profile: http://svgshare.com/i/4XN.svg
Allocation profile: http://svgshare.com/i/4X_.svg (note that this one may be inaccurate due to profile method skew)

Observations:
1) Query string parsing is dominating CPU consumer. 
E.g. for comparison two OK methods, one without query string and one with medium-size one (~80 characters):
```
Benchmark                      Mode  Cnt  Score   Error  Units
FullBenchmark.sayOK            avgt   10  3.507 ± 0.062  us/op
FullBenchmark.sayOKLongParams  avgt   10  5.783 ± 1.286  us/op
```
It can be simply optimized (pre-size `ValuesMap`, don't use lazy filtering sequences for splitting, etc.)

2) Most of lazy properties shouldn't be thread-safe (`SynchronizedLazyImpl` -> `UnsafeLazyImpl`). It's specific for `TestApplicationRequest` and `TestApplicationResponse`, but I've seen this in real request/response classes (e.g. in netty)
3) Headers, probably, shouldn't be lazy at all neither in request nor in response, because they are always required and read.

4) `Pipeline#merge` is implemented in non-trivial (for me) way:
```
val interceptors = ArrayList<PipelineInterceptor<TSubject, TContext>>(fromContent.interceptors.size)
interceptors.fastAddAll(fromContent.interceptors)
```
where `fastAddAll` ensures capacity and adds element one by one, where each `add` ensures capacity on its own.
Why is it better than 
```
val interceptors = ArrayList<PipelineInterceptor<TSubject, TContext>>(fromContent.interceptors)
```
?
It's rather about code style, than performance though

5) `ValuesMap#ensureListForKey` (~15% of CPU) may be implemented via `computeIfAbsent`, though it's should be measured first.

If you think these issues are valid I don't mind to fix them

**Comment by orangy** [comment]
Thanks! I would like to get these measurements myself, could you please send a PR with benchmarking code first?

**Comment by qwwdfsad** [comment]
Sure: https://gist.github.com/qwwdfsad/89ad7b709afcbd2880374c36f0dee424
It's `FullBenchmark.kt` ran in an infinite loop.
For profiling I've used async-profiler and cleaned up traces a bit (from test and JMH infrastructure via `grep "kotlinx/coroutines/experimental/BuildersKt.runBlocking" ...`)

**Comment by orangy** [comment]
Thanks. Small note, benchmarks infra can do better:

```
    benchmark(args) {
        threads = 1
        iterations = 10000
        run<FullBenchmark>("sayOKLongParams")
    }
```

Instead of manually commenting annotations and modifying constants.

**Comment by orangy** [comment]
I've pushed some optimizations, new tests for query parsing and some benchmark infra fixes to be able to run IntegrationBenchmark (with real servers). Please test it on your machine and tell us back if it helps. Thanks for your input!

**Comment by orangy** [comment]
Optimizations are merged into `master`

**Comment by orangy** [comment]
> Headers, probably, shouldn't be lazy at all neither in request nor in response, because they are always required and read.

This is not necessary true. On request, routing can instantly find there is nothing to serve and respond with 404 without inspecting headers. On response, it's a lot more complex because of content transformations, e.g. if you serve a file and it's gzipped and then conditional-headers-controlled, it might not need to generate original headers at all.

**Comment by qwwdfsad** [comment]
Yep, it's become _way_ faster if compare from branch!
New profile: https://screencast.com/t/i9joQC9rn0D
~30% is now `Pipeline#merge` and ~15% is coroutines overhead

But in master there is 4bdbe0d41326120447b2f98306f066db1e00d35e (not sure if I spotted right commit) which invalidates all previous results, now test spends most of the time in byte buffer instantiation: https://screencast.com/t/Lfm8PcDs

**Comment by e5l** [comment]
Allocation problem is fixed here https://github.com/ktorio/ktor/commit/2535bd626ffcb56e5ec01accafdce82efd318ac3, but main problem was in grep filter:
`grep "kotlinx/coroutines/experimental/BuildersKt.runBlocking"`(there is no runBlocking in TestApplicationEngine)

**Comment by qwwdfsad** [comment]
Thanks, I will close this issue.
FYI this session revealed https://youtrack.jetbrains.com/issue/KT-22042
