### ISSUE TITLE
Responding with an html resource

### ISSUE THREAD

**Issue by byersw** [ktorio/ktor#278]
Hi everyone! Quick question. I'd like to know if there's a better way to do this. I just want to return an html resource when a 404 happens.

```
install(StatusPages) {
    status(HttpStatusCode.NotFound) {
        val html = Thread.currentThread().contextClassLoader.getResource("missing.html").readText()
        call.respondText(html, ContentType.Text.Html, HttpStatusCode.NotFound)
    }
}
```

Is there anything like the following? Something that maybe caches the resource if its not already being cahced. 
```
call.respondResource("missing.html", ContentType.Text.Html, HttpStatusCode.NotFound)
```
How would you guys implement something like this? I'm not terribly familiar with java resources and how they work. I'm coming from a dotnet background. Any obvious gotchyas?

**Comment by orangy** [comment]
```
            application.install(StatusPages) {
                statusFile(HttpStatusCode.NotFound, filePattern = "error#.html")
            }
```
Will serve `error404.html` from resources

**Comment by byersw** [comment]
That makes it easy. Thanks!
