### ISSUE TITLE
How can a REST endpoint receive JSON

### ISSUE THREAD

**Issue by tucamsam** [ktorio/ktor#282]
I've got this code (using version 0.9.0):
```
@location("/submit") data class UserSubmit(val id: String, val name: String, val age: Int)
fun Route.submit() {
    post<UserSubmit> {
        // other stuff that would use UserSubmit object
        call.respondText("User submitted", ContentType.Text.Html)
    }
}
```
This is my application definition:
```
fun Application.main() {
    install(DefaultHeaders)
    install(CallLogging)
    install(Locations)
    install(ContentNegotiation) {
        gson {
            setDateFormat(DateFormat.LONG)
            setPrettyPrinting()
        }
    }
    install(Routing) {
        submit()
        retrieve()
    }
}
```
When I add the attributes as query parameters, it seems to work fine, but when I submit them as JSON in the body of the request, it says that the request was unhandled.

Is there some additional configuration I need to do to make this endpoint handle json?

**Comment by tucamsam** [comment]
Turns out changing the code to this worked:
```
post("/submit") {
        val sub = call.receive<UserSubmit>()
```
Is this the only way to receive a json payload through a rest endpoint?

**Comment by orangy** [comment]
Locations are designed to be round-trip, so that you can create an URL from a location object. They are describing endpoints, not payload. Using `receive` is a proper way of getting to payload.
