### ISSUE TITLE
Override options in application.conf via CMD parameters

### ISSUE THREAD

**Issue by GinoHereIam** [ktorio/ktor#284]
Hi together,

is it possible to override the options in the application.conf via CMD parameters? For e.g. the port?
Right now I can only put a static port in my config, but I would like to be able to change the port from outside either. (Not pleasure to build all time a new Jar with different config. :x) 

I read the embedded sample should solve this issue, but I don't see there how to pass the right parameter there: ` -Dktor.port=8080` 

I solved by reading the gradle.build file, so for anyone else with same issue:
`java -jar your.jar -config=/path/to/your/application.conf`

Best Regards
Gino

**Comment by orangy** [comment]
You can also use substitutions from environment variables, see HOCON docs: https://github.com/lightbend/config
