### ISSUE TITLE
http://ktor.io/quickstart/intellij-idea.html needs to highlight the 'set up the build files' section.

### ISSUE THREAD

**Issue by sleekweasel** [ktorio/ktor#287]
It would have saved me quite a lot of time if the ktor intellij quick-start guide made 'set up the build files' a significant, headline-level point, instead of whispering about it.

There doesn't seem to be a contact for ktor.io, so perhaps someone here who knows about it could suggest it to them? A quick start guide isn't supposed to be an obstacle course!

**Comment by goreRatzete** [comment]
This is the official repository for the ktor.io website: https://github.com/ktorio/ktorio.github.io

You can open an issue / submit a pull request there. 
Please close this one afterwards.

**Comment by orangy** [comment]
Moved to https://github.com/ktorio/ktorio.github.io/issues/46
