### ISSUE TITLE
DefaultRequest Plugin - InvalidMutabilityException When Changing Anything Except Protocol - 2.0.0-beta-1 on iOS

### ISSUE THREAD

**Issue by codesplode** [ktorio/ktor#2875]
I have been following the updates to remove InvalidMutabilityExceptions on iOS and have upgrade my app to 2.0.0-beta-1 because of the beneficial changes to the API and stability for our testing.

When using the DefaultRequest plugin with any one of the commented out lines active, an InvalidMutabilityException similar to all the past issues occurs. I am including the entire client configuration for completeness.

```kotlin
val client = HttpClient {
	install(DefaultRequest)

        install(ContentNegotiation) {
            json(Json {
                isLenient = false
		encodeDefaults = true
                ignoreUnknownKeys = true
            })
        }

        if (isDevelopment) {
            install(Logging) {
                logger = Logger.SIMPLE
                level = LogLevel.ALL
            }
        }

	/*
	 * Default request settings only if a relative url path is defined (host is blank).
	 */
	defaultRequest {
		if (host.isBlank()) {
			//url("https://${if (isDevelopment) DEV_DOMAIN else LIVE_DOMAIN}/$basePath/")
			url {
				protocol = URLProtocol.HTTPS
				//host = if (isDevelopment) DEV_DOMAIN else LIVE_DOMAIN
				//path("$basePath/")
			}

			//log.i("Default Request : ${url.protocol.name}://${url.host}${url.encodedPath}")
		}
	}
}
```
Example of Exception
```
Error(error=kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen ...@1f049c8)
```

This functionality works perfectly on Android.

I am happy to assist in debugging if there are any ideas. As a workaround, we have exposed a protected baseUrl computed property and used that in all of our many API subclasses and it works correctly.

**Comment by Stexxe** [comment]
This error is absent with a new memory model enabled (`kotlin.native.binary.memoryModel=experimental` in Gradle) and with Ktor EAP version, like `2.0.0-eap-329`, that is released after the beta. To download Ktor artifacts you have to include the following repositories:
```
maven { url "https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven" }
maven { url "https://maven.pkg.jetbrains.space/public/p/ktor/eap" }
```
