### ISSUE TITLE
Update coroutines dependency

### ISSUE THREAD

**Issue by egorzhdan** [ktorio/ktor#289]
The latest release, as well as master, use alpha versions of `kotlinx.coroutines`, and if a project depends on Ktor and some other library using coroutines, there'll probably be some issues.

In fact, when I tried using Ktor with another library depending on`kotlinx.coroutines 0.21`, WebSockets were broken (there was an exception on application launch).

**Comment by orangy** [comment]
I think this is solved?

**Comment by egorzhdan** [comment]
Yes, it uses up-to-date version now, thanks!
