### ISSUE TITLE
Ktor server :: not working when application in background Android API 21 (5.0+)

### ISSUE THREAD

**Issue by kambojumang** [ktorio/ktor#2923]
I have followed this link  **Example Netty-based Ktor server for Android 5+** 

https://github.com/gnarea/minimal-ktor-server-android 
 
Finding a way the **application can work even in the background for Android 5+ Api level 21**
 
Please help me **I have already created an entire project just stuck on API level 21.**

Code snipped:: 

class MainActivity : AppCompatActivity() {
    private val coroutineContext = Dispatchers.IO

    private val logger = Logger.getLogger("KtorServer")

    private val server by lazy {
        embeddedServer(Netty, 13276, watchPaths = emptyList()) {
            install(WebSockets)
            install(CallLogging)

            routing {
                get("/") {
                    call.respondText("All good here in ${Build.MODEL}", ContentType.Text.Plain)
                }

                webSocket("/ws") {
                    logger.info("Sending message to client...")
                    send("foo")

                    val receivedMessage = incoming.receive()
                    val messageFormatted = if (receivedMessage.frameType == FrameType.TEXT) {
                        receivedMessage.readBytes().toString(Charset.defaultCharset())
                    } else {
                        "<non-text frame>"
                    }
                    logger.info("Got message from client: $messageFormatted")

                    logger.info("Closing connection...")
                    close()
                }
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        CoroutineScope(coroutineContext).launch {
            logger.info("Starting server...")
            server.start(wait = true)
        }
    }

Is there any way please help or let me know if it is not even possible.
Thanks and Regards
Umang Kamboj

**Comment by e5l** [comment]
Hey @kambojumang, thanks for the report. Github issues are closed in Ktor, please consider reopening the issue on YT
