### ISSUE TITLE
Upgrade Netty and Jetty

### ISSUE THREAD

**Issue by goreRatzete** [ktorio/ktor#293]
There are new versions of Netty and Jetty available. Might be worth considering an upgrade before the next release. 

Artifact | Project Version | Latest Version
------------ | ------------- | -------------
Netty | 4.1.12.Final | 4.1.19.Final 
Netty_tcnative | 2.0.5.Final | 2.0.7.Final 
Jetty | 9.4.6.v20170531 | 9.4.8.v20171121
jetty_alpn_boot | 8.1.11.v20170118 | 8.1.12.v20180117

**Comment by orangy** [comment]
Yes, that's we are going to do. Netty changed APIs regarding HTTP/2, so it requires some work.

**Comment by cy6erGn0m** [comment]
Note that jetty_alpn_boot version shouldn't be rolled as it depends on JDK version
