### ISSUE TITLE
ktor quickstart with IDEA does not seem to work. 

### ISSUE THREAD

**Issue by thawkins** [ktorio/ktor#296]
Im following these instructions 

http://ktor.io/quickstart/intellij-idea.html

using IDEA 2017.3.3, openjdk 1.8

Added kotlin plugin 1.2.20 

Every thing works untill I get to the stage on creating the appp

It cant find the imports. It defiantly has auto-importing enabled 

See images. 

![screenshot from 2018-01-22 16-28-15](https://user-images.githubusercontent.com/14537/35211677-76d22ef8-ff92-11e7-8520-4e28c0b5dc2c.png)
![screenshot from 2018-01-22 16-35-46](https://user-images.githubusercontent.com/14537/35211678-7702e016-ff92-11e7-90ab-25cfdf6948dc.png)

.

**Comment by orangy** [comment]
Try using fresh alpha build instead `0.9.1-alpha-9`

**Comment by thawkins** [comment]
What do you mean?, the build is installed exactly as per the instructions in the document listed, i did not ask for an alpha. How do i specify to use 0.9.1-alpha-9?, what changes do i need to make?

**Comment by orangy** [comment]
At some point we migrated from `org.jetbrains.ktor` to `io.ktor`, and documentation is not fully migrated (working on it). You need to replace `0.9.0` with `0.9.1-alpha-9` in ktor dependencies. We are planning to release `0.9.1` soon with all the stuff in place and finish syncing docs.

**Comment by thawkins** [comment]
Can you check this build.gradle.kts file, i cant quite seem to get it to work still. 

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
    var kotlin_version: String by extra
    var ktor_version: String by extra
    kotlin_version = '1.2.20'
    ktor_version = '0.9.1-alpha-9'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath(kotlinModule("gradle-plugin", kotlin_version))
    }
}

group = "Example"
version = "1.0-SNAPSHOT"

apply {
    plugin("java")
    plugin("kotlin")
}

val kotlin_version: String by extra
val ktor_version: String by extra

repositories {
    mavenCentral()
    maven { url "https://dl.bintray.com/kotlin/kotlinx" }
    maven { url "https://dl.bintray.com/kotlin/ktor" }
}

dependencies {
    compile(kotlinModule("stdlib-jdk8", kotlin_version))
    testCompile("junit", "junit", "4.12")
}

configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}
tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

```

**Comment by ralphie9224** [comment]
Getting all the same errors as @thawkins after following the sample gradle file in the docs and changing `0.9.1` to `0.9.1-alpha-9`

**Comment by orangy** [comment]
@thawkins I don't see ktor dependencies in the given build script.

**Comment by orangy** [comment]
As a side note, soon we are going to move samples from ktor project to separate project and make them depend on ktor via published artifacts, so these samples should be copy-pastable.

**Comment by beornharris** [comment]
I just thought I would give a little feedback - I just went through the quickstart referenced by the OP, and everything was up and running as described.

**Comment by soywiz** [comment]
I have added the artifact, and added a side note with detailed instructions to setup the `build.gradle` file:
http://ktor.io/quickstart/intellij-idea.html#start-a-project
