### ISSUE TITLE
HttpClient interceptors do not run.

### ISSUE THREAD

**Issue by mjburghoffer** [ktorio/ktor#300]
When I attempt to run HttpClient post, after installing a JsonFeature, an exception is thrown at HttpClientCall line 47:

```kotlin
val content = client.requestPipeline.execute(context, requestBuilder.body) as? OutgoingContent ?: error("")
```

as client.requestPipeline.execute always returns `Unit` no matter what interceptors are installed.  No interceptor code is ever called.  The error string is simply empty, too, to make matters worse.

Here is the full unit test (the server just echoes the json it receives):

```kotlin
data class Widget(
    val name: String,
    val value: Int,
    val tags: List<String> = emptyList()
)

    @Test
    fun testSerialize() {
        val client = HttpClient(Jetty) {
            install(JsonFeature)
        }

        val widget = Widget("Foo", 1000, listOf("bar", "baz", "qux"))
        val result = runBlocking {
            client.post<Widget>(body = widget, port = port) {
                contentType(ContentType.Application.Json)
            }
        }
        assertEquals(widget, result)
    }
```

**Comment by e5l** [comment]
Fixed here https://github.com/ktorio/ktor/commit/3182a53821b91197b80f1859528be4d3874f8ccf
