### ISSUE TITLE
Old version of jwt

### ISSUE THREAD

**Issue by SilenLoc** [ktorio/ktor#3002]
It would be good to update this version of jwt for two reasons: it forces you to use this version or 3.0.14 (one higher) or your token serialization can break. And it has not all the new security updates they added. This is a one year old version.

https://github.com/ktorio/ktor/blob/9ca85c50e297a2c0a124f11f1c1a453909417ecf/gradle/libs.versions.toml#L38

**Comment by e5l** [comment]
We will accept the PR, the Ktor GitHub tracker is closed for accepting issues: was hard to manage them here. Please consider logging a new issue in YT(using the button `New issue`)
