### ISSUE TITLE
Provide mechanism to override parallelism in Netty

### ISSUE THREAD

**Issue by fugithub** [ktorio/ktor#305]
We would like to use Ktor to expose management endpoints for a non-HTTP service that uses a different threadpool than Ktor's threadpool.

To reduce number of overall threads, it would be nice to be able to override parallelism instead of using all available processor cores.  If we could reduce Netty threads by pretending that there are only 1-2 processors available, that would do the trick.

It seems like just making the parallelism overridable in the ApplicationEngine's core Configuration might conflict with Ktor's design, otherwise I would have just contributed a patch. :)

**Comment by orangy** [comment]
You can do it in 0.9.1. Just set the value in the configuration file like this: 
```
ktor {
    deployment {
        port = 9090
        autoreload = false
        watch = [ ]
        connectionGroupSize = 2
        workerGroupSize = 5
        callGroupSize = 10
    }
…
}
```

**Comment by fugithub** [comment]
How about that.  Thanks for the info!

I would be happy to contribute to documentation for this.  Is there a place I can submit potential documentation to be added to the ktor website?

**Comment by soywiz** [comment]
The documentation has been updated with this information.
You can find it here: http://ktor.io/servers/configuration.html#available-config

**Comment by admackin** [comment]
@soywiz yes that page *lists* the parameters but I still don't know what they mean beyond what I can infer from this thread. Any chance of getting some docs (even one sentence) about what each of those parameters mean?
