### ISSUE TITLE
(with Netty) First request after booting is much longer

### ISSUE THREAD

**Issue by k4zuk0** [ktorio/ktor#306]
Hi,

I'm really very new to this framework, I've just only implemented a "ping" endpoint. I currently work with Spring Boot, and really wanted to try something lighter for side-projects.

Anyway, this may be really, really dumb, but I've noticed that the first request I execute after I boot my app takes 600+ ms to only answer "pong", with a Content-Type header, and any following request takes around than 2ms.

I can provide my `build.gradle` or `Application.kt` content, but there's really nothing more than the required skeleton to run a ping endpoint using Ktor & Netty

This may only be a beginner's problem, but I'm curious to know if anybody else experienced it, if it comes from Ktor or Netty, and maybe how to avoid this.

**Comment by orangy** [comment]
First time anything runs in a JVM it does class loading and then JITting, which might take quite some time depending on the system. I'm not saying it is exactly the reason, but it needs investigation. Is it a problem for your application or are you just curious?

**Comment by k4zuk0** [comment]
Curiosity only, mostly to know if there was maybe something to do to warm things up, and also to know what caused it. Less than a second at startup is not a problem for me (I don't use Ktor for production yet, only for side-projects)

**Comment by orangy** [comment]
You can warm the system up slightly by doing an http request to self, but I don't think it's really important. Subsecond application start and first response time is considered very good these days :)
