### ISSUE TITLE
Allow ContentNegotiation to match against missing Accept header

### ISSUE THREAD

**Issue by remen** [ktorio/ktor#307]
Given the following snippet:

```kotlin
embeddedServer(Netty, 8080) {
    install(ContentNegotiation) {
        register(ContentType.Any, JacksonConverter())
    }

    routing {
        get("/") {
            call.respond(mapOf("message" to "Hello World"))
        }
    }
}.start(wait = true)
```

It would be convenient to be able to send requests without an `Accept` header and have it match against `ContentType.Any`.

Currently, I get the following:

```bash
❯ curl -i -H 'Accept:' localhost:8080
HTTP/1.1 406 Not Acceptable
Content-Length: 0
```

Would it make sense to change this to support missing Accept headers? Would you appreciate a PR?

**Comment by orangy** [comment]
Empty `Accept` is not any. Any is `*/*`.

**Comment by remen** [comment]
I see.

How would you recommend I deal with the example above? I want to serve `application/json` by default if the client does not supply a `Accept` header.

**Comment by orangy** [comment]
Hmm, looks like it's not possible right now. But that's good suggestion, I think `Any` can be handled without `Accept` header indeed.

**Comment by remen** [comment]
I can send you a PR if you'd like, I think a reasonable place to change is at https://github.com/ktorio/ktor/blob/8fbae7d508660538ebd3dc7cb139217c9b1ceaad/ktor-server/ktor-server-core/src/io/ktor/features/ContentNegotiation.kt#L68
```kotlin
                val suitableConverters = call.request.acceptItems().mapNotNull { (contentType, _) ->
                    feature.registrations.firstOrNull {
                        it.contentType.match(contentType)
                    }
                }
```

where we could choose to have a "special" path if acceptItems is an empty list.

**Comment by orangy** [comment]
Exactly, PRs are very welcome!

**Comment by remen** [comment]
See PR above.

**Comment by orangy** [comment]
Fixed
