### ISSUE TITLE
location-based routing doesn't seem to parse body into lambda param with Gson

### ISSUE THREAD

**Issue by Naliwe** [ktorio/ktor#308]
Hi !

I've been having some issues with location-based routing. I have:

```kotlin
@Location("/login")
data class Login(val username: String = "", val password: String = "")

fun Route.login() {
    post<Login> { userInfo ->
        println(userInfo.username)         // Prints an empty line

        val test = call.receive<Login>()
        println("Test: $test")                    // Correctly prints the data class

        call.respond(Login("test", "testPass")) // works as expected
    }
}

fun Application.main() {
    ... // feature installation

    install(ContentNegotiation) {
        gson {
            setDateFormat(DateFormat.LONG)
            setPrettyPrinting()
        }
    }
    routing {
        login()
    }
}
```

But I couldn't find any way to make the lambda parameter filled w/o filling it myself by calling `receive` from a wrapper function. I thought that was kind of the point of the type arg we pass to `post`

Note that this exact code works in Thinkter demo, but the packages are quite outdated.

Any ideas ?

**Comment by orangy** [comment]
Locations don't bind post parameters, you have to receive them from the call. This is by design. Post data doesn't belong to "location".

**Comment by Naliwe** [comment]
Thanks for the reply,

But then why does this work ?

```kotlin
post<PostThought> {
        val user = call.sessionOrNull<Session>()?.let { dao.user(it.userId) }
        if (user == null || !call.verifyCode(it.date, user, it.code, hashFunction)) {
            call.respond(HttpStatusCode.Forbidden)
        } else {
            val id = dao.createThought(user.userId, it.text, it.replyTo)
            call.respond(PostThoughtResult(dao.getThought(id)))
        }
    }
```

**Comment by orangy** [comment]
It doesn't, this code is outdated.

**Comment by Naliwe** [comment]
Alright, so there has been a change in the way Locations work then ? That's basically what I thought, but wasn't quite sure.

I agree that post data doesn't *belong* to *Locations*, but the call to receive is somewhat mandatory and can actually be handled by the `post` (and assimilated) function with little modification, why not provide it ? (That's more of a curiosity-based query than an actual problem-related question, I'll just wrap the calls to provide this behavior)

**Comment by orangy** [comment]
Well, that's some magic that's hard to configure. What if you want to receive different instances depending on query parameters? E.g.
```
post<Foo> {
   if (it.value > 10) {
       val data = call.receive<Data1>()
       …
   } else 
   {
       val data = call.receive<Data2>()
       …
   }
}
```

**Comment by Naliwe** [comment]
I don't really see the problem here ~

I give `Foo` as the type parameter to post, so I know I want a Foo instance as my lambda parameter. What I do with the contents and how I handle it is indeed not the `post` function concern.

I just think the default use case is wanting to have an instance of the Location I give to post, not the opposite. Edge cases can be handled in several ways, the code you've just shown being one of them.

But maybe I didn't understand your point from your code ?

**Comment by orangy** [comment]
Foo instance is a location data class, which you can convert to text link and send in email, a/href, etc. It is guaranteed that when user follows the link, you will get exactly same instance of Foo. With post data you cannot do this.

**Comment by Naliwe** [comment]
Alright, I trust your design choices are carefully thought out, and yes, I guess being assured of this *value-ness* for `Locations` is interesting most of the times. But in my case it's not, since I'm developing a simple Json REST API; I'll just wrap the call to post to suit my needs :)

Thanks for your time
