### ISSUE TITLE
Allow for custom cookie types

### ISSUE THREAD

**Issue by noncom** [ktorio/ktor#310]
This code: https://github.com/ktorio/ktor/blob/694594dba0b885e40f8971c9124f1491d154a704/ktor-server/ktor-server-core/src/io/ktor/sessions/SessionSerializerReflection.kt#L236 makes it impossible to have custom cookie types. Please make it possible to somehow make a custom cookie serializable. For example, by forcing it to implement an interface. Because if a cookie stores some custom fields, it is currently impossible to serialize it. It could be a custom data type or even a JSON...

**Comment by cy6erGn0m** [comment]
In this case you shouldn't use this serializer but your custom `SessionSerializer` implementation. The idea of `SessionSerializerReflection` is to make compact representation for simple data classes that consist of primitive and basic types. For complex types you need to use custom. Perhaps we could provide some json-based serializer but in this case serialized cookies will be much bigger

**Comment by noncom** [comment]
Hmm, I did not know about the possibility to use a custom serializer, but it sounds logical.. The only mention of it I find here: http://ktor.io/features/sessions.html but it's quite bare.. I think there should be an example of how to do this, and under some kind of an informative header, not just "Configuration". Currently I feel like I'll have to dig into Ktor code and investigate on how to use this.

And I also like the idea of JSON cookies that could work well for many cases, greatly simplifying bootstrapping an application and serving the "avoid premature optimization" credo.

**Comment by orangy** [comment]
@soywiz docs! :D

**Comment by soywiz** [comment]
https://ktor.io/features/sessions.html#extending-serializers
