### ISSUE TITLE
WebSocket is not being closed in the sample

### ISSUE THREAD

**Issue by egorzhdan** [ktorio/ktor#314]
In `ktor-samples-websocket` the `memberLeft` function is not being called.
It continues to wait for messages from a closed socket.

**Comment by egorzhdan** [comment]
Turned out to be an issue with my network config. Closing this.

**Comment by orangy** [comment]
Can you elaborate a little bit? Might help someone and give us some information to consider if get strange reports in the future.

**Comment by egorzhdan** [comment]
I think this was something proxy-related. I reconfigured proxy settings from scratch after I noticed weird WebSockets errors on other websites. Now it is working fine.

**Comment by orangy** [comment]
Okay, thanks!
