### ISSUE TITLE
Change default log level for CallLogging feature to INFO

### ISSUE THREAD

**Issue by elizarov** [ktorio/ktor#319]
The rational behind this proposal is that a production deployment of an application shall typically run with `INFO` threshold on its logs (`DEBUG` and `TRACE` are typically used only for debugging of certain subsystems) and we expect that all requests shall be logged in a production deployment by default, since the log of requests represents the starting point for investigation of any production incidents.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-806">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in `2.0.0`
