### ISSUE TITLE
URLProtocol.createOrDefault causes missing port in result urls

### ISSUE THREAD

**Issue by Prototik** [ktorio/ktor#330]
It seems illogical that createOrDefault examine port for protocol (or at least uses user-provided port for protocol default), as it introduces unexpected behavior:
```kotlin
println(URLBuilder().apply {
  takeFrom(URI.create("http://localhost:8080/path"))
}.buildString()) // Prints http://localhost/path (without a port)
```
It caused by url.protocol == URLProtocol("http", 8080), what is obviously wrong (8080 isn't default port for http)

**Comment by e5l** [comment]
fixed here https://github.com/ktorio/ktor/commit/9b2e431592cfc1aca7e0998b63570ccc641cb60e

**Comment by Prototik** [comment]
@e5l well, this fixes http(s)/ws(s) protocols, but what about custom ones? E.g. `custom://localhost:8080/path` will lead to same behavior.

**Comment by e5l** [comment]
Thank you for notice. I'll prepare the fix.

**Comment by e5l** [comment]
fixed here https://github.com/ktorio/ktor/commit/0fa8842b6408eac07b3cfa7f21a757bf39d0ca97
