### ISSUE TITLE
netty server freezes after start error

### ISSUE THREAD

**Issue by jarekczek** [ktorio/ktor#336]
I runned the hello world example and it's ok. When I launch a second instance at the same time, I get *java.net.BindException: Address already in use: bind*. Perfect. But I expected the second instance to end with a failure. Instead I get a hanging netty application (a thread waiting in some netty routine).

Here is the code: https://github.com/jarekczek/ktorSimple/blob/master/src/main/java/WwwServer.kt
It never gets after the ` server.start(wait = false)` line.

I know a workaround. Catch the exception and `System.exit()`.

What's also strange is that if I don't do `server.stop`, the program never ends. I expect that when my application comes to the end of the main method, the program would stop. It works this way in finnagle. But not here.

So a final question: should netty prevent the application from terminating?

**Comment by Stexxe** [comment]
To reproduce execute the following code with some in use port:
```kotlin
embeddedServer(Netty, 35645) {
    routing {
        get("/") {
            call.respondText("Test", ContentType.Text.Html)
        }
    }
}.start(wait = false)
```
As a result main thread never exits.
We may fix it by shutting down `EventLoopGroup` while catching `BindException` when we synchronize `bind` future:
```kotlin
channels = bootstraps.zip(environment.connectors)
.map { it.first to it.first.bind(it.second.host, it.second.port) }
.map {
    val (bootstrap, future) = it
    try {
        future.sync().channel()
    } catch (e: BindException) {
        bootstrap.config().group().shutdownGracefully().sync()
        throw e
    }
}
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-803">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
