### ISSUE TITLE
Sending byte array as response

### ISSUE THREAD

**Issue by philipphager** [ktorio/ktor#337]
Hey there!
I want to build a simple REST server that serves protobuffs.
I therefore need to send a plain byte array to the client.
Is this supported? I haven't found such a usecase in the docs or samples, so I tried a little bit around. But e.g.  this results in an illegal argument exception.
```
call.respond { ByteArrayContent(bytes) }
```
Do I need to wrap the bytes in a file to be able to send them?

**Comment by orangy** [comment]
`call.respond(bytes)` should work, no need to wrap it in a lambda

**Comment by philipphager** [comment]
Sorry my bad, thank you for your fast response :)!
