### ISSUE TITLE
Locations support for ContentNegotiation (e.g. Jackson + Locations)

### ISSUE THREAD

**Issue by aviadmini** [ktorio/ktor#339]
Afaik currently locations only support query params. 

In my case I'm using Jackson feature to parse request body to JSON. 
And there's no option of using `post<T> { ... }` and having `it` ready to use, so I implemented it the good old way
```kotlin
post("/path") {
    val t: T
    try {
        t = call.receive()
    } catch (e: Exception) {
        call.respond(HttpStatusCode.BadRequest)
        return@post
    }
    // do whatever I like with T
}
```
Would be pretty neat to have locations support for similar cases, although I'm not sure what to do with malformed requests which throw on `call.receive<T>`

**Comment by raharrison** [comment]
You can get around the try/catch boilerplate by using the Status Pages feature to handle the exception generated by Jackson and just return a 400 error etc.

**Comment by aviadmini** [comment]
Sounds great, is there any docs (apart from samples) on Status Pages feature?

**Comment by raharrison** [comment]
http://ktor.io/features/status-pages.html
