### ISSUE TITLE
Java 9 Module Resolution Error

### ISSUE THREAD

**Issue by raharrison** [ktorio/ktor#342]
When creating a completely barebones ktor app, copied directly from the quickstart at http://ktor.io/quickstart/intellij-idea.html I get some Java 9 module issues when when modifying the app to use the `application.conf` file and the `DevelopmentEngine`:

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules ktor.utils and ktor.server.core export package io.ktor.util to module kotlin.stdlib.jdk8
```

This is using `jdk-9.0.1`

Everything works fine when using a standard main function with `embeddedServer`, it is only an issue when using the application gradle plugin and io.ktor.server.netty.DevelopmentEngine. I guess this would work fine on Java 8 and isn't a huge issue, but would be nice to be able to use autoreload with jdk9.

**Comment by orangy** [comment]
Closing as a specific case of #321
