### ISSUE TITLE
Routing dynamic files

### ISSUE THREAD

**Issue by whiteshadoww** [ktorio/ktor#343]
```
 static("img/profile") {
            val f = File("/tmp/public")
            staticRootFolder = f

            files(f)
        }
```
using this method only serves static files that are available when app lunches.Adding another file to the folder the server does not recognize it.

**Comment by orangy** [comment]
I cannot reproduce it locally, are you sure you're adding files to the `/tmp/public` folder? 

Also `staticRootFolder` here is useless, because your file path is absolute.
