### ISSUE TITLE
Content-Length not specified with ktor-html

### ISSUE THREAD

**Issue by jarekczek** [ktorio/ktor#345]
I launched the [sample html](https://github.com/ktorio/ktor/tree/master/ktor-samples/ktor-samples-html) application and it doesn't behave properly. When I run `wget -O out.txt -S http://localhost:8080` it freezes. Probably due to lack of Content-Length header in ktor server response. I suspect a bug somewhere in it. Could you please fix it?

**Comment by orangy** [comment]
It uses `transfer-encoding: chunked`, so it shouldn't have a `Content-Length` header. I tried this command and it worked perfectly fine, with `wget`, `curl`, `httpie` and browser. Can you post output from `curl -v localhost:8080` and your wget command?

**Comment by jarekczek** [comment]
`wget --version`
`GNU Wget 1.11.4`

I guess this old version (the only one available under windows) does not suport the chunk stuff. I workaround like this:

    call.respondText(ContentType.Text.Html) {
      createHTML().html {

If you mean *won't fix*, please close. Thank you for investigating the issue.

**Comment by orangy** [comment]
HTML is being written to a `Writer` while it builds, so we cannot know the length upfront, and thus cannot emit correct `Content-Length` header. You workaround is correct, you build a String and then send it, and length is known of course. However, chunked encoding is HTTP/1.1 standard and should be supported by any client these days, it's just how web works today. 

From some stackoverflow answer:
> Wget has a support of HTTP/1.1 and chunked transfer since version 1.13
