### ISSUE TITLE
ktor-client should not keep JVM from shutting down

### ISSUE THREAD

**Issue by elizarov** [ktorio/ktor#347]
See this sample code:
https://github.com/ktorio/ktor-samples/blob/master/feature/json-client/src/JsonClient.kt

The code is concise (we want it this way), but it does not actually work (main function does not terminate). It should work.

**Comment by e5l** [comment]
Fixed here https://github.com/ktorio/ktor/commit/d308c0feae97b4e47ab84b9003800326bc1f5292
