### ISSUE TITLE
question: why to set full url in packet instead of just query for proxy?

### ISSUE THREAD

**Issue by dmitryskorbovenko** [ktorio/ktor#3473]
https://github.com/ktorio/ktor/blob/62c12b3309078026066967f7bdda80d55fd26cb7/ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt#L47

it looks strange in Charles log
<img width="633" alt="image" src="https://user-images.githubusercontent.com/8803463/229587973-a46e7ab7-800f-474b-a6bb-6fa1fae743a1.png">

**Comment by Stexxe** [comment]
Can you please describe the steps to reproduce this problem?

**Comment by dmitryskorbovenko** [comment]
- setup proxy for CIO engine for Ktor client
```
HttpClient(CIO) {
        engine {
           proxy = ProxyBuilder.http(proxyUrl)
        }
```
- send any request
- check logs on your proxy, Charles in our case
- Charles reports that path contains full request url, not just path itself (look at screenshot in my comment above, path should be '/' but it is 'https://colector.bestdoctor.ru/' actually)

I've found the source responsible for this https://github.com/ktorio/ktor/blob/62c12b3309078026066967f7bdda80d55fd26cb7/ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/utils.kt#L47

so when `useProxy=true` we use `normalizedUrl.toString()` (full url with scheme and domain) otherwise `normalizedUrl.fullPath` (only path)

so why is it done this way?

this thing makes Charles working incorrectly: request breakpoints doesn't work and some other stuff

fyi, when we used OkHttp library with proxy set up before moving to ktor, Сharles reported path correctly without host prepended

**Comment by Stexxe** [comment]
That's an expected behavior to put a complete URL into a request line. From the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#start_line):
> A complete URL, known as the absolute form, is mostly used with GET when connected to a proxy. `GET https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages HTTP/1.1`

**Comment by dmitryskorbovenko** [comment]
thx for explanation
