### ISSUE TITLE
Feature: Redirect to SSL

### ISSUE THREAD

**Issue by elizarov** [ktorio/ktor#348]
We need out-of-the box feature with automatic redirect from non-secure to secure connector to complement HSTS feature. It should be incorporate into SSL sample: https://github.com/ktorio/ktor-samples/tree/master/feature/ssl

**Comment by orangy** [comment]
Anything wrong with `HttpsRedirect` feature?

**Comment by elizarov** [comment]
Works like a charm.

**Comment by orangy** [comment]
The problem with all that features is that they are undiscoverable if you don't know about smart completion that will just show you all the features. Any ideas how to fix it?

**Comment by soywiz** [comment]
Pressing `ctrl+space` inside the `Application.install` call-site should display just compatible properties/methods with that signature? Or at least display them first and in bold? Is that the smart completion? At least it doesn't work for me.

The only thing I can thing that doesn't depend on IDE features would be something like this:
```kotlin
object Features

val Features.Feat1 = MyFeature1
val Features.Feat2 = MyFeature2
```
But forces to add to every `install` the `Features`.

Independently to that: I'm adding the `HttpsRedirect` feature to http://ktor.io/features/index.html and the start proposal. That should help people discovering it using the website documentation at least.

**Comment by orangy** [comment]
Smart completion is `Ctrl+Shift+Space`.

**Comment by soywiz** [comment]
Awesome. I though I read sometime ago about it, but never used it because was not working for me. 
And indeed it doesn't work now either with that key combination. I have tried with `Code -> Completion -> SmartType` and works like a charm and I have rebinded keys, and also seems to work. 
So I have to figure out why `Ctrl+Shift+Space` doesn't work (it doesn't seem to be bound to the OS and I'm using the default `Mac OS X 10.5+` key map in IntelliJ).

And yes, it seems that smart completion doesn't show all the features available (the ones using the companion object).

**Comment by soywiz** [comment]
What about doing this instead?

```kotlin
object HttpsRedirect2 : ApplicationFeature<ApplicationCallPipeline, HttpsRedirect2.Configuration, HttpsRedirect2.Value> {
    override val key = AttributeKey<HttpsRedirect2.Value>("HttpsRedirect")
    override fun install(pipeline: ApplicationCallPipeline, configure: Configuration.() -> Unit): HttpsRedirect2.Value {
        val feature = HttpsRedirect2.Value(Configuration().apply(configure))
        pipeline.intercept(ApplicationCallPipeline.Infrastructure) {
            if (call.request.origin.scheme == "http") {
                val redirectUrl = call.url { protocol = URLProtocol.HTTPS; port = feature.redirectPort }
                call.respondRedirect(redirectUrl, feature.permanent)
                finish()
            }
        }
        return feature
    }

    class Value(val config: Configuration) {
        val redirectPort = config.sslPort
        val permanent = config.permanentRedirect
    }

    class Configuration {
        var sslPort = URLProtocol.HTTPS.defaultPort
        var permanentRedirect = true
    }
}
```

**Comment by orangy** [comment]
Why? May be better fix completion? :)

**Comment by Orfund** [comment]
Still redirect doesnt work (installed ofc). How can i do force-redirect any http request to https?

**Comment by cy6erGn0m** [comment]
> Still redirect doesnt work (installed ofc). How can i do force-redirect any http request to https?

There are both HttpsRedirect and HSTS feature. Could you please explain, what exactly doesn't work?

**Comment by Orfund** [comment]
> > Still redirect doesnt work (installed ofc). How can i do force-redirect any http request to https?
> 
> There are both HttpsRedirect and HSTS feature. Could you please explain, what exactly doesn't work?

Well really i have already solved that problem by intercepting route and accessing port in request.

The case was building a PWA, that needs the traffic to be forced to go through https. Such a headache to be honest.

`install(HttpsRedirect)` doesnt work as declared, that really did not help

**Comment by cy6erGn0m** [comment]
Could you please explain, what exactly didn't work?
