### ISSUE TITLE
Ktor doesn't follow Kotlin Best Practices around package naming for using coroutines

### ISSUE THREAD

**Issue by JLLeitschuh** [ktorio/ktor#355]
> **IMPORTANT NOTE**: We advise library authors to follow the same convention: add the "experimental" (e.g. com.example.experimental) suffix to your packages exposing coroutine-based APIs so that your library remains binary compatible. When the final API is released, follow these steps:
>
> - copy all the APIs to com.example (without the experimental suffix),
> - keep the experimental package around for backward compatibility.
> 
> This will minimize migration issues for your users.

https://kotlinlang.org/docs/reference/coroutines.html#experimental-status-of-coroutines

What is the plan for these API's when the package of the coroutines API changes?

**Comment by orangy** [comment]
This would put the whole `ktor` into `experimental` package, so it doesn't make sense here. If you wish, ktor is all experimental in this sense and will definitely break compatibility when coroutines are released. However, there will be IDE support for one-shot migration for sure, so I don't think it will cause a lot of damage. You will need to update the app source once and that's it.

**Comment by JLLeitschuh** [comment]
Will this one shot migration support also work for `ktor` or will it all be by hand?

**Comment by orangy** [comment]
Migration will be for coroutines, essentially changing packages and APIs whenever required.

**Comment by JLLeitschuh** [comment]
Okay, thanks!
