### ISSUE TITLE
config doesn't load while running ktor-test

### ISSUE THREAD

**Issue by sachinahuja** [ktorio/ktor#358]
Simple test
```kotlin
@Test fun getTest() = withTestApplication(Application::main){
        with(handleRequest(HttpMethod.Get, "/")) {
            assertEquals(HttpStatusCode.OK, response.status())
        }
    }
```

Fails because the app is unable to load its properties:
```shell
io.ktor.config.ApplicationConfigurationException: Property db.user not found.

	at io.ktor.config.MapApplicationConfig.property(MapApplicationConfig.kt:31)
	at opprt.Data.<init>(Data.kt:18)
	at opprt.AppKt.main(App.kt:36)
	at opprt.ApiTests$getTest$1.invoke(ApiTests.kt:17)
	at opprt.ApiTests$getTest$1.invoke(ApiTests.kt:14)
        ...
```
`at io.ktor.config.MapApplicationConfig.property(MapApplicationConfig.kt:31)` - looks like that map config is being loaded, although I have a HoconConfig (`application.conf`) in my app.

Here's what's happening in my app:
```kotlin
fun Application.main(){

        val dbConfig = environment.config.config("db")
        val dao = Data(dbConfig).migrateDb()
```

Likely problem is somewhere in `TestEngine.kt` ... looks like it's overwriting any app level configuration with a fresh test config:

```kotlin
fun createTestEnvironment(configure: ApplicationEngineEnvironmentBuilder.() -> Unit = {}) = applicationEngineEnvironment {
    config = MapApplicationConfig("ktor.deployment.environment" to "test")
    log = LoggerFactory.getLogger("ktor.test")
    configure()
}
```
I don't see any function that's sending in a relevant `configure` function in to `createTestEnvironment`. 

Please help resolving the issue.

**Most Likely Explanation**: I just haven't figured out how to set the configuration up.

**Comment by sachinahuja** [comment]
Can probably be closed. Here's what I had to do to make this work:

## Initialize the engine in a companion object with the relevant configuration
```kotlin
class ApiTests {

    companion object {
        val engine = TestApplicationEngine(createTestEnvironment({
            config = HoconApplicationConfig(ConfigFactory.load("application-test.conf"))
        }))

        @BeforeClass @JvmStatic fun setup(){
            logger.debug("Starting application with config ....")
            engine.start(wait = false)
            engine.application.main()
        }

        
    }
```
Use `with(engine)` instead of `withTestApplication`:

```kotlin
@Test fun testSomething = with(engine){
        with(handleRequest(HttpMethod.Get, uri, {
            addHeader("accept", "application/json")
        })) {
            assertions...
        }
}
```

**Comment by BreimerR** [comment]
with(engine){
   ... request test
}

```
404 Not Found: POST - /api/users

expected:<200 OK> but was:<404 Not Found>
Expected :200 OK
Actual   :404 Not Found
```

**Comment by rajda** [comment]
You can also create function:
`fun <R> withServer(test: TestApplicationEngine.() -> R) {
    withApplication(createTestEnvironment {
        config = HoconApplicationConfig(ConfigFactory.load("application-test.conf"))
    }, test = test)
}`

and use it:
`    @Test
    fun testSomething() = withServer {
        handleRequest(HttpMethod.Get, uri) {
            addHeader("accept", "application/json")
        }.apply {
            response.status() shouldBeEqualTo HttpStatusCode.Unauthorized
        }
    }`
