### ISSUE TITLE
Add ability to override HttpAsyncResponseConsumer

### ISSUE THREAD

**Issue by mpires** [ktorio/ktor#360]
Currently the HttpAsyncResponseConsumer in use is the internal ApacheResponseConsumer and this doesn't seem to be overridable.

For custom behaviours such as limiting the total size of the response payload without needing to actually fetch everything beforehand, would be advantageous

**Comment by e5l** [comment]
Hi @mpires.  `HttpAsyncResponseConsumer` is engine class and it intentionally internal. Notice that, `ByteChannel`(used by the consumer) is limited to 4096 bytes and reads request on demand. It's possible to make a feature that limits the total response size.

If there is a problem in implementation, could you provide some additional use cases?

**Comment by mpires** [comment]
Thanks @e5l for your response.
I basically want to do the same as [done here](https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/HeapBufferedAsyncResponseConsumer.java) where the consumer essentially caps the total response size.
Additional use cases include, when we the caller do not trust the content length of the payload provided by the callee and want to abort if it reaches a given threshold.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-797">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Hey, sorry for the delay. We're not going to make `HttpAsyncResponseConsumer` public.
If you want to use a limiter, consider writing feature wrapping `ByteReadChannel` instead.
