### ISSUE TITLE
Ability to set version headers in the application call

### ISSUE THREAD

**Issue by haxwagon** [ktorio/ktor#361]
The examples for ConditionalHeaders are very confusing as to correct usage.  All examples/tests use application-wide etag values:

```
class ETagsTest {
private fun withConditionalApplication(body: TestApplicationEngine.() -> Unit) = withTestApplication {
        application.install(ConditionalHeaders) {
            version { listOf(EntityTagVersion("tag1")) }
        }
        application.routing {
            handle {
                call.respondText("response")
            }
        }
        body()
    }
}
```

More common would be wanting to set the the actual content last modified and/or etag in the handle method itself (dynamic content) like so:
```
class ETagsTest {
    private fun withConditionalApplication(body: TestApplicationEngine.() -> Unit) = withTestApplication {
        application.install(ConditionalHeaders) 
        application.routing {
            handle {
                call.response.headers.append(HttpHeaders.ETag, "tag1")
                call.respondText("response")
            }
        }

        body()
    }
}
```

The etag provided in the response is not picked up by the default version handlers which should pick up that Etag = "tag1" header.  Also, writing a custom etag provider is not working b/c the OutgoingContent headers do not include the headers set in the response.  

What is the correct way to set the headers in a handler?

Thanks!

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-796">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
