### ISSUE TITLE
Exception or warning on mismatch with optional path param and non default valued parameter of location class

### ISSUE THREAD

**Issue by spand** [ktorio/ktor#363]
Currently this cannot be routed to with `itemId` missing. The author of this code probably intended it to be optional but forgot `= null`. The framework ought to report this mismatch when installing it in routing.
```
    @Location("/items/{itemId?}")
    class OptionalityTestLocation(val itemId: Int?)
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-795">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
