### ISSUE TITLE
How to authenticate only some routes

### ISSUE THREAD

**Issue by stasbar** [ktorio/ktor#367]
Hello.
How to authenticate only some routes ?

I would like to authenticate /login and /users but not /signup.
```
install(Routing) {
        authentication {
            basicAuthentication(myRealm.name) { credentials ->
                ...
            }
            get("/login"){
               //called fine when authenticated
            }
            get("/users"){
                // called fine when authenticated
            }
        }

        post("/signup") {
            // skipped
        }

    }
```

in this case, my `post("/signup")` is never called if I don't pass any Authentication header, why ?

and btw. the sample in https://github.com/ktorio/ktor/blob/master/ktor-samples/ktor-samples-auth/src/io/ktor/samples/auth/BasicAuthApplication.kt
is outdated since there is no more `authenticate("realmName")`

**Comment by soywiz** [comment]
@stasbar that sample is not outdated, but rather too new. We have changed how authentication is done in master.

Before, you had to apply authentication to routes.

In the next version of Ktor >= 0.9.2 (not including 0.9.1) (the one from the master sample), you will have to define named authentication strategies and then apply that authentication to several routes:

```kotlin
install(Authentication) {
    basic("myauth") {
        realm = myRealm.name
        validate { credentials -> }
    }
}

install(Routing) {
    authenticate("myauth") {
        get("/login"){
           //called fine when authenticated
        }
        get("/users"){
            // called fine when authenticated
        }
    }

    post("/signup") {
        // skipped
    }
}
```

But if you are using 0.9.1, you would have to do something like this in the meantime (untested):

```kotlin
fun Application.module() {
routing {
    route("/login") {
          myauth()
          handle { } // called fine when authenticated
    }
    route("/users") {
          myauth()
          handle { } // called fine when authenticated
    }
    route("/signup") {
          handle { } // called fine when authenticated
    }
}
}

fun Route.myauth() {
    authentication {
        basicAuthentication("ktor") { credentials -> }
    }
}
```

**Comment by stasbar** [comment]
It's working, thank you 👍
