### ISSUE TITLE
Lazy value not initialised yet

### ISSUE THREAD

**Issue by jozefdransfield** [ktorio/ktor#371]
When using the testApplication in a unit test:

``
 fun test() = withTestApplication(Application::main) {
 with(handleRequest(HttpMethod.Post, "/check")) {
            assertEquals(HttpStatusCode.OK, response.status())
            assertEquals("Test String", response.content)
        }
}
``

and a route which resembles:

``
  post("/check") {
            call.respond(SomeObject())
        }
``

When I run my test the status code is 406 and the realContent of the response is:

"Lazy value not initialized yet."

However this works fine when the app is actually running

**Comment by cy6erGn0m** [comment]
Fixed in master
