### ISSUE TITLE
receiveOrNull susceptible to type erasure

### ISSUE THREAD

**Issue by mjburghoffer** [ktorio/ktor#377]
https://github.com/ktorio/ktor/blob/84f213a320f38e11ffaafe7b5e7f321a6b7adaab/ktor-server/ktor-server-core/src/io/ktor/request/ApplicationReceiveFunctions.kt#L70

The highlighted code is susceptible to type erasure.  If I want to `receiveOrNull<Map<String, List<String>>>()`, for instance, at runtime I will only have access to `Map<*, *>::class`.  This is a problem for a lot of serializations frameworks, like jackson, who use `TypeToken`s or the like.

**Comment by nikolajakshic** [comment]
This [sample](https://gist.github.com/nikolajakshic/0a7ea29a53fab557e40deb14d7d201be) throws [this exception](https://gist.github.com/nikolajakshic/0cba31c828c8b970da8d4e399396e0ad). I just want to be sure that this is related, right? If so, any updates on this?

**Comment by mjburghoffer** [comment]
Yes this is 100% related. As far as I know there have been no updates to
this issue.

**Comment by mkobit** [comment]
From the client side, there are https://github.com/ktorio/ktor/issues/346 and https://github.com/ktorio/ktor/issues/365 which are similar

**Comment by dmakarenko-connyun** [comment]
Guys, any progress on this?

**Comment by nikolajakshic** [comment]
@cy6erGn0m commenting just as a reminder, similar issues on the client side are solved, somehow this got forgotten.

**Comment by tylerbobella** [comment]
Commenting on this because I started to create a small web app with ktor + jackson and this was a full-stop for me since i could not receive a `List<MyType>`. Is there a workaround for this? Does the gson plugin work with something like `List<MyType>` or @mjburghoffer example?

**Comment by nikolajakshic** [comment]
@tylerbobella Same thing happens with Gson as well. And for workaround, well you can still take the whole string and convert it with jackson/gson manually.

With Gson, instead of:
```kotlin
val items = call.receive<List<MyType>>()
```
use
```kotlin
val items = Gson().fromJson<List<MyType>>(call.receiveText(), object : TypeToken<List<MyType>>() {}.type)
```

You can write extension function and make it look prettier.

**Comment by tylerbobella** [comment]
Thanks for the reply @nikolajakshic. I will try something similar with Jackson tonight and will report back.

**Comment by tylerbobella** [comment]
For those using jackson I created this extension function that allows us to serialize a list of objects

```
inline fun <reified T> String.serialize(): T {
  return jacksonObjectMapper().readValue(this)
}
```

Usage:
```
call.receiveText().serialize<List<MyType>>()
```

**Comment by mjburghoffer** [comment]
What I have done is essentially married Jackson's TypeToken with KClass as a workaround:

```kotlin
@Suppress("unused")
abstract class KTypeToken<T> protected constructor() : KClass<Any>, ClassBasedDeclarationContainer {

    val javaType: Type
    val javaClass: Class<T>
    val kotlinClass: KClass<*>

    init {
        val superClass = (this as Any).javaClass.genericSuperclass
        javaType = (superClass as ParameterizedType).actualTypeArguments[0]
        val rawJavaClass = when (javaType) {
            is ParameterizedType -> javaType.rawType as Class<*>
            is Class<*> -> javaType
            else -> throw IllegalArgumentException("Cannot get KTypeToken from type: $javaType")
        }
        kotlinClass = rawJavaClass.kotlin
        @Suppress("UNCHECKED_CAST")
        javaClass = rawJavaClass as Class<T>
    }

    override val annotations get() = kotlinClass.annotations
    override val constructors get() = kotlinClass.constructors
    override val isAbstract get() = kotlinClass.isAbstract
    override val isCompanion get() = kotlinClass.isCompanion
    override val isData get() = kotlinClass.isData
    override val isFinal get() = kotlinClass.isFinal
    override val isInner get() = kotlinClass.isInner
    override val isOpen get() = kotlinClass.isOpen
    override val isSealed get() = kotlinClass.isSealed
    override val members get() = kotlinClass.members
    override val nestedClasses get() = kotlinClass.nestedClasses
    override val sealedSubclasses get() = kotlinClass.sealedSubclasses
    override val objectInstance get() = kotlinClass.objectInstance
    override val qualifiedName get() = kotlinClass.qualifiedName
    override val simpleName get() = kotlinClass.simpleName
    override val supertypes get() = kotlinClass.supertypes
    override val typeParameters get() = kotlinClass.typeParameters
    override val visibility get() = kotlinClass.visibility
    override val jClass: Class<*> get() = javaClass
    override fun isInstance(value: Any?) = kotlinClass.isInstance(value)

    override fun toString(): String = javaType.typeName

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is KTypeToken<*>) return false
        return javaType == other.javaType
    }

    override fun hashCode(): Int {
        return javaType.hashCode()
    }
}
```

It is a little ugly, but you can pass it into `receiveOrNull` since it is a `KClass`, and if you add your own `ContentConverter`, you can check if the request type is a `KTypeToken` or just a regular `KClass` and handle accordingly.

```kotlin
override suspend fun convertForReceive(context: PipelineContext<ApplicationReceiveRequest, ApplicationCall>): Any? {
    when (val type = request.type) {
        is KTypeToken<*> -> {
            // type is fully reified here
        }
        else -> {
            // type is not reified here
        }
    }
}
```


I don't know if this is 100% the best solution, but it does seem to work well enough for me.  I actually would hope that something like `KTypeToken` would exist in `kotlin-reflect-jvm`.  So many third part libraries each implement their own flavor of this class (Guava, Jackson, Gson, etc.)

**Comment by cy6erGn0m** [comment]
Since 1.3.0 `KType` is available (from `typeOf(`) and kotlinx.serialization support should work as well. You may check it in version `1.3.0-rc`
