### ISSUE TITLE
Proguard on Android issues

### ISSUE THREAD

**Issue by felislynx-silae** [ktorio/ktor#379]
Hi, i'm using ktor for simple rest server on Android app. Everything works fine, but if i run proguard, then hell is unleashed and i have over 680 issues with progurad.
100% problems is resolved by:
```
-dontwarn io.netty.**
-dontwarn io.ktor.**
-dontwarn com.typesafe.**
```
But server is not responding after start so i'm assuming, that proguard rules should be different :)

**Comment by soywiz** [comment]
Check/try this sample:
https://github.com/ktorio/ktor-samples/pull/13/files

**Comment by felislynx-silae** [comment]
@soywiz in android we use proguard-rules.pro file
i've tried to move this file as rules:
```
-keep class io.ktor.server.netty.DevelopmentEngine {*;}
-keep class kotlin.reflect.jvm.internal.** {*;}
-keep class io.ktor.samples.hello.HelloApplicationKt {*;}
-keep class kotlin.text.RegexOption {*;}
```
And i've over ~680 errors still, like
```
...
Warning: io.netty.handler.ssl.ConscryptAlpnSslEngine$BufferAdapter: can't find superclass or interface org.conscrypt.AllocatedBuffer
Warning: io.netty.handler.ssl.ConscryptAlpnSslEngine$BufferAllocatorAdapter: can't find superclass or interface org.conscrypt.BufferAllocator
...
Warning: com.typesafe.config.impl.ConfigBeanImpl: can't find referenced class java.beans.PropertyDescriptor
Warning: com.typesafe.config.impl.ConfigBeanImpl: can't find referenced class java.beans.BeanInfo
...
Warning: io.ktor.util.SSLKt: can't find referenced class sun.security.x509.X509CertInfo
Warning: io.ktor.util.SSLKt: can't find referenced class sun.security.x509.CertificateSerialNumber
...

Warning: io.netty.util.internal.logging.Log4J2LoggerFactory: can't find referenced class org.apache.logging.log4j.LogManager
Warning: io.netty.util.internal.logging.Log4J2LoggerFactory: can't find referenced class org.apache.logging.log4j.LogManager
```

**Comment by soywiz** [comment]
Related to this:
https://stackoverflow.com/questions/49945584/attempting-to-run-an-embedded-ktor-http-server-on-android

I have done this example and seems to work:
https://github.com/soywiz/android-ktor-example

Let me know if it works for you

**Comment by zhuosun-rally** [comment]
@soywiz you just close the minify, that does not really solve the problem, ^^, 
Could you guide us how to config the proguard-rules.pro for ktor-android?

**Comment by mikezliu** [comment]
This worked for me. Running release apk works too.

# Ktor
-keep class io.ktor.** { *; }
-keep class kotlinx.coroutines.** { *; }
-dontwarn kotlinx.atomicfu.**
-dontwarn io.netty.**
-dontwarn com.typesafe.**
-dontwarn org.slf4j.**

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-791">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in the origin issue

**Comment by kairos34** [comment]
Hello,
Could you share latest proguard rules for Android please?

**Comment by jacklai24** [comment]
Hello,
Could you share latest proguard rules for Android please? Thank you.

**Comment by alessioemireni** [comment]
+1

**Comment by luispereira** [comment]
+1

**Comment by stobor827** [comment]
Adding these two lines to the config above worked for me on 2.3.2, but beware I have no idea what I'm doing
```
-keep class io.netty.** {*; }
-keep class kotlin.reflect.jvm.internal.** { *; }
```

**Comment by kiviabritosq** [comment]
Sharing the rules that worked for me:
```
# Keep Ktor classes for the Local Connect feature.
-keep class io.ktor.** { *; }
-keepclassmembers class io.ktor.** { *; }

# Keep Netty classes for the Local Connect feature.
-keep class io.netty.** { *; }
-keepclassmembers class io.netty.** { *; }
# Ignore warnings related to io.netty package (e.g., unused classes or reflection issues)
-dontwarn io.netty.**
```
