### ISSUE TITLE
no SSL

### ISSUE THREAD

**Issue by marshallwalker** [ktorio/ktor#383]
How can i tell the ktor client not to use ssl, I'm trying to connect to a site that does not use SSL and i get the error "Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?"

**Comment by e5l** [comment]
Hi, @PurePlugin, could you provide some code snippet?

**Comment by PurePlugin** [comment]
@e5l

`        val client = HttpClient(Jetty) {
            this.install(JsonFeature) {
                serializer = GsonSerializer {
                    serializeNulls()
                    disableHtmlEscaping()
                }
            }
        }

        val result = client.get<String>("http://google.ca")

        println(result)`

**Comment by e5l** [comment]
Yep, there is a problem here.

Please note that `Jetty` engine is `h2`(http2 over TLS)(https://http2.github.io/faq/#can-i-implement-http2-without-implementing-http11) and it requires server support, http2 `h2c` is currently in progress. 

Consider using different backend(e.x. `CIO`) if `http2` is not critical.

**Comment by PurePlugin** [comment]
Ended up using Apache engine, when i need ssl i'll move back to Jetty
