### ISSUE TITLE
is docs about extracting route wrong?

### ISSUE THREAD

**Issue by defaultbr** [ktorio/ktor#387]
im crazy or are the same thing the topics hello world and extracting routes

![image](https://user-images.githubusercontent.com/5432351/38591934-b4b3e4fe-3d0f-11e8-924d-f8cc81cd9ebf.png)

where its extracting the routes ??!?!?!?!?!

source: https://ktor.io/servers/structure.html

if its different, how can i avoid a big  main method and separte in other files?

btw awesome lib, using and working, i just need to organize it

**Comment by soywiz** [comment]
It seems that that page was not finished. I have fixed that section already and now I'm completing it.

Thanks for reporting!
