### ISSUE TITLE
Dynamically changing a html page

### ISSUE THREAD

**Issue by vellrya** [ktorio/ktor#390]
Hello! In fact, there is no problem here. The point is that even after studying all available examples, I never found a way to realize this possibility using ktor. 
Briefly: html page code should be changed after it was opened in the browser without updating it. When the server has data, it should immediately show them to the user. I will be very grateful if you provide a sample code or a link to the official documentation (maybe I missed something)
Thank you in advance

**Comment by soywiz** [comment]
> html page code should be changed after it was opened in the browser without updating it

Looks like something to be done at javascript, right? By manipulating the DOM.

Or do you mean something else? Like a stat counter for the next visit?

**Comment by cy6erGn0m** [comment]
React?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-787">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
