### ISSUE TITLE
Documentation for Post using Location feature isn't updated

### ISSUE THREAD

**Issue by ralphie9224** [ktorio/ktor#391]
According to the issue https://github.com/ktorio/ktor/issues/190

the kweet app has been updated to show how to pass in parameters using Post with the Locations feature. 
using `val params = call.receive<Parameters>()`
However, this is not reflected in the docs for Locations so it's pretty hard to find.

**Comment by soywiz** [comment]
This should be addressed already: https://ktor.io/servers/calls/requests.html#receiving
