### ISSUE TITLE
Better SSL support for raw sockets

### ISSUE THREAD

**Issue by OtakuSenpai** [ktorio/ktor#394]
>import io.ktor.cio.*
>import io.ktor.network.sockets.*
>import io.ktor.network.tls.*
>import kotlinx.coroutines.experimental.*
>import kotlinx.coroutines.experimental.io.*
>import java.net.*

>fun main(args: Array<String>) {
>    runBlocking {
>        val socket = aSocket().tcp().connect(InetSocketAddress("chat.freenode.net", 6697)).tls()
>        val w = socket.openWriteChannel(autoFlush = false)
>        val r = socket.openReadChannel()
>        println(r.readASCIILine())
>   }
>}

This line of code produces the following error:- 
>Exception in thread "io-thread-2" io.ktor.network.tls.TLSException: Unsupported TLS handshake type CertificateRequest
>	at io.ktor.network.tls.TLSClientSession.handshake(TLSClientSession.kt:308)
>	at io.ktor.network.tls.TLSClientSession.processHandshakeMessage(TLSClientSession.kt:79)
>	at io.ktor.network.tls.TLSClientSession.tlsHandshakeAndNegotiation(TLSClientSession.kt:64)
>	at io.ktor.network.tls.TLSClientSession$tlsHandshakeAndNegotiation$1.doResume(TLSClientSession.kt)
>	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
>	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
>	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
>	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
>	at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
>	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
>	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
>	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
>	at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:175)

**Comment by e5l** [comment]
The TLS sockets support single cipher suite for now. WIP

**Comment by e5l** [comment]
The fix is complete and would be available in `1.1.2`.
