### ISSUE TITLE
MPP Http Client?

### ISSUE THREAD

**Issue by ScottPierce** [ktorio/ktor#396]
Are there any plans to provide ktors http client for MPP?

**Comment by orangy** [comment]
Yes, we are working towards this goal, but we need to build the whole MPP stack bottom up, from buffers and sockets, through coroutines into a proper multiplatform HTTP client.

**Comment by ScottPierce** [comment]
I see. That's much larger in scope than I had assumed, but it makes sense.

**Comment by JonasFranzDEV** [comment]
@ScottPierce Is there a PR / issue to follow the progress?

**Comment by ScottPierce** [comment]
@e5l Could you update this ticket when it's released? My team is very interested in this.

**Comment by e5l** [comment]
Sure :)

**Comment by e5l** [comment]
Recent release includes `android-ios` MPP-support: `0.9.4-alpha-2`

**Comment by JonasFranzDEV** [comment]
@e5l Is there an example using common modules with native, jvm and js support?

**Comment by e5l** [comment]
You could find android and ios samples here: https://github.com/ktorio/ktor-samples/tree/mpp-client/mpp/client-mpp
There are no support for Linux native and javascript engines for now.

**Comment by amrboxit4me** [comment]
Updated link [](https://github.com/ktorio/ktor-samples/tree/master/mpp/client-mpp)
