### ISSUE TITLE
String#escapeHTML unsafe

### ISSUE THREAD

**Issue by Bluexin** [ktorio/ktor#400]
The implementation for `String#escapeHTML` (in package `io.ktor.util`) is (in my opinion) unsafe.
I have noticed two issues :
 * Escape code used for `'` is not part of the HTML spec (see [section 24.4.1](https://www.w3.org/TR/html4/sgml/entities.html#h-24.4.1))
 * Many "uncommon" characters used in XSS aren't handled. Below is the list I usually use (but maybe I missed some too, if so please point them out ;p )

```kotlin
when (ch) {
    '\"' -> append("&quot")
    '&' -> append("&amp;")
    '<' -> append("&lt;")
    '>' -> append("&gt;")
    ' ' -> append("&#x20;")
    '!' -> append("&#x21;")
    '$' -> append("&#x24;")
    '%' -> append("&#x25;")
    '\'' -> append("&#x27;")
    '/' -> append("&#x2F;")
    '+' -> append("&#x2b;")
    ',' -> append("&#x2c;")
    '=' -> append("&#x3d;")
    '@' -> append("&#x40;")
    '[' -> append("&#x5b;")
    ']' -> append("&#x5d;")
    '`' -> append("&#x60;")
    '{' -> append("&#x7b;")
    '}' -> append("&#x7d;")
    else -> append(ch)
}
```

**Comment by cy6erGn0m** [comment]
- `&apos;` is valid in HTML5 however IE doens't get it so we need to replace it with `&#x27;`

- There is absolutely no reason to escape most of those characters. Only quotes, amp and lt/gt are actually dangerous while using `{`, `[` and so on is completely safe.

**Comment by cy6erGn0m** [comment]
I don't see how a backtick added anywhere could inject executable javascript
