### ISSUE TITLE
Brotli Support

### ISSUE THREAD

**Issue by yampug** [ktorio/ktor#408]
Just curious if there are plans to add support for [brotli](https://github.com/google/brotli) compression? 

Saw the implementation in `ktor-server/ktor-server-core/src/io/ktor/features/Compression.kt` for Gzip and Deflate. Wanted my application to respond with a brotli compressed js script (as it is 30% smaller than the gzip version) but failed to overwrite the Content-Encoding in the response header with **br**.

Miserable attempt: (the file was already compressed outside of ktor)
```
get("/bundle.min.js") {
   // attempt 1
    call.respondFile(File("public/js/bundle.min.js.br"), {
        setProperty(AttributeKey("Content-Type"), "application/octet-stream")
        setProperty(AttributeKey("Content-Encoding"), "br")
        finish()
    })
   // attempt 2 bout = ByteArrayOutputStream
    call.respondWrite(ContentType.Application.OctetStream, HttpStatusCode.OK, { bout })
}
```

**Comment by soywiz** [comment]
I have looked for brotli artifacts at maven:
http://search.maven.org/#search%7Cga%7C1%7Cbrotli
But it seems that there is only one pure java decoder there. And can't see jni-based encoders either :(

For serving already-compressed brotli files. I have tried this and seems to work:
```
get("/hello.txt") {
    //echo hellohellohellohello | brotli -9 -f | base64
    //GxQAACQUchBFhKnCc/oE
    val data = Base64.getDecoder().decode("GxQAACQUchBFhKnCc/oE")
    call.response.header("Content-Encoding", "br")
    //call.respond(LocalFileContent(File("public/js/bundle.min.js.br"), ContentType.Application.OctetStream))
    call.respond(ByteArrayContent(data))
}
```

**Comment by cy6erGn0m** [comment]
@soywiz FYI there is extension point for implementing custom content encodings:

https://github.com/ktorio/ktor/blob/2554c84782b5c16dfe5b7e74bf6eb9187d4678f3/ktor-server/ktor-server-tests/test/io/ktor/tests/server/features/CompressionTest.kt#L123

**Comment by cy6erGn0m** [comment]
What we could try is https://github.com/dominikhlbg/BrotliHaxe However it's quite big and I have no ideas if it is stable or not

**Comment by soywiz** [comment]
I looked at the Haxe version sometime ago. The thing they forgot is to put the C++ reference version there, so anyone can replace it with a new version, see what changed and backport those changes (they state it is from a version 2 years old, and it was on mid-2017) so maybe that would be worthwhile.

Not sure how stable it is either. But I can try to get a small corpus and try to compress/decompress with the brotli cli version and the library and compare the results.

The other thing that I have noticed (from the benchmark in the readme) is that the transpiled Java version is one order of magnitude slower. I bet it is possible to optimize it.

If you think it is worthwhile I can try to build it and upload to central somewhere.

**Comment by cy6erGn0m** [comment]
Not sure if it has so high priority for now. The other issue is that haxe doesn't support Kotlin output (and as far as it is written in okaml, I believe it is not so easy to add). So without kotlin version we will be unable to port it to Native.

**Comment by Flakesz** [comment]
@soywiz Thank you, your approach works (at least in chrome) but its setting also two Content-Encoding headers which might be interpreted wrongly by other browser (one with br and one with gzip, as I got gzip module enabled for other stuff). Do you know a way to prevent the gzip header to be added?

To your discussion: brotli got a quite slow encoding time (but awesome decoding time, **[see](https://www.opencpu.org/posts/brotli-benchmarks/)**), so doing it on the fly is quite a bad approach anyway and better suited to do in a preprocessing step (like in webpack or custom script).

**Comment by soywiz** [comment]
Actually, brotli can be faster while still produce better compression than gzip at the same compression speed: https://certsimple.com/blog/nginx-brotli
But still you will get the best benefits from slower settings. The same goes for gzip, lzma or zstd. So offline compression/caching compression for static files could make sense.

---

It seems that the Compression feature calls to this:
```
private fun ApplicationCall.isCompressionSuppressed() = Compression.SuppressionAttribute in attributes
```

Untested. But I guess you can add the `Compression.SuppressionAttribute` to prevent recompressing?

**Comment by Flakesz** [comment]
`Compression.SuppressionAttribute` sadly did not work. I just created a second server for now handling brotli compressed files. The overhead is reasonable, so I can live with this solution for now.
Guess we can close this :)!

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-785">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
