### ISSUE TITLE
RFE: Support for Unix domain sockets for both server/client

### ISSUE THREAD

**Issue by mkobit** [ktorio/ktor#412]
Netty (I believe) already has support for this (https://netty.io/4.1/api/io/netty/channel/unix/package-summary.html) so this may already be possible with the existing engines with some tweaking or configuration.

### Example server use case 

Authoring a Docker plugin: https://docs.docker.com/engine/extend/plugin_api/ that runs locally. With [`jlink` in Java 9](https://docs.oracle.com/javase/9/tools/jlink.htm) entire "native"-like services can be shipped.

### Example client use case 

Communicating with Docker engine which by default `/var/run/docker.sock`. For example, `curl` supports making requests to a UNIX socket:

```
curl --unix-socket /var/run/docker.sock http:/containers/json
[]
```

**Comment by nailgilaziev** [comment]
This is only one issue that contains request for supporting Unix Domain Socket. Stale label can be removed.

**Comment by nailgilaziev** [comment]
Re: This is only one issue that contains request for supporting Unix Domain Socket. Stale label can be removed.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-781">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
