### ISSUE TITLE
HttpResponse.receive method documented but missing

### ISSUE THREAD

**Issue by JLLeitschuh** [ktorio/ktor#413]
http://ktor.io/clients/http-client.html#HttpResponse

These three methods are documented but don't seem to be present anywhere:
```kotlin
val readChannel = response.receive<ByteReadChannel>()
val multiPart = response.receive<MultiPartData>()
val inputStream = response.receive<InputStream>()
```

**Comment by soywiz** [comment]
It seems that the documentation was wrong. (I have updated it). The receive method is part of the call.
So you can call `response.call.receive` instead.

**Comment by e5l** [comment]
Fixed in `master`
