### ISSUE TITLE
Feature request (?): Observe response state and set headers appropriately

### ISSUE THREAD

**Issue by marshallpierce** [ktorio/ktor#417]
Goal: I'd like to give hints to a browser front-end about its authentication state. 

I can't use response status codes to do this because some endpoints emit 2xx when unauthenticated. While I'm open to ideas for better ways, the current approach I'd like to try is adding a custom header to all responses with whether or not the request provided a valid session (or a valid session was created when processing the request, for the case of operations like logging in a user). This will let the front-end observe the header and hide/show UI elements appropriately.

It seems like what I want is a way to observe the state of `call.session` as the response is heading outbound and add a header accordingly. Is this something I should write a custom `Feature` for, or is there some other way? Conceivably this could be bolted into authentication, but I think that doesn't make a lot of sense since I want this to be available for *all* endpoints, not just ones that have authentication applied.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-780">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Responded in YT issue
