### ISSUE TITLE
assigning the default port number will potentially break signed url

### ISSUE THREAD

**Issue by zdevwu** [ktorio/ktor#428]
https://github.com/ktorio/ktor/blob/7092c30706f34242419a5f0c81445dca06461dc3/ktor-http/src/io/ktor/http/URLUtils.kt#L14

I'm trying to get a s3 file using pre-signed url, the port number added here makes the URLBuilder built url invalid

**Comment by soywiz** [comment]
Why? Can you elaborate with a sample reproducing the error?
Looking at that code, only sets the port when not > 0.

**Comment by zdevwu** [comment]
Say for example, the pre-signed url is like:
https://bucket.s3.amazonaws.com/a/file?Signature=xxx
After parsing and rebuild the url will be turned into:
https://bucket.s3.amazonaws.com:443/a/file?Signature=xxx

**Comment by e5l** [comment]
Fixed in `master`
