### ISSUE TITLE
https handshakeFailure with CIO HttpClient

### ISSUE THREAD

**Issue by henry1986** [ktorio/ktor#439]
I want to implement a HttpClient, that connects via https for a websocket communication.

Currently only the CIO HttpClient supports websockets, but it seems to have an issue with https.

When using Apache HttpClient, a

`client.call("ip")` 

works fine, but with CIO Client it throws 

> Exception in thread "io-thread-1" io.ktor.network.tls.TLSException: Received alert during handshake. Level: FATAL, code: HandshakeFailure
> 	at io.ktor.network.tls.TLSClientSession.processHandshakeMessage(TLSClientSession.kt:96)
> 	at io.ktor.network.tls.TLSClientSession.tlsHandshakeAndNegotiation(TLSClientSession.kt:64)
> 	at io.ktor.network.tls.TLSClientSession$tlsHandshakeAndNegotiation$1.doResume(TLSClientSession.kt)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
> 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
> 	at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
> 	at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt)
> 	at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:78)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
> 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
> 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
> 	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
> 	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
> 	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
> 	at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:73)
> Exception in thread "ForkJoinPool.commonPool-worker-1" io.ktor.network.tls.TLSException: Received alert during handshake. Level: FATAL, code: HandshakeFailure
> 	at io.ktor.network.tls.TLSClientSession.processHandshakeMessage(TLSClientSession.kt:96)
> 	at io.ktor.network.tls.TLSClientSession.tlsHandshakeAndNegotiation(TLSClientSession.kt:64)
> 	at io.ktor.network.tls.TLSClientSession$tlsHandshakeAndNegotiation$1.doResume(TLSClientSession.kt)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
> 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
> 	at kotlinx.coroutines.experimental.io.internal.MutableDelegateContinuation.run(MutableDelegateContinuation.kt:14)
> 	at io.ktor.network.util.IOCoroutineDispatcher$IODispatchedTask.run(IOCoroutineDispatcher.kt)
> 	at io.ktor.network.util.IOCoroutineDispatcher$IOThread$run$1.doResume(IOCoroutineDispatcher.kt:78)
> 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
> 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
> 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
> 	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
> 	at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:244)
> 	at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:185)
> 	at io.ktor.network.util.IOCoroutineDispatcher$IOThread.run(IOCoroutineDispatcher.kt:73)
> 

Same happens on client.wss(...) 

Is there a difference between the implementation of the TLS Handshake of the Apache HttpClient and the CIO client? And if so, why? If I look in the code, TLS Handling seems to be independent of Apache Client and CIO Client, but maybe I have overseen something. I would appreciate some help.

**Comment by soywiz** [comment]
Related to this? https://github.com/ktorio/ktor/issues/394

**Comment by henry1986** [comment]
Actually I can't tell, if it is the same. Exception is different, and in the linked issue they are talking about a certificate problem, which it doesn't seem to be, because it doesn't even get to the TrustManager (i've tested)

**Comment by henry1986** [comment]
To give you a reproducible example:

`
 fun main(args: Array<String>) {
     var client: HttpClient = HttpClient(CIO) {
         // var client: HttpClient = HttpClient(Apache){`
` 
         install(WebSockets) {
         }
     }
     launch {
         val status = client.call("https://elster.de")
             .response.status
         println("status: $status")
     }
     Thread.sleep(10000L)
 }
`

Pay attention - other websites like "https://google.com" or "https://facebook.com" have no TLS Problem. They work fine and deliver a status 301

**Comment by henry1986** [comment]
And if change the url to

"https://www.elster.de" the exception is slightly different:

> Exception in thread "io-thread-1" Exception in thread "ForkJoinPool.commonPool-worker-1" io.ktor.network.tls.TLSException: Handshake failed: premature end of stream
> 	at io.ktor.network.tls.TLSClientSession.tlsHandshakeAndNegotiation(TLSClientSession.kt:61)
> 	at io.ktor.network.tls.TLSClientSession$tlsHandshakeAndNegotiation$1.doResume(TLSClientSession.kt)
> 
> ...

**Comment by e5l** [comment]
Hi, @henry1986. Thanks for the report. It look's like the problem that had been already fixed, and the fix will appear in next alpha release. 

Just to make sure, could you provide `java -version` output?

**Comment by e5l** [comment]
Unfortunately "https://elster.de" use `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` encryption which is currently unsupported in `CIO` engine.
`TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` implementation WIP.

 Consider using `Apache` engine for now.

**Comment by henry1986** [comment]
Using Apache is not really an option, because we want to use websockets ;) 

Actually, elster.de was just an example, we use different websites and I have looked with chrome, what the cipher suite is:

The connection to this site is encrypted and authenticated using TLS 1.2 (a strong protocol), ECDHE_RSA with P-256 (a strong key exchange), and AES_128_GCM (a strong cipher).

Is this currently not supported, too? Or can I make a build with the master branch and use that?

**Comment by e5l** [comment]
Fixed in `master`
