### ISSUE TITLE
Client - NativePRNGNonBlocking SecureRandom not available on Windows

### ISSUE THREAD

**Issue by raharrison** [ktorio/ktor#441]
The `randomAlgorithm` defined in `TLSClientSession` is set to `NativePRNGNonBlocking`, but this is not available on Windows machines.

Attempted creation of the `SecureRandom` results in a `java.security.NoSuchAlgorithmException`.

Presumably have to fallback to `SecureRandom.getInstanceStrong();` on Windows even though it blocks?

**Comment by e5l** [comment]
Hi, @raharrison. Thanks for the report.
You could configure it through `HttpsConfig`:
```
HttpClient(CIO.config {
    https.apply {
        randomAlgorithm = "..."
    }
})
```

**Comment by raharrison** [comment]
Ah nice, thanks for the quick response!

**Comment by mohit-gurumukhani** [comment]
Hey! I would like to use this in common  module. Unfortunately, CIO is available for jvm modules only and the base engine for common does not allow for https. Is there some other way around this?

**Comment by e5l** [comment]
Fixed in `master`.
