### ISSUE TITLE
Error Get session with wrong header

### ISSUE THREAD

**Issue by VincentBrule** [ktorio/ktor#445]
Hello,
I have a problem when I do : call.sessions.get<MySession>() with a wrong header. I have the following error 2018-06-18 15:59:07.681 [nettyCallPool-4-1] DEBUG Application - Failed to lookup session: java.util.NoSuchElementException: No session data found for id 684eb3846f0441113ab51e24471b8062f1d30f5290a11046d17d5725470fdce7.

"For unexistant sessions that are not available, would be like if no session was provided and you can do whatever you need in your route handler"

Thank for your help !

**Comment by cy6erGn0m** [comment]
Why is it a problem? This message is logger at DEBUG log level. It doesn't break anything and `application.sessions.get<T>()` should return `null`

**Comment by pmorch** [comment]
In my opinion, this is a problem because libraries should not log anything by default. Especially if the user of the library can't do anything about it. And an exception in this case no less. I assumed I was using some interface or API wrong at first...

**Comment by pmorch** [comment]
And for the next guy looking for what is going on: I was using 

```
cookie<MyType>("mycookie", storage = SessionStorageMemory()) {
    ...
}
```

When I've run the application once it has set a cookie in the browser. If the app is restarted, the cookie is still set in browser and therefore sent to the app, but not found in the session storage in memory in the app's new `SessionStorageMemory`. Hence the debug line. 

My debugging shows that it is logged before `call.sessions.get()` is called (contrary to what the OP says).
