### ISSUE TITLE
Exception close cause not propagated on other end of websocket connection

### ISSUE THREAD

**Issue by coder82** [ktorio/ktor#446]
If I close the socket like this on one side of the connection:

```
catch(e:Throwable) {
            close(e)
        }
```

on the other side, on receive:

```
    private fun filterTestCampus(tap:TestApplicationEngine, customer:String, query:String, verify:(Container<CalendarData>?) -> Unit = {}) {
        tap.handleWebSocketConversation("/$ctx/ws/afClient/$customer/1016?$query") {incoming, _ ->
            val frame = incoming.mapNotNull {it as? Frame.Text}.receive()
            val result = validateJson(DeSerializers.calendarDataDeSerializer, removeFixedJson(frame.readText()))
            verify(result)
        }
    }
```

I don't get the original exception, all I get is the standard:
kotlinx.coroutines.experimental.channels.ClosedReceiveChannelException: Channel was closed

I should receive whatever exception I throw on the oder side as a reason for the closure, but that doesn't come through, I get only the standard exception when calling receive on a closed channel.

**Comment by e5l** [comment]
Hi, @coder82. Thanks for the report. 
It looks like you try to throw an exception on a client and catch it on a server. There is no way to pass exception over the network for now. And the `TestApplicationEngine` behavior tries to be the same as a real engine.

If it's the different case, could you provide some additional about where you throw and catch the exception?
