### ISSUE TITLE
Support: Static Content

### ISSUE THREAD

**Issue by vpasquier** [ktorio/ktor#447]
Hello!

I'm sorry in advance to use this channel, I have asked here first a small question about static content I'm struggling with: https://stackoverflow.com/questions/50901472/ktor-static-content-routing

If you have any advice about this topic, I would really appreciate. Thank you in all cases for this framework I love to work with. And sorry for the pollution. Don't hesitate to tell me if there is a more appropriate platform for questions and support.

**Comment by vpasquier** [comment]
oops i reopen the issue if you needed to document this use case.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-775">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed, see origin issue.
