### ISSUE TITLE
HttpClient: Support POST calls with MultiPart data

### ISSUE THREAD

**Issue by soywiz** [ktorio/ktor#448]
Requested at Slack

**Comment by soywiz** [comment]
Once implemented, we should update the sample to use it: https://github.com/ktorio/ktor-samples/tree/master/other/client-multipart

**Comment by e5l** [comment]
Implemented here https://github.com/ktorio/ktor/commit/4760a3670edb21f80ad1094f3ed32c6542d82f25

**Comment by e5l** [comment]
in `master`
