### ISSUE TITLE
Ktor with Apache Http Server?

### ISSUE THREAD

**Issue by Buzzele** [ktorio/ktor#451]
Hi,

is it possible to use Ktor on an Apache HTTP Server?

Best Regards

**Comment by cy6erGn0m** [comment]
ktor doesn't support mod_* yet however you can setup Tomcat with [mod_jk](http://tomcat.apache.org/connectors-doc/) and deploy ktor application into it

**Comment by Buzzele** [comment]
Ok, thanks
