### ISSUE TITLE
TypeInfo should be a data class

### ISSUE THREAD

**Issue by JLLeitschuh** [ktorio/ktor#459]
Currently, you are unable to do the following:
```kotlin
assertEquals(typeInfo<List<String>>(), typeInfo<List<String>>)
```

This makes it difficult to test that these objects are being created correctly when writing libraries that need to produce these types.

**Comment by e5l** [comment]
Hi, @JLLeitschuh. Thanks for the report.
Could you provide any use case of such comparisons?

**Comment by JLLeitschuh** [comment]
I'm working on the swagger code generator for Ktor.
I have tests that look like this:
```kotlin
    class GenericSubModel<S>(val value: S)
    class ModelWithNestedGeneric<T>(val subModelElement: GenericSubModel<T>)

    @Test
    fun `generic type extraction`() {
        val typeInfo = typeInfo<ModelWithNestedGeneric<String>>()

        val property = ModelWithNestedGeneric::class.memberProperties.first()

        val typeInfoForProperty = typeInfo<GenericSubModel<String>>()

        assertEqualTypeInfo(typeInfoForProperty, property.returnTypeInfo(typeInfo.reifiedType))
    }

    @Test
    fun `extract generic sub-model element`() {
        val modelWithDiscovered =
            createModelData(typeInfo<ModelWithNestedGeneric<String>>())

        assertEqualTypeInfo(typeInfo<GenericSubModel<String>>(), modelWithDiscovered.second.first())

        val property = modelWithDiscovered.first.properties["subModelElement"]!!
        property.`$ref`.should.equal("#/definitions/GenericSubModelOfString")
    }
```

You can see other related tests here:
https://github.com/JLLeitschuh/ktor-swagger/pull/1

This is part of my work for this issue which I'd also love feedback on.
https://github.com/ktorio/ktor/issues/453

**Comment by e5l** [comment]
Ok, now I see. We'll consider to add it in next alpha release.

**Comment by JLLeitschuh** [comment]
Thanks @e5l!

**Comment by e5l** [comment]
No problem. We always happy to have an issue or pull request :)
