### ISSUE TITLE
WebSocket outbound channel blocking on send()

### ISSUE THREAD

**Issue by sanity** [ktorio/ktor#462]
I'm finding that after a bunch of messages have been sent successfully, the call to send() suddenly blocks.  The fact that it's a continuation makes it particularly difficult to figure out why it is blocking.

This is version 0.9.3

**Comment by sanity** [comment]
Oh, both isFull and isClosedForSend were false immediately before calling send.

**Comment by sanity** [comment]
Possible that exceptions are being swallowed here: https://github.com/ktorio/ktor/blob/master/ktor-http-cio/src/io/ktor/http/cio/websocket/WebSocketWriter.kt#L35 (per @soywiz )

**Comment by sanity** [comment]
I think I found a workaround, which was to switch from Netty to Jetty.  Not ideal, but at least I'm not blocking.

**Comment by e5l** [comment]
Hi, @sanity. Could you reproduce the issue with ktor `1.0.0-alpha-3`?

**Comment by sanity** [comment]
@el5 Apologies, not easily from my current codebase :(
