### ISSUE TITLE
Ktor client has no access to useful `OutgoingContent` implementations

### ISSUE THREAD

**Issue by rocketraman** [ktorio/ktor#465]
Currently, most of the `OutgoingContent` implementations are in the `ktor-server-core` artifact e.g. `LocalFileContent`, `JarFileContent`, `WriterContent`, etc. This artifact is not on the classpath for a ktor client-only application, and therefore are not accessible to the code using the client.

Can these implementations be moved to a common jar, like `ktor-http`?

cc: @soywiz

**Comment by e5l** [comment]
Hi, @rocketraman. Thanks for the issue
