### ISSUE TITLE
Add support for the SameSite cookie attribute

### ISSUE THREAD

**Issue by mdr** [ktorio/ktor#466]
It would be useful if ktor was able to set the `SameSite` attribute on a cookie, including as part of the sessions support (`CookieIdSessionBuilder`).

https://www.owasp.org/index.php/SameSite

**Comment by marshallpierce** [comment]
Since this is a normal "key-value" cookie attribute (unlike, say, httponly), you can do this with the existing `extensions` mechanism:

```
cookie.extensions["SameSite"] = "lax"
```

I wouldn't object if there was a type safe way to do that, but I don't have a problem with the above either.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-770">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
