### ISSUE TITLE
of multipart request, part.dispose should be called explicitly?

### ISSUE THREAD

**Issue by kobe2000** [ktorio/ktor#469]
Hi
  When I test file upload function, I found the temporary files used by file uploading are never deleted. Should I call part.dispose manually?

**Comment by cy6erGn0m** [comment]
Unfortunately yes. Perhaps we can change it in the future

**Comment by trumpetlicks** [comment]
I am running a system where the intent IS to keep the entire file in RAM, not hitting the disk at all, so I find this fairly disappointing that it writing anything.  I am trying to perform operations as fast as I can, and any disk access lowers performance in an environment where the data is transient.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-768">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Answered
