### ISSUE TITLE
Implementing micrometer.io metrics in Ktor

### ISSUE THREAD

**Issue by dave08** [ktorio/ktor#474]
I wonder if Ktor will be implementing micrometer.io metrics, vert.x seemed to do it just for the popularity of Prometheus on Kubernetes https://vertx.io/blog/eclipse-vert-x-metrics-now-with-micrometer-io/.

If someone would want to start an implementation, what would be an overview of what need to be done?

**Comment by dave08** [comment]
Here's the pull request for starters: https://github.com/dave08/ktor/pull/1

**Comment by michael-barker** [comment]
Will this be in the 1.0 release for Kotlin 1.3?

**Comment by dave08** [comment]
There's https://github.com/ktorio/ktor/pull/480 currently open with a few little adjustments left. I won't have time until about a week and a half to do this though. Comments are also appreciated if there might be something missing. @michael-barker

**Comment by dave08** [comment]
But it currently works as is (and is being used in internal projects), so you could always just copy the code over and add the deps.

**Comment by michaelbannister** [comment]
#480 is replaced by #718. Really keen to see Micrometer support as it's much more Prometheus-friendly.

**Comment by JotBePunkt** [comment]
#718 is replaced now by #1037
