### ISSUE TITLE
Unable to transform request

### ISSUE THREAD

**Issue by martmists** [ktorio/ktor#475]
Content:
```kotlin
data class CreateAccountContent(
        val id: Int,
        val password: String
)
```
Main.kt:
```kotlin
fun main(args: Array<String>){
    val handler = DatabaseHandler()
    val server = embeddedServer(Netty, port = 12345) {
        routing {
            // ...
            post("/account"){
                try {
                    val post = call.receive<CreateAccountContent>()
                    if (handler.createUser(post)) {
                        call.respond(HttpStatusCode.OK, "OK")
                    } else {
                        call.respond(HttpStatusCode.BadRequest, "BAD")
                    }
                } catch (e: Exception) {
                    println(e)
                }
            }
        }
    }
    server.start(wait = true)
}
```
Curl request:
```curl
curl --request POST \
     --header "Content-Type: application/json" \
     --data '{"id": 7, "password": "ABCDEF"}' \
     http://localhost:12345/account
```
Output:
```kotlin
io.ktor.request.CannotTransformToTypeException: Cannot transform this request's content to class com.martmists.moneyservice.content.CreateAccountContent
```

Alternatively, I have tried the following Lua code: 
```lua
http.post("http://localhost:12345/account",  -- url
          "id=7&password=ABCDEF")  -- POST Body
```

**Comment by soywiz** [comment]
You have to install the ContentNegotiation feature:  https://ktor.io/features/content-negotiation.html

**Comment by martmists** [comment]
How would I use this to convert any POST request with the correct body (standard or json) to be converted?

**Comment by martmists** [comment]
Managed to get most of this working, but `application/x-www-form-urlencoded` seems to not be handled at all. Any reason why?

**Comment by soywiz** [comment]
`application/x-www-form-urlencoded` is handled differently:
https://ktor.io/servers/requests.html#receiving

`val postParameters: Parameters = call.receiveParameters()`

You would normally use `application/xwww.form-urlencoded` for handling HTML forms and `JSON` for APIs.

**Comment by martmists** [comment]
Due to the nature of this application, a route should be able to handle both, as the two applications use their own preferred method, json versus forms

**Comment by soywiz** [comment]
Converters use the Content-Type for deciding which one to use (check this https://github.com/ktorio/ktor/blob/master/ktor-features/ktor-jackson/src/io/ktor/jackson/JacksonConverter.kt ), other than that, you have to do it manually right now.

When you call `call.respondText` you can specify a `contentType` that will be used to choose the right converter

**Comment by martmists** [comment]
```kotlin
override suspend fun convertForReceive(context: PipelineContext<ApplicationReceiveRequest, ApplicationCall>): Any? {
        val request = context.subject
        val channel = request.value as? ByteReadChannel ?: return null
        val reader = channel.toInputStream().reader(context.call.request.contentCharset() ?: Charsets.UTF_8)
        val result = mutableMapOf<String, Any>()
        for (pair in reader.readText().split('&')) {
            val strings = pair.split("=")
            val decoded = URLDecoder.decode(strings[1], "UTF-8")
            val arg = try {
                decoded.toInt()
            } catch (e: Exception) {
                decoded
            }
            result[strings[0]] = arg
        }
        println(result.map { e -> "${e.key} -> ${e.value}"})
        return result.toMap()
    }
```
The println statement has the correct values (prints: `[id -> 7, jwt -> nojwt]`), but when looking at the contents it still seems to fail. It has been registered with
```kotlin
    val server = embeddedServer(Netty, port = 12345) {
        install(ContentNegotiation){
            jackson {

            }

            register(ContentType.Application.FormUrlEncoded, BodyConverter())
        }
```
And the error is `
io.ktor.request.CannotTransformToTypeException: Cannot transform this request's content to class com.martmists.moneyservice.content.CreateAccountContent` despite having the id and jwt data.

**Comment by soywiz** [comment]
@martmists can you join the Slack #ktor channel? http://slack.kotlinlang.org/ Since troubleshooting requires bidirectional feedback, it would be faster, and other people can help there too.

**Comment by martmists** [comment]
Is there a service I could use that doesn't require me to get an account on yet another service? (IRC or Discord for example)

**Comment by martmists** [comment]
I'm there, waiting for you to reply.

**Comment by NanoSpicer** [comment]
So what was the solution at the end of the day??

**Comment by sokarcreative** [comment]
Same issue here :/

**Comment by theothermattm** [comment]
For anyone else who hits this, my issue was that I mistakenly `install`ed `ContentNegotiation` inside the `routing` block and it should have been done outside it.
