### ISSUE TITLE
Missing Ktor HTTP Client For Linux

### ISSUE THREAD

**Issue by napperley** [ktorio/ktor#479]
Ktor's HTTP client library has ports for multiple platforms. There is no Kotlin Native Linux [port](https://github.com/ktorio/ktor/tree/mpp-client/ktor-client) (incl amd64 and armv7). Having a port would provide the following advantages for Kotlin Native programs targeting Linux (amd64/armv7):

- Lower maintenance (only need to deal with ARC for memory management, instead of dealing with manual memory management via [C interop](https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md))
- Decreased learning curve (using Kotlinic style APIs that Kotliners are used to, and makes interop *seamless*)
- Increased ROI (can use the **core** APIs on other platforms that the Ktor HTTP client library supports)

There is a [Serverless Function project](https://github.com/JetBrains/kotlin-native/pull/1746#discussion_r202273385) using Kotlin Native (targets Linux amd64) that would be a good use case for the port.

**Comment by e5l** [comment]
Hi, @napperley. Thanks for the request.
We'll consider adding Linux-engine implementation in near future.

**Comment by luca992** [comment]
@e5l Is there any technical reason you guys are only generating a native framework for ios? Or is it just that you guys haven't gotten around to it yet? I was able to compile a Klibrary targeting ios without a problem.

**Comment by napperley** [comment]
> Is there any technical reason you guys are only generating a native framework for ios? Or is it just that you guys haven't gotten around to it yet? I was able to compile a Klibrary targeting macos_x64 without a problem with the eap13 branch.

What does MacOS have to do with Linux?

**Comment by luca992** [comment]
@napperley Well sorry, I haven't actually tested setting the target to linux_x64 yet. But I am assuming that will also work just fine. Only reason I brought up compiling for macos is that it also is not targeted... So I am thinking Linux is not targeted for the same reason macos is not targeted.

**Comment by e5l** [comment]
Hi, @luca992.
@luca992, I'll test `macos_x64` target and publish the artifacts if everything is fine.

Unfortunately, Linux x64 target wouldn't work for now.

**Comment by luca992** [comment]
@e5l 
I see, too bad. Is windows support also a definite no for now?

Well regarding macos, while I can compile a klib that targets macos_x64... my actual http requests are not working.

I have tried a simple program like:
    
    import kotlinx.coroutines.runBlocking
    import io.ktor.client.engine.ios.*
    import io.ktor.client.*
    import io.ktor.http.*
    import io.ktor.client.request.*


    fun main(args: Array<String>) = runBlocking<Unit> {
        val client = HttpClient()
        val htmlContent = client.get<String>("https://en.wikipedia.org/wiki/Main_Page")
    
        println("$htmlContent")
        return@runBlocking 
    }

it hangs at `client.get<String>("https://en.wikipedia.org/wiki/Main_Page")`

I can make a seperate issue for macos if you would like

**Comment by cy6erGn0m** [comment]
Should be fixed in #777

**Comment by e5l** [comment]
Merged in `master`
