### ISSUE TITLE
Memory leak when GZIP compression is enabled

### ISSUE THREAD

**Issue by iSynaptic** [ktorio/ktor#489]
Steps to reproduce:

Take the "Hello World" sample application from the README, add gzip compression to the embeddedServer configuration, run the app, and hit it with a few thousand requests per second using something like [wrk](https://github.com/wg/wrk) or [ganda](https://github.com/tednaleid/ganda).  It will quickly eat up all the available system memory and then get killed by the OOMKiller.  The leaked memory doesn't appear to be visible to the JVM runtime (the JVM heap stays within the configured max), so I'm assuming it is leaking in some native code.  The HTTP request doesn't need to include headers asking for a compressed response - reproducing the issue only requires that the gzip feature be included in the embeddedServer configuration.

Reproduced Using:
ktor 0.9.3
Ubuntu 16.04.4

**Comment by cy6erGn0m** [comment]
You are absolutely right. There is a leak of native deflater.

**Comment by iSynaptic** [comment]
Is this something the ktor team can address or does a issue/bug need to be opened somewhere else?

**Comment by iSynaptic** [comment]
Just noticed your commit (`5cee549`). Not a leak in the native code, just forgot to signal the native code that the memory could be released?

**Comment by cy6erGn0m** [comment]
Yes, because this class is not documented and release method called "end" that is not obvious.

**Comment by iSynaptic** [comment]
Excellent. This fix is confirmed?

Looking at the  Javadoc documentation for the `Deflater` class (and the source, the "real" documentation), the end method is called by the `finalize()` method. So although it wouldn't be immediate, wouldn't the native memory get freed when `Deflater` instance is finalized?  Is there any reasons the JVM would consider these `Deflater` objects not eligible for garbage collection? I suppose it might not have enough memory pressure to trigger garbage collection....

**Comment by iSynaptic** [comment]
I confirmed it's a lack of memory pressure causing `finallze()` not to be called.  I ran my testbed with only `128MB` of heap space to encourage memory pressure and the `end()` method is being called (via the `finalize()` method).

**Comment by cy6erGn0m** [comment]
Exactly, we pay attention to memory pressure in ktor core and default pipeline

**Comment by cy6erGn0m** [comment]
Fixed in 0.9.4
