### ISSUE TITLE
StaticContentResolution: problem with dot in resourcePackage

### ISSUE THREAD

**Issue by andreas-mausch** [ktorio/ktor#494]
Hi,

https://github.com/ktorio/ktor/blob/aa29ebcd48962e7bb3d80638c67c3fc45d640db3/ktor-server/ktor-server-core/src/io/ktor/content/StaticContentResolution.kt#L20

here it replaces dots with slashes (probably to translate package names to paths).

I'd like to load static files from a webjar:

```
static("static") {
  resources("/META-INF/resources/webjars/vue/2.5.16/dist")
}
```

now, the dots are replaced by slashes, causing the resolution to fail. How can I solve this?

![kotlin staticcontentresolution fail](https://user-images.githubusercontent.com/1736847/43038141-79693840-8d14-11e8-95af-013af9ce7867.png)

**Comment by viniciusccarvalho** [comment]
I was just thinking about contributing with webjar support. It would be nice to have it as a feature such as `install(webjars)` and then having any `/webjars/*` assets to be handled by the `webjars-locator` I'd love to give this a spin as a first PR ir no one else wants to take this

**Comment by andreas-mausch** [comment]
Sounds perfect to me. I'd appreciate it a lot. :)

**Comment by magro** [comment]
Is this resolved now with the webjars plugin?

**Comment by andreas-mausch** [comment]
@magro Sounds promising. I'll check it out.

**Comment by andreas-mausch** [comment]
I can confirm this is resolved now. :)

Thank you very much @viniciusccarvalho @cy6erGn0m @e5l @magro
