### ISSUE TITLE
Ktor HTTP Server on Android 5.0 (API 21) leads to an error

### ISSUE THREAD

**Issue by matths** [ktorio/ktor#495]
Running the Ktor embedded HTTP Server in an Android app on a real Android 5.0 device (Lenovo Tab3 Essential 7) or in the Emulator leads to exactly the error described already [at stackoverflow](https://stackoverflow.com/questions/49945584/attempting-to-run-an-embedded-ktor-http-server-on-android) by someone else.
When running the same app out of Android Studio in the Emulator with Android 7, it is working well without an error.

The basic code that leads to the error:
`val server = embeddedServer(Netty, port = 8080) {
            routing {
                get("/") {
                    call.respondText("Hello World!", ContentType.Text.Plain)
                }
            }
        }
`

The Error / Stacktrace:
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.tabelos.tabelos, PID: 4028
                  java.lang.NoClassDefFoundError: io.ktor.application.ApplicationEvents$subscribe$1
                      at io.ktor.application.ApplicationEvents.subscribe(ApplicationEvents.kt:18)
                      at io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:29)
                      at io.ktor.server.engine.BaseApplicationEngine.<init>(BaseApplicationEngine.kt:15)
                      at io.ktor.server.netty.NettyApplicationEngine.<init>(NettyApplicationEngine.kt:17)
                      at io.ktor.server.netty.Netty.create(Embedded.kt:10)
                      at io.ktor.server.netty.Netty.create(Embedded.kt:8)
                      at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:50)
                      at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:40)
                      at io.ktor.server.engine.EmbeddedServerKt.embeddedServer$default(EmbeddedServer.kt:27)
                      at com.tabelos.tabelos.MainActivity.runServer(MainActivity.kt:48)
                      at com.tabelos.tabelos.MainActivity.access$runServer(MainActivity.kt:21)
                      at com.tabelos.tabelos.MainActivity$runnable$1.run(MainActivity.kt:43)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

I would welcome any help or advice, because I definitely need to target Android 5.0 because of the mentioned Lenovo Tab 3 Essential 7 Tablets, I'm using.
I already tried downgrading kotlin, ktor versions without any luck so far.

**Comment by soywiz** [comment]
Have tried to reproduce the error. But I'm having troubles (other kind of errors at editing time related to Android SDK not specified). Can you provide a zip file or so with the android project that I can try?

**Comment by matths** [comment]
I quickly created a repo for you https://github.com/matths/tabelos

**Comment by soywiz** [comment]
Can't get it working either with my Android Studio 3.1.3, I have the same problem. But if I create a project from scratch targeting the latest version, it works for me. I'm not too familiar with Android Studio. Any tips? If I can get it working I can try to guess what's going on.

![screen shot 2018-07-22 at 18 08 24](https://user-images.githubusercontent.com/570848/43047647-bdc2b1bc-8dda-11e8-9913-1a8203929e9d.png)
![screen shot 2018-07-22 at 18 09 05](https://user-images.githubusercontent.com/570848/43047648-bddb2c1a-8dda-11e8-933b-1cde00971c58.png)

**Comment by matths** [comment]
@soywiz you probably need to download / check SDKs for minsdkversion and targetsdkversion. You find that at Tools > SDK Manager.
![bildschirmfoto 2018-07-22 um 18 30 29](https://user-images.githubusercontent.com/264769/43047800-6b10b1b4-8ddd-11e8-862c-d113b216c508.jpg)

**Comment by soywiz** [comment]
Yes I checked that before already.

![screen shot 2018-07-22 at 19 32 15](https://user-images.githubusercontent.com/570848/43048323-05baf5a0-8de6-11e8-9f8d-509a32470e0d.png)

Maybe I have something bad installed. But tried reinstalling Android Studio without luck. So I'm afraid I cannot help you at this point.

**Comment by matths** [comment]
I was facing the "Error: Please select Android SDK" some time before, too. I don't know exactly what to do, but I'm sure I tried things similar to these suggested at [stackoverflow here](https://stackoverflow.com/questions/34353220/android-studio-please-select-android-sdk).

I really hope for help with the initial problem, because the Android 5.0 is a fixed requirement in my use case. ;)

**Comment by cy6erGn0m** [comment]
`java.lang.NoClassDefFoundError: io.ktor.application.ApplicationEvents$subscribe$1` that should be a part of ktor so most likely it is wiped out by your buildchain. Do you have proguard enabled?

**Comment by cy6erGn0m** [comment]
It's a lambda instance passed as an argument to `computeIfAbsent`

**Comment by cy6erGn0m** [comment]
Added an answer at SO

**Comment by cy6erGn0m** [comment]
@soywiz according to comment at SO ktor server runs well on Android 7 (API 24) so we probably could note it somewhere in the docs until we will fix it somehow

**Comment by soywiz** [comment]
https://ktor.io/quickstart/faq.html#android-support

**Comment by matths** [comment]
Good for ktor.io that we did clarify. Sad for me, as I'll have to switch to another server library to get my ideas come to life. Thank you @cy6erGn0m, @soywiz for your support.

**Comment by cosminstefanxp** [comment]
So, there's no way to get this fixed for real?

**Comment by matths** [comment]
Well, I switched to NanoHTTPD for my Android 5 WebServer inside my app needs.

**Comment by dkrivoruchko** [comment]
Looks like AGP 4.0 will desugar it [https://developer.android.com/studio/preview/features#j8-desugar](https://developer.android.com/studio/preview/features#j8-desugar) so it should work

**Comment by gnarea** [comment]
I confirm I can run ktor on Android 5.0 with Android Studio 4. :tada: 

There's only one issue I've come across but the fix is easy: https://stackoverflow.com/a/62760629/129437

**Comment by gnarea** [comment]
FYI, I created this minimal repo to demo ktor 1.6 on Android 5+: https://github.com/gnarea/minimal-ktor-server-android

**Comment by kambojumang** [comment]
> FYI, I created this minimal repo to demo ktor 1.6 on Android 5+: https://github.com/gnarea/minimal-ktor-server-android

Hello @gnarea 
After following you amazing solution for Android API 21, I have used Ktor in my application. Ktor is wonderful
 At the end stage I realized that Ktor Server on Android API 21, routing {} will not work in background. 

Is there any amazing fix to it :: If I can run Ktor in server on any background thread, so it will be available even when app is in background.  I have already try starting ktor in Globlescope, didn't work. 

Thanks and Regards,
Umang Kamboj

**Comment by gnarea** [comment]
@kambojumang, we're running a ktor server in the background in https://github.com/relaycorp/relaynet-gateway-android, in case you want a real-world example. Here's the ktor server implementation: https://github.com/relaycorp/relaynet-gateway-android/tree/3680176902629b045a7231a2207d0585a20a8998/app/src/main/java/tech/relaycorp/gateway/pdc/local

**Comment by gamarmustafa** [comment]
> Looks like AGP 4.0 will desugar it https://developer.android.com/studio/preview/features#j8-desugar so it should work

desugaring fixed the issue. thanks for the tip!
