### ISSUE TITLE
Option for TestApplicationEngine to make a real request

### ISSUE THREAD

**Issue by jeiea** [ktorio/ktor#496]
Current `TestApplicationEngine` has the advantage that it can test application without making a real request. But I have a difficulty to check how request/response wrong.
I want to use Fiddler, a web proxy test tool, to see whole request/response. But it's not possible because there's no real traffic.
Is there a way to deal with this? If not, how about to give an option for testing with a real web request?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-766">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
