### ISSUE TITLE
Ktor improvements

### ISSUE THREAD

**Issue by e5l** [ktorio/ktor#497]
Would be nice to have some useful extensions in ktor:

- [ ] `ApplicationCall.respond(OutgoingContent)`
- [ ] `ApplicationCall.respond(ByteReadChannel, contentType = OctetStream)`
- [ ] `ApplicationCall.respond(ByteReadPacket, contentType = OctetStream)`

**Comment by cy6erGn0m** [comment]
There is one small issue: we have several extensions called `respondText`, `respondBytes` and so on. We have to decide what names should we use

**Comment by e5l** [comment]
Obsolete
