### ISSUE TITLE
ktor intellij idea plugin doesn't create a src folder and other folder  when creating a project

### ISSUE THREAD

**Issue by kldMohammed** [ktorio/ktor#499]
ktor intellij idea plugin doesn't create a src folder and other folder  when creating a project it only crreate gradle file 

i use idea CE  2018.2 
os :windwos

ktor plugin :0.0.5

![untitled](https://user-images.githubusercontent.com/17613367/43316201-2794699a-91a1-11e8-9ddf-77a41fb44fac.png)

i try to create more than one project and gave me the same structure

**Comment by soywiz** [comment]
Confirmed to happen on Windows (happens with CE and Ultimate, JDK8 and 10, gradle, maven and any selected features). Going to investigate. Thanks for reporting!

**Comment by raharrison** [comment]
Go to Settings->Build,Execution,Deployment->Gradle and tick 'Create directories for empty content roots automatically'.

**Comment by soywiz** [comment]
Fixed here: https://github.com/ktorio/ktor-init-tools/commit/92a652e132804cfb959219ab3a39eafd56bc7bb9

It was throwing an exception related to windows separator '\', but not reported at all, for files inside two or more subfolders (that was the case of the wrapper binaries).

Will be available in the next version.
