### ISSUE TITLE
Isolated module for connector

### ISSUE THREAD

**Issue by dybarsky** [ktorio/ktor#501]
Hi. I'm trying to make multiple connectors. And I want to assign specific module to specific connector. Here is my code: 
```
fun main(args: Array<String>) {
    val environment = applicationEngineEnvironment {
        module {
            config()
        }
        connector {
            port = 8080
            module { getFist() }
        }
        connector {
            port = 8081
            module { getSecond() }
        }
    embeddedServer(CIO, environment).start(wait = true)
}
```

The  module A: 
```
fun Application.getFirst() {
    routing {
        get("/") {
            println("first")
            call.respondHtml {
                body { p { +"PAGE 1" } }
            }
        }
    }
}
```

The  module B: 
```
fun Application.getSecond() {
    routing {
        get("/") {
            println("second")
            call.respondHtml {
                body { p { +"PAGE 2" } }
            }
        }
    }
}
```

So, I expect the module A to be invoked while request to `localhost:8080` and module B to be invoked while opening `localhost:8081`. 
But they both are invoked.

---

Looking to source code, I realized the `module` function belongs to `ApplicationEngineEnvironmentBuilder`. So, nesting `module` into `connector` makes no difference in behaviour.

My questions is:
Is it possible to define modules for specific connector? What is the good practice to do that?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-765">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by dybarsky** [comment]
@oleg-larshin Thank you for letting me know. I will star YouTrack issue.
