### ISSUE TITLE
Question: Log first X bytes of a request.

### ISSUE THREAD

**Issue by bhandfast** [ktorio/ktor#505]
Hi,

For debug purposes I'm trying to log the first X bytes of a POST request on the server. Is there a way to do this with an interceptor? I've tried the following naive way of logging it (which doesn't work):

```kotlin
suspend private fun intercept(pipelineContext: PipelineContext<Unit, ApplicationCall>) {
      logger.info("Intercept");
      val stream = pipelineContext.context.request.call.receiveStream()
      stream.mark(1024)

      val bytes = stream.readBytes(1024)
      stream.reset()
}
```

Channels seem to be the underlying infrastructure for the stream, and that doesn't support mark/reset as far as I know. And they cannot be replaced as I understand it.

**Comment by e5l** [comment]
Hi, @bhandfast. Thanks to notice.

You could insert the interceptor that wraps channel in following way:
```
fun ByteReadChannel.logFirst(count: Int): ByteReadChannel = writer(DefaultDispatcher) {
    val source = this@logFirst
    
    val head = ByteArray(count)
    source.readFully(head)
    
    // perform logging of head here
    
    channel.writeFully(head)
    source.joinTo(channel) // or source.copyTo(channel)
}.channel
```
