### ISSUE TITLE
Basic WebSocket client example fails to compile

### ISSUE THREAD

**Issue by xSke** [ktorio/ktor#507]
This code:
```kotlin
package test

import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO
import io.ktor.websocket.WebSockets
import kotlinx.coroutines.experimental.launch

fun main(args: Array<String>) {
    launch {
        val client = HttpClient(CIO).config {
            install(WebSockets)
        }
    }
}
```

Fails to compile:
```
Error:(11, 13) Kotlin: None of the following functions can be called with the arguments supplied: 
public final fun install(client: HttpClient): Unit defined in io.ktor.client.HttpClientConfig
public final fun <TBuilder : Any, TFeature : Any> install(feature: HttpClientFeature<???, ???>, configure: ???.() -> Unit = ...): Unit defined in io.ktor.client.HttpClientConfig
```

This error occurs both on 0.9.3 and 0.9.4-alpha-2.

Is this me being dumb, or is this an issue? I can't find any example code of using WebSocket clients... at all, really.

**Comment by xSke** [comment]
Nevermind.

Turns out there's another (undocumented!) artifact (io.ktor:ktor-client-websocket) that adds the required client feature - it works now, although this should really be listed in the docs.

**Comment by soywiz** [comment]
It was referenced here: https://ktor.io/clients/http-client.html#websockets
But you are right, was not referenced in the right page ( https://ktor.io/clients/websockets.html ). I have fixed it already: https://github.com/ktorio/ktorio.github.io/commit/cc71463d7dc757a6fda7251d9594d65cf18bc89a
