### ISSUE TITLE
Some URLs treated as invalid format

### ISSUE THREAD

**Issue by Prototik** [ktorio/ktor#511]
Due to new mpp URL parser some URLs cannot be parsed:  
`http://localhost/foo:bar` due to `:` character  
`http://localhost/foo@bar` due to `@` character

[RFC1738](https://tools.ietf.org/html/rfc1738#section-5) allows it for HTTP segment:
```
hsegment       = *[ uchar | ";" | ":" | "@" | "&" | "=" ]
```

**Comment by e5l** [comment]
Hi, @Prototik. Thanks for the report.
It's obviously a bug and we fix it asap.

**Comment by e5l** [comment]
Fix in `master`.
