### ISSUE TITLE
`call.respond(someObj)` returns 404 silently, should be `500`?

### ISSUE THREAD

**Issue by freewind** [ktorio/ktor#512]
Code responds an object of class `Hello`:

```
fun main(args: Array<String>) {
    val server = embeddedServer(Netty, port = 8080) {
        routing {
            get("/") {
                val hello = Hello("Hello Ktor", System.currentTimeMillis())
                call.respond(hello)
            }
        }
    }
    server.start(wait = true)
}

data class Hello(val content: String, val timestamp: Long)
```

You can see there is no `ContentNegotiation` setup:

```
install(ContentNegotiation) {
    gson {}
}
```

When visit <http://localhost:8080>, it responds 404, without any error or warnings.

```
curl -I http://localhost:8080
HTTP/1.1 404 Not Found
Content-Length: 0
```

I think `404` means there is no such route defined in server, but in this case, I do defined `get('/')`, the real problem is `call.respond(hello)` fails internally. I think it should be `500` and with some warnings in server log.

**Comment by e5l** [comment]
Hi, @freewind. Thanks for the report.
@cy6erGn0m what do you think?

**Comment by cy6erGn0m** [comment]
curl's `-I` does `HEAD` request instead of `GET` so it simply doesn't match `get("/")`. However you can install `AutoHeadResponse` to get HEAD requests working in this scenario.

**Comment by cy6erGn0m** [comment]
Otherwise you can force curl to dump headers, `curl -D - http://loclahost:8080/`

**Comment by cy6erGn0m** [comment]
If you don't see a stacktrace in the log then you probably need to configure logger properly. See http://ktor.io/servers/logging.html for details

**Comment by freewind** [comment]
@cy6erGn0m  Thanks for helping my issue! Sorry for this issue !
