### ISSUE TITLE
`static()` routing responds `404` if specified a wrong directory

### ISSUE THREAD

**Issue by freewind** [ktorio/ktor#513]
```
fun main(args: Array<String>) {
    val server = embeddedServer(Netty, port = 8080) {
        routing {
            static("/") {
                staticRootFolder = File("./non-existent-static")
                default("index.html")
            }
        }
    }
    server.start(wait = true)
}
```

The `staticRootFolder` is not existent (e.g. typo, or wrong understanding how ktor works)

```
curl -I http://localhost:8080
HTTP/1.1 404 Not Found
Content-Length: 0
```

It response `404`, and there is no any warning or error in server log. Which makes it very hard to find or guess where is the real problem, especially for a newbie of ktor

**Comment by cy6erGn0m** [comment]
Just answering here again just in case: `curl -I` does `HEAD` request wich is not handled by ktor by default. You need to setup `AutoHeadResponse` feature (http://ktor.io/features/autoheadresponse.html) or handle them explicitly.

**Comment by cy6erGn0m** [comment]
@soywiz Could you please add warning at static content page? (http://ktor.io/features/static-content.html)

**Comment by freewind** [comment]
@cy6erGn0m I think the main problem is not the `curl -I`, in the issue. 

If you use `curl -D - http://localhost:8080`, which still responds `404`:

```
HTTP/1.1 404 Not Found
Content-Length: 0
```

or use httpie:

```
$ http http://localhost:8080
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 0
```
