### ISSUE TITLE
ContentConverter for Protobuf

### ISSUE THREAD

**Issue by YuriDenison** [ktorio/ktor#517]
Currently only JSON converters supported out of the box (Gson, Jackson)
It would be nice to have Protobuf converter to be able to use (kotlin + retrofit + protobuf) on android client side and (ktor + protobuf) on server side.

It is quite common use case to migrate from Json to Protobuf in mobile projects in case of large amount of small objects passing to requests/responses. The reasons are simple - improved parsing performance, lower CPU usage than gson/jackson,  fixed protocol, api versioning etc.

On Android client side Retrofit supported Proto converter more than a year ago - https://github.com/square/retrofit/blob/master/retrofit-converters/protobuf/src/main/java/retrofit2/converter/protobuf/ProtoConverterFactory.java

**Comment by hartmut-co-uk** [comment]
+1
ideally via https://github.com/Kotlin/kotlinx.serialization ..?!

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-763">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
