### ISSUE TITLE
Auto push styleLink and others when using ApplicationCall.respondHtml

### ISSUE THREAD

**Issue by guicamest** [ktorio/ktor#525]
It would be really great if when using: [respondHtml](https://github.com/ktorio/ktor/blob/master/ktor-features/ktor-html-builder/src/io/ktor/html/RespondHtml.kt#L15), **styleLink**, **script** and **img** tags are "auto" pushed just like JSF does: https://www.ibm.com/developerworks/library/j-javaee8-servlet4/index.html

This way there is no need for this: 
```
get("/"){   
   call.push("some.css")
   ...
   call.respondHtml { head { styleLink("some.css") ...
   }
}
```

Of course there has to be some logic whether they are relative/absolute and it might require some collaboration from [kotlinx.html](https://github.com/Kotlin/kotlinx.html)

**Comment by cy6erGn0m** [comment]
It is possible via custom consumer-interceptor

**Comment by guicamest** [comment]
@cy6erGn0m Would you like me to implement it and submit a pull request?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-761">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Http2 push is deprecated. Closed
