### ISSUE TITLE
Tailcard parameter matcher capturest rest of its segment 

### ISSUE THREAD

**Issue by NekoiNemo** [ktorio/ktor#526]
Example:  
Using `get("explore{path...}")` handler, url ending with `/explore/log/server.log` will result in `call.parameters.getAll("path")` returning list containing: "explore, log, server.log", rather than just last 2

Using `get("explore/{path...}")`, however, returns only last 2 as expected

See https://kotlinlang.slack.com/archives/C0A974TJ9/p1534363258000100

**Comment by cy6erGn0m** [comment]
Why 2 components are expected? I'd expect it to be `"explore", "log", "server.log"` or `"", "log", "server.log"`. For sure `"explore{path...}"` and `"explore/{path...}"` are not the same patterns

**Comment by NekoiNemo** [comment]
Well, i guess 3 starting with "" would be most logical one. Then again, empty segments are a bit pointless. But in any case, i don't think "explore", located outside of part captured by parameter, should be included

**Comment by cy6erGn0m** [comment]
Fixed ignoring prefix
