### ISSUE TITLE
Can I set base path to ktor client?

### ISSUE THREAD

**Issue by jeiea** [ktorio/ktor#537]
What I expect:
```
val http = HttpClient(Apache.create()) {
  install(HttpBasePath) {
    basePath = "http://somewhere.in"
  }
}
http.get("/a") // => http://somewhere.in/a
http.get("http://a.b.com") // => http://a.b.com
```
I tried implementing the above feature, but I couldn't tell a "localhost" string is the something set or just default.

**Comment by gildor** [comment]
It would be a very useful feature because most of REST APIs is some host + base path (usually with API version), so you want to extract this part and use for all your reqests that use particular instance of HttpClient
Probably make sense to support new property `baseUrl/basePath ` that includes protocol, host and path prefix. IMO it's the most common way to specify base path.
One more open question how to override base path (not base host), maybe we should use the same behavior as Retrofit, which ahas baseUrl (host + basePath). if particular request path starts from `/` basePath will be ignored (request explicitly uses full path), otherwise basePath will be used

**Comment by qrezet** [comment]
Any update on this? 🤔

**Comment by jeiea** [comment]
https://ktor.io/clients/http-client/features/default-request.html
Maybe that feature can address this issue. But I can't sure that can prepend url pathname partially. If that could this issue can be closed.

**Comment by ScottPierce** [comment]
I'm not sure that this solves this. It only allows the setting of a default host, but not a base path from what I can see.

@jeiea could you please open this back up?

**Comment by rusnasonov** [comment]
`DefaultRequest` also allow the setting `URL` with path, but request doesn't join paths.

```
val client = HttpClient(){
    defaultRequest {
        url(URL("http://example.com/foo"))
    }
}
client.get("bar") // request to http://example.com/foo
```
```

**Comment by paslavsky** [comment]
This is works for me:
```
val client = HttpClient(){
    defaultRequest {
            url.host = "example.com"
            url.protocol = URLProtocol.HTTP
            url.encodedPath = "/foo/" + url.encodedPath
    }
}
client.get("bar") // request to http://example.com/foo/foo
```

**Comment by fluidsonic** [comment]
I've also stumbled over this now. I expected `defaultRequest` to set **defaults** which can be overridden.

```kotlin
val client = HttpClient {
    defaultRequest {
        url("https://example.com/foo/")
    }
}

client.get<…> { url.appendPath("graphql") } // appended to "https://example.com/foo/"
client.get<…> { url("https://otherdomain.com/foo") } // completely overwrites URL
```

The fact that defaults are applied **after** the specific per-request configuration is really confusing.

**Comment by sgarfinkel** [comment]
`defaultRequest` can be used to get this behavior, sort of:

```kotlin
val basepath = Url("https://example.com")

val client = HttpClient {
    defaultRequest {
        url.takeFrom(URLBuilder().takeFrom(basepath).apply {
            encodedPath += url.encodedPath
        })
    }
}

// calls https://example.com/foo/bar
client.get {
    url.path("foo", "bar")
}
```

Note that the `url` that is in scope in the `defaultRequest` block is the url defined in the calling request--in this case the `client.get { }` call.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-759">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by lyellss** [comment]
> `DefaultRequest` also allow the setting `URL` with path, but request doesn't join paths.
> 
> ```
> val client = HttpClient(){
>     defaultRequest {
>         url(URL("http://example.com/foo"))
>     }
> }
> client.get("bar") // request to http://example.com/foo
> ```

but how to change the default config?

**Comment by lyellss** [comment]
> I've also stumbled over this now. I expected `defaultRequest` to set **defaults** which can be overridden.
> 
> ```kotlin
> val client = HttpClient {
>     defaultRequest {
>         url("https://example.com/foo/")
>     }
> }
> 
> client.get<…> { url.appendPath("graphql") } // appended to "https://example.com/foo/"
> client.get<…> { url("https://otherdomain.com/foo") } // completely overwrites URL
> ```
> 
> The fact that defaults are applied **after** the more specific per-request configuration is really confusing.

I want to change the defaultRequest config when runing ,  if have the method qu change it ?

**Comment by Stexxe** [comment]
Unfortunately, the `DefaultRequest`'s config is immutable.
