### ISSUE TITLE
Corrupted files with low connection rate (Jetty)

### ISSUE THREAD

**Issue by cy6erGn0m** [ktorio/ktor#538]
According to users, if a user has poor connection some resources and scripts received by Chrome web browsers are corrupted

**Comment by Stexxe** [comment]
I was unable to reproduce it on [sample project](https://github.com/ktorio/ktor-samples/tree/master/feature/static-content) with `Jetty` engine and with activated slow 3G throttling.
Chrome 83.0.4103.116 (Official Build) (64-bit)

**Comment by cy6erGn0m** [comment]
@Stexxe Thanks for checking!

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-758">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
