### ISSUE TITLE
embeddedServer for CIO and Netty inconsistency

### ISSUE THREAD

**Issue by qwwdfsad** [ktorio/ktor#543]
CIO and Netty behave differently for simple hello-server (e.g. `netty-embedded` from samples)

`embeddedServer(Netty, commandLineEnvironment(args)).start()`  // Works
`embeddedServer(CIO, commandLineEnvironment(args)).start()` // Application exits right after `start` call

Even though one may use `start(wait = true)`, it would be nice for `CIO` to be a drop-in replacement for `Netty`

**Comment by Selbeforth** [comment]
Are they going to be made consistent at some point or is this a case of CIO requires to wait for thread related reasons so therefore it can't/won't be updated?

**Comment by Koriit** [comment]
I prefer CIO's behaviour. If your main function finishes then your application does too, which I find natural and correct.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-755">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
