### ISSUE TITLE
oauth2 misleading message on error 405 (wrong method) getting token

### ISSUE THREAD

**Issue by jarekczek** [ktorio/ktor#550]
When I get 405 Method Not Allowed error from oauth2 server, ktor gives me an error message: "unsupported content type */*".

I play with ktor and keycloak. When I forgot to set the requestMethod in oauth2 settings, I got this misleading message. The content is empty. In this case ktor should report 405 and not try to decode the content.

Probably in case of any unexpected http status, it should be reported as an error. Second thing, decoding should not be attempted on empty content, give a better message instead.

**Comment by cy6erGn0m** [comment]
Fixed in 1.0.0-beta-2
