### ISSUE TITLE
Fail to parse URL

### ISSUE THREAD

**Issue by e5l** [ktorio/ktor#553]
Fail to parse URL when `/` is missing between hostname and query parameters `?`

example: `https://www.test.com?test=ok&authtoken=testToken`

**Comment by olbpetersson** [comment]
My team have seen issues where the httpClient throws 'IllegalStateException: Invalid url format' when a url contains '~' (tilde). Tried this on both 0.9.3 and 0.9.4

**Comment by e5l** [comment]
The `~` character is not the valid part of URL according to rfc(https://tools.ietf.org/html/rfc3986).
 Please consider encoding `~` character for now.
