### ISSUE TITLE
[client] MPP WebSockets client

### ISSUE THREAD

**Issue by Prototik** [ktorio/ktor#556]
Since client is MPP now, it'll be great if websocket support also ported to MPP. Now it's jvm-only since http-cio is jvm module.

**Comment by orangy** [comment]
That's on the radar, but there is a long chain before we can get there.

**Comment by danthonywalker** [comment]
What's the status of this issue? I see `ktor-client-websocket` has some common stuff for WebSockets, but obviously not usable for common modules yet.

**Comment by e5l** [comment]
The `WebSocket` implementation is common between JVM, js, and Android.
Native implementation is on the way.

**Comment by danthonywalker** [comment]
Can I use the current implementations now? i.e. use common/jvm/js in my build.gradle? How would I go about doing that?

**Comment by Prototik** [comment]
That commit (e8de451d76c22e4466a5692975acfcc3edf17d4f) unreleased yet, so if you want to try mpp websockets - you must use git version of ktor for now. Or just wait for the next release ¯\_(ツ)_/¯

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-751">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
