### ISSUE TITLE
Setting multiple cache control directives is impossible with current API

### ISSUE THREAD

**Issue by coder82** [ktorio/ktor#557]
Using the install for CachingHeaders I want to configure it  in such a way it produces this header:

> Cache-Control: no-cache, no-store, must-revalidate

I cannot do it.
For example I tried this:

>         options { outgoingContent ->
>             when (outgoingContent.contentType?.withoutParameters()) {
>                 ContentType.Text.CSS -> CachingOptions(CacheControl.NoCache(null))
>                 else -> null
>             }
>         }
>         options { outgoingContent ->
>             when (outgoingContent.contentType?.withoutParameters()) {
>                 ContentType.Text.CSS -> CachingOptions(CacheControl.NoStore(null))
>                 else -> null
>             }
>         }
>    

it makes it twice:

> cache-control: no-cache
> cache-control: no-store

The best would be if options can return a lamda with a list of CachingOptions as return value, then the system would add all of them. Or allow caching options to accept varargs?

Also, why is "must revalidate" tied to max age?
See this, it can be also on it's own:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Examples

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-750">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in Ktor 1.4.2
