### ISSUE TITLE
ktor-http: [URLBuilder] Specifying a protocol with a default port value overwrites an already specified port

### ISSUE THREAD

**Issue by bradynpoulsen** [ktorio/ktor#561]
## Overview

| Library | Version |
|-|-|
| ktor-http | `0.9.4` |

Given the following execution,
```kotlin
val url = URLBuilder().apply {
    takeFrom(getenv("MYSQL_URL")) // import from "mysql://user:password@localhost:34567/myDb"
    protocol = URLProtocol("mysql", 3306)
}.build()
```

## Expected Outcome

I expected the default port to be used on the protocol only if a port was not explicitly specified

```kotlin
println(url) // "mysql://user:password@localhost:34567/myDb"
```

## Actual Outcome

The port is always overwritten when a protocol is set

```kotlin
println(url) // "mysql://user:password@localhost/myDb" (implying port `3306`)
```

https://github.com/ktorio/ktor/blob/a65667a6f0ca98128c38025f989bad7cb6da4576/ktor-http/src/io/ktor/http/URLBuilder.kt#L16-L18

## Suggested Resolution

https://github.com/ktorio/ktor/blob/a65667a6f0ca98128c38025f989bad7cb6da4576/ktor-http/src/io/ktor/http/URLProtocol.kt#L19

The default port on a URLProtocol that has not already been mapped is `-1`, represented by the following code:
```kotlin
val url = URLBuilder().apply {
    takeFrom(getenv("MYSQL_URL")) // import from "mysql://user:password@hostUsingDefaultPort/myDb"
}.build()
```

the following is built

```kotlin
println(url.port) // "-1"
```

Since this is the case, I propose that the `port` is only overwritten when the protocol would overwrite a port of `-1`

```kotlin
var protocol: URLProtocol by observable(protocol) { _, _, value -> 
    if (port == -1) {
        port = value.defaultPort 
    }
} 
```

## Current Workaround

Currently, my solution is to build the `Url` beforehand and check if a port was specified after applying the protocol
```kotlin
val url = URLBuilder().apply {
    val envUrl = Url(getenv("MYSQL_URL")) // import from "mysql://user:password@localhost:34567/myDb"
    takeFrom(envUrl)
    protocol = URLProtocol("mysql", 3306)
    if (envUrl.port > 0) {
        port = envUrl.port
    }
}.build()
```

**Comment by e5l** [comment]
Hi, @bradynpoulsen. It's the expected behavior.
If you specify the protocol by hand - it changes the URL port on the protocol default port.
In other cases, you have to always explicitly set the port after the protocol switch.

You could just reorder the builder statement:
```
val url = URLBuilder().apply {
    protocol = URLProtocol("mysql", 3306)
    takeFrom(getenv("MYSQL_URL")) // import from "mysql://user:password@localhost:34567/myDb"
}.build()
```

**Comment by bradynpoulsen** [comment]
Here's an example of outputting the resulting port if you did not explicitly set the port

```kotlin
val url = URLBuilder().apply {
    protocol = URLProtocol("mysql", 3306)
    takeFrom("mysql://user:pass@host/mySchema")
}.build()
println(url.port) // outputs -1
```

**Comment by e5l** [comment]
Let use `0` value for a port as the default value for the current protocol.
Server use `0` value for port auto selection.
