### ISSUE TITLE
[Bug][Routing] call.uri does not contain anything after # in url.

### ISSUE THREAD

**Issue by rnett** [ktorio/ktor#563]
For example, if I make a request to `localhost:8000/test/#page2?param=value` `call.uri` will be set to `/test/`.

This makes it impossible to get url params if you are using fragment identifiers (they don't show up in `call.request.queryParameters` either).

**Comment by rnett** [comment]
Yeah.  I see why the fragment itself wouldn't be sent, but the problem I'm running in to is that the url parameters (`?param=1&param2=2` etc.) also get cut off (because they end up after the fragment identifier).

**Comment by rnett** [comment]
I looked into it a bit more, it seems likely this is client side, and that adding the params after the # is bad practice anyways.

**Comment by e5l** [comment]
Thanks for the quick response. 

Closed.
