### ISSUE TITLE
[Regression Bug 0.9.4] Adding call.respond to pipeline throws java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by saltyJeff** [ktorio/ktor#566]
Hi,
I'm having trouble using call.respond anywhere in my application. If I add it, the application pipeline dies and the server exits.

[Error log](https://gist.github.com/saltyJeff/7218951b892562b3da4839285fbbbfc2)
[App Source](https://gist.github.com/saltyJeff/62a2e865f73cc31d446543dabc6b4d87)
[Gradle dependencies](https://gist.github.com/saltyJeff/fd14ae82106c7690470a953e04a4e4e7)

Machine: Windows 10, running in Intellij IDE

The strange thing is that if I use only `call.respondText`, the server can listen to messages. Using `call.respond` is what kills the app before it can start listening

Thanks in advance for any help

It might have been related to [this ticket](https://github.com/ktorio/ktor/issues/475), but the error specified there is more high level than my stack dump.

**Comment by saltyJeff** [comment]
I did more testing and this is a newly introduced error. Bug does not occur when using `$ktor_version 0.9.3`

**Comment by cy6erGn0m** [comment]
Could you please send relevant binary class files ?

**Comment by saltyJeff** [comment]
[error_proj.zip](https://github.com/ktorio/ktor/files/2376233/error_proj.zip)

JDK 1.8/ windows 10
Kotlin 1.2.61

**Comment by cy6erGn0m** [comment]
Hm, `out/production/...` - this means that you use IDEA's plugin to build your project rather than gradle. Which plugin version do you have? Which IDEA's version?

**Comment by saltyJeff** [comment]
IntelliJ IDEA 2018.2.3 x64
How do you figure out what gradle plugin version it's using?

Are you sure it has something to do with the gradle build version? Like I said it works when switching back to 0.9.3

**Comment by saltyJeff** [comment]
You were right, it worked perfectly after `gradlew run`.

Is this an error you have experienced before, or should I repost this on the IDEA issues page.

The thing that still bugs me is that it works on 0.9.3, any explanation?

**Comment by cy6erGn0m** [comment]
No clue yet. I need an IDEA plugin version, not just IDEA's version.

**Comment by saltyJeff** [comment]
How do you find that out?

**Comment by cy6erGn0m** [comment]
Open plugins dialog (you can find it by Ctrl-A then "plugins") and find Kotlin in the list

**Comment by saltyJeff** [comment]
Version: 1.2.51-release-IJ2018.2-1

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-748">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
