### ISSUE TITLE
ktor-client doesn't send body sometimes

### ISSUE THREAD

**Issue by jeiea** [ktorio/ktor#569]
I uploaded [sample project](https://github.com/jeiea/ktor-issue1).

With netty ktor-server and apache ktor-client, it posts form-data a lot in short time and any moment a request with missing body occurs. This appears as `java.io.IOException: Broken delimiter occurred`.

Is this bug?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-747">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Cannot reproduce since ktor 1.4.0
