### ISSUE TITLE
`HttpClient.readText` issue

### ISSUE THREAD

**Issue by soywiz** [ktorio/ktor#570]
I have reproduced a hang with `HttpClient.readText` in 0.9.4 (it doesn't happen on 0.9.3 so looks like a regression).

You can reproduce it here in the ktor.io documentation repository (branch `readText.issue`):
https://github.com/ktorio/ktorio.github.io/tree/readText.issue

The hangs happens in the checkLinks script:
https://github.com/ktorio/ktorio.github.io/blob/readText.issue/checkLinks.kt#L92

Steps to reproduce:

Preparing:

```
git clone git@github.com:ktorio/ktorio.github.io.git
git checkout readText.issue
```

In one terminal (start the jekyll server (requires docker), this might take up to one minute depending on the machine):

```
./docker-run.sh
```

Once the server is running (requires kscript, using sdk you can `sdk install kscript`), in other terminal:

```
./checkLinks.kt
```

It will output:
```
...
done
url: http://127.0.0.1:4000/servers/configuration/environments.html
done
url: http://127.0.0.1:4000/servers/deploy.html
```

and will hang in there.

If you change https://github.com/ktorio/ktorio.github.io/blob/readText.issue/checkLinks.kt#L20-L24 from 0.9.4 to 0.9.3, it works.

Also works when replacing `response.readText(Charsets.UTF_8)` with `response.readBytes().toString(Charsets.UTF_8)`

**Comment by e5l** [comment]
Hi, @soywiz. Thanks for the report :) 
Could you reproduce the bug with `1.0-alpha-1`

**Comment by soywiz** [comment]
Was not able to test it directly because kscript uses Kotlin 1.2, but created a separate custom project and indeed it is fixed already 👍
