### ISSUE TITLE
Netty configuration doesn't allow configuring request max length

### ISSUE THREAD

**Issue by impatient** [ktorio/ktor#580]
We need to be able to support urls of length 8kb, however, NettyChannelInitializer has no way of customizing the HttpServerCodec added to the pipeline.

https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-netty/src/io/ktor/server/netty/NettyChannelInitializer.kt#L101

HttpServerCodec (maxInitialLineLength is relevant argument):
https://netty.io/4.0/api/io/netty/handler/codec/http/HttpServerCodec.html

**Comment by renannprado** [comment]
Just would like to let whoever is taking a look at the same issue that I'm working on it and that I'm planning to send a PR for this today.

**Comment by impatient** [comment]
@renannprado Thanks again.  We worked around this previously, but have run into a case where we don't have as much flexibility.  Glad this made it in.
