### ISSUE TITLE
Client does not support sending or receive json null value

### ISSUE THREAD

**Issue by spand** [ktorio/ktor#588]
How does one send and receive the json `null` value ?

I had a look at implementing the change myself but it seems the non-nullability of the various content properties are quite pervasive so I am not sure how such a change would be most desirable to implement. I get the feeling that making them all nullable isnt appropriate.

According to https://tools.ietf.org/html/rfc8259#section-2 it seems to be valid.
```
2.  JSON Grammar

   A JSON text is a sequence of tokens.  The set of tokens includes six
   structural characters, strings, numbers, and three literal names.

   A JSON text is a serialized value.  Note that certain previous
   specifications of JSON constrained a JSON text to be an object or an
   array.  Implementations that generate only objects or arrays where a
   JSON text is called for will be interoperable in the sense that all
   implementations will accept these as conforming JSON texts.
```

**Comment by spand** [comment]
Could you elaborate on my question if you are not working on this yourself @e5l ?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-745">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
