### ISSUE TITLE
ktor-client-json always serializes body when contenttype is set as JSON

### ISSUE THREAD

**Issue by NikkyAI** [ktorio/ktor#590]
maybe it should not waste time serializing the empty body on a `GET` request or similar that will not use the body ?
also kotlinx-serializer currently seems to crash when trying to find the serializer for `EmptyContent`

```
val client = HttpClient(CIO) {
    install(JsonFeature) {
        serializer = KotlinxSerializer()
    }
}
val result = client.get<Map<String, User>>(path = "/userMap", port = serverPort) {
    contentType(ContentType.Application.Json)
}
```

this would cause a rather cryptic exception at runtime, being unable to find the serializer for the body,
when it really does not need to

**Comment by cy6erGn0m** [comment]
I'd say setting content type need to be prohibited however that's not easy to do

**Comment by NikkyAI** [comment]
based on the method `get` vs `post` the lambda would be
`RequestBuilder<GET>.() -> Unit` or  
`RequestBuilder<POST>.() -> Unit`

and setting contenttype would be a extension function defined only on `RequestBuilder<POST>`

seems like a pain to make sure every possible http verb is supported, but not impossible

**Comment by e5l** [comment]
Unfortunately, there are many APIs where the `get` request sends the body.
We try to prevent such use cases, but there were tickets asking to make support.

Btw we could try to prevent a creation of such API's in a server(or at least make a notice with a warning:))

**Comment by e5l** [comment]
We could also process the `EmptyContent` separate.
