### ISSUE TITLE
ktor-client-json TypeInfo for request pipeline

### ISSUE THREAD

**Issue by NikkyAI** [ktorio/ktor#591]
kotlinx-serilization would greatly beefit from knowing the type of the body when serializing the body of a call

for that maybe the body in a post call should be a reified type: https://github.com/ktorio/ktor/blob/f79c076b41ca4475bda14de226690484ed87dfb7/ktor-client/ktor-client-core/src/io/ktor/client/request/HttpRequest.kt#L84
`reified T: Any`
`body: T = EmptyContent`

and later be turned into a `TypeInfo` and passed along the Pipeline
the `class HttpResponsePipeline : Pipeline<HttpResponseContainer, HttpClientCall>` holds a TypeInfo in the `HttpResponseContainer`
a similar thing is missing from the `class HttpRequestPipeline : Pipeline<Any, HttpRequestBuilder>`

this might have been a enough for Gson and Jackson, but kotlinx-serialization needs to be able to work without reflection on IOS and other native clients, so obtaining typetokens is a must

**Comment by e5l** [comment]
Hi, @NikkyAI. Thanks for the report.

We could create the `typeInfo` only with inline function with a reified generic type parameter on the callsite. I have no idea(for now) how to pass the reified type, but PR(or at least nice idea) is always welcome :)

**Comment by NikkyAI** [comment]
i have not dug deep enough into the code of the pipelines to even guess to know what i am saying, but just like `HttpResponseContainer` holds a typeinfo, there could be a `HttpRequestContainer`

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-744">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
