### ISSUE TITLE
Allow configuring client certificate auth in Netty engine

### ISSUE THREAD

**Issue by mwudka** [ktorio/ktor#595]
The Netty engine config allows configuring the server's SSL parameters, but it doesn't expose the `SslContextBuilder `. This makes it hard to create a ktor server that requires clients to supply a certificate verified against a custom CA. It would be great if the Netty engine config allowed specifying that client certificates are required, and a custom trust store for validating them.

**Comment by belobrov-andrey** [comment]
@mwudka Is there a workaround? Can you provide code sample how to enable client certificate verification in Ktor server?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-742">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
