### ISSUE TITLE
Locatons instance would help reverse routing a lot

### ISSUE THREAD

**Issue by alexvas** [ktorio/ktor#597]
Ktor has a great `Locations` feature, which is about type-safe routing. Imagine that one wants to get type-safe routing also in templates, e.g. to use
```kotlin
// somewhere in controller, once
@Location("/products")
class Products {
    @Location("/{id}")
    class Item(val id: Int)
}

// and later reuse them in every link or form
a(href=href(Products.Item(id))) { "#$id" }
```
instead of
```kotlin
// using error-prone and refactoring-hard string template to build href
a(href="/products$id") { "#$id" }
```

The **problem is** function
```kotlin
// converts given location into URL string
fun href(location: Any): String
```
definition. For now the function is available only in Routing context, and passing it explicitely into templates makes code too verbose. Like
```kotlin
fun Routing.productRoutes() {
    // same line per every controller function
    fun href(location: Any) : String = application.locations.href(location)

    // per every get or post call
    get<Products> { _ ->
        call.respondHtmlTemplate(
                ListTemplate(
                        title = "All products",
                        tableModel = allProductTableModel(::href),
                        href = ::href
                )
        ) {}
    }
}
```
instead of just
```kotlin
fun Routing.productRoutes() {
   get<Products> { _ ->
       call.respondHtmlTemplate(
               ListTemplate(title = "All products", tableModel = allProductTableModel())
       ) {}
   }
}
```
if `Locations` instance were available standalone, one was able to use it inside a template directly.

**Comment by cy6erGn0m** [comment]
Unfortunately it couldn't be a top-level function as it requires application's settings and, perhaps, an application call to build complete path

What about an extension function like this so it will be available in every handler function ?

```
fun PipelineContext<Unit, ApplicationCall>.href(location: Any): String {
    return call.application.locations.href(location)
}
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-741">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
