### ISSUE TITLE
Kotlin 1.3.x non-experimental co-routines

### ISSUE THREAD

**Issue by LaurenceGA** [ktorio/ktor#598]
With [coroutines become stable](https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-3-rc-is-here-migrate-your-coroutines/), ktor will need to upgrade to them.
I'm trying to upgrade to Kotlin 1.3.0-rc-57 and coroutines eap13, but ktor is broken as it's using experimental coroutines still.
Will there be a preview build for kotlin 1.3 or will I have to wait until it's released properly?

**Comment by e5l** [comment]
Hi, @LaurenceGA. Thanks for the report.
You could use `0.9.5-rc13` version. 
The latest version also appears in our slack channel: `kotlinlang.slack.com` :)
