### ISSUE TITLE
ktor-client-json (>0.9.3) isn't usable on Gradle

### ISSUE THREAD

**Issue by Tea-Ayataka** [ktorio/ktor#600]
Somehow, Gradle fails to resolve ktor-client-json. this problem didn't exist before version 0.9.3.

Gradle 4.8
Kotlin 1.2.70

**Comment by e5l** [comment]
Hi, @Tea-Ayataka. Thanks for the report.
Gradle version  `4.7` is not supported with the current version of ktor.

**Comment by Tea-Ayataka** [comment]
Hi. Thanks for your fast reply. However, I tried some older versions of Gradle (4.6 and 4.4) but it's still failing to resolve.
Anything changed by adding *-jvm packages?

**Comment by e5l** [comment]
We use gradle-metadata feature to publish(until 1.0). It requires same gradle version, and 4.7 is only supported for now.

**Comment by windoze** [comment]
@e5l  So what is exactly the supported version? 4.7 or not 4.7? I'm a little confused.

**Comment by windoze** [comment]
Thanks for the clarification 😄
