### ISSUE TITLE
ktor-auth: remove junit compile-time dependency

### ISSUE THREAD

**Issue by cvmocanu** [ktorio/ktor#602]
``ktor-auth`` has a compile-time dependency of ``json-simple`` which has a **compile-time** dependency of junit 4.

This can cause nasty conflicts:
- with a different version of junit
- with a different version of hamcrest (junit 4 embeds hamcrest, without shadowing it). This is actually my problem.

A quick look at json-simple makes me think that the author simple forgot to add ``<scope>test</scope>``, since I don't see junit being used outside of tests.

Because of this, the simplest solution would be to exclude ``junit`` when you depend on ``json-simple`` (in the ``ktor-auth`` build.gradle file.

A better solution (but that may take more time) would be to use another library for JSON parsing, since ``json-simple`` hasn't been updated in 4 years.

Although, because ktor is a library, maybe you should use a good library and shade it (see for example the maven shade plugin) to avoid potential conflicts with dependencies of applications using ktor.

**Comment by orangy** [comment]
We are planning to use `kotlinx.serialization` pretty soon for it.

**Comment by alexvas** [comment]
Any progress on that?

**Comment by alexvas** [comment]
Moreover, ktor-server-test-host also depends on JUnit of version 4.12! This way JUnit 4 leaks into public API also.

**Comment by wyaeld** [comment]
@cy6erGn0m Can this issue be closed now?  The commit implied it is fixed.

**Comment by e5l** [comment]
Closed. Thanks
