### ISSUE TITLE
How upload Ktor project to Firebase

### ISSUE THREAD

**Issue by moisesvs** [ktorio/ktor#603]
Hi everybody,

I have already finished my backend with kTor. Now I want to deploy this project to Firebase Server, so I was searching information about this topic but I didn't found nothing about this. 

Are there some information about how I can deploy a project to Firebase console? In other case, If you can give me any information about the topic ... 

Regards

**Comment by BudiNverse** [comment]
IIRC firebase does not provide you a way to run JVM based applications, so there isn't any way for you to deploy your application to firebase.
