### ISSUE TITLE
How to get body parameters of post

### ISSUE THREAD

**Issue by allphfa** [ktorio/ktor#611]
python
```python
import requests

requests.post("http://localhost/generate", data=dict(a=1, b=2))

```
> body:    a=1&b=2

Can you read multiple form data only? How to read ordinary post data？？

**Comment by soywiz** [comment]
To be sure: what you want is to receive in the server a `application/x-www-form-urlencoded` encoded body?

Doesn't `call.receive<Parameters>()` work for you? As described in:
https://ktor.io/servers/calls/requests.html#receiving
