### ISSUE TITLE
error when adding some feature 

### ISSUE THREAD

**Issue by kldMohammed** [ktorio/ktor#625]
when i try to use gson or template i got this 

> /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=55371:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Users/macbook/IdeaProjects/ktor-example/out/production/classes:/Users/macbook/IdeaProjects/ktor-example/out/production/resources:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-server-netty/0.9.5/35f9da926235310b745d8598ce8dd7f2c26fdbe7/ktor-server-netty-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-html-builder/0.9.5/6a859802f341df6e60e013a55949acd2ae7f69c/ktor-html-builder-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-server-host-common/0.9.5/f4d9f7991945baef3157e3fb9549953ef9dd1e91/ktor-server-host-common-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-webjars/0.9.5/9b70213a8920f40f70889ae5f5053ca49bc9574e/ktor-webjars-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-gson/0.9.5/b5048e55fb21aba83d574ef42cf8ca23fbc1cc7d/ktor-gson-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-freemarker/0.9.5/2be2b0db0bc0b6c61bb38ebc9bd4e6d32c4f4d2c/ktor-freemarker-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.koin/koin-ktor/1.0.1/c0ddd62488431030bc0826835edb5d7fc490ab9c/koin-ktor-1.0.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-server-core/0.9.5/dc1f6cf15348860a64fb07a649d5861a62f2425e/ktor-server-core-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-http-cio/0.9.5/ecb91cc6826b810e6e4ba9a91068691cbff187ae/ktor-http-cio-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-http-jvm/0.9.5/d86ccaf6c55cb8ac47ad65a0c9bdd822dcfbeaaf/ktor-http-jvm-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-network/0.9.5/3c148239650b03ca47f6626db662a5f927d5477a/ktor-network-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-utils-jvm/0.9.5/ba1e36ba2dfdd8bf72149a99bfda7bc2122559d6/ktor-utils-jvm-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.2.70/17bdfaa19afad44a641a778a1cacc53b0e95dddc/kotlin-stdlib-jdk8-1.2.70.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.1/706a8b8206ead3683ec639dd270d11fd948fbb0e/logback-classic-1.2.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/bootstrap-datepicker/1.8.0/67caeacc39cf10fd3ba64ee21f64100ce6503aa6/bootstrap-datepicker-1.8.0.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/bootstrap/4.1.3/9d56b244ee26918d9431c2b446d97bf2042ebc78/bootstrap-4.1.3.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/jquery/3.2.1/3202162bb547fa5a9c97a22b5bbb3b5de7a9e40a/jquery-3.2.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.hibernate/hibernate-core/5.3.6.Final/42c7130757c3f67dda008d8edb28b381a09a7ce6/hibernate-core-5.3.6.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/mysql/mysql-connector-java/5.1.13/631249c6055be15a1fab26b3c28a3e5c6f3d97e0/mysql-connector-java-5.1.13.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/font-awesome/5.3.1/6066b61ccf7d260d18697f31c3c571dd57dc951b/font-awesome-5.3.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/bootswatch-materia/4.1.3/e6295c48f47d16bdf1a77ad1df91f5b3eb9c5e27/bootswatch-materia-4.1.3.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/vue/2.5.16/636ae60136d1730d9eaaed21794d29d0214332f/vue-2.5.16.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars.npm/vue-router/3.0.1/6a8174a631b7548bd38548d01cb48a4b47f2f2de/vue-router-3.0.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.2.70/9318bb9dadaa56534ac8b0728a1ffa2bd0e48b28/kotlin-stdlib-jdk7-1.2.70.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.2.70/895ff3421bed43cef31459dc9f2e9c0e6e0cb64b/kotlin-reflect-1.2.70.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-jdk8/0.25.0/8cb32ddf50480b58c3a1d4493c5731dcc3f9601/kotlinx-coroutines-jdk8-0.25.0.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-io-jvm/0.1.0-alpha-4/300fe330418af9c9d6046dbdc8b1c8fc29c43e31/kotlinx-coroutines-io-jvm-0.1.0-alpha-4.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core/0.25.0/5664ba2d20c6dcc88c912cc9666baa7f03203bcd/kotlinx-coroutines-core-0.25.0.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-io-jvm/0.1.0-alpha-4/5c2c83739e7c052c7e6e2ec3e940ea3d2b40d177/kotlinx-io-jvm-0.1.0-alpha-4.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-html-jvm/0.6.11/f00e83265b61a8a9c3abab62a7eaf9172d4496d6/kotlinx-html-jvm-0.6.11.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.koin/koin-core-ext/1.0.1/bae239e1877ed18dc5400334d865cec1e846b520/koin-core-ext-1.0.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.koin/koin-core/1.0.1/fb3816d35ef25b7f6e9074c2cdd5131408baf7a0/koin-core-1.0.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.70/b5b9449f73ce7bf312e89a7560cb3c209a0fa13e/kotlin-stdlib-1.2.70.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/webjars-locator-core/0.35/87e90bbd44accfb331783ac30dac2d166c41ba6d/webjars-locator-core-0.35.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/com.typesafe/config/1.3.1/2cf7a6cc79732e3bdf1647d7404279900ca63eb0/config-1.3.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http2/4.1.24.Final/c0c0d9d20402e4493083447052b59d5680e88b2e/netty-codec-http2-4.1.24.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.eclipse.jetty.alpn/alpn-api/1.1.3.v20160715/a1bf3a937f91b4c953acd13e8c9552347adc2198/alpn-api-1.1.3.v20160715.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.2.1/378913dfc3c6c71e7e2a2853eff2c3e8ac27599/logback-core-1.2.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.1/2a8e0aa38a2e21cb39e2f5a7d6704cbdc941da0/gson-2.8.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.freemarker/freemarker/2.3.28/7200064467a935052f99d114c2c05c3d189bc6d6/freemarker-2.3.28.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.hibernate.common/hibernate-commons-annotations/5.0.4.Final/965a18fdf939ee75e41f7918532d37b3a8350535/hibernate-commons-annotations-5.0.4.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jboss.logging/jboss-logging/3.3.2.Final/3789d00e859632e6c6206adc0c71625559e6e3b0/jboss-logging-3.3.2.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/javax.persistence/javax.persistence-api/2.2/25665ac8c0b62f50e6488173233239120fc52c96/javax.persistence-api-2.2.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.javassist/javassist/3.23.1-GA/c072c13dcb7f705471c40bafb1536171df850ab2/javassist-3.23.1-GA.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.8.17/9a36bc0f6eb9f941da0526ad89c4fb4b8ab580f0/byte-buddy-1.8.17.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/antlr/antlr/2.7.7/83cd2cd674a217ade95a4bb83a8a14f351f48bd0/antlr-2.7.7.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jboss.spec.javax.transaction/jboss-transaction-api_1.2_spec/1.1.1.Final/a8485cab9484dda36e9a8c319e76b5cc18797b58/jboss-transaction-api_1.2_spec-1.1.1.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jboss/jandex/2.0.5.Final/7060f67764565b9ee9d467e3ed0cb8a9c601b23a/jandex-2.0.5.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/com.fasterxml/classmate/1.3.4/3d5f48f10bbe4eb7bd862f10c0583be2e0053c6/classmate-1.3.4.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/javax.activation/javax.activation-api/1.2.0/85262acf3ca9816f9537ca47d5adeabaead7cb16/javax.activation-api-1.2.0.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/dom4j/dom4j/1.6.1/5d3ccc056b6f056dbf0dddfdf43894b9065a8f94/dom4j-1.6.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.webjars/popper.js/1.14.3/b882ad0d6393d5153f08be36253625f4e0b0eb4b/popper.js-1.14.3.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-http/0.9.5/2c84eaf2b7621a8471113f71d564b4427c6771b5/ktor-http-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-utils/0.9.5/97bbc432edc82bb856b1b90ccd1aed9859b7ff29/ktor-utils-0.9.5.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-io/0.1.0-alpha-4/1e67e7d1e421e3f7ec7d2209bbd0742a9f5cc204/kotlinx-coroutines-io-0.1.0-alpha-4.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-common/0.25.0/99f08d4693e6d5f2134dabcc440f6f0867018513/kotlinx-coroutines-core-common-0.25.0.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-io/0.1.0-alpha-4/abb7a001d058c057b299223365ab7382bb2405a6/kotlinx-io-0.1.0-alpha-4.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-common/0.11.3/8f4a66dcd4f0413f828b4df51e736918e05dbd1e/atomicfu-common-0.11.3.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.2.70/6ea722d7d0b9451293e739076ddb6a4108d57b6b/kotlin-stdlib-common-1.2.70.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.1.24.Final/8f20009953b2c7c3d860cef928007bc01aa58ac/netty-codec-http-4.1.24.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.1.24.Final/bad56e7da211c5ebe031ae155cb648b1065c7bb6/netty-handler-4.1.24.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.1/905075e6c80f206bbe6cf1e809d2caa69f420c76/commons-lang3-3.1.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-compress/1.9/cc18955ff1e36d5abd39a14bfe82b19154330a34/commons-compress-1.9.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.7.3/1499b854ae9f370409792db5af1b552dc7d9682f/jackson-core-2.7.3.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.1.24.Final/290857e5103956bbda11836e33245f2439226b77/netty-codec-4.1.24.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.1.24.Final/d37292c94d3a4cba48d9b6cfb6e8e55282035d0d/netty-transport-4.1.24.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.1.24.Final/e354bed2e60b568307138e403f55ba241c1c16d2/netty-buffer-4.1.24.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-resolver/4.1.24.Final/dbc1e5b50d31aed883ea3beeb6489e1977d0687f/netty-resolver-4.1.24.Final.jar:/Users/macbook/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.1.24.Final/7eeecd7906543214c3c1c984d275d3c6de10b99d/netty-common-4.1.24.Final.jar com.kld.ktor.example.ApplicationKt
> 2018-10-04 21:21:05.152 [main] TRACE Application - {
>     # application.conf @ file:/Users/macbook/IdeaProjects/ktor-example/out/production/resources/application.conf: 7
>     "application" : {
>         # application.conf @ file:/Users/macbook/IdeaProjects/ktor-example/out/production/resources/application.conf: 8
>         "modules" : [
>             # application.conf @ file:/Users/macbook/IdeaProjects/ktor-example/out/production/resources/application.conf: 8
>             "com.kld.ktor.example.ApplicationKt.module"
>         ]
>     },
>     # application.conf @ file:/Users/macbook/IdeaProjects/ktor-example/out/production/resources/application.conf: 2
>     "deployment" : {
>         # application.conf @ file:/Users/macbook/IdeaProjects/ktor-example/out/production/resources/application.conf: 3
>         "port" : 8080,
>         # application.conf @ file:/Users/macbook/IdeaProjects/ktor-example/out/production/resources/application.conf: 5
>         "watch" : [
>             # application.conf @ file:/Users/macbook/IdeaProjects/ktor-example/out/production/resources/application.conf: 5
>             "ktor-example"
>         ]
>     },
>     # Content hidden
>     "security" : "***"
> }
> 
> 2018-10-04 21:21:14.820 [main] DEBUG Application - Java Home: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents
> 2018-10-04 21:21:14.820 [main] DEBUG Application - Class Loader: jdk.internal.loader.ClassLoaders$AppClassLoader@4459eb14: []
> 2018-10-04 21:21:15.406 [main] INFO  Application - No ktor.deployment.watch patterns match classpath entries, automatic reload is not active
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at kotlin.reflect.jvm.internal.FunctionCaller$Method.callMethod(FunctionCaller.kt:97)
> 	at kotlin.reflect.jvm.internal.FunctionCaller$StaticMethod.call(FunctionCaller.kt:107)
> 	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
> 	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod(KCallableImpl.kt:148)
> 	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
> 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:334)
> 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:285)
> 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:262)
> 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:119)
> 	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:234)
> 	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:90)
> 	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:16)
> 	at io.ktor.server.engine.ApplicationEngine$DefaultImpls.start$default(ApplicationEngine.kt:46)
> 	at io.ktor.server.netty.DevelopmentEngine.main(DevelopmentEngine.kt:14)
> 	at com.kld.ktor.example.ApplicationKt.main(application.kt:30)
> Caused by: java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     com/kld/ktor/example/ApplicationKt$module$5$3.doResume(Ljava/lang/Object;Ljava/lang/Throwable;)Ljava/lang/Object; @150: getfield
>   Reason:
>     Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'com/kld/ktor/example/ApplicationKt$module$5$3$doResume$$inlined$respond$1'
>   Current Frame:
>     bci: @150
>     flags: { }
>     locals: { 'com/kld/ktor/example/ApplicationKt$module$5$3', 'java/lang/Object', 'java/lang/Throwable', 'io/ktor/util/pipeline/PipelineContext', 'kotlin/Unit', 'com/kld/ktor/example/User', 'io/ktor/application/ApplicationCall', 'io/ktor/freemarker/FreeMarkerContent', top, 'java/lang/Object', top, top, top, top, top, 'java/lang/Object' }
>     stack: { 'java/lang/Object' }
>   Bytecode:
>     0000000: b800 1f3a 0f2a b400 23aa 0000 0000 0127
>     0000010: 0000 0000 0000 0000 0000 0013 2c59 c600
>     0000020: 04bf 572a b400 254e 2ab4 0027 3a04 bb00
>     0000030: 2959 122b 122d b700 313a 052d 3a06 1906
>     0000040: b600 34c0 0036 3a06 bb00 3859 123a 123c
>     0000050: 1905 b800 42b8 0048 124a 0110 0801 b700
>     0000060: 4d3a 072a c100 4f99 0023 2ac0 004f 3a09
>     0000070: 1909 b600 5312 547e 9900 1219 0959 b600
>     0000080: 5312 5464 b600 58a7 000d bb00 5a59 2ab7
>     0000090: 005d 3a09 1909 b400 613a 0a19 09b4 0065
>     00000a0: 3a0b b800 1f3a 0c19 09b6 0066 aa00 0000
>     00000b0: 0000 0076 0000 0000 0000 0001 0000 0018
>     00000c0: 0000 0057 190b 59c6 0004 bf57 1906 b900
>     00000d0: 6a01 00b9 0070 0100 1906 1907 1909 1909
>     00000e0: 1906 b500 7319 0919 07b5 0076 1909 04b6
>     00000f0: 0077 b600 7d59 190c a600 2619 0c3a 0d57
>     0000100: a700 2c19 09b4 0076 3a07 1909 b400 73c0
>     0000110: 0036 3a06 190b 59c6 0004 bf57 190a 57a7
>     0000120: 000d bb00 7f59 1281 b700 84bf b200 87b0
>     0000130: bb00 7f59 1281 b700 84bf               
>   Stackmap Table:
>     full_frame(@28,{Object[#2],Object[#148],Object[#150],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#148]},{})
>     same_locals_1_stack_item_frame(@34,Object[#150])
>     full_frame(@138,{Object[#2],Object[#148],Object[#150],Object[#11],Object[#13],Object[#41],Object[#54],Object[#56],Top,Top,Top,Top,Top,Top,Top,Object[#148]},{})
>     full_frame(@148,{Object[#2],Object[#148],Object[#150],Object[#11],Object[#13],Object[#41],Object[#54],Object[#56],Top,Object[#148],Top,Top,Top,Top,Top,Object[#148]},{})
>     full_frame(@196,{Object[#2],Object[#148],Object[#150],Object[#11],Object[#13],Object[#41],Object[#54],Object[#56],Top,Object[#148],Object[#148],Object[#150],Object[#148],Top,Top,Object[#148]},{})
>     same_locals_1_stack_item_frame(@203,Object[#150])
>     same_frame(@259)
>     full_frame(@283,{Object[#2],Object[#148],Object[#150],Object[#11],Object[#13],Object[#41],Object[#54],Object[#148],Top,Object[#148],Object[#148],Object[#150],Object[#148],Top,Top,Object[#148]},{Object[#150]})
>     same_locals_1_stack_item_frame(@286,Object[#148])
>     full_frame(@290,{Object[#2],Object[#148],Object[#150],Object[#11],Object[#13],Object[#41],Object[#54],Object[#56],Top,Object[#148],Object[#148],Object[#150],Object[#148],Top,Top,Object[#148]},{})
>     full_frame(@300,{Object[#2],Object[#148],Object[#150],Object[#11],Object[#13],Object[#41],Object[#54],Object[#148],Top,Object[#148],Object[#148],Object[#150],Object[#148],Top,Top,Object[#148]},{})
>     full_frame(@304,{Object[#2],Object[#148],Object[#150],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#148]},{})
> 
> 	at com.kld.ktor.example.ApplicationKt$module$5.invoke(application.kt:122)
> 	at com.kld.ktor.example.ApplicationKt$module$5.invoke(application.kt)
> 	at io.ktor.routing.Routing$Feature.install(Routing.kt:65)
> 	at io.ktor.routing.Routing$Feature.install(Routing.kt:51)
> 	at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:59)
> 	at io.ktor.routing.RoutingKt.routing(Routing.kt:93)
> 	at com.kld.ktor.example.ApplicationKt.module(application.kt:56)
> 	... 19 more
> 
> Process finished with exit code 1

`

i use jdk 10 is this the reason of this problem

**Comment by e5l** [comment]
Hi, @kldMohammed. Thanks for the report. 
It looks like the project failing to run with the `green arrow`.
Could you try to run it with Gradle?

If it's not helping could you provide the snippet to clarify the problem?
Thanks
