### ISSUE TITLE
HttpClient Apache double escaping (no escaping) path

### ISSUE THREAD

**Issue by vehovsky** [ktorio/ktor#638]
There is a issue with escaping path for Apache backend of HttpClient.

Current version of Ktor 0.9.5 is "double escaping" the provided encoded path.
Latest version of Ktor 1.0.0-alpha-1 is not escaping (at least not correctly) the path.

Concrete example: Gitlab RES API endpoint for retrieving [file ](https://docs.gitlab.com/ee/api/repository_files.html)from specific repository:

`GET /projects/:id/repository/files/:file_path`

obviously the ":id" and ":file_path" needs to be escaped. Basic example:

`/api/v4/projects/1/repository/files/test%2Ffile%2Ejson/raw`

But current version of ktor 0.9.5 is "double escaping" so it escapes

> %2F

into

> %252F

`/api/v4/projects/1/repository/files/test%252Ffile%252Ejson/raw`

And the final request fails because of it.

As you can see in [ApacheRequestProducer](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-apache/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt) latest version of Ktor is decoding the url part and encoding again. But that again breaks the original intent.

So instead of

> /api/v4/projects/1/repository/files/test%2Ffile%2Ejson/raw
 
we end up with 

> /api/v4/projects/1/repository/files/test/file.json/raw

And again the final request fails because of it.

**Comment by e5l** [comment]
Hi, @vehovsky. Thanks for the report.
It's the real tricky case here, cause the Apache internals to encode everything except the `%2F`(`/`) in a path.
I think we ignore decoding `%2F` in a path for that case(and provide the fix in next minor release).

**Comment by vehovsky** [comment]
Hi @e5l 

It is tricky case indeed. Anyway if you simply ignore decoding I'm afraid we will end up with double escaping again. Because of the URIBuilder [here](https://github.com/ktorio/ktor/blob/e22d6a32d71a31d4c8e7e47e1f6e3fbb6781fb66/ktor-client/ktor-client-apache/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt#L123)

that will encode 

> %2F

 to

> %252F

**Comment by e5l** [comment]
I want to skip `%2F` decoding only when I pass the `path` to the Apache.

**Comment by e5l** [comment]
Fixed in `beta-1`
