### ISSUE TITLE
ktor 1.0 alpha-1,2,3: StatusPages exception handling misbehaves when exception thrown inside coroutine

### ISSUE THREAD

**Issue by marshallpierce** [ktorio/ktor#646]
In short, `exception<FooException> {}` seems to behave differently when an exception is thrown immediately inside a route's handler lambda vs when it's thrown inside, say, an `async` coroutine builder in that lambda.

Minimal reproduction: https://bitbucket.org/marshallpierce/ktor-exception-handler-repro/src/master/

**Comment by marshallpierce** [comment]
happens with -beta-1 too.

**Comment by cy6erGn0m** [comment]
Had no change to fix it in beta, sorry.

**Comment by marshallpierce** [comment]
No problem; just keeping the issue up to date so you don't have to bother checking if it's fixed in later versions :)

**Comment by cy6erGn0m** [comment]
Fix is available in 1.0.0-beta-2
