### ISSUE TITLE
Available for read from channel 4088

### ISSUE THREAD

**Issue by zerezhka** [ktorio/ktor#654]
When I'm trying to read bytes from channel it's always 4088 availableForRead, if I send long http body (more than 4088)
I can read it with breakpoints on `while(availableForRead>0){...readFully()...}`, but when it's running normally, code in the scores runs only one time <img width="363" alt="screen shot 2018-10-17 at 20 00 32" src="https://user-images.githubusercontent.com/10316435/47091862-8921ba00-d247-11e8-8a67-727abb800030.png">

If I try read it by lines with `readUTF8Line()`, it also can miss something

I really don't understand what is going on, I can't use ktor correctly

**Comment by e5l** [comment]
`ByteChannel` is fixed size primitive of 4088 bytes. When you try to write more than 4088, it writes 4088 and suspends writer.

**Comment by e5l** [comment]
If you want in-memory bytes container - use `ByteReadPacket` and `buildPacket` instead.

**Comment by zerezhka** [comment]
I just want read Http-Body =(

**Comment by e5l** [comment]
And you actually could: use ‘readRemaining’ on the response ‘ByteChannel’.
