### ISSUE TITLE
Best praxis for logging response from http client with scope.responsePipeline.intercept

### ISSUE THREAD

**Issue by Syrou** [ktorio/ktor#660]
```
scope.responsePipeline.intercept(HttpResponsePipeline.Receive) {
            Logger(LOGGER_TYPE.DEBUG, "Response body: ${context.response.readText(charset = Charsets.UTF_8)}")
            proceedWith(subject)
}
```
For obvious reasons this code will deplete the stream before it reaches its goal. That does however bring up the question, how would one the most efficient way log out the response?

**Comment by e5l** [comment]
Hi @Syrou, thanks for the report.
Probably the issue is solved by the `Logging` feature.

**Comment by zezutom** [comment]
Hi, I'm a bit late into the party, but I was able to successfully log the full response including the response body in the `After` phase, e.g.

```
 scope.responsePipeline.intercept(HttpResponsePipeline.After) {
     // Log response status and headers
     ...
     // Now also capture and log the response body:
     val responseBody = context.response.content.tryReadText(charset) ?: "[response body omitted]"
     ...
     proceed()
}
```
