### ISSUE TITLE
JWT: all the verification exceptions are suppressed

### ISSUE THREAD

**Issue by dmakarenko-connyun** [ktorio/ktor#664]
I'm using ktor-jwt feature and there is no way to identify the cause of unauthorized response because of suppressing all the JWTVerificationException
```
    val jwt = try {
        token.getBlob(schemes)?.let { jwtVerifier?.verify(it) }
    } catch (ex: JWTVerificationException) {
        null
    } ?: return null
```
It would be very helpful to have at least log messages in the application log.

**Comment by cy6erGn0m** [comment]
Added loggin on trace log level in 1.0.0-beta-2
