### ISSUE TITLE
Basic sample fails with

### ISSUE THREAD

**Issue by bbetter** [ktorio/ktor#669]
Error:Kotlin: [Internal Error] java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: Error type encountered: [ERROR : For SuccessOrFailure] (ErrorType).
Cause: Error type encountered: [ERROR : For SuccessOrFailure] (ErrorType).
File being compiled at position: (12,22) in ./Main.kt
The root cause was thrown at: KotlinTypeMapper.java:114

**Comment by cy6erGn0m** [comment]
This is because of mixed kotlin versions. It should be strictly 1.3.0-rc-131 or newer

**Comment by AllanWang** [comment]
I seem to have the same issue as well with ktor 1.0.0-beta-3 and kotlin 1.3.0.

[build.gradle](https://github.com/AllanWang/Prim/blob/multiplatform/server/build.gradle)

Did I misconfigure something? I also tried adding a newer coroutine version

**Comment by anonymousGiraffe** [comment]
experiencing the same issue here.

**Comment by AllanWang** [comment]
@anonymousGiraffe if you have a multiplatform project gradle version >= 4.8, try downgrading to 4.7.

I've since remove multiplatform dependencies on my project and it works for me

**Comment by anonymousGiraffe** [comment]
downgraded to 4.7 didnt work. i saw your message on slack.

**Comment by anonymousGiraffe** [comment]
`Error:Kotlin: [Internal Error] java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: Error type encountered: [ERROR : For SuccessOrFailure] (ErrorType).
Cause: Error type encountered: [ERROR : For SuccessOrFailure] (ErrorType).
File being compiled at position: (13,20) in /Users/guy.peleg/dev/ptbox-red/src/main/kotlin/Main.kt
The root cause was thrown at: KotlinTypeMapper.java:114
File being compiled at position: file:///Users/guy.peleg/dev/ptbox-red/src/main/kotlin/Main.kt
The root cause was thrown at: ExpressionCodegen.java:320
	at org.jetbrains.kotlin.codegen.CompilationErrorHandler.lambda$static$0(CompilationErrorHandler.java:24)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:74)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:97)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:68)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:446)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:142)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:161)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:57)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:96)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:52)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)`

**Comment by anonymousGiraffe** [comment]
`buildscript {
    ext.kotlin_version = '1.3.0-rc-131'
    ext.ktor_version = '1.0.0-beta-3'

    repositories {
        mavenCentral()
        maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'application'

group 'PTBOX'
version '1.0'

sourceCompatibility = 1.8

mainClassName = 'MainKt'

repositories {
    mavenCentral()
    jcenter()
    maven { url "https://dl.bintray.com/kotlin/ktor" }
    maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compile "io.ktor:ktor-server-netty:$ktor_version"
    compile "ch.qos.logback:logback-classic:1.2.3"
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

sourceCompatibility = 1.8
compileKotlin { kotlinOptions.jvmTarget = "1.8" }
compileTestKotlin { kotlinOptions.jvmTarget = "1.8" }

kotlin { experimental { coroutines "enable" } }`

**Comment by AllanWang** [comment]
wait so do you have multiplatform or no? Have you tried kotlin 1.3.0? [This](https://github.com/AllanWang/Prim/blob/740e944a848fc6d1f4b4050f2243c2055953f009/build.gradle#L13) is my config if that helps

**Comment by anonymousGiraffe** [comment]
@AllanWang i am not sure how to check it

**Comment by anonymousGiraffe** [comment]
updated the plugin nothing helps though

**Comment by anonymousGiraffe** [comment]
resolved using intelij 18.3 EAP

**Comment by cy6erGn0m** [comment]
For sure you had unreleased 1.3.0-eap plugin that is unfortinately not compatible with the release one
