### ISSUE TITLE
Do not register connector if the port/host is not set when using commandLineEnvironment()

### ISSUE THREAD

**Issue by Spartakovic** [ktorio/ktor#670]
commandLineEnvironment() is a convinient function to parse configs, but it registers a connector no matter what. I don't want to expose non ssl connectors and the only way to do it is to parse configs myself, which is mostly copy paste from this function.

I don't see a reason to register a connector by default even when it's not specified in the configs.

**Comment by cy6erGn0m** [comment]
What if we provide a way to disable the default 80th connector? Something like `-P:port=0 -P:sslPort=443` ?

**Comment by orangy** [comment]
I think better solution would be indeed no default connector, but in case of no connector registered at all, bail out with a diagnostic message telling people what to do. Especially when config is (accidentally) not found – currently error message `ktor config not found` is not very helpful.

**Comment by Spartakovic** [comment]
Agree on having no default connector and a diagnostic message

**Comment by cy6erGn0m** [comment]
Fixed in 1.0.0-beta-2
