### ISSUE TITLE
Support native windows HTTP client 

### ISSUE THREAD

**Issue by dtretyakov** [ktorio/ktor#671]
To create native windows applications could be useful to have native HTTP client which supports using Windows certificates store for SSL connections, proxy settings configuration on the system level, etc.

Microsoft recommends using [WinHTTP](https://docs.microsoft.com/en-us/windows/desktop/winhttp/about-winhttp) for server-side applications and services. WinHTTP is used in .NET [windows http client](https://github.com/dotnet/corefx/tree/master/src/System.Net.Http.WinHttpHandler/src/System/Net/Http) so it's a good candidate to use it on Windows. WinHTTP could work in sync and [async mode, which is recommended to use](https://docs.microsoft.com/en-us/windows/desktop/api/winhttp/nf-winhttp-winhttpopen#remarks) and async calls could be wrapped by using Kotlin coroutines.

**Comment by dtretyakov** [comment]
The sample kotlin native application which provides WinHTTP-based client is available here: https://github.com/dtretyakov/kotlin-winhttp

Currently it has the following problems:
* To use suspend functions in kotlin native coroutines should be supported multi-threading working mode, since WinHTTP uses pool of worker threads and completion callback could be executed on any of them: (https://github.com/Kotlin/kotlinx.coroutines/issues/462)
* WinHTTP headers are not included as Windows platform library in kotlin native, so [it requires having cintorop library](https://github.com/dtretyakov/kotlin-winhttp/blob/master/src/mingwMain/c_interop/winhttp.def). I'm not sure where is a better place to have winhttp interop in the [windows platform](https://github.com/JetBrains/kotlin-native/tree/master/platformLibs/src/platform/mingw) or in this repository.
* In WinAPI most of calls returns string as UTF16 and I it looks like kotlin native library is missing helper functions to create Kotlin strings from `ShortArray`s and it requires constructing string [like that](https://github.com/dtretyakov/kotlin-winhttp/blob/63d83476219aaa986cd21b421d995bf169505a49/src/mingwMain/kotlin/sample/RequestContext.kt#L119-L121):
```
val buffer = allocArray<ShortVar>(size)
// Call to fill in the buffer
String(CharArray(size) {
    buffer[it].toChar()
})
```

**Comment by cy6erGn0m** [comment]
Kotlinx I/O supports string constructor  `String(ByteArray, Charset)`, perhaps I can support construction from any CPointer as well

**Comment by cy6erGn0m** [comment]
I believe it's ok to have winhttp cinterop in the client

**Comment by cy6erGn0m** [comment]
To get it work with coroutines a set of hacks need to be applied: currently coroutines only work in the main thread so you need to send signals from a callback thread. The other issue is that there is no main loop implemented on Windows so it's not clear who can listen to such signals.

**Comment by cy6erGn0m** [comment]
@dtretyakov  Does winhttp support streaming for request and response body?

**Comment by dtretyakov** [comment]
@cy6erGn0m, WinHTTP async read/write operations are based on request -> callback response style of invocation: https://msdn.microsoft.com/en-us/library/windows/desktop/aa383138%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#art_winhttpheaders

So it looks like e.g. the response body could be consumed as a stream while invoking series of:
```
WinHttpQueryDataAvailable(...)
// -> WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE callback
// allocate buffer
WinHttpReadData(...)
// -> WINHTTP_CALLBACK_STATUS_READ_COMPLETE callback
// read from the buffer
```
until `WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE` returns 0 for `statusInfo`

**Comment by cy6erGn0m** [comment]
Note that we are going to introduce curl client, see #777

**Comment by e5l** [comment]
Merged in `master`

**Comment by msink** [comment]
Why this was closed?
On Windows `libcurl` from `msys2-mingw` is not well integrated and hard to redistribute.
So implementation based on `winhttp` or `wininet` client still required.

**Comment by dtretyakov** [comment]
@cy6erGn0m, @e5l I've added preliminary PR to support WinHTTP-based client: https://github.com/ktorio/ktor/pull/957

**Comment by Dominaezzz** [comment]
Is the WinHTTP client going to be released soon or has it been indefinitely put aside?

**Comment by PatrickLemke** [comment]
Just to clarify: There is currently no ktor client available for windows, correct?

**Comment by e5l** [comment]
CURL client engine supports Windows.

**Comment by PatrickLemke** [comment]
That's interesting, since if I include both required imports:

`        mingwX64().compilations["main"].defaultSourceSet {
            dependencies {
                implementation("io.ktor:ktor-client-core:$ktorVersion")
                implementation("io.ktor:ktor-client-curl:$ktorVersion")
            }
        }`

I can still not import io.ktor.* Is there anything else I need to take into consideration?

**Comment by msink** [comment]
> CURL client engine supports Windows

Does not support `https:`, only `http:` works.

**Comment by PatrickLemke** [comment]
@msink Thanks, I think I need to look into other options then. Probably WinHTTP with C interop.

**Comment by PatrickLemke** [comment]
@msink https works for me

**Comment by msink** [comment]
@PatrickLemke - it works in debug mode, but I failed to make distribution package.
Do you have any example how to distibute it?

**Comment by PatrickLemke** [comment]
@msink I haven't tried that yet. Are you referring to the difficulty of installing msys on the client system? I was thinking to use an installer like NSIS to install it manually.

**Comment by msink** [comment]
If I remember correctly - it works only if .exe was copied to msys2 bin/ directory, and runned from here. Something like as Git for Windows is distributed.

**Comment by PatrickLemke** [comment]
Well I guess you could also copy all the libraries you need into your own folder. The only thing that should matter is that mysys has access to all the libraries it needs.

**Comment by msink** [comment]
Not exactly - it looks for ssl certificates in directory relative to .exe - ../ssl , so .exe should be in subdirectory, for example bin/

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-735">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
