### ISSUE TITLE
GAE support

### ISSUE THREAD

**Issue by cy6erGn0m** [ktorio/ktor#672]
Currently GAE support is broken. In spite of that we have a lot of unconfined in blocking servlet engine, there are several places where we use coroutine's default and IO dispatchers that is not possible in GAE.

**Comment by cy6erGn0m** [comment]
Blocked by https://github.com/ktorio/ktor/issues/742

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-734">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
