### ISSUE TITLE
Network errors on Windows machines

### ISSUE THREAD

**Issue by cy6erGn0m** [ktorio/ktor#674]
Known failures at socket close:
- Software caused connection abort: recv failed with Netty engine

**Comment by cy6erGn0m** [comment]
Fixed in 1.1.0

**Comment by morj** [comment]
This breaks websocket closing on Jetty engine (because `EndPointReader` is set to ignore `onIdleExpired`) in `EndPointChannels.kt` of `io.ktor.server.jetty`.
