### ISSUE TITLE
Exactly the same self-signed certificates setup fails in Netty, but not in Jetty

### ISSUE THREAD

**Issue by Spartakovic** [ktorio/ktor#677]
We are using self-signed certificates. I set them up the way it's done in the tutorial. 
```
security {
    ssl {
      keyStore = ${?KEYSTORE_LOCATION}
      keyStorePassword = ${?KEYSTORE_PASSWORD}
      privateKeyPassword = ${?KEY_PASSWORD}
    }
  }
```

I know for sure that all those params and the keystore exist, but it fails with very hardly traceble error
 `Exception in thread "main" java.lang.IllegalStateException: connector.keyStore.getCe…Chain(connector.keyAlias) must not be null
        at io.ktor.server.netty.NettyChannelInitializer.<init>(NettyChannelInitializer.kt:41)
        at io.ktor.server.netty.NettyApplicationEngine.<init>(NettyApplicationEngine.kt:77)
`
However! Jetty with exact same settings just works. 
They way I start server is just `embeddedServer(Netty, commandLineEnvironment(args)).start()` in main method

**Comment by Spartakovic** [comment]
I am not sure what other debug info I can provide, but feel free to ask for more, just tell me what :)

**Comment by bulbigood** [comment]
I ran into the same problem. Error here:
..
val chain1 = connector.keyStore.getCertificateChain(connector.keyAlias).toList() as List<X509Certificate>
..
I think the problem here is in the cast to the List, but'm not sure

**Comment by avently** [comment]
@Spartakovic I'm creating applicationEngineEnvironment programmatically and without correct keyAlias it will not start. So try to include keyAlias:
```
keyAlias = correctAlias
```
in your config. 
This page has examples https://ktor.io/quickstart/guides/ssl.html

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-732">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
Cannot reproduce with Ktor 1.6.1.
