### ISSUE TITLE
ktor client iOS hangs forever in runBlocking

### ISSUE THREAD

**Issue by bootstraponline** [ktorio/ktor#678]
[**commonMain**](https://github.com/bootstraponline/run_blocking/blob/master/src/commonMain/kotlin/example/GitHub.kt)

```kotlin
expect fun <T> runBlocking(context: CoroutineContext = EmptyCoroutineContext, block: suspend CoroutineScope.() -> T): T

fun getGitHub(): HttpClientCall = runBlocking {
    HttpClient().call("https://www.github.com")
}
```

[**iosMain**](https://github.com/bootstraponline/run_blocking/blob/master/src/iosMain/kotlin/example/GitHubIos.kt)

```kotlin
actual fun <T> runBlocking(context: CoroutineContext, block: suspend CoroutineScope.() -> T): T {
    return kotlinx.coroutines.runBlocking(context, block)
}
```

![image](https://user-images.githubusercontent.com/1173057/47571438-86d5f480-d906-11e8-954b-f3bdbeb8edba.png)

Xcode hangs forever when invoking the method:

```swift
func testRunBlocking() {
  GitHubKt.getGitHub()
}
```

If I delete `HttpClient` in `runBlocking` then the method successfully returns a value on iOS.

Versions:

```gradle
kotlin_version=1.3.0-rc-190
coroutines_version=1.0.0-RC1
ktor_version=1.0.0-beta-2
serialization_version=0.8.2-rc13
```

Is it a known issue that ktor iOS doesn't work in runBlocking? Is this even a ktor issue or a coroutines issue? https://github.com/Kotlin/kotlinx.coroutines/issues/462

**Comment by cy6erGn0m** [comment]
Why do you use `runBlocking` on ios? You should never block main loop.

**Comment by cy6erGn0m** [comment]
Read [Guide to UI programming with coroutines](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md) first

**Comment by cy6erGn0m** [comment]
Unfortunately `Dispatchers.Main` doesn't work with ios yet. See https://github.com/Kotlin/kotlinx.coroutines/issues/470

**Comment by bootstraponline** [comment]
I want to block the main loop. I am using this in the context of a testing library that's run in a separate process from the application. Specifically this is an iOS XCUITest.

My confusion is that the code doesn't work. I am not finding any possible way to fix (even using a background threads)

**Comment by bootstraponline** [comment]
> See [Kotlin/kotlinx.coroutines#470](https://github.com/Kotlin/kotlinx.coroutines/issues/470)

I tried that solution as well, using the custom `MainLoopDispatcher` and runBlocking never returns when used with ktor.

**Comment by cy6erGn0m** [comment]
Well, running coroutines on background threads are not yet supported. Using runBlocking is quite dangerous. Are you sure you actually need blocking?

**Comment by bootstraponline** [comment]
> Are you sure you actually need blocking?

Yeah, I'm replacing an existing blocking networking client (based on gRPC Swift). This is all test code run in a different process from the app. It's not related to production at all.

**Comment by cy6erGn0m** [comment]
One possible reason is that the client is trying to resume on main loop while it is blocked. Also note that a client need to be closed

**Comment by bootstraponline** [comment]
I pushed some fixes:

- https://github.com/bootstraponline/run_blocking/commit/aceb86baeb1a5743d9c3c4d82f0725289a3320f8
- https://github.com/bootstraponline/run_blocking/commit/3615c42be111aa24de119d49125ea1547b7b17d5

anything else obviously wrong?

**Comment by cy6erGn0m** [comment]
However it makes no difference. ios client is configured to schedule callback to the main loop that is blocked. This is why it doesn't work. So there is no way to use runBlocking with ktor client.

**Comment by cy6erGn0m** [comment]
Why can't you simply make `getGitHub` suspend?

**Comment by cy6erGn0m** [comment]
You fix looks too verbose, you can use `use` function for client to get it closed

```
val result = HttpClient().use { it.get<String>("https://.... ") }
```

**Comment by bootstraponline** [comment]
> there is no way to use runBlocking with ktor client.

Thanks for clarification.

> Why can't you simply make `getGitHub` suspend?

How do I call a Kotlin suspend function in a blocking way from Swift? The beauty of runBlocking is the calls are synchronous from the consumer perspective.

**Comment by bootstraponline** [comment]
When defining `getGitHub` as suspend, there's no method generated in `run_blocking.h` From Swift, the method doesn't exist.

```kotlin
suspend fun getGitHub(): HttpClientCall {
    return HttpClient().use { it.call("https://www.github.com") }
}
```

I guess iOS is not working yet?

**Comment by bootstraponline** [comment]
>  Currently, there's no way to have coroutines in Objective-C or Swift, so exposing suspend functions look tricky.
>
> https://github.com/JetBrains/kotlin-native/issues/1684

**Comment by cy6erGn0m** [comment]
Yes, for now there is no way to call suspend functions from swift. However you can invoke swift functions from kotlin coroutines.

The simplified it looks like this

common.kt
```kotlin
interface MyAppView {
    fun onDataLoadComplete(text: String)
}

class MyPresenter(private val view: MyAppView)  {
    fun load() {
        launch {
            val result = client.get<String>("http://....")
            view.onDataLoadComplete(result)
        }
    }
}
```

MyAppViewIos.swift
```swift
class MyAppViewIos:  ....  , MyAppView {
    lazy var presenter: MyPresenter = { 
        MyPresenter(view: self)
    }

    func somethingClicked() {
        presenter.load()
    }
}
```

See complete example here: https://github.com/JetBrains/kotlinconf-app

Relevant files are:

view interface (Kotlin): https://github.com/JetBrains/kotlinconf-app/blob/master/common/src/commonMain/kotlin/org/jetbrains/kotlinconf/presentation/SessionListView.kt

presenter (Kotlin)
https://github.com/JetBrains/kotlinconf-app/blob/master/common/src/commonMain/kotlin/org/jetbrains/kotlinconf/presentation/SessionListPresenter.kt

view implementation (Swift)
https://github.com/JetBrains/kotlinconf-app/blob/master/konfios/konfswift/ui/SessionsViewController.swift

UI dispatcher implementation
https://github.com/JetBrains/kotlinconf-app/blob/master/konfios/konfswift/ui/UI.swift

**Comment by bootstraponline** [comment]
> there is no way to call suspend functions from swift. However you can invoke swift functions from kotlin coroutines.

I think a synchronous REST API defined in Kotlin and called by Swift is blocked then. Probably this will be possible once multithreaded support lands.

The callback approach is interesting. I see that as a good fit for writing apps.

Thanks for all the info.

**Comment by bootstraponline** [comment]
The async callback code works. With the callback API, it doesn't seem possible to wait for operations to finish. I tried using an operation queue and that crashed.

``` swift
// Swift
let queue = OperationQueue()
queue.addOperation { ... }
queue.waitUntilAllOperationsAreFinished()
```

```kotlin
// Kotlin
fun hello(cb: (result: Int) -> Unit) {
    GlobalScope.launch(MainLoopDispatcher) {
        val result = HttpClient().use {
            it.call("https://www.github.com")
        }
        cb(result.response.status.value)
    }
}

object MainLoopDispatcher : CoroutineDispatcher() {
    override fun dispatch(context: CoroutineContext, block: Runnable) {
        NSRunLoop.mainRunLoop().performBlock {
            block.run()
        }
    }
}
```


```swift
// Swift
class KotlinNativeTests: XCTestCase {

  func testKotlinNative() {
    GitHubIosKt.hello(cb: swiftCb)
    // Must keep the run loop alive or the test will end before the callback returns
    RunLoop.current.run(until: NSDate().addingTimeInterval(1) as Date)
  }
}
```

**Comment by e5l** [comment]
Thanks for the idea :)
