### ISSUE TITLE
There should to be a better way to set platform specific defaultCharset in the HttpResponseConfig

### ISSUE THREAD

**Issue by Syrou** [ktorio/ktor#681]
Ktor info:
```
ktor_version=1.0.0-beta-2
```

The solution
```
open class HttpResponseConfig {
    /**
     * Default [Charset] for response content if not specified, the initial value is ISO_8859_1.
     * If ISO_8859_1 is not available, UTF-8 is used as a fallback.
     */
    var defaultCharset: Charset = try {
        Charset.forName("ISO_8859_1")
    } catch (_: Throwable) {
        Charsets.UTF_8
    }
}
```
To set UTF8 on IOS if the given charset is not found seems weird to me. 

I do not want to trigger an exception in Xcode just to set the correct charset. Is there an easy way where I can define HttpResponseConfig on each platform and then send it to be used by the common in the initilization step? If not there really should be. I do not have the option to override the HttpClient since its final it seems like.

Setting it within the DSL in 
```
io.ktor.client.HttpClient { ... }
``` 
is too late it seems like too, the exception has already been triggered

**Comment by e5l** [comment]
The fix in the `master` branch. Fixed by introducing `Charsets` configuration builder.
