### ISSUE TITLE
CIO client never responds when running on AWS

### ISSUE THREAD

**Issue by lukaswelte** [ktorio/ktor#682]
When I run the CIO http client (0.9.5 same as 1.0.0.beta-3) on my local machine it responds nicely.
But when running it on AWS it stopped working with 0.9.5 (was working under 0.9.3).
Using the apache client works.

How could I help identifying the bug?

**Comment by lukaswelte** [comment]
Like I said, I tried `1.0.0-beta-3` as well and it is also not working.

No logs the client request is performed and then never returns (suspends forever).

Seems like I'm not the only one with this problem ([Slack](https://kotlinlang.slack.com/archives/C0A974TJ9/p1540481694000100?thread_ts=1540478414.000100&cid=C0A974TJ9)).

**Comment by e5l** [comment]
VM: OpenJDK 25.162-b12
Java: Java 1.8.0-8u162

**Comment by lukaswelte** [comment]
I don't know what exactly fixed it, but with `1.0.0-beta-4` this problem is resolved 🍾
