### ISSUE TITLE
ktor-client-json-js: NoTransformationFound when using JsonFeature

### ISSUE THREAD

**Issue by jonasbark** [ktorio/ktor#683]
Version: 1.0.0-beta-3

When installing JsonFeature using this:

```
install(JsonFeature) {

            serializer = KotlinxSerializer().apply {
                register(StartPage.serializer())
            }
        }
```

this error is thrown during execution:
```
NoTransformationFound: No transformation found: class JsHttpResponse -> class StartPage
   at Coroutine$receive_jo9acv$.doResume (http://127.0.0.1:8080/lib/ktor-client-core-js.js:1240:21)
```

The same code is working fine on JVM & iOS. It looks like KotlinxSerializer does not work properly, yet.

**Comment by e5l** [comment]
Hi, @jonasbark. Thanks for the report. 
The fix in `master` and would be available in next minor release.

**Comment by keiththompson** [comment]
@e5l Is this only a known issue for js? I've become stuck with this on the jvm.
