### ISSUE TITLE
Can't set a base url that includes path data

### ISSUE THREAD

**Issue by ScottPierce** [ktorio/ktor#684]
My team is trying to move from using OkHttp to using ktor as our HttpClient. We've found this difficult because there doesn't seem to be a way to set the default base url.

If we have the following requests:
```
https://www.example.com/api/getA/
https://www.example.com/api/getB/
https://www.example.com/api/getC/
```

It's common practice to have the ability to set the base url for the http client as `https://www.example.com/api/`, and then only specify the suffix of the path (`/getA/`, `/getB/`, `/getC/`) at the actual request site.

I like the way you can create a `defaultRequest` when creating the http client with ktor and then intuitively override what's needed at the request site, however this functionality needs to be extended to allow the inclusion of path data in the base url. This functionality is available in OkHttp and also Retrofit. Otherwise it requires significant refactoring in our code-base when switching between environments, as base urls and base paths often change between environments. I imagine this will be a common problem.

If somehow this is already possible, it's not clear that it is, and in which case, this should be documented better.

**Comment by svlada** [comment]
@ScottPierce Have you found solution for this problem?

**Comment by ScottPierce** [comment]
We're just including the base url in every request. It's pretty annoying.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-730">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
