### ISSUE TITLE
io.ktor.locations.location being deprecated

### ISSUE THREAD

**Issue by sannysoft** [ktorio/ktor#688]
Hello.

I am using both Location and location in my files 
```
@Location("/test")
class TestLocation(
        val id: String? = null
)

fun Route.test() {
    location<TestLocation> {
        handle<TestLocation> {
```

I import all the classes by using 
```
import io.ktor.locations.Location
import io.ktor.locations.handle
import io.ktor.locations.location
```

Starting 1.0.0-beta-3 it stopped compiling (`Using 'typealias location = Location' is an error. Use Location instead`) and `import io.ktor.locations.location` is being highlighted by Idea. I have to change the imports to be `import io.ktor.locations.*` in order to work.

However Idea expands this to the specific imports above after each file edit.
Is there a way to fix it? Is it time to remove typealias at all?

Thanks.

**Comment by e5l** [comment]
Deprecations would be removed after major version switch.
About `*` imports: https://ktor.io/quickstart/code-style.html.

Hope the issue was resolved in slack. Please reopen if you have remaining questions.
