### ISSUE TITLE
Support for unsigned types

### ISSUE THREAD

**Issue by brezinajn** [ktorio/ktor#689]
Is support for unsigned types planned? At the moment doing
```Kotlin
@Location("/test/{ulong}")
    protected data class TestRoute(val ulong: ULong)
```
gives me
```
Inconsistent number of parameters in the descriptor and Java reflection object: 2 != 1
Calling: public constructor TestRoute(ulong: kotlin.ULong) defined in <path>.TestRoute[DeserializedClassConstructorDescriptor@1e0d7e1]
Parameter types: [long, class kotlin.jvm.internal.DefaultConstructorMarker])
Default: false
```

**Comment by cy6erGn0m** [comment]
At least https://youtrack.jetbrains.com/issue/KT-26765 need to be fixed first

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-729">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
