### ISSUE TITLE
Make MockEngine multiplatform

### ISSUE THREAD

**Issue by nvbln** [ktorio/ktor#693]
Currently, it seems that the `MockEngine` only works on the JVM. In a multiplatform project, tests have to be duplicated or the `MockEngine` has to be wrapped. Since this is rather inconvenient, I was wondering if this is something that is already being worked on (or something that is planned to be worked on in the future).

**Comment by e5l** [comment]
Hi, @nvbln. Thanks for the request. 
It's planned with `kotlin-multiplatform` plugin migration. Is it a blocker for you?

**Comment by nvbln** [comment]
No, not yet. Currently we're only working on the Android platform, so just the JVM is fine. However, we plan on going multiplatform in the future, so at that point it would become a blocker.
