### ISSUE TITLE
enhance api for ConditionalHeaders usage

### ISSUE THREAD

**Issue by kutoman** [ktorio/ktor#697]
sorry if there is already an appropriate way of doing this what I'm going to ask for. Since the documentation is lacking with respect to the usage of the `ConditionalHeaders` feature I coulnd't find a way of managing it concisely. 
As far as I could see, in order to utilize `ConditionalHeaders` the `OutgoingContent`'s headers need to be set. Thus this here

```
// somewhere in installation phase
    install(ContentNegotiation) {
        register(ContentType.Application.Json, GsonConverter())
    }
    install(ConditionalHeaders)

// somewhere in api call
ctx.call.response.header(HttpHeaders.LastModified, lastModifiedTime)
ctx.call.respond(HttpStatusCode.OK, anydata)
```

don't have any effect since the header of the ApplicationResponse is set (instead of the content). 
Therefore when I use `ContentNegotiation` I would need to adapt the conversion process so that the produced OutgoingContent instances also contain the relevant headers which is imho against the concise api nature of ktor.

wouldn't it make sense that ApplicationResponse headers are applied to the OutgoingContent headers?

**Comment by cy6erGn0m** [comment]
I see only two options:
- a content converter need to know how to extract lastModified/etag from a data object
- conditional headers feature could check both content and response headers

**Comment by cy6erGn0m** [comment]
Please note that there is `version` function in `ConditionalHeaders`

```kotlin
application.install(ConditionalHeaders) {
    version { obj -> listOf(EntityTagVersion("tag1")) }
}
```

Unfortunately it's usage is very limited and need to be improved

**Comment by cy6erGn0m** [comment]
@soywiz it's not documented btw

**Comment by kutoman** [comment]
as a workaround I'll use this for the moment:

    install(ContentNegotiation) {
        register(ContentType.Application.Json, GsonConverter())
    }

    sendPipeline.intercept(ApplicationSendPipeline.Render) { subject ->
        if(subject is OutgoingContent.ByteArrayContent) {
            proceedWith(ContentWithResponseHeaders(subject, context.response.headers.allValues()))
        }

    }

    install(ConditionalHeaders)

**Comment by kutoman** [comment]
the workaround I shared with you a year ago was actually causing the issue of duplication #1471. Therefore the fix needs to happen in the feature itself

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-728">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
