### ISSUE TITLE
TestApplication return a null HttpStatusCode when a route isn't found

### ISSUE THREAD

**Issue by dave08** [ktorio/ktor#702]
Running in Ktor 1.0.0-beta-3.

In unit tests this is very confusing, since I would expect it to return something like `HttpStatusCode.NotFound`.

**Comment by mkporwit** [comment]
This is still an issue in 1.1.1 :(

**Comment by cy6erGn0m** [comment]
The reason why we have `null` is that we differentiate handled and unhandled in test application. In real engines ktor could bypass unhandled to the underlying engine, e.g. to servlet container. Not sure if we actually need it

**Comment by mkporwit** [comment]
Fair enough. On the flip side, sometimes when writing tests, it's a little annoying to expect some sort of a valid response (a 404, or a 500, or anything, really) and get null instead without any clue as to why that happened. Not a huge deal, so I understand if you leave it the way it is, but it is a bit of a niggle every once in a while.

**Comment by cy6erGn0m** [comment]
Btw, it's easy to workaround

```kotlin

private fun TestApplicationEngine.installFallback() {
    application.intercept(ApplicationCallPipeline.Fallback) {
        if (call.response.status() == null) {
            call.respond(HttpStatusCode.NotFound)
        }
    }
}
```
