### ISSUE TITLE
Page not fully rendered (Compression + HTML builder)

### ISSUE THREAD

**Issue by gzoritchak** [ktorio/ktor#708]
I put brackets on Compress and HTML builder because I'm not completely sure of what is happening. 

The problem appeared on some pages generated from markdown files through HTML builders. The MD files are parsed and transformed into HTML with a third party library. This HTML is then injected into HTML builders using an `unsafe` block. MD files, and by extension unsafe content, can be quite big. 

When loading pages from a browser they often appear to be only partially rendered even though the HTTP code is 200. 

My current intuition, after some debugging and with a partial knowledge of ktor internals, is that the bug comes from the combination of `Compression` feature and big html streams. At one moment, the html stream uses some `BufferedWriter` and the compression takes the content of buffer and ends the HTTP request even if the content as not complete the html generation.

**Comment by gzoritchak** [comment]
I was able to reproduce this bug on Jetty and Netty.

**Comment by Bluexin** [comment]
Might be the same cause as #685

**Comment by cy6erGn0m** [comment]
Workarounded in 1.0.0-beta-4

**Comment by gzoritchak** [comment]
Thanks @cy6erGn0m for this quick resolution. 

You indicates the solution to be a workaround. Are there some limitations with this implementation?

**Comment by cy6erGn0m** [comment]
This solution is not good enough due to performance impact (introduces scheduling delay)

**Comment by Bluexin** [comment]
Is there an issue open for tracking updates for an actual definitive fix ? Seeing this is just a workaround (so it doesn't get forgotten)

**Comment by cy6erGn0m** [comment]
See https://github.com/ktorio/ktor/issues/742
