### ISSUE TITLE
Add Feature - Thymeleaf template engine

### ISSUE THREAD

**Issue by ddeya** [ktorio/ktor#709]
Thymeleaf it´s an important template engine and it´s pretty common on the Java Backend World. I think we should added to the feature list along with Freemarker and Velocity.
For more info about Thymeleaf: [https://www.thymeleaf.org/](url)
For more info about template engines: [https://dzone.com/articles/template-engines-at-one-spring-boot-and-engines-se](url)

**Comment by lbednarski** [comment]
Hi. I'm using Ktor in my application and right now i'm working on frontend part. I wanted to use Freemarker  but I prefer to use Thymeleaf. As I see (and I it's really nice surprise for me) you are working on provide Thymeleaf to Ktor. Do you know when this task will be finished and when can I use Thymeleaf in my project? As I see PR is open right now so I hope it's almost finished.
