### ISSUE TITLE
websocket send frame from non suspending progress listener 

### ISSUE THREAD

**Issue by stasbar** [ktorio/ktor#717]
Hello.
I'm facing problem with webockets. 
I want to send frame each time my "manager" calls listener with progress.
```kotlin
        webSocket("/blockChainSyncProgress") {
            manager.addBlockChainProgressListener { progress ->
                launch {
                    outgoing.send(Frame.Text("$progress"))
                }
            }
        }
```
since the .addBlockChainProgressListener is not suspending function, websocket will close after the listener is added.
I can add `while (isActive) delay(1000)`
so the function looks like:
```kotlin
        webSocket("/blockChainSyncProgress") {
            manager.addBlockChainProgressListener { progress ->
                launch {
                    outgoing.send(Frame.Text("$progress"))
                }
            }
            while (isActive) delay(1000)
        }
```
but I'm not sure if it's the recommended way of doing that.

**Comment by stasbar** [comment]
Thank you for the answer. `Manager` is a global singleton.
So here is what you suggest right?
```kotlin
val channel = Channel<Int>(Channel.CONFLATED)
manager.addBlockChainProgressListener { progress ->
    channel.sendBlocking(progress)
}
webSocket("/blockChainSyncProgress") {
    channel.consumeEach { progress ->
        outgoing.send(Frame.Text("$progress"))
        if (progress == 100) close()
    }
}
```
I tested it, and it's working fine 👍

**Comment by cy6erGn0m** [comment]
The other alternative is to use a global instance of [BroadcastConflatedChannel](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-conflated-broadcast-channel/) to publush manager's current state and subscribe client's session.

**Comment by cy6erGn0m** [comment]
Also note that it looks like you are not unsubscribing: is that ok in your particular case?

**Comment by stasbar** [comment]
You are right! Thank you very much.
