### ISSUE TITLE
Provide a Logging Feature for Http Client Logging

### ISSUE THREAD

**Issue by ScottPierce** [ktorio/ktor#722]
Logging support in the Http Client seems like it has to be done manually by each user currently. Please provide a feature for logging with the library, that allows you to set the log level, similar to something like the [OkHttp Logging Interceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor).

You could argue that I should be using the OkHttp logging interceptor, but it seems like a much better fit that ktor would provide their own version of this for all engines and platforms.

**Comment by e5l** [comment]
Hi @ScottPierce, thanks for the report.
Maybe the issue could be resolved with `ResponseObserver` feature?
https://github.com/ktorio/ktor/blob/5f40b062457817870b3ecfa62b539782db2e65db/ktor-client/ktor-client-core/src/io/ktor/client/features/observer/ResponseObserver.kt

**Comment by ScottPierce** [comment]
@e5l With this feature, it'd be useful to be able to route log messages to our own custom logger (which is basically essential on Android anyways). This is provided by the [OkHttp Logging Interceptor](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor). Another feature that would be nice to copy over from okhttp would be the ability to set how much data is logged (full request / response, NONE, and a few options in-between.

**Comment by zhuosun-rally** [comment]
@e5l do you have the estimated time of completion for this feature release? 
this is blocking us for the API development, we are looking forward to this feature.

**Comment by e5l** [comment]
Hi, @zhuosun-rally. We expect in ~1.5 weeks with ktor 1.0.1

**Comment by zhuosun-rally** [comment]
Thank you @e5l, I got the new version and the logger is nice.
