### ISSUE TITLE
MockEngine missing from 1.0.0-beta-4?

### ISSUE THREAD

**Issue by forseti** [ktorio/ktor#726]
Hi there,

I just updated the deps to 1.0.0-beta-4 and it seems the ktor-client-mock doesn't contain any classes at all. Only metadata files. Is this expected?

Thanks!!

Donny

**Comment by cy6erGn0m** [comment]
It is multiplatoform now so `ktor-client-mock-jvm` should be used in platform modules.

**Comment by forseti** [comment]
Thanks @cybergnom!!

**Comment by andylamax** [comment]
After reading through, I realized the beta-4 is moved into multiplatform naming conversions. can someone please show me how to add ktor-client in jvm and js modules?

**Comment by forseti** [comment]
Hi @andylamax 

The artifact name will be ```ktor-client-$platform``` and ```ktor-client-mock-$platform```
You can try:
- ```ktor-client-js```  and ```ktor-client-mock-js``` for JS 
- ```ktor-client-mock-jvm``` and ```ktor-client-mock-jvm``` for Java

**Comment by andylamax** [comment]
Thanks alot @forseti was very helpful. although after going through maven repositories, I realized that ktor-client-jvm is still in 0.9.0-alpha-1 (hasn't reached 1.0.0-beta). But somehow I feel like this is already implemented somehow to beta. am I wrong? should I open an issue requesting to bump the jvm version to beta as well?

**Comment by andylamax** [comment]
Another funny fact, is that `ktor-client-jvm` is stuck at `0.9.0-alpha-1`, while `ktor-client-js` has reached `1.0.0-beta-4`, but does not have any version below `1.0.0-beta-1` (doesn't have version `0.9.0-alpha-1`)

**Comment by forseti** [comment]
Hi @andylamax

On JVM, You need to use one of the following engines instead of ```ktor-client-jvm```:
- Apache HTTP: ```ktor-client-apache``` (https://mvnrepository.com/artifact/io.ktor/ktor-client-apache)
- Kotlin CIO: ```ktor-client-cio```  (https://mvnrepository.com/artifact/io.ktor/ktor-client-cio)
- Jetty: ```ktor-client-jetty```  (https://mvnrepository.com/artifact/io.ktor/ktor-client-jetty)

**Comment by forseti** [comment]
Hi @andylamax

You can try ```ktor-client-$platform```
so if it

**Comment by jcornaz** [comment]
@forseti Can you please document that here: https://ktor.io/clients/http-client/testing.html ?

**Comment by forseti** [comment]
@jcornaz
Sure. I'm going to add them in the docs
