### ISSUE TITLE
[ktor-common-client] Custom timeouts

### ISSUE THREAD

**Issue by sergiocasero** [ktorio/ktor#728]
Hello guys! I've detected that the timeout feature/option is not available yet in the common ktor client. 

Could you please add it?

Thanks!

**Comment by Syrou** [comment]
@e5l Any news on this? I really need this feature for MPP common client

**Comment by nehahemnani92** [comment]
Is there a plan to add this enhancement in the near future?

**Comment by e5l** [comment]
Hi @Syrou, @nehahemnani92, @sergiocasero. Thanks for the report!
It looks like the most cases could be covered by:
```kotlin
withTimeout(...) {
    client.get<Data>(...)
}
```

What kind of timeout would you like to see?

**Comment by sergiocasero** [comment]
Ohh, looks pretty nice @e5l , let me check it because I think that yes, this will cover the 90% of cases.

**Comment by Syrou** [comment]
@e5l Pretty sure what I want is to have that ability from the configuration phase. Sure it works setting it on each request/call but I'd want to be able to define a default timeout in the configuration step and then override that by using the withTimeout(...)

**Comment by enleur** [comment]
See https://github.com/ktorio/ktor/issues/1134#issuecomment-591477101

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-723">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Obsolete with timeouts feature: https://ktor.io/docs/timeout.html
