### ISSUE TITLE
Add samples or utilities for using MockEngine in cross-platform unit tests

### ISSUE THREAD

**Issue by russhwolf** [ktorio/ktor#731]
### Ktor Version
1.0.0-beta4

### Ktor Engine Used(client or server and name)
MockEngine

### JVM Version, Operating System and Relevant Context
Multiplatform Android/IOS app

### Feedback
MockEngine ideally should facilitate cross-platform unit testing, but there's no guidance on how to set it up. Naively I would expect it to be possible to wrap tests in `runBlocking` but while this is fine on JVM, it just hangs on iOS. Per @e5l on Slack it may be possible to use [XCTextExpectation](https://developer.apple.com/documentation/xctest/asynchronous_tests_and_expectations/testing_asynchronous_operations_with_expectations) but I haven't had a chance to test that yet.

**Comment by russhwolf** [comment]
As of 1.1.1, unit tests work as expected and no longer hang when using `runBlocking` and `MockEngine`. For example I have a demo project [here](https://github.com/russhwolf/ktor-demo) which includes [this `runBlocking` test](https://github.com/russhwolf/ktor-demo/blob/9f1d9e45e20c0040c099a5276c4cbf1fd5f3b2ce/app/src/commonTest/kotlin/sample/KtorClientTest.kt).

**Comment by e5l** [comment]
Mock engine is common now and the example can be found here: https://github.com/ktorio/ktor-samples/blob/0aeebb24390e50be2f090e25096d30a7aa4bbc80/feature/auth/test/io/ktor/samples/auth/OAuthTest.kt.

`runBlocking`: releates to https://github.com/Kotlin/kotlinx.coroutines/issues/770

Closed.
