### ISSUE TITLE
json not send

### ISSUE THREAD

**Issue by gmetekorkmaz** [ktorio/ktor#734]
### Ktor Engine Used: netty

i have a problem. i want to send response as application/json. But if i using double quotes in json text not working. WHY ? i have to send json text with double quotes.

NOT WORKING ) 
```
post("/test") {
                val resultJson = " {\"name\": \"test\"} "
                call.respondText(resultJson, ContentType.Application.Json)
}
```

WORKING ) 
```
post("/test") {
                val resultJson = " {'name': 'test'} "
                call.respondText(resultJson, ContentType.Application.Json)
}
```

**Comment by renannprado** [comment]
what do you mean by `not working`? do you get an exception?

**Comment by gmetekorkmaz** [comment]
i dont get exception. Ktor does not return content. 200ok but content empty.

**Comment by gmetekorkmaz** [comment]
i added cors and fixed problem. sorry, it was my fault

**Comment by clarksandholtz** [comment]
@gmetekorkmaz I'm glad you got it figured out! @renannprado Should this issue be closed since the problem has been resolved?

**Comment by renannprado** [comment]
@clarksandholtz I'm not allowed to do so, but yes I think it should be closed :)

**Comment by gmetekorkmaz** [comment]
Thanks :)
