### ISSUE TITLE
War artifact name is included in route resolution

### ISSUE THREAD

**Issue by hmarggraff** [ktorio/ktor#738]
### Ktor Version
1.0.0-rc

### Ktor Engine Used(client or server and name)
Servlet (Tomcat)

### JVM Version, Operating System and Relevant Context
JVM 8.x Win 10

### Feedback
When a web app is deployed via x.war, then routes in ktor must start with /x. I.e. renaming the war file results in failing routes. Ktor seems to use the wrong path for routing. (Not dispatch path, but coyote path)

**Comment by hmarggraff** [comment]
buildscript {
    ext.tomcat_plugin_version = '2.4.2'
    ext.tomcat_version = '9.0.4'

    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        //classpath "com.bmuschko:gradle-tomcat-plugin:$tomcat_plugin_version"
    }
}

apply plugin: 'kotlin'
apply plugin: 'war'

sourceSets {
    main.kotlin.srcDirs = [ 'src' ]
    main.resources.srcDirs = [ 'resources' ]
}

repositories {
    jcenter()
    maven { url "https://kotlin.bintray.com/ktor" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile "io.ktor:ktor-server-servlet:$ktor_version"
    compile "io.ktor:ktor-html-builder:$ktor_version"
    compile "org.slf4j:slf4j-jdk14:$slf4j_version"
}

war {
    archiveName = 'x.war'
    webXml = file('myweb.xml') // copies a file to WEB-INF/web.xml
}

**Comment by cy6erGn0m** [comment]
Fixed in 1.2.0-rc2
