### ISSUE TITLE
KotlinxSerializer only supports last registered list

### ISSUE THREAD

**Issue by keiththompson** [ktorio/ktor#739]
KotlinxSerializer only supports the last registered list. 
Each time a new list is registered (i.e `MyObject.serializer().list`), it replaces the previously registered list. 

I have a project with failing test cases here: https://github.com/keiththompson/KotlinxSerializer-Bug

Ktor Version: 1.0.0
Client: OkHttp
OS: MacOS
JVM: 
``` 
/usr/libexec/java_home -V
Matching Java Virtual Machines (1):
1.8.0_144, x86_64:  "Java SE 8"     
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
```

**Comment by e5l** [comment]
Hi, @keiththompson thanks for the report. It's a known issue.
The serializers registered by the target `KClass` object and it is the same for all lists: `List<*>`. There is no class `Type` in kotlin-native and kotlin-js for now, so the `KClass` is the only one possible key. 

If you have any thoughts about a possible solution you could share it with us. 
btw. PRs are always welcome :)

**Comment by Bluexin** [comment]
I guess this is true for any generic type?
Inlining of reified generic type could be recursive for this kind of use case.

**Comment by e5l** [comment]
We could make `registerListSerializer` for the list item `KClass` and handle it separately. 
I'll try to implement it in the next minor release.

**Comment by Bluexin** [comment]
The serialization library uses [this helper method](https://github.com/Kotlin/kotlinx.serialization/blob/fe24276aac0f2c21dab9579924dcd585a30ab01d/runtime/jvm/src/main/kotlin/kotlinx/serialization/Resolving.kt#L68-L72).
Maybe ktor could store the TypeToken as well instead of just the KClass?

I would really like the fix for this to work for any generic class, not just Lists ;p

**Comment by keiththompson** [comment]
@Bluexin That would only work on the jvm though, `Type` doesn't exist for native or js.

**Comment by Bluexin** [comment]
I forgot about that "small" detail 👼

**Comment by keiththompson** [comment]
I think some pre-factoring might be needed for a solution to support all generics. At present both read and write methods do a lookup on the serialiser map. So the only key we can use at all is the kClass because it's all we get passed in to write. 
```
interface JsonSerializer {
    fun write(data: Any): OutgoingContent

    suspend fun read(type: TypeInfo, response: HttpResponse): Any
}
```
Would it be a correct assumption to make that we'd at least need `TypeInfo` passed into write to perform a lookup on _anything_ else? Not sure of the implications of that elsewhere in ktor though.

**Comment by feresr** [comment]
Could I have an example of how to use this now, please?

```
private val client = HttpClient {
        install(JsonFeature) {
            serializer = KotlinxSerializer(Json.nonstrict).apply {
                registerList(Foo.serializer())
                registerList(Bar.serializer())
            }
        }
    }
```

^^ gets me the original error for both `Foo` and `Bar`: 

```
kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class ... for generic classes, such as lists, please provide serializer explicitly.
```

**Comment by feresr** [comment]
So after a day of research, I found that this problem is not really fixed:
https://github.com/ktorio/ktor/issues/969

I might be wrong, leaving this here for reference
