### ISSUE TITLE
Blocking adapters vs single-threaded dispatcher

### ISSUE THREAD

**Issue by cy6erGn0m** [ktorio/ktor#742]
Blocking coroutines can cause dead-locks with async filtering/processing coroutines (such as compression) on single-threaded dispatcher (single-threaded or pinned to thread event loop).

**Comment by cy6erGn0m** [comment]
It depends on https://github.com/Kotlin/kotlinx.coroutines/issues/850

**Comment by cy6erGn0m** [comment]
Should be partially fixed in 1.1.1

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-720">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
