### ISSUE TITLE
Outgoing websocket channel silently fails to send text frame

### ISSUE THREAD

**Issue by serebit** [ktorio/ktor#743]
### Ktor Version
All versions tested from 1.0.0-alpha-2 to 1.0.0
### Ktor Engine Used(client or server and name)
Websocket client
### JVM Version, Operating System and Relevant Context
JDK 1.8.0_192, Linux (Solus, latest updates)
### Feedback
I've minified the issue to the following, which requires a Discord API token to run. When using Ktor websockets, the application hangs on `socket.openSession`, and eventually times out. When using Http4k websockets, the application runs successfully. The demo project is here: https://gitlab.com/serebit/ktor-error-demo. **The master branch is the Http4k version, and the ktor branch is the Ktor version.**

**Comment by e5l** [comment]
The issue was in the CIO TLS implementation and fixed in `1.1.2`.
