### ISSUE TITLE
Streaming support in ContentConverter::convertForSend for ContentNegotiation

### ISSUE THREAD

**Issue by GRascm** [ktorio/ktor#747]
Looks like it's currently missing(or lacking documentation), and if i want to response large amount of data i have to fully convert it to string/bytes first.

**Comment by cy6erGn0m** [comment]
`convertToSend` can return an instance of sealed class `OutgoingContent`. Some of it's members provide ability to handle streaming.

**Comment by cy6erGn0m** [comment]
See https://ktor.io/servers/calls/responses.html#sending-response-content

**Comment by GRascm** [comment]
Looks like `WriteChannelContent` is something i was looking for, thank you very much.

Also i want to mention, that I've had to make some research to understand how to write custom `ContentConverter`. It was clear for me how to make `convertForReceive` from documentation and samples, but `convertForSend` that returns `Any?`, and have one example returning TextContent, was a little bit puzzle, that, i failed to solve without your help.

Oh, and the page you gave me cannot be found by "ContentNegotiation" search request.

PS Thank you for the great framework and language :)
