### ISSUE TITLE
Add default headers when using okHttpClient

### ISSUE THREAD

**Issue by ghostbuster91** [ktorio/ktor#754]
### Ktor Version
1.0.0
### Ktor Engine Used(client or server and name)
client-okHttp
### JVM Version, Operating System and Relevant Context
1.8
### Feedback
I notice that when I use retrofit with okHttp it adds some default headers like:
- accept-encoding
- connection
- host
- user-agent
I wonder if ktor client should do similar thing.

**Comment by cy6erGn0m** [comment]
`Host` is always added as it is required by HTTP/1.1
`Connection` is not required as it is `keep-alive` by default in HTTP/1.1 so there is no need to add it unless you need HTTP upgrade or `Connection: close`

`User-Agent` and `Accept-Endcoding` are user-specific and for sure ktor client shouldn't add them by default. 

However you can configure default header value by installing [DefaultRequest](https://ktor.io/clients/http-client/features/default-request.html) feature.


However it's easy to achieve by using

**Comment by ghostbuster91** [comment]
Ok, thanks for explaination, I will use `DefaultRequest` feature.
