### ISSUE TITLE
Default thread names in jetty-server.

### ISSUE THREAD

**Issue by bhandfast** [ktorio/ktor#756]
While debugging I noticed that the jetty server threads isn't named anything special. It would be great if they have a name that can be identified as ktor.

https://github.com/ktorio/ktor/blob/c820da63642c547e2c1941c68a318c5af9a53952/ktor-server/ktor-server-jetty/src/io/ktor/server/jetty/JettyKtorHandler.kt#L26

**Comment by cy6erGn0m** [comment]
Fixed in 1.1.0
