### ISSUE TITLE
Difference of cookies management strategies in ktor-client

### ISSUE THREAD

**Issue by dtolstyi** [ktorio/ktor#761]
### Ktor Version
1.0.0

### Ktor Engine Used(client or server and name)
Client with ApacheAsyncClient Engine

### JVM Version, Operating System and Relevant Context
1.8.x

### Feedback
There's not much info in docs but as far as I understood there are 2 possibilities to manage cookies:
1. **ktor**
```kotlin
            install(HttpCookies) {
                storage = AcceptAllCookiesStorage()
            }
```
In that case all new cookies are going to be saved

2. **Apache Async Client**
```kotlin
private val client = io.ktor.client.HttpClient(Apache) {
        engine {
            customizeClient {
                addInterceptorFirst(RequestAddCookies())
                addInterceptorFirst(ResponseProcessCookies())

                val cookiesStore = BasicCookieStore()
                setDefaultCookieStore(cookiesStore)
          }
     }
}
```

_Here are my questions:_
1. What's the difference between these approaches and which one is preferred way to manage cookies sessions?
2. In case of usin **ktor** approach is it possible to dynamically add cookies per request instance and not only during the initial configuration of client?

P.S. When both methods are used simultaneously there's a bug because "Cookie" header is added 2 times and when it's being sent it's merge into 1 header using `.joinToString(", ")`. And, if during the first request there are some default cookies the first cookie is going to be broken as far as it's name will be prepended with `", "` (e.g. `JSESSIONID=242` will become `, JSESSIONID=242`).
But, I don't think that someone is going to use both of them at the same time (except me when I was discovering how it works :D)

**Comment by e5l** [comment]
Hi, @dtolstyi. Thanks for the question. 
The first way is to use the `ktor` `HttpCookies` feature is cross-engine: you could write code once for all engines on every platform we have.
Some details about cookie feature: https://ktor.io/clients/http-client/features/http-cookies.html

To insert new cookie you could provide your custom `CookiesStorage` :
```
class CustomCookieStorage(private val defaultStorage: CookiesStorage): CookiesStorage {
    override suspend fun get(requestUrl: Url): List<Cookie> {
        val stored = defaultStorage.get(requestUrl)
        ...
        return myCookie
    }

    override suspend fun addCookie(requestUrl: Url, cookie: Cookie) {
        ...
    }

}
```

The second way is `Apache` engine specific, you could find more information about in the original docs:
https://hc.apache.org/httpcomponents-asyncclient-ga/index.html

**Comment by dtolstyi** [comment]
Thank you for explanation Leonid @e5l !
So, am I right that it's impossible to add cookies during the request phase with `AcceptAllCookiesStorage()` and to be able to do this I will have to recreate storage from the very beginning?

**Comment by e5l** [comment]
You could also save the reference to `AcceptAllCookiesStorage` and 
use `suspend fun addCookie(requestUrl: Url, cookie: Cookie): Unit ` method

**Comment by dtolstyi** [comment]
Wow. You are absolutely right. I forgot that I can create extensions functions with Kotlin. Thank you! Will do this!
