### ISSUE TITLE
FormBuilder lacks API constructing file upload request with custom body header

### ISSUE THREAD

**Issue by skyline75489** [ktorio/ktor#766]
### Ktor Version

1.0.0

### Ktor Engine Used(client or server and name)

OkHttp

### JVM Version, Operating System and Relevant Context

Android 28

### Feedback

With ktor, it seems that we can't post `Multipart/form-data` that has both `Content-Type` and `Content-Disposition` with `FormBuilder`.

Currently the following APIs are available:

```kotlin
fun FormBuilder.append(key: String, headers: Headers = Headers.Empty, bodyBuilder: BytePacketBuilder.() -> Unit)
fun FormBuilder.append(key: String, filename: String, bodyBuilder: BytePacketBuilder.() -> Unit) 
```

But we can't use filename and headers together to form body likes(copied from https://stackoverflow.com/a/28380690/3562486):

```plaintext
POST / HTTP/1.1
[[ Less interesting headers ... ]]
Content-Type: multipart/form-data; boundary=---------------------------735323031399963166993862150
Content-Length: 834
-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="file1"; filename="a.txt"
Content-Type: text/plain

Content of a.txt.

-----------------------------735323031399963166993862150
Content-Disposition: form-data; name="file2"; filename="a.html"
Content-Type: text/html

<!DOCTYPE html><title>Content of a.html.</title>
```

Inside the body both `Content-Type` header and `filename` are used.

**Comment by cy6erGn0m** [comment]
Please note that we probably shouldn't provide way to specify any headers as far as not all server allow custom headers. So only several should be allowed here such as `content-type` and `content-disposition`

**Comment by e5l** [comment]
Mergred
