### ISSUE TITLE
Requesting locations with fields of incompatible type gives Error 500

### ISSUE THREAD

**Issue by dsqrt4** [ktorio/ktor#767]
Say you have a location/routing like this:
```
//…
routing {
        get<Page> {
            call.respondText("On page ${it.page}")
        }
    }
// …
@Location("/pages/{page}")
class Page(val page: Int)
```

Requesting `http://service/pages/abc` will cause an exception because the `String` *abc* can't be cast to an `Int` which will ultimately lead to a response with *500 Internal Server Error*.

Wouldn't responding with something like *404 Not Found* or *400 Bad Request* be more appropriate?

**Comment by cy6erGn0m** [comment]
Fixed
