### ISSUE TITLE
"response.readText()" never returns (probably infinite loop)

### ISSUE THREAD

**Issue by dtolstyi** [ktorio/ktor#768]
### Ktor Version
1.0.0

### Ktor Engine Used(client or server and name)
Apache

### JVM Version, Operating System and Relevant Context
JDK 1.8.x, Win / Linux

### Feedback
After about 1-2 hours of constant requests using ktor client it unexpectedly hangs on line:
```
val data = response.readText()
```
ktor will never pass this line. Even after 9 hours it's still on this line.
No exceptions are thrown and the process is not closed.

This might do something with the response from the server because it's unpredictable at all. It might happen after 10 minutes and might be after 6 hours.

Are there any suggestions what this can be or how can I investigate this issue?
Maybe, there are some timeouts that I need to set?

Thank you.

**Comment by dtolstyi** [comment]
I don't have reproducer to provide but I can do any subset of steps that you tell me on my configuration. This isssue is constant on my system and I can reproduce it locally.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-717">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed. The fix will be released in Ktor `1.4.2`
