### ISSUE TITLE
Cookies per request

### ISSUE THREAD

**Issue by alamothe** [ktorio/ktor#769]
Is it possible to set cookie store per request (as opposed to per client instance)? Would you consider adding such feature?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-716">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in Ktor `1.5.0`
