### ISSUE TITLE
`OutputStreamContent` in server-core jar, but could be used by client as well

### ISSUE THREAD

**Issue by rocketraman** [ktorio/ktor#774]
### Ktor Version
1.0.0

### Ktor Engine Used(client or server and name)
Client CIO

### JVM Version, Operating System and Relevant Context
JDK 8, Linux

### Feedback
This is a follow-up to https://github.com/ktorio/ktor/issues/465. It looks like most of the content implementations were moved to a common jar, which is great, but for some reason [OutputStreamContent](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-core/src/io/ktor/http/content/OutputStreamContent.kt) was not? I don't see why I shouldn't be able to use this from a client as well.

**Comment by rocketraman** [comment]
> Well, how do you expect it to work? There is no `java.io.OutputStream` in common

Huh? `java.io.OutputStream` is in the JDK?

**Comment by rocketraman** [comment]
I verified this works fine from the client -- I copied the bits of this class directly into my project and used it without any problems.

**Comment by cy6erGn0m** [comment]
Ah I see, you mean common in terms server-client, not jvm-js-native, sorry

**Comment by rocketraman** [comment]
> Ah I see, you mean common in terms server-client, not jvm-js-native, sorry

Yup, sorry I didn't specify that... I keep forgetting Kotlin can do native :-)

**Comment by e5l** [comment]
We could make separate `OutputStreamContent` for jvm client engines
