### ISSUE TITLE
Working with config file

### ISSUE THREAD

**Issue by lightway82** [ktorio/ktor#778]
I have a section in config file:
app{
     users{
          user1 = some_value
          user2 = some_value
          user3 = some_value
      }
}

How i cat get list properties from users section? 
I can get properties by name, but I would like to get the entire list of properties in the section.
HoconApplicationConfig   can use config.getConfig("app.users").entrySet(),  but we dont can it (

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-714">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
