### ISSUE TITLE
Multiplatform NodeJS Http Client.

### ISSUE THREAD

**Issue by EltonZhong** [ktorio/ktor#782]
When will node js HTTP client be released?

**Comment by EltonZhong** [comment]
js-client use window.fetch api, which is not supported in node.js.

**Comment by EltonZhong** [comment]
Have you got a solution or plan for this? Have I missed anything in the document? BTW, I'm glad to contribute the node-js support.

**Comment by cy6erGn0m** [comment]
Doesn't [node-fetch](https://www.npmjs.com/package/node-fetch) provide fetch implementation?

**Comment by EltonZhong** [comment]
> Doesn't [node-fetch](https://www.npmjs.com/package/node-fetch) provide fetch implementation?

Yes

**Comment by EltonZhong** [comment]
> Hi, @EltonZhong. We're not focusing on node client for now, but we would really happy to accept the PR.

OK, working on it.

**Comment by EltonZhong** [comment]
Hi @e5l , Could you please have a look at https://github.com/ktorio/ktor/pull/791 ?
The node.js support for js-client based on 'node-fetch'.

**Comment by e5l** [comment]
Merged
