### ISSUE TITLE
Ktor-Client-iOS truncates JSON responses

### ISSUE THREAD

**Issue by spawn150** [ktorio/ktor#787]
### Ktor Version
1.0.1

### Ktor Engine Used(client or server and name)
ktor-client, ktor-client-android and ktor-client-ios

### JVM Version, Operating System and Relevant Context
iOS

### Feedback
We are developing a multiplatform app for Android and iOS. While for Android everything works smoothly, we are facing an issue with iOS version and Ktor client. It seems that randomly, calling the API, the response is truncated and we receive partial JSON data. We also tried starting from scratch using the Ktor Sample MPP App and we have the same behaviour simply changing the endpoint.

Here the Ktor sample app code changed:

     
    package io.ktor.samples.mpp.client

    import io.ktor.client.*
    import io.ktor.client.request.*
    import io.ktor.http.*
    import kotlinx.coroutines.*

    internal expect val ApplicationDispatcher: CoroutineDispatcher

    class ApplicationApi {
        private val client = HttpClient()

        //var address = Url("https://tools.ietf.org/rfc/rfc1866.txt")
        var address = Url("https://newsapi.org/v2/top-headlines?apiKey=cfe7a44a40e041ccaf8b9de9b1c71c28&country=us")

        fun about(callback: (String) -> Unit) {
            GlobalScope.apply {
                launch(ApplicationDispatcher) {
                    val result: String = client.get {
                        url(this@ApplicationApi.address.toString())
                    }

                    callback(result)
                }
            }
        }
    }

**Comment by e5l** [comment]
Hi, @spawn150. Thanks for the report. 

Could it be related with the response format? (I've got the string: ` according to a draft report fro… [+11921 chars]"}]}` in chrome).

**Comment by GiuseppeGiacoppo** [comment]
Hi @e5l , I have the exact same issue. I'm developing a multiplatform app that calls some rest apis and the response randomly gets truncated. Do you know when the fix could be available?
Thanks

**Comment by e5l** [comment]
Could you reproduce the issue with 1.1.2?

**Comment by e5l** [comment]
Fixed by [Kotlin/kotlinx-io#36](https://github.com/Kotlin/kotlinx-io/pull/36)

**Comment by cy6erGn0m** [comment]
Fixed in 1.1.3.
