### ISSUE TITLE
Support for consuming SSEs in HttpClient as a channel

### ISSUE THREAD

**Issue by ilya40umov** [ktorio/ktor#795]
Ktor version: 1.0.1

**Context**: While preparing an internal workshop on concurrency in Kotlin, where I was comparing different approaches and frameworks, I couldn't find a built-in way of using Ktor's HttpClient to consume SSEs as a channel. Instead, I ended up using `reactor.netty.http.client.HttpClient`, getting a Flux<String> from it, which I then converted into a channel:
https://github.com/ilya40umov/kotlin-concurrency/blob/master/coroutines/src/main/kotlin/org/ilya40umov/kc/coroutines/stream/StreamWinnerApi.kt#L17

**Expected**: Ktor should come with a built-in mechanism for consuming SSEs over HTTP

P.S. For the sake of comparison, here is how it looks with Spring's WebFlux:
https://github.com/ilya40umov/kotlin-concurrency/blob/master/reactive/src/main/kotlin/org/ilya40umov/kc/reactive/demo/DemoApiClient.kt#L31
https://github.com/ilya40umov/kotlin-concurrency/blob/master/reactive/src/main/kotlin/org/ilya40umov/kc/reactive/webflux/WebfluxWinnerHandler.kt#L27

**Comment by e5l** [comment]
Hi @ilya40umov, thanks for the report.
It could be a nice feature :)
Do you have an idea how to implement it?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-711">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by ilya40umov** [comment]
As mentioned in https://youtrack.jetbrains.com/issue/KTOR-711, this issue should be obsolete by now.
