### ISSUE TITLE
ktor-logging: logging multipart form data results in crash

### ISSUE THREAD

**Issue by jonasbark** [ktorio/ktor#797]
### Ktor Version
1.0.1

### Ktor Engine Used(client or server and name)
"io.ktor:ktor-client-core-jvm:$ktor_version"
"io.ktor:ktor-client-json-jvm:$ktor_version"
"io.ktor:ktor-client-logging-jvm:$ktor_version"
'com.squareup.okhttp3:okhttp:3.11.0'

### JVM Version, Operating System and Relevant Context
JVM, tested on Android

### Feedback
```
kotlinx.io.charsets.MalformedInputException: Input length = 1
                  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
                  at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
                  at android.os.Handler.handleCallback(Handler.java:873)
                  at android.os.Handler.dispatchMessage(Handler.java:99)
```
Happens e.g. with this code:
```
MultiPartFormDataContent(formData {
                    append("test", json, Headers.build {
                        append("Content-Type","application/json")
                    })
                    append("test2", bytearrayval, Headers.build {
                        append("Content-Type", ContentType.Application.OctetStream)
                        append("Content-Disposition", "form-data; name='file'; filename='test.jpg'")
                    })
                })
````

**Comment by e5l** [comment]
Hi, @jonasbark. Thanks for the report.
It's probably a bug and would be fixed in next release.

**Comment by e5l** [comment]
It looks like a bug in content encoding with `kotlinx-io`. Could you provide the `test.jpg` file?

**Comment by jonasbark** [comment]
If I'm not entirely mistaken this was indeed already fixed a while ago. We didn't encounter it again after updating - I'm closing this ticket
