### ISSUE TITLE
Digest challenge invokes browser credentials popup

### ISSUE THREAD

**Issue by sethchhim** [ktorio/ktor#798]
### Ktor Version
1.0.1

I would like to retrieve an initial digest response so that I can work with the response headers it gives. This works well but it also throws an `Unauthorized 401` response resulting in an unwanted browser popup requesting credentials. I believe this is because of the specific status of 401. Could we use a generic status instead to prevent this?

[DigestAuth.kt](https://github.com/ktorio/ktor/blob/6c724f804bd6f25158d284d05c49235c67573019/ktor-features/ktor-auth/src/io/ktor/auth/DigestAuth.kt) Line 75-78
```
context.challenge(digestAuthenticationChallengeKey, cause) {
    call.respond(UnauthorizedResponse(HttpAuthHeader.digestAuthChallenge(realm)))
    it.complete()
}
```

Thank you for any consideration.

**Comment by sethchhim** [comment]
I solved this by changing `UnauthorizedResponse` to a `ForbiddenResponse`. I'm sure 401 is correct and standard practice but that browser popup is not needed for my use case. 

```
fun Authentication.Configuration.digestFix(name: String? = null, configure: DigestAuthenticationProvider.() -> Unit) {
    val provider = DigestAuthenticationProvider(name).apply(configure)
    val realm = provider.realm
    val userNameRealmPasswordDigestProvider = provider.userNameRealmPasswordDigestProvider
    val digester = provider.digester

    provider.pipeline.intercept(AuthenticationPipeline.RequestAuthentication) { context ->
        val authorizationHeader = call.request.parseAuthorizationHeader()
        val credentials = authorizationHeader?.let { authHeader ->
            if (authHeader.authScheme == AuthScheme.Digest && authHeader is HttpAuthHeader.Parameterized) {
                authHeader.toDigestCredential()
            } else
                null
        }

        val principal = credentials?.let {
            if ((it.algorithm ?: "MD5") == digester.algorithm
                && it.realm == realm
                && it.verifier(call.request.local.method, digester, userNameRealmPasswordDigestProvider))
                UserIdPrincipal(it.userName)
            else
                null
        }

        when (principal) {
            null -> {
                val cause = when (credentials) {
                    null -> AuthenticationFailedCause.NoCredentials
                    else -> AuthenticationFailedCause.InvalidCredentials
                }

                context.challenge("Digest", cause) {
                    call.respond(ForbiddenResponse(HttpAuthHeader.digestAuthChallenge(realm)))
                    it.complete()
                }
            }
            else -> context.principal(principal)
        }
    }

    register(provider)
}
```

```
class ForbiddenResponse(vararg val challenges: HttpAuthHeader) : OutgoingContent.NoContent() {
    override val status: HttpStatusCode?
        get() = HttpStatusCode.Forbidden

    override val headers: Headers
        get() = if (challenges.isNotEmpty())
            headersOf(HttpHeaders.WWWAuthenticate, challenges.joinToString(", ") { it.render() })
        else
            Headers.Empty
}
```

**Comment by cy6erGn0m** [comment]
For sure it shouldn't be forbidden. According to the specification digest auth should reply with 401 Unauthorized. 

The question is what is your usecase and why you don't need a popup?

**Comment by cy6erGn0m** [comment]
Ah I see, perhaps you are trying to achieve this, right? https://stackoverflow.com/questions/9859627

**Comment by cy6erGn0m** [comment]
Please note that Fetch API doesn't show popup:

```javascript
fetch("http://httpstat.us/401", {requiredStatus: 'ok'})
    .then(function(response) {
        console.log("Status: " + response.status);
    }).catch(function() {
        console.log("fail!");
    }); 
```
Prints

>Status: 401

**Comment by sethchhim** [comment]
`Ah I see, perhaps you are trying to achieve this, right?`

  Correct, I am using my own html input form to handle credential input. This should be a popular use case.

`Please note that Fetch API doesn't show popup:`

  The popup shows when the authentication header provides the scheme of Basic or Digest: 

  `WWW-Authenticate: Digest realm="Ktor Server", nonce="85b86e6ca341f18d", algorithm="MD5"`

**Comment by sethchhim** [comment]
No action required, solution posted above.
