### ISSUE TITLE
What Dispatcher should I use with socket?

### ISSUE THREAD

**Issue by kobe2000** [ktorio/ktor#799]
### Ktor Version
1.0.1
### Ktor Engine Used(client or server and name)
Server Netty and Client traditional commons httpclients in Java
### JVM Version, Operating System and Relevant Context
1.8.152 Windows10
### Feedback

I use ktor for a few month. In one of my project (a heavy CPU-bound program), I use a global instance as a socket factory:
```
val tcp = aSocket(ActorSelectorManager(Dispatchers.IO)).tcp()
```
But I found there are often huge network delay, above ten senconds and more. Then I change it to:
```
val tcp = aSocket(ActorSelectorManager(Executors.newSingleThreadExecutor().asCoroutineDispatcher())).tcp()
```
Then there are no delay any more.

I wrap all heavy computation in such manner:
```
val processThreadPools = Array<CoroutineContext>(processThreadCount) { thread ->
        Executors.newSingleThreadExecutor { runnable ->
            Thread(null, runnable, "process-thread-$thread", OMP_STACKSIZE)
        }.asCoroutineDispatcher()
    }
......
withContext(processThreadPools[thread]) {
   ....//Heavy Computation
}
```

To my knowlege, it should be OK and correct to use `Dispatchers.IO` because sockets are IO, isn't it? Or there are some code "block" the dispatcher while I did't aware of?

Thanks

**Comment by Bluexin** [comment]
All I know (from the doc) is `Dispatchers.IO` can share threads with the default one, but that shouldn't matter since you use your own threadpool for your heavy compute stuff.

**Comment by e5l** [comment]
Hi @Bluexin, consider using `Dispatchers.IO`.
