### ISSUE TITLE
kCFStreamErrorDomainSSL, -9807 only when running tests

### ISSUE THREAD

**Issue by nestserau** [ktorio/ktor#810]
Ktor Version: 1.0.0
Ktor Engine Used: MPP, Native
JVM Version: 1.8, macOS 10.14.2

I have an MPP library which I compile to a framework for iOS and Android. The issue is with the iOS counterpart. When I run the code exposing HttpClient from a unit test, it stops with the following message in the terminal: `test.kexe[30902:4165297] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9807)`. But when I include my library in a Swift project and invoke the method from there, I don't get this error anymore and everything works as expected.

The code:

```
suspend fun <T> send(message: MessageStrategy<T>): MessageResult<T> {

        val request = message.buildRequest()
       ...

        val payload: ByteArrayContent = {
            val encodedMessage = request.record.encode()
            val bytes = ByteArray(encodedMessage.size) { encodedMessage[it].toByte() }
            ByteArrayContent(bytes)
        }()

        val url = session.host

        val response: HttpResponse

        try {
            response = client.post(url) { body = payload } // It hangs here not reaching the catch block
        }
        catch (e: Throwable) {
            return MessageResult.failed(MessageError.NetworkError())
        }

        return ...
    }
```
The test:
```
    @Test
    fun loginTest() = runBlocking<Unit> {
        val session = Session(MockDefaultsStorage())
        val backend = Backend(session)
        val login = ...
        val result = backend.send(LoginMessageStrategy(login))
        assertTrue(result is MessageResult.ok<SessionState>, "$result")
       ...
    }
```
So it doesn't even reach the `assertTrue`. However, the same code works perfectly when I call it from Swift. But for Swift I use a help method, because suspend functions don't get exposed:

```
fun <T> send(message: MessageStrategy<T>, callback: (MessageResult<T>) -> Unit) {
        GlobalScope.apply {
            launch(ApplicationDispatcher) {
                callback(send(message))
            }
        }
    }
```
One would think that the issue is with the Info.plist, but my Info.plist for the Swift project is default, no SSL related settings. I also tried to copy a custom Info.plist to the directory with the test binary, however it didn't have any effect on how it goes.

**Comment by e5l** [comment]
You can't use `runBlocking` with `ios` client engine for now:  the request is scheduled in the main queue.

**Comment by nestserau** [comment]
I get it. That might also be the reason for this weird error. Could you advise how I test suspend functions in iOS? Or alternatively standard functions, but with a callback?

**Comment by nestserau** [comment]
So I've implemented runBlocking for iOS using this code as example: https://github.com/bootstraponline/run_blocking/commit/a7953192c7078ab41dbf382f56bdc4432a46c84b#diff-c1a933ca71f0c706f65401b240f8c806 Further for testing purposes I'm now using clear-text HTTP. I'm closing the issue for now.
