### ISSUE TITLE
how can i configuring the client

### ISSUE THREAD

**Issue by luckyxiaomo** [ktorio/ktor#814]
### Ktor Version
    ktor_version 1.0.1
### Ktor Engine Used(client or server and name)
    compile "io.ktor:ktor-client-apache:$ktor_version"
    compile "io.ktor:ktor-client-core:$ktor_version"
    compile "io.ktor:ktor-client-core-jvm:$ktor_version"
    compile "io.ktor:ktor-client-json-jvm:$ktor_version"
    compile "io.ktor:ktor-client-gson:$ktor_version"
    compile "io.ktor:ktor-client-netty:$ktor_version"

**Comment by e5l** [comment]
Hi @luckyxiaomo, could you clarify the question?

There is no `ktor-client-netty` yet :), probably you should try without it.

**Comment by luckyxiaomo** [comment]
Sounds like it's all I can do is without it
