### ISSUE TITLE
Error 'Fail to obtain native stream' in Firefox

### ISSUE THREAD

**Issue by lambcode** [ktorio/ktor#816]
### Ktor Version
1.0.1

### Ktor Engine Used(client or server and name)
JsClientEngine

### JVM Version, Operating System and Relevant Context
Firefox 64.0

### Feedback
I am getting a "IllegalStateException: Fail to obtain native stream" error when doing a GET request on firefox. The network tab in the debug tools shows that the request completed successfully. The same code works in Chrome.

It looks like this may be due to the Reponse.body property not being supported yet in firefox. https://developer.mozilla.org/en-US/docs/Web/API/Body/body

The error appears to be coming from https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/ktor-client-core-js/src/io/ktor/client/engine/js/compatible/browser/BrowserUtils.kt when the resp.body property is accessed.

My code
```
fun makeRequest() {
    HttpClient(JS).get("http://localhost:8080/")
}
```

Let me know if you need more info

**Comment by e5l** [comment]
Hi @lambcode. It looks like browser incompatibility here. Do you have an idea how to fix it?

**Comment by egoossens** [comment]
Hi, I'm getting the same error in React Native.

Using ktor-client in a Kotlin Multiplatform project producing JS for a node module that is later used in a React Native app. The response is obtained correctly when I console.log it just before the exception. 

I only need to get the response as a string. Isn't there a way to bypass the getBodyContentAsChannel function and get the raw response?

Thanks

**Comment by e5l** [comment]
Hi, @egoossens. What version of ktor do you use? 
Did you install `note-fetch`module?

**Comment by egoossens** [comment]
1.1.2

**Comment by egoossens** [comment]
I'm using 1.1.2
I'm not sure it's connected to node-fetch as the exception is thrown from BrowserUtils?
I'll install it though and see what happens.

**Comment by egoossens** [comment]
No change after installing `node-fetch`.
The response object has _bodyInit and _bodyText properties containing the raw response. Any way to access that and bypass the exception? I could write my own engine but maybe there's something easier?

**Comment by e5l** [comment]
Fixed in `master`.
