### ISSUE TITLE
Implement proper unhandled exception handling strategy 

### ISSUE THREAD

**Issue by orangy** [ktorio/ktor#82]
If exception happens in ktor and is not handled by an interceptor such as StatusPages, it should propagate up to host and be handled there without using any ktor facilities like response pipeline. The reason is that we don't know which part of the system were at fault and it could very well be response pipeline itself. So unhandled exception should be propagated to the host-specific facilities and responded with 500 status code natively there.

Note, that it would make `500 Internal Server Error` status produced in this case not interceptable by `StatusPage` feature on a per code basis, but exception filter in the same feature can be installed on `Throwable` and do pretty much any custom handling there. At this moment exception would be considered handled and won't be part of this issue.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-835">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in Ktor 1.5.0
