### ISSUE TITLE
MapApplicationConfig should not be final

### ISSUE THREAD

**Issue by wem** [ktorio/ktor#822]
### Ktor Version
1.0.1

### Ktor Engine Used(client or server and name)
CIO

### JVM Version, Operating System and Relevant Context
Linux Mint / Debian
Java 8 / 11

### Feedback

As mentioned in the documentation on https://ktor.io/servers/configuration.html#custom the MapApplicationConfig can be used for custom configuration. It would be nice when this class is also not final, like the Hocon variant is.

**Comment by cy6erGn0m** [comment]
Fixed in 1.1.0
