### ISSUE TITLE
Environment doesn't match class Interface

### ISSUE THREAD

**Issue by chrisjenx** [ktorio/ktor#825]
### Ktor Version
1.1.0

### Ktor Engine Used(client or server and name)
Netty

### JVM Version, Operating System and Relevant Context
1.8.0_181, OSX, Running from IDEA

### Feedback

Trying to talk to the Enviroment but get this:
java.lang.ClassCastException: io.ktor.server.engine.ApplicationEngineEnvironmentReloading cannot be cast to io.ktor.server.engine.ApplicationEngineEnvironmentReloading

I'm going to take a guess because of the class reloading, I'm assuming we're in different class loaders so while the classes are really the same, they are in different loaders.

This might actually be a Java bug?

Relative code:
```
fun Application.hrefWithHostname(location: Any): String {
    val env = environment as ApplicationEngineEnvironmentReloading
    val connectors = env.connectors
    val hostname = connectors.lastOrNull()?.let { "${it.type}://${it.host}:${it.port}" }
    return URLBuilder("$hostname${locations.href(location)}").buildString()
}
```

Thanks!

**Comment by cy6erGn0m** [comment]
1. This class need to be internal 
2. It should be protected from double class-loading
3. `connectors` should be available through some API when accessible (could be inaccessible)

The question is why do you access it from an application instance? Shouldn't you detect it from a call?

**Comment by chrisjenx** [comment]
I don't need access to them. I was just trying to calculate external link
including host and port, it seemed the easiest place to get that info.

I.e. sending an email with a public activation link.

**Comment by cy6erGn0m** [comment]
Well, these are usually generated by a request but I can imagine cases when it is done by schedule. The problem is that there is no way to get connectors it an application is deployed into a servlet container like tomcat: it doesn't provide any API to find connectors details. The other problem is that it's not clear which connector need to be used if there are multiple connectors configured so accessing connector is not suitable in many production configurations.

**Comment by dave08** [comment]
I also had many times a use case with microservices that I need to expose two connectors, one for internal api such as metrics to be pulled by Prometheus and other inter microservice communication, and the other external with a domain name or different port for external api.

In such cases it would have been useful to not only expose connectors if available, but to have an embeddedServer declaration to make it easy to construct (like a list of ports), and some routing helpers in the DSL for port and domain...

**Comment by cy6erGn0m** [comment]
Accessing connectors would look like this for now:

```
val environment = application.environment
val connectors = when (environment) {
    is ApplicationEngineEnvironment -> environment.connectors
    else -> throw UnsupportedOperationException("Connectors configurations is not accessible")
}
```

However this requires future bugfixes since `ApplicationEngineEnvironment` is also not protected from double classloading

**Comment by cy6erGn0m** [comment]
And yes, in cases when no request available, it is usually done via application config
