### ISSUE TITLE
ContentConverter for list, map or other generic types

### ISSUE THREAD

**Issue by syhily** [ktorio/ktor#831]
### Ktor Version

1.0.1

### Ktor Engine Used(client or server and name)

Jetty Server

### JVM Version, Operating System and Relevant Context

1.8.0 Update 191, macOS 10.14.2

### Feedback

![image](https://user-images.githubusercontent.com/1761698/50422822-e6aa3680-0888-11e9-9d22-3da36afad60e.png)

I use `post<List<ConfigCorepage>>("/api/pageName/update")` to accept the json content from user request, but ktor couldn't recognize the type `List<ConfigCorepage>`, it use `List` instead.

I debug the code, and find that the [code](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-core/jvm/src/io/ktor/request/ApplicationReceiveFunctions.kt#L57) here shouldn't use `T::class`.

Jackson use a `TypeReference` class for preserving class info, ktor should use the same tricks.

**Comment by syhily** [comment]
Could we move the https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/common/src/io/ktor/client/call/TypeInfo.kt to upper level to let the server & client share the same typeinfo definition.

**Comment by ansman** [comment]
Just as an FYI, this relates to both serializing and deserializing. If the user uses the type `List<String>` but passes `EmptyList` libraries like `Moshi` won't find an adapter for it so it would be great if the type could be explicitly specified rather than being inferred from the object that is sent.

**Comment by respinha** [comment]
Will this be fixed? It can really stop you from using Jackson as a serializer.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-707">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed since Ktor 1.3.2
