### ISSUE TITLE
ios artifact naming

### ISSUE THREAD

**Issue by CedricGatay** [ktorio/ktor#837]
### Ktor Version
1.1.0 and onward
### Ktor Engine Used(client or server and name)
Client with a native target iOS
### JVM Version, Operating System and Relevant Context
JDK 8 / MacOS Mojave / Multiplatform build
Since 1.1.0 it seems that the artifact are badly named, if I browse bintray I can see that 
 * io.ktor:ktor-client-core-ios and io.ktor:ktor-client-json-ios do not contain versions higher than 1.0.1
 * new artifacts seem to be published under io.ktor:ktor-client-core-ios[arm64,macosx64]

### Feedback
If there is a clean migration path for artifact names I did not find it, if I downgrade ktor to 1.0.1 everything works fine, here is my multiplatform build excerpt

```
iOSMain.dependencies{
            api "io.ktor:ktor-client-ios:${ktor_version}"
            api "io.ktor:ktor-client-core-ios:${ktor_version}"
            api "io.ktor:ktor-client-json-ios:${ktor_version}"
}
```

Kind regards,

**Comment by e5l** [comment]
Hi @CedricGatay. 
Could you try?

```
iOSMain.dependencies{
            api "io.ktor:ktor-client-ios:${ktor_version}"
            api "io.ktor:ktor-client-core-native:${ktor_version}"
            api "io.ktor:ktor-client-json-native:${ktor_version}"
}
```

https://ktor.io/quickstart/migration/1.1.1.html

**Comment by CedricGatay** [comment]
Hi @e5l
It works flawlessly with this change !
I've completely misread this part of the changelog, sorry for wasting your time :-(

**Comment by e5l** [comment]
No problem :)
