### ISSUE TITLE
Unable to use KotlinxSerializer for Json List values in response

### ISSUE THREAD

**Issue by wem** [ktorio/ktor#839]
### Ktor Version
1.1.1

### Ktor Engine Used(client or server and name)
JS

### Feedback
For me, it's not possible to deserialize a JSON list value from an HTTP response.

**Comment by e5l** [comment]
Hi @wem, thanks for the report.
It's an known issue with `kotlinx.serialization`. 
The possible workarund is to register list serializer manualy(with `KotlinxSerializer`).

**Comment by e5l** [comment]
Could you try to use `registerList` method in `1.1.2`?

**Comment by wem** [comment]
It's still not working on responses for requests like client.get<List<Dto>>(...) { ... }

But i think this is currently anyway not possible because of type erasure as a list is a parameterized type. 
When i take a look into the code the listMappers are also not queried on lookupSerializerByType

**Comment by e5l** [comment]
Fixed with `typeOf` support in 1.3.0
