### ISSUE TITLE
Unsupported format version '0.3' specified in module metadata. This version of Gradle supports format version 0.4 only.

### ISSUE THREAD

**Issue by jittya** [ktorio/ktor#841]
### Ktor Engine Used ktor-client-android:1.0.1

Build error when ever i use new gradle metadata.

**Comment by e5l** [comment]
Hi @jittya, thanks for the report.
Please make sure that you're using gradle 4.7 version. 
It's the only supported gradle version for now.

**Comment by jittya** [comment]
thanks i was using 4.10. Fixed

**Comment by mehdok** [comment]
I'm using Gradle 4.10.1 and having same problem. The problem occurs when I enable Gradle metadata `enableFeaturePreview('GRADLE_METADATA')`
