### ISSUE TITLE
If use @location ,At the same time, this route needs post method to solve. I can only use the post of io.ktor.routing.post, but it feels weird

### ISSUE THREAD

**Issue by LEFrost** [ktorio/ktor#844]
such as
get<MyRoute> {
...
}
post("/myroute"){
...
}

This does not seem to be type-safe route

**Comment by cy6erGn0m** [comment]
There is `post<T>` function in locations, see https://github.com/ktorio/ktor/blob/46f42b89dda5bff12c8bf49491603cfe11192ff6/ktor-features/ktor-locations/jvm/src/io/ktor/locations/Location.kt#L119

So there are several `post` functions and you probably need to import the right one. Try `import io.ktor.locations.post`

**Comment by LEFrost** [comment]
thanks,I have solved it before. It turns out that I did not add default arguments ​​to the fields, so I can't use it.
