### ISSUE TITLE
When Route.authenticate has multiple configurations (>1) only first configuration is used to authenticate

### ISSUE THREAD

**Issue by orangefiredragon** [ktorio/ktor#847]
### Ktor Version
1.1.1
### Ktor Engine Used(client or server and name)
Server Netty
### JVM Version, Operating System and Relevant Context
OpenJDK 11, OSX
### Feedback
authenticate("a1", "a2") {...
If "a1" authentication is not successful, "a2" is not used and response is 401 Unauthorized

**Comment by annacox** [comment]
Fwiw, I'm also seeing this issue on version 0.9.3. I'm not sure if it's the same root cause or not.

**Comment by fouady** [comment]
I see the same problem in version 1.3.0
Any idea when this can be fixed?

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-702">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by rsinukov** [comment]
Fixed in 1.3.1 by #1586
