### ISSUE TITLE
Version of com.auth0:jwks-rsa used by ktor-auth-jwt contains known security vulnerability

### ISSUE THREAD

**Issue by annacox** [ktorio/ktor#856]
### Ktor Version
All

### Ktor Engine Used(client or server and name)
`ktor-auth-jwt`

### Feedback
The current version of `com.auth0:jwks-rsa` that is being used by `ktor-auth-jwt` (0.5.0) contains a security vulnerability in the `com.google.guava:guava` library. See https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236 for details. `com.auth0:jwks-rsa` has resolved this vulnerability by upgrading their guava dependency in version [0.6.1](https://github.com/auth0/jwks-rsa-java/releases/tag/0.6.1). Would it be possible to upgrade the jwks-rsa version to 0.6.1 or later?

**Comment by cy6erGn0m** [comment]
Did upgrade to 0.7.0. Thanks!

**Comment by annacox** [comment]
Thank you for the speedy response, I really appreciate it!
