### ISSUE TITLE
No Generate `suspend` method in iOS 

### ISSUE THREAD

**Issue by ImanX** [ktorio/ktor#858]
### Ktor Version 1.1.1 

I use kotlin native and implemented `ktor` when I define `suspend` function don't generate method in iOS `.framework` while in Android generate and usable.
How to use `HttpRequest` on iOS ?

**Comment by e5l** [comment]
Unfortunately, there is no way to call suspend function from the Swift objective C code.

Probably you could write the callback adapters for iOS or use some patterns(MVP: https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93presenter and etc).

You could check https://github.com/JetBrains/kotlinconf-app for examples.

**Comment by ImanX** [comment]
@e5l Thank you bro.
 I changed my opinion and I used `observer` pattern it but don't receive response in iOS while Android work it.

**Comment by e5l** [comment]
Let's figure it out. Could you provide the code sample?

**Comment by ImanX** [comment]
@e5l OK, I recently wrote code by `closure` but again don't work but Android is still right.

**Comment by ImanX** [comment]
@e5l 
in my `common` package
`fun createRequest(bar: (m: String) -> Unit) {
    val client = HttpClient()
    client.async {
        val call = client.call("https://google.com") {
            method = HttpMethod.Get
        }
        bar(call.response.readText());
    }
}`

my code in Swift:
`
APICoreKt.createRequest { (s) -> KotlinUnit in
            let lbl = UILabel(frame: CGRect(x: 100, y: 100, width: 100, height: 100));
            lbl.text = s;
            lbl.textColor = UIColor.black;
            self.view.addSubview(lbl);
            return KotlinUnit();
        }
`
any response don't reach in closure body.

**Comment by ImanX** [comment]
@e5l Now what I do ? 👀

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-700">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
https://youtrack.jetbrains.com/issue/KT-51891
