### ISSUE TITLE
call.sessions.set<SessionData> doesn't do anything in websocket

### ISSUE THREAD

**Issue by henry1986** [ktorio/ktor#864]
### Ktor Version
1.1.1
### Ktor Engine Used(client or server and name)
netty
### JVM Version, Operating System and Relevant Context
kotlin version 1.3.11
### Feedback

We are using websockets and are trying to store session data in the websocket session.

```kotlin
embeddedServer(Netty, port = conf.port) {
            install(DefaultHeaders)
            install(CallLogging)
            install(Sessions) {
                cookie<SessionData>("cookie_name")
            }
            install(WebSockets) {
                pingPeriod = Duration.ofMinutes(1)
            }
            routing {
                webSocket("/ws") {
                    val s = call.sessions.get<SessionData>()
                    if (s != null) {
                        logger.debug { "session found $s" }
                    } else {
                        call.sessions.set(SessionData("websocketSession"))
                    }
                }
                get("/session") {
                    val s = call.sessions.get<SessionData>()
                    if (s == null) {
                        println("no existing session")
                        call.sessions.set(SessionData("wow"))
                    } else {
                        println("hello session: $s")
                    }
                    call.respondHtml {
                        // some respond
                    }
                }
// some further code
```

Calling a default http - get Method http://127.0.0.1:$port/sessions works wonderful, as expected - the session data is stored at first call.

But with using `webSocket("/ws"`, no sessions data is ever stored.

Am I doing something wrong, or is this by design or is this bug? If the latter is the case, is there a workaround or is this going to be fixed?

Best Regards

**Comment by cy6erGn0m** [comment]
Setting session in websocket is impossible because HTTP protocol is already upgraded to the binary webosocket protocol. We have to crash at attempt to set session if a response has been ready sent.

**Comment by henry1986** [comment]
Before the http upgrade I don't have the information I would like to have, so this doesn't help at all ;)

I did some research on this and if I understand you correctly, it is not possible, to store session data after the http upgrade.

But what is the bug then, that you are planing to fix? To crash at attempt doesn't sound like a solution anyone would like to have, would they? 

And maybe the better solution in general would be, if I store the cookie by javascript on the client side and send the information via websockets to the server. There I have to manage it on my own, and not by Ktor.

So in this case, the only thing that is to be fixed in the ktor library would be to show the user of ktor, that session data could not be stored in a websocket session. Maybe by throwing a RuntimeException?

Just my thoughts.

**Comment by cy6erGn0m** [comment]
Yes, the bug is that ktor allows you to set session with no errors. So yes, an exception should be thrown. There is absolutely no way to do that on server side unless to send a custom message to a client that may parse it and apply session data via JavaScript.

**Comment by cy6erGn0m** [comment]
Fixed: ability to set session if it's too late is prohibited.
