### ISSUE TITLE
ktor-client-logging: Sending empty body after logging at BODY/ALL 

### ISSUE THREAD

**Issue by detouched** [ktorio/ktor#868]
### Ktor Version
1.1.1

### Ktor Engine Used(client or server and name)
Client, Apache

### JVM Version, Operating System and Relevant Context
JDK 8, macOS 10.14.2

### Feedback
`Logging` feature with `level` set to `BODY` or `ALL` irrevocably consumes request body causing it to be fired with an empty content in case body was passed in as an input stream.

I'd expect the client to either skip such body when logging the request or maybe support something like mark/reset when possible.

**Comment by e5l** [comment]
Hi @detouched, thanks for the report.
Could you reproduce it with `1.1.3`?

**Comment by detouched** [comment]
Hi @e5l,

Yes, my sandbox project is using `1.1.3`. It basically sends a POST request using `formData` like described in the [docos](https://ktor.io/clients/http-client/calls/requests.html) and passes in content as a stream, something like `append("file", someFile.asInput()`.

**Comment by e5l** [comment]
Yep. It looks like an issue that form data could be consumed only once. Thanks for the details, [WIP].
