### ISSUE TITLE
Allow resolving URLs against another URL similar to a browser

### ISSUE THREAD

**Issue by ansman** [ktorio/ktor#874]
### Ktor Version
1.1.1

### Ktor Engine Used(client or server and name)
N/A

### JVM Version, Operating System and Relevant Context
N/A

### Feedback
When modeling a large API using a ktor HTTP client it would very useful to allow resolving a string against another URL.

Usually one would have a base URL that includes the common things (protocol, host, base path etc) and each endpoint only knows specific things. For example this would be nice:
```kotlin
val baseUrl = Url("https://example.com/api/v1/")
val client = HttpClient(...)
suspend fun getStuff() =
    // Would get stuff from https://example.com/api/v1/stuff
    client.get<Stuff>(baseUrl.resolve("stuff"))
```

Here are some more examples of how it would work:
```kotlin
// Sibling when the base URL doesn't end with a /
Url("https://example.com/api/v1").resolve("foo") // => https://example.com/api/foo
// Child when the base URL doesn't end with a /
Url("https://example.com/api/v1/").resolve("foo") // => https://example.com/api/v1/foo
// Root when the appending URL starts with a /
Url("https://example.com/api/v1/").resolve("/foo") // => https://example.com/foo
// Replacing when the appending URL is a full URL
Url("https://example.com/api/v1/").resolve("https://other.com") // => https://other.com
// Protocol inferred from other URL
Url("https://example.com/api/v1/").resolve("//other.com") // => https://other.com
```

**Comment by e5l** [comment]
Hi @ansman, thanks for the report.
`UrlBuilder.takeFrom` could work for you.

**Comment by ansman** [comment]
The `takeFrom` method is close but doesn't work like a browser resolving a URL:
```kotlin
URLBuilder("https://example.com/api/v1")
    .takeFrom("foo").build() // https://example.com/foo
URLBuilder("https://example.com/api/v1/")
    .takeFrom("foo").build() // https://example.com/foo
URLBuilder("https://example.com/api/v1/")
    .takeFrom("/foo").build() // https://example.com/foo
URLBuilder("https://example.com/api/v1/")
    .takeFrom("https://other.com").build() // https://other.com
URLBuilder("https://example.com/api/v1/")
    .takeFrom("//other.com").build() // https://other.com
```

Notably it's resolving relative paths that doesn't work as `resolve` would.

**Comment by e5l** [comment]
Thanks for the notice

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-699">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
