### ISSUE TITLE
JsonSerializer.write should also receive a type

### ISSUE THREAD

**Issue by ansman** [ktorio/ktor#875]
### Ktor Version
1.1.1

### Feedback
Currently `JsonSerializer.read` accepts a `TypeInfo` object which is great since it handles parameterized types. The `write` method does not which is unfortunate since it can lead to problematic cases.

If you consider the case where you pass `emptyList<String>()` the actual type is `EmptyList` which on some JSON libraries (for example Moshi) fails to return an adapter.

It can also lead to problems when using inheritance:
```kotlin
interface Named {
  val name: String
}

data class Person(val email: String, override val name: String) : Named

fun getName(): Named {
  return Person("info@example.com", "Nicklas")
}

client.post<SomeResponseType>("https://example.com") {
  // Since the return type of getName is Named we expect the JSON to be written to be
  // {"name": "Nicklas"} but it will instead be serialized as a Person
  body = getName()
}
```

A proposed solution could be to introduce a `bodyType` property of `HttpRequestBuilder` and add a `body` function that is reified and will get the type of the object as far as the call site is concerned.

**Comment by e5l** [comment]
Hi @ansman, thanks for the report. 
Do you have the idea of how to pass body type info?

**Comment by jbenoit2011** [comment]
This feature would be great since currently serialization of parameterized type is not possible since type parameter is erased at compile-time and inferred data type does not contain type parameter.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-698">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
