### ISSUE TITLE
routing that match both * and ""

### ISSUE THREAD

**Issue by stanbar** [ktorio/ktor#878]
### Ktor Version
1.1.1
### Ktor Engine Used(client or server and name)
netty
### JVM Version, Operating System and Relevant Context
OracleJDK 1.8.0_172 macOS
### Feedback
I'm building frontend app with React.
My routing is managed in webapp using [react-router-dom](https://reacttraining.com/react-router/web/guides/quick-start)
And I would like to host it from Ktor. Here is how I'm doing it right now
```kotlin
  routing {
    route("/api") {
      get("/foo") {
        ...
      }
      get("/bar") {
        ...
      }
    }
    static("*") {
      staticBasePackage = "assets"
      resources("static")
      resource("favicon.ico")
      resource("index.html")
      resource("manifest.json")
      resource("asset-manifest.json")
      resource("service-worker.js")
      defaultResource("index.html")
    }
  }
```

and almost everything is working fine, besides defaultResource.
When I call `localhost:8080` then I get `ERROR 404` ( * doesn't match empty path)
But when I call `localhost:8080/books` (which is one of my routing handled by react-router-app) then it property display my webapp starting from default `index.html`
The workaround is to add another route matching empty path: 
```kotlin
    static("") {
      staticBasePackage = "assets"
      resources("static")
      resource("favicon.ico")
      resource("index.html")
      resource("manifest.json")
      resource("asset-manifest.json")
      resource("service-worker.js")
      defaultResource("index.html")
    }
```
but I'm wondering if there is something that match both of them.
BTW. is there any way to add all files from staticBasePackage to the resources ? `resources("*")`doesn't work

**Comment by userquin** [comment]
@stasbar try this:

```java
routing {
    route("/api") {
      get("/foo") {
        ...
      }
      get("/bar") {
        ...
      }
    }
    static("/") {
      staticBasePackage = "assets"
      resources("static")
      resource("favicon.ico")
      resource("index.html")
      resource("manifest.json")
      resource("asset-manifest.json")
      resource("service-worker.js")
      defaultResource("index.html")
    }
  }
```

**Comment by stasbar** [comment]
I just found cleaner way of doing that.
```kotlin
fun Application.module() {
  routing {
    static("") {
      webapp()
    }
    static("*") {
      webapp()
    }
  }
}

private fun Route.webapp() {
  resources("assets")
  staticBasePackage = "assets"
  resources("static")
  defaultResource("index.html")
}
```
So eventually I ended with the result I wanted to achieve. But still, it would be great to merge "" and "*" together

**Comment by wiwiwa** [comment]
+1

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-696">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
You can use a [tail card](https://ktor.io/docs/routing-in-ktor.html#tailcard) matcher to solve your problem:
```kt
static("{...}") {
    // ...
}
```
