### ISSUE TITLE
Can't set FormUrlEncoded header for ktor http client request

### ISSUE THREAD

**Issue by wilyarti** [ktorio/ktor#882]
### Ktor Version 
1.1.1

### Ktor Engine Used(client or server and name) 
Apache

### JVM Version, Operating System and Relevant Context 
Ubuntu 18.04
Information:Kotlin: kotlinc-jvm 1.3.11 (JRE 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)

### Feedback
I am trying to POST a request to an API that uses Content-Type: application/x-www-form-urlencoded.

```
val message = client.post<Unit> {
    url(URL("https://tapi.telstra.com/v2/oauth/token"))
    contentType(ContentType.Application.FormUrlEncoded)
    body = getAuth(client_id = "overriddenkey", client_secret = "overridenpass")
}
```
I get the error: io.ktor.http.UnsafeHeaderException: Header Content-Type is controlled by the engine and cannot be set explicitly

I can't figure out how to set the headers in the client constructor. The documentation [https://ktor.io/clients/http-client/calls/requests.html](url) specifies that custom headers can be set using HttpRequestBuilder.

How do I specify the contentType and set the header data? I could not figure it out from your documentation.

**Comment by tasmalinakis** [comment]
Hi, we bumped into this problem a while ago as well. Going through the code, I believe that the current way of doing this is by using `FormDataContent` like so (without specifying a contentType):

` body = FormDataContent(parametersOf(
       "client_id" to "overriddenkey", 
       "client_secret" to "overridenpass") )
`

Last time I checked this was not stated somewhere in the documentation though.

**Comment by wilyarti** [comment]
Thanks that seems to work. Although I still need to also be able to set the body of the message with JSON to communicate with the API.

But at least I am 50% there now.

**Comment by FrancoSabadini** [comment]
I'm having this same issue, I need to add the header and the body, but seems like it's not possible to add both, which makes the API call fail. Has anyone found a workaround for this?

**Comment by semyannikov** [comment]
@e5l I will start changing documentation in few days, any comments related to PR are welcome.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-695">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by woniupapa** [comment]
Anyone fixed this problem? help, the same problem.

**Comment by wilyarti** [comment]
> Anyone fixed this problem? help, the same problem.

I haven't looked at this issues in a long time. What I did at the time was use a different http client.

**Comment by woniupapa** [comment]
![1591606717481_ pic](https://user-images.githubusercontent.com/2526267/100575794-d2de9900-3317-11eb-9dd9-a9087dc5b78a.jpg)
![1601606717561_ pic](https://user-images.githubusercontent.com/2526267/100575944-1507da80-3318-11eb-99cd-2f9d168f1428.jpg)
![1611606717644_ pic](https://user-images.githubusercontent.com/2526267/100575999-2c46c800-3318-11eb-99e4-720df20d6f6e.jpg)
![1621606718988_ pic](https://user-images.githubusercontent.com/2526267/100577486-4cc45180-331b-11eb-97b4-b2c10bea7633.jpg)
Please help me!,There are many pictures.

**Comment by woniupapa** [comment]
@wilyarti  I don't know how to post with formdata content.

**Comment by woniupapa** [comment]
@wilyarti Dear Wilyarti, I removed  //contentType(ContentType.Application.Json) code,It work!!!

**Comment by Stexxe** [comment]
@wilyarti as a workaround you can override a `contentType` property of the `OutgoingContent` class. Here is an example:
```kt
val message = client.post<String> {
    url(URL("https://httpbin.org/post"))
    body = object : OutgoingContent.ByteArrayContent() {
        override val contentType = ContentType.Application.FormUrlEncoded
        override fun bytes(): ByteArray {
            return """{"x": 123}""".toByteArray(Charsets.UTF_8)
        }
    }
}
```

**Comment by EhsanMsz** [comment]
I'm currently working on this.
to override `contentType`, it must be removed from `UnsafeHeadersArray` in `HttpHeaders.kt`.
Is it ok to remove this from `UnsafeHeadersArray`?
