### ISSUE TITLE
Can't receive form data

### ISSUE THREAD

**Issue by carterhudson** [ktorio/ktor#891]
When trying to receive form data (like so https://ktor.io/samples/feature/post.html) I get an error saying `Content type multipart/form-data is not supported`. Does this mean I need to install custom `ContentNegotiation` for it? Is this not something we get out of the box? None of the examples I can find that receive form data seem to do this. Also, `application/x-www-form-urlencoded` isn't supported either?

**Comment by cy6erGn0m** [comment]
Looks like `ContentNegotiation` interferes with the default receive interceptor that provides support for multipart

**Comment by cy6erGn0m** [comment]
Receiving request is only possible once. Unfortunately it is not prohibited so extra attempts may fail or may return some empty value. We need to make it fail in any case similar to double attempt to respond a call.

**Comment by cy6erGn0m** [comment]
Diagnostics improved in 1.2.3 and introduced `DoubleReceive` feature
