### ISSUE TITLE
Invalid session cookie handling when creating 100-year cookies

### ISSUE THREAD

**Issue by vonox7** [ktorio/ktor#892]
Ktor 1.1.1 reverts fixes that are made in https://github.com/ktorio/ktor/pull/686:

If you crate a cookie with `cookie.duration = Duration.ofDays((100 * 365).toLong())` a cookie without a duration (session-cookie) is created. Apparently the commit https://github.com/ktorio/ktor/commit/17bb8fb17947f62621c67801cc51ef0e7210bb49 which fixed another issue broke that case

I see here 2 ways to fix it:
a) throw if `maxAge > Int.MAX_VALUE` (so at least the error would be found immediately and not after several days of debugging)
b) move the `?.takeIf { it <= Int.MAX_VALUE }` from line 31 to line 38, so line 38 would be `maxAge?.takeIf { it <= Int.MAX_VALUE }?.toInt() ?: 0,`

**Comment by cy6erGn0m** [comment]
Other possible options would be: 
- bump `maxAge` to `Int.MAX_VALUE` since usually people simply want very very long duration and it doesn't matter what exact value it will be (for now I'll prefer it as a quick fix)
- replace `Int` with `Long` to support larger values
