### ISSUE TITLE
Session cookie with very long max age duration

### ISSUE THREAD

**Issue by cy6erGn0m** [ktorio/ktor#893]
When configuring a very very long session duration it may cause integer overflow. It need to be decided what should be done in this case:

- fail at attempt to set `duration`
- bump `max-age` to `Int.MAX_VALUE` or `Long.MAX_VALUE` (long type requires changes, probably breaking changes)

This is related to #892.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-692">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed. Will be released in 1.5.2
