### ISSUE TITLE
Kotlin/Native iOS test freezes on get request with error: NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9807)

### ISSUE THREAD

**Issue by icarumbas** [ktorio/ktor#895]
Hey!

I'm using ktor in my multiplatform application. I have problem with testing ktor client get request to any page. It totally freezes. Other tests work. (Same test on Android works well)

My test looks like this:
```
@Test
fun downloadPageContent() {
    runBlocking(Dispatchers.Unconfined) {
        HttpClient().use {
            it.get<String>("https://stackowerflow.com")
        }
    }
}
```

My run ios test gradle script:
```
task iosTest {
    description = "Runs tests for target 'ios' on an iOS simulator"

    def device = project.findProperty("iosDevice")?.toString() ?: "iPhone 8"
    dependsOn 'linkTestDebugExecutableIos'
    group = JavaBasePlugin.VERIFICATION_GROUP

    doLast {
        def binary = kotlin.targets.ios.compilations.test.getBinary('EXECUTABLE', 'DEBUG')
        exec {
            commandLine 'xcrun', 'simctl', 'spawn', device, binary.absolutePath
        }
    }
}
```

Versions:
```
ktor_version = '1.1.1'
coroutines_version = '1.1.0'
kotlin_version = '1.3.11'
```

PS:
If i change url to random characters error no longer prints, but it still freezes.

**Comment by mikezliu** [comment]
It is because of a deadlock. On Android I think you can workaround by using a different client like CIO. On iOS I don't think you have a choice, so you could define an interface that uses swift/objc code to make the network call then return the string.

**Comment by icarumbas** [comment]
@mikezliu what do you mean? I don't want to use objc code to load something... I use ktor for http requests and i want to test it. As i mentioned same code works if i run main app from XCode 

> On iOS, you could try defining an interface that uses swift/objc code to make the network call then return the string.

**Comment by e5l** [comment]
Hi @icarumbas, thanks for the report.
Could you try to run it with `launch` instead of `runBlocking`?

**Comment by icarumbas** [comment]
@e5l 
I can't just use `launch` in tests. They will just pass then. 

I've also got that:
1) this error also appears in simple `runBlocking` without passing any Dispatcher. 
2) it works the same from iosMain module

**Comment by and-marsh** [comment]
Hello! I have the same problem. Any progress on it?

**Comment by e5l** [comment]
blocked by https://github.com/Kotlin/kotlinx.coroutines/issues/770

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-691">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by docee** [comment]
It is a deadlock problem.
See this [KTOR-2683](https://youtrack.jetbrains.com/issue/KTOR-2683)

**Comment by Stexxe** [comment]
Fixed by [KTOR-2683](https://youtrack.jetbrains.com/issue/KTOR-2683).
