### ISSUE TITLE
Installing Logging on CIO HttpClient with WebSockets blocks incoming messages from being received.

### ISSUE THREAD

**Issue by luca992** [ktorio/ktor#899]
### Ktor Version
1.1.1
### Ktor Engine Used(client or server and name)
CIO engine client
### JVM Version, Operating System and Relevant Context
Jvm 1.8, macOs, Kotlin 1.3.20
### Feedback

    val client = HttpClient(CIO).config {
        install(Logging) {
            level = LogLevel.ALL
        }
        install(WebSockets)
    }

When connecting to a websocket with the above client (with Logging installed). I am unable to recieve messages from the websocket. I think the logger either consumes them or blocks them? Sending messages to the websocket works. I had to remove Logging to be able to recieve messages

**Comment by e5l** [comment]
Hi @luca992, thanks for the report. 
It looks like logging and WebSocket features are in conflict.
