### ISSUE TITLE
flexible OkHttp configuration

### ISSUE THREAD

**Issue by Jesus13** [ktorio/ktor#903]
I looked for a method to set my OkHttp instance and i didn’t find it.
Why do you hard code builder into OkHttpEngine? It isn’t flexible
I have a base OkHttp configuration and a few additional ones which extends base.
For example:
```kotlin
fun createBaseOkHttp() = 
 OkHttpClient.Builder().apply {
        readTimeout(TIMEOUT_IN_SECONDS, TimeUnit.SECONDS)
        connectTimeout(TIMEOUT_IN_SECONDS, TimeUnit.SECONDS)
        addLoggingInterceptor()
  }

fun createPublicOkHttp() = 
     createBaseOkHttp().apply {
         addPublicInterceptor()
      }

fun createPrivateOkHttp() = 
     createBaseOkHttp().apply {
         addPrivateInterceptor()
 }
```

How should I do it with ktor?
The same applies to other elements for example gson

**Comment by e5l** [comment]
Hi @Jesus13, thanks for the report.
Probably we should support that feature.

You could use ktor `OkHttpConfig` for now.
