### ISSUE TITLE
HttpStatusCode should not check description for equals()

### ISSUE THREAD

**Issue by codyoss** [ktorio/ktor#905]
### Ktor Version
Current 1.1.1 (and all?)
### Ktor Engine Used(client or server and name)
All
### JVM Version, Operating System and Relevant Context
All
### Feedback
`HttpStatusCode`  should be a normal class with only `value` used for `equals()` and `hashCode()`. The reason I think this as a user I feel it is idiomatic to do a `when` switch on `HttpResponse.status`. When I do this I would expect I can compare my status to one of the companion objects like `HttpStatusCode.OK`

**Comment by codyoss** [comment]
If this issue is accepted it can be assigned to me. Would love to contribute to the project!

**Comment by e5l** [comment]
Complete in `master`
