### ISSUE TITLE
Start ktor server on random port

### ISSUE THREAD

**Issue by adhesivee** [ktorio/ktor#909]
### Ktor Version
1.1.2

### Ktor Engine Used(client or server and name)
Netty server

### JVM Version, Operating System and Relevant Context
JDK 11

### Feedback
Being able to get the local port when starting ktor on a random port:
```
embeddedServer(Netty, port = 0)
```
The information is available in case of netty on [channel](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt#L77), but I can not get this information of `NettyApplicationEngine` itself

**Comment by pilotclass** [comment]
This is particularly useful when running ktor in an integration test - being able to use a random port and then hit that from your tests removes any potential port clashes that would otherwise cause a test failure.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-686">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by e5l** [comment]
Fixed in `2.0.0`

**Comment by MEJIOMAH17** [comment]
@e5l how to use it?

**Comment by andreyaksenov** [comment]
> @e5l how to obtain real port after creation server?

@MEJIOMAH17 For a server running using `embeddedServer`, you can get a  port using the [ApplicationEngine.resolvedConnectors](https://ktor.io/docs/eap/configurations.html#embedded-basic) function.

**Comment by Stexxe** [comment]
Before 2.0.0:
```
val port = (server.application.environment as ApplicationEngineEnvironment).connectors.first().port
println(port)
```
In 2.0.0:
```
val port = runBlocking { server.resolvedConnectors().first().port }
println(port)
```
