### ISSUE TITLE
Debug variable has value always false 

### ISSUE THREAD

**Issue by wildmouse** [ktorio/ktor#911]
### Ktor Version
1.1.2

I've found redundant `debug` variable which value is always `false`.
Is this variable still used in development? 

https://github.com/ktorio/ktor/blob/40da754769ab44455134de745782a54e470e41e5/ktor-server/ktor-server-test-host/jvm/src/io/ktor/server/testing/HighLoadHttpGenerator.kt#L660-L677

**Comment by wild-mouse** [comment]
Actually I don't.
I read and analyzed project codes with IDE and found this so I opened this issue.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-685">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
