### ISSUE TITLE
Extend MockEngine

### ISSUE THREAD

**Issue by sevichAk** [ktorio/ktor#913]
Hi! 

I stumbled upon a problem when writing client tests in Ktor. There is MockEngine which you pass to a HttpClient so you can mock http responses. The documentation uses matching on a url when http call is processed. But what if I want to give different responses to the same url called? Like requesting authorisation token with a different expiration date. So I can give responses based on order, in which they were added to a MockEngine. 

So I was thinking about how MockWebServer works and came up with some MockEngine implementation, where one can just enqueue MockResponses to a MockEngine and they will be given back in the order they are added. I also keep requests that are passed to MockEngine, so I can check what is actually packed into the request. 

Then I can define one MockEngine instance for client test and just reset it before every test:
```kotlin
val mockEngine = MockEngineExtended(HttpClientEngineConfig())

fun test() {
    mockEngine.enqueueResponses(
        respondOkFile("first.json"),
        respondOkFile("second.json")
    )

    val responseOne = service.fireRequest()
    val responseTwo = service.fireRequest()
    // assertions
}

fun reset() {
  mockEngine.reset()
}
```

Here is the implementation

```kotlin
class MockEngineExtended(
    override val config: HttpClientEngineConfig
) : HttpClientEngine {

    private var invocationCount = 0

    private val responses: MutableMap<Int, HttpClientCall.() -> MockHttpResponse> = mutableMapOf()

    private val processedRequests: MutableList<MockHttpRequest> = mutableListOf()

    fun enqueueResponses(vararg mockResponses: HttpClientCall.() -> MockHttpResponse) {
        mockResponses.forEachIndexed { index, function ->
            responses[index] = function
        }
    }

    fun reset() {
        responses.clear()
        processedRequests.clear()
    }

    fun takeRequest(order: Int = processedRequests.size - 1) = processedRequests[order]

    override val dispatcher: CoroutineDispatcher = Dispatchers.Unconfined

    override val coroutineContext: CoroutineContext = dispatcher + CompletableDeferred<Unit>()

    override suspend fun execute(call: HttpClientCall, data: HttpRequestData): HttpEngineCall {
        val request = data.toRequest(call)
        if (invocationCount == responses.size) {
            error("Unhandled ${request.url} on invocationCount=$invocationCount")
        } else {
            processedRequests.add(request)
            val response = responses[invocationCount++]!!.invoke(call)
            return HttpEngineCall(request, response)
        }
    }

    override fun close() {}

    companion object : HttpClientEngineFactory<HttpClientEngineConfig> {
        override fun create(block: HttpClientEngineConfig.() -> Unit): HttpClientEngine =
            MockEngineExtended(
                HttpClientEngineConfig().apply(
                    block
                )
            )
    }
}
```

Helper functions to create responses:
```kotlin
fun respondOkJsonFromFile(filePath: String): HttpClientCall.() -> MockHttpResponse = { this.respondOkJsonFromFile(filePath) }

fun HttpClientCall.respondOkJsonFromFile(filePath: String) = MockHttpResponse(
    this,
    HttpStatusCode.OK,
    getResourceFileAsByteReadChannel(filePath),
    contentJson()
)
```

Is there anything wrong with the implementation? Did I miss anything? If this approach is a way to go is it possible to have it in added to Ktor?

Thanks!

**Comment by e5l** [comment]
Hi @sevichAk. Awesome job ;)

Could you create the PR to `MockEngine`?
Also would be nice to have basic tests.

**Comment by e5l** [comment]
Merged.

**Comment by nicola-farina** [comment]
I am also interested in having the method `reset()` which clears response and request histories on the current `MockEngine` implementation, in order to reuse the client in multiple tests. I cannot find a way to do it myself since those two histories are exposed as List, not MutableList. Any chance this could be added?

**Comment by ts-hans-wage** [comment]
Sorry for replying to this old issue, but since this is the first result in Google and hard to find, yes this still exists Ktor as addHandler. Multiple calls can be chained as follows:
```kotlin
val mockEngine = MockEngine.config {
  addHandler {
    respond(
      content = ByteReadChannel(jsonStringA),
      status = HttpStatusCode.OK
    )
  }
  addHandler {
    respond(
      content = ByteReadChannel(jsonStringB),
      status = HttpStatusCode.OK
    )
  }
}

val httpClient = HttpClient(mockEngine)
```

**Comment by Osthekake** [comment]
reset() function would be very useful

**Comment by polarene** [comment]
A brute force method for resetting the history can be this one, I've employed it in one of my tests:
```
// using Kotest
afterEach {
    (mockEngine.requestHistory as MutableList).clear()
}
