### ISSUE TITLE
ktor with with mustache 415 Unsupported Media Type: POST

### ISSUE THREAD

**Issue by kldMohammed** [ktorio/ktor#925]
### Ktor Version
1.1.2
### Ktor Engine Used(client or server and name)
netty
### JVM Version, Operating System and Relevant Context
java version 10.0.2
mac os
### Feedback

i built a small app to test mustache with ktor but when i try to post data using html form in mustache file .hbs file 
the post gave me an 

> 415 Unsupported Media Type: POST
when i try to recieve a typed json 
` val param = call.receive<Quote>()`

and also give me a null value when i try 
`  val param = call.receive<Parameters>()
        val author = param["author"]!!
        val qouteText = param["quoteText"]!!`

and this is my html form 

> 
![screen shot 2019-02-02 at 8 49 10 pm](https://user-images.githubusercontent.com/17613367/52167952-1ff98000-272c-11e9-92c4-9e6afb00f673.png)

` <form role="form" class="col-xs-3 text-center" style="width: 30%" action="/quotes"
              method="post" >
            <div class="form-group">
                <label for="titleInput">Author</label>
                <input type="text" class="form-control" id="author" required="required">
            </div>

            <div class="form-group">
                <label for="quote">Quote</label>
                <br>
                <textarea class="form-control" id="quote" rows="3" required="required"></textarea>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary mb-2 text-center">Confirm</button>
            </div>

        </form>`

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-679">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by misakamaiyako** [comment]
by default, ktro server accept  post request with `Content-Type: application/json;charset=UTF-8` header,  but form submit's header is `application/x-www-form-urlencoded` and server won't receive it.
you can use axios instead of form submit to upload your data.

**Comment by kldMohammed** [comment]
Its older version of ktor so , i should close this

**Comment by Harin-Kaklotar** [comment]
Actually, this happens when we forgot to install ContentNegotiation with JSON. 
Don't forget to add a dependency and plugin for serialization and request with the header "Content-Type": "application/json"

**Comment by thegeniusprogrammer** [comment]
Add Header "Content-Type": "application/json" while sending request in postman, 
and don't forget to add ContentNegotiation plugin in your ktor project.
