### ISSUE TITLE
Jackson 2.9.2 bug on POJO that has exactly one property

### ISSUE THREAD

**Issue by abangkis** [ktorio/ktor#928]
### Ktor Version
1.1.2

### Ktor Engine Used(client or server and name)
Server

### JVM Version, Operating System and Relevant Context
Jackson

### Feedback
There's a bug in jackson 2.9.2 when serializing/deserializing on POJO that has exactly one property. This only happens if you use custom property naming strategy. Here's the [ticket](https://github.com/FasterXML/jackson-databind/issues/1832). I think it has been fixed in jackson 2.9.6

**Comment by cy6erGn0m** [comment]
Fixed in 1.1.3.
