### ISSUE TITLE
CORS is rejecting some standard headers

### ISSUE THREAD

**Issue by fluidsonic** [ktorio/ktor#939]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) and [W3](https://www.w3.org/TR/cors/#simple-header) the two headers `Accept` and `Accept-Language` are *simple headers* and allowed by default or CORS requests, so they don't need be specified in `Access-Control-Request-Headers`.

Unfortunately Internet Explorer 11 specifies `Accept` anyway and because Ktor doesn't list them as default headers CORS requests from IE 11 get rejected by `403 Forbidden`:

https://github.com/ktorio/ktor/blob/cf7d8e43c80a4adfe3363a0191cc5df9afb78bdc/ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt#L225-L234

`Access-Control-Request-Headers` is checked in the following code and `.CorsDefaultHeaders` being used through `.allHeadersSet`/`.allHeaders`:

https://github.com/ktorio/ktor/blob/cf7d8e43c80a4adfe3363a0191cc5df9afb78bdc/ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt#L153-L157

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-673">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by cy6erGn0m** [comment]
This is already fixed in 1.2.3 , revision 8833146454be7e9314f5c96298134a357af90f4c
