### ISSUE TITLE
ktor-client-curl on osx fails with "ld invocation reported errors"

### ISSUE THREAD

**Issue by SimonSchubert** [ktorio/ktor#943]
### Ktor Version
1.1.2
### Ktor Engine Used(client or server and name)
client curl
### JVM Version, Operating System and Relevant Context
java version "1.8.0_191", macOS 10.14.3 

Dependency:
implementation("io.ktor:ktor-client-curl:1.1.2")

Error:
```
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_curl_multi_wait", referenced from:
      _libcurl_kniBridge38 in combined.o
  "_iconv", referenced from:
      _platform_iconv_kniBridge1 in combined.o
  "_iconv_close", referenced from:
      _platform_iconv_kniBridge2 in combined.o
  "_iconv_open", referenced from:
      _platform_iconv_kniBridge0 in combined.o
ld: symbol(s) not found for architecture x86_64
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors
```

The documentation(https://ktor.io/clients/http-client/engines.html) states that we can use curl engine for macos_64. It also says "..you must have the installed curl library at least version 7.63". So I checked my installed curl version which is below 7.63. Next I installed the newest version via brew which is 7.64. But the same error still appeared. I tried to dig deeper into it and found in the "ktor-client-curl-cinterop-libcurl.klib" manifest file on line 6:
`compilerOpts.osx=-I/opt/local/include -I/usr/local/include -I/usr/include -I/usr/local/Cellar/curl/7.62.0/include -I/usr/local/Cellar/curl/7.63.0/include` there is a mention about curl version 7.62 and 7.63 but not the one I just installed. So I downgraded the version to 7.63. 

I also executed the following commands:
```
 If you need to have curl first in your PATH run:
  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile

For compilers to find curl you may need to set:
  export LDFLAGS="-L/usr/local/opt/curl/lib"
  export CPPFLAGS="-I/usr/local/opt/curl/include"

For pkg-config to find curl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
```

But nothing changed, I always got the same error. Does the error even has to do with curl itself? I'm lost and appreciate any help.

**Comment by e5l** [comment]
Hi @SimonSchubert, thanks for the report.
Probably you should add  ```-L/usr/local/opt/curl/lib -I/usr/local/opt/curl/include``` to kotlin-native `compilerOpts`. It looks like kotlin-native compiler skip env `CPPFLAGS` and `LDFLAGS`.

**Comment by SimonSchubert** [comment]
I couldn't find much information on how to define the compilerOpts for kotlin-native in Clion. Is this the correct place to define it? Both locations "/usr/local/opt/curl/lib" and "/usr/local/opt/curl/include" exist on my system. But I still get the same error.

<img width="1096" alt="screenshot" src="https://user-images.githubusercontent.com/1833337/52803179-cecd8280-3081-11e9-8d8d-51ab6a4fe6b3.png">

**Comment by ilmat192** [comment]
You need to specify the linker options for all binaries you have (including the test one):

```kotlin
kotlin {
    // Change the target if you need.
    // Or you can configure all targets just by replacing it with `targets.all`
    iosX64 {
        binaries.all {
            // If you are using the Kotlin DSL:
            linkerOpts += listOf("-L/usr/local/opt/curl/lib", "-lcurl")

            // If you are using the Groovy DSL:
            linkerOpts += ["-L/usr/local/opt/curl/lib", "-lcurl"]
        }
    }
}
```

See also about configuring binaries: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#configuring-binaries.

**Comment by SimonSchubert** [comment]
Thank you both for helping. Unfortunately I still couldn't get it working. Maybe I'm doing something else wrong? If someone has time please have a look ino it. Here is the source code of the project:
https://github.com/SimonSchubert/Restkid

**Comment by SimonSchubert** [comment]
I ended up with this linkedOpts settings:
```
macosX64 {
    binaries.all {
        linkerOpts = mutableListOf("-L/usr/local/opt/curl/lib", "-I/usr/local/opt/curl/include", "-lcurl")
    }
}
```
But still getting the same error.

**Comment by e5l** [comment]
Could you verify that actual curl installation located in `/usr/local/opt/curl/`? 
If it's yes, could you provide the full build log?

**Comment by SimonSchubert** [comment]
Curl is installed:
`Simons-MacBook-Pro:bin simon$ cd /usr/local/opt/curl/
Simons-MacBook-Pro:curl simon$ ls -l
total 464
-rw-r--r--  1 simon  staff  222202 Feb 12 02:20 CHANGES
-rw-r--r--  1 simon  staff    1088 Feb  6 07:58 COPYING
-rw-r--r--  1 simon  staff     624 Feb 12 02:20 INSTALL_RECEIPT.json
-rw-r--r--  1 simon  staff    1610 Feb  6 07:58 README
drwxr-xr-x  4 simon  staff     128 Feb 12 02:20 bin
drwxr-xr-x  3 simon  staff      96 Feb  6 07:58 include
drwxr-xr-x  6 simon  staff     192 Feb  6 07:58 lib
drwxr-xr-x  3 simon  staff      96 Feb  6 07:58 libexec
drwxr-xr-x  5 simon  staff     160 Feb  6 07:58 share
Simons-MacBook-Pro:curl simon$ cd bin
Simons-MacBook-Pro:bin simon$ ls -l
total 424
-r-xr-xr-x  1 simon  staff  207644 Feb 12 02:20 curl
-r-xr-xr-x  1 simon  staff    5577 Feb 12 02:20 curl-config`

I will give it another try with kotlin 1.3.30 on the weekend and I will report.

**Comment by SimonSchubert** [comment]
I updated to kotlin 1.31.0 and ktor 1.1.5 but I still couldn't get it working.

Here is the build info:

19:40:07: Executing task 'build --info'...

The client will now receive all logging from the daemon (pid: 30148). The daemon log file: /Users/simon/.gradle/daemon/5.4.1/daemon-30148.out.log
Starting 20th build in daemon [uptime: 30 mins 20.697 secs, performance: 100%, GC rate: 0.00/s, heap usage: 7% of 358.1 MB, non-heap usage: 40% of 268.4 MB]
Using 4 worker leases.
Starting Build
Settings evaluated using settings file '/Users/simon/projects/Restkid/settings.gradle.kts'.
Projects loaded. Root project using build file '/Users/simon/projects/Restkid/build.gradle.kts'.
Included projects: [root project 'Restkid']

> Configure project :
Evaluating root project 'Restkid' using build file '/Users/simon/projects/Restkid/build.gradle.kts'.
Kotlin Multiplatform Projects are an experimental feature.
Kotlin/Native distribution: /Users/simon/.konan/kotlin-native-macos-1.2.1
Kotlin/Native distribution: /Users/simon/.konan/kotlin-native-macos-1.2.1
file or directory '/Users/simon/projects/Restkid/src/commonMain/kotlin', not found
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':compileKotlinLibui', task ':compileKotlinMacosX64', task ':linkDebugExecutableLibui', task ':linkReleaseExecutableLibui', task ':libuiProcessResources', task ':libuiMainKlibrary', task ':linkTestDebugExecutableLibui', task ':macosX64ProcessResources', task ':macosX64MainKlibrary', task ':linkTestDebugExecutableMacosX64', task ':compileKotlinMetadata', task ':metadataMainClasses', task ':metadataJar', task ':assemble', task ':libuiTest', task ':macosX64Test', task ':check', task ':build']
:compileKotlinLibui (Thread[Execution worker for ':',5,main]) started.

> Task :compileKotlinLibui UP-TO-DATE
Caching disabled for task ':compileKotlinLibui' because:
  Build cache is disabled
Skipping task ':compileKotlinLibui' as it is up-to-date.
:compileKotlinLibui (Thread[Execution worker for ':',5,main]) completed. Took 0.144 secs.
:compileKotlinMacosX64 (Thread[Execution worker for ':',5,main]) started.

> Task :compileKotlinMacosX64
file or directory '/Users/simon/projects/Restkid/src/macosX64Main/kotlin', not found
file or directory '/Users/simon/projects/Restkid/src/commonMain/kotlin', not found
Cleaned previous output of task ':compileKotlinMacosX64' as it has no source files.
:compileKotlinMacosX64 (Thread[Execution worker for ':',5,main]) completed. Took 0.009 secs.
:linkDebugExecutableLibui (Thread[Execution worker for ':',5,main]) started.

> Task :linkDebugExecutableLibui
Caching disabled for task ':linkDebugExecutableLibui' because:
  Build cache is disabled
Task ':linkDebugExecutableLibui' is not up-to-date because:
  Task has failed previously.
file or directory '/Users/simon/projects/Restkid/src/commonMain/kotlin', not found
file or directory '/Users/simon/projects/Restkid/src/commonMain/kotlin', not found
Run tool: konanc with args: -g -ea -target macos_x64 -p program -o /Users/simon/projects/Restkid/build/bin/libui/debugExecutable/Restkid.kexe -l /Users/simon/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-client-curl-macosx64/1.1.5/4cfcc96fd2f340b60e2b9d1bcdf16dccd8e0cbcd/ktor-client-curl.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-client-curl-macosx64/1.1.5/7ce13c45eea0b4abdceff664a7552a9257c511a/ktor-client-curl-cinterop-libcurl.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/com.github.msink/libui-macosx/0.1.3/6a7d74060256db7c72d39de1cc84cd41410bbd75/libui.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/com.github.msink/libui-macosx/0.1.3/54e477ff022346f47072bffd65ad9155caf89e92/libui-cinterop-libui.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-serialization-runtime-native_debug_macos_x64/0.11.0/7f51b92a28bf690f372d2f90746a07394dd893e8/kotlinx-serialization-runtime-native.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-client-core-macosx64/1.1.5/e17473c6203a72167b8e41b022a98905bb25a27b/ktor-client-core.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-http-cio-macosx64/1.1.5/278ec999d6ade95d88854ffd3fe12ccfa7abd2c9/ktor-http-cio.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-http-macosx64/1.1.5/3efa0cc21df46ff9be931dd94a790ea529c32ad9/ktor-http.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-utils-macosx64/1.1.5/92002c396610dccc75b552a1c419d2c340437838/ktor-utils.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-utils-macosx64/1.1.5/52340e46aa2f552d0ddc596451d7a8594545f4d6/ktor-utils-cinterop-utils.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-io-macosx64/0.1.8/f9d3317583b32582c4826df50ee74dd717fff3d5/kotlinx-coroutines-io.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-macosx64/1.2.0/6dfa600801039f3f1621a8c3dd7e3ba0551f9783/kotlinx-coroutines-core.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-io-macosx64/0.1.8/4d5bb1fe95379d601e12ea45b70a36c02f73758/kotlinx-io.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-io-macosx64/0.1.8/d764ce8ce2279b58be71031fecae619ba73ddf64/kotlinx-io-cinterop-sockets.klib -l /Users/simon/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-macos64/0.12.3/4ea4e6296c16553b484de67d4ca09ac8c1ddf227/atomicfu.klib -Xmulti-platform -Xplugin=/Users/simon/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-serialization-unshaded/1.3.31/87712349a24c6399739710bd7bd1214387c24424/kotlin-serialization-unshaded-1.3.31.jar /Users/simon/projects/Restkid/src/libuiMain/kotlin/App.kt
Starting process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java''. Working directory: /Users/simon/projects/Restkid Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java -DCVS_PASSFILE=~/.cvspass -D__idea.mac.env.lock=unlocked -Dapple.laf.useScreenMenuBar=true -Dawt.toolkit=sun.lwawt.macosx.LWCToolkit -Dcom.apple.mrj.application.live-resize=false -Dcom.jetbrains.suppressWindowRaise=false -Dfile.encoding.pkg=sun.io -Dfile.separator=/ -DgopherProxySet=false -Dide.mac.useNativeClipboard=false -Didea.active=true -Didea.cycle.buffer.size=1024 -Didea.dynamic.classpath=false -Didea.executable=clion -Didea.fatal.error.notification=disabled -Didea.home.path=/Applications/CLion.app/Contents -Didea.jars.nocopy=true -Didea.max.content.load.filesize=20000 -Didea.max.intellisense.filesize=2500 -Didea.no.launcher=false -Didea.paths.selector=CLion2019.1 -Didea.platform.prefix=CLion -Didea.popup.weight=heavy -Didea.registered=false -Didea.smooth.progress=false -Didea.version=2019.1.2 -Dio.netty.machineId=28:f0:76:ff:fe:16:65:0e -Dio.netty.processId=20107 -Dio.netty.serviceThreadPrefix=Netty  -Djava.awt.graphicsenv=sun.awt.CGraphicsEnvironment -Djava.awt.printerjob=sun.lwawt.macosx.CPrinterJob -Djava.class.path=/Users/simon/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib/gradle-launcher-5.4.1.jar -Djava.class.version=52.0 -Djava.ext.dirs=/Users/simon/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java -Djava.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre -Djava.library.path=/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/nativelib -Djava.net.preferIPv4Stack=true -Djava.rmi.server.disableHttp=true -Djava.rmi.server.hostname=127.0.0.1 -Djava.runtime.name=OpenJDK Runtime Environment -Djava.runtime.version=1.8.0_191-b12 -Djava.specification.name=Java Platform API Specification -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=1.8 -Djava.util.Arrays.useLegacyMergeSort=true -Djava.util.concurrent.ForkJoinPool.common.threadFactory=com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory -Djava.vendor=Oracle Corporation -Djava.vendor.url=http://java.oracle.com/ -Djava.vendor.url.bug=https://youtrack.jetbrains.com -Djava.version=1.8.0_191 -Djava.vm.info=mixed mode -Djava.vm.name=Java HotSpot(TM) 64-Bit Server VM -Djava.vm.specification.name=Java Virtual Machine Specification -Djava.vm.specification.vendor=Oracle Corporation -Djava.vm.specification.version=1.8 -Djava.vm.vendor=Oracle Corporation -Djava.vm.version=25.191-b12 -Djavax.swing.rebaseCssSizeMap=true -Djb.vmOptionsFile=/Applications/CLion.app/Contents/bin/clion.vmoptions -Djbre.popupwindow.settype=true -Djdk.http.auth.tunneling.disabledSchemes="" -Djna.encoding=UTF8 -Djna.loaded=true -Djna.nosys=true -Djna.platform.library.path=/usr/lib:/usr/lib -Djna.tmpdir=/Users/simon/Library/Caches/CLion2019.1/tmp -Djnidispatch.path=/Users/simon/Library/Caches/CLion2019.1/tmp/jna5501054608600439690.tmp -Dkonan.home=/Users/simon/.konan/kotlin-native-macos-1.2.1 -Dkotlin.environment.keepalive=true -Dlibrary.jansi.path=/Users/simon/.gradle/native/jansi/1.17.1/osx -Dline.separator=
 -Dlog4j.defaultInitOverride=true -Dorg.jetbrains.kotlin.cliMessageRenderer=GradleStyle -Dos.arch=x86_64 -Dos.name=Mac OS X -Dos.version=10.14.4 -Dpath.separator=: -Dpty4j.preferred.native.folder=/Applications/CLion.app/Contents/lib/pty4j-native -Dpty4j.tmpdir=/Users/simon/Library/Caches/CLion2019.1/tmp -Drun.processes.with.pty=TRUE -Dsun.arch.data.model=64 -Dsun.boot.class.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/classes -Dsun.boot.library.path=/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib -Dsun.cpu.endian=little -Dsun.cpu.isalist -Dsun.io.unicode.encoding=UnicodeBig -Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.4.1 -Dsun.java.launcher=SUN_STANDARD -Dsun.jnu.encoding=UTF-8 -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Dsun.os.patch.level=unknown -Dswing.bufferPerWindow=true -Duser.dir=/Users/simon/projects/Restkid -Duser.home=/Users/simon -Duser.name=simon -Duser.timezone=Europe/Berlin -XX:TieredStopAtLevel=1 -Xmx3G -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/var/folders/mz/z0n0w5yx6691b8glbf3wvk880000gn/T/ -Duser.country=DE -Duser.language=en -Duser.variant -ea -cp /Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/kotlin-stdlib.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/klib.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/Runtime.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/protobuf-java-2.6.1.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/shared.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/kotlin-script-runtime.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/kotlin-compiler.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/kotlin-reflect.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/konan.metadata.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/utilities.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/backend.native.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/trove4j.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/StubGenerator.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/konan.serializer.jar:/Users/simon/.konan/kotlin-native-macos-1.2.1/konan/lib/Indexer.jar org.jetbrains.kotlin.cli.utilities.MainKt konanc @/var/folders/mz/z0n0w5yx6691b8glbf3wvk880000gn/T/konancArgs2219182979976064650.lst
Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java''
Undefined symbols for architecture x86_64:
  "_curl_multi_wait", referenced from:
      _libcurl_kniBridge34 in combined.o
  "_iconv", referenced from:
      _platform_iconv_kniBridge1 in combined.o
  "_iconv_close", referenced from:
      _platform_iconv_kniBridge2 in combined.o
  "_iconv_open", referenced from:
      _platform_iconv_kniBridge0 in combined.o
ld: symbol(s) not found for architecture x86_64
e: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld invocation reported errors

> Task :linkDebugExecutableLibui FAILED
:linkDebugExecutableLibui (Thread[Execution worker for ':',5,main]) completed. Took 59.563 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':linkDebugExecutableLibui'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s
3 actionable tasks: 2 executed, 1 up-to-date
Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
19:41:07: Task execution finished 'build --info'.

**Comment by SimonSchubert** [comment]
@e5l After reinstalling my macOS the problem is gone. Sorry for the false alarm and thanks for the help. 

I will close the issue.
