### ISSUE TITLE
Ktor Client JS Sends a request with method OPTIONS when a header is appended

### ISSUE THREAD

**Issue by andylamax** [ktorio/ktor#945]
```
val client = HttpClient()
            val jsons = client.request<String>("http://my-url") 
             headers {
                    append("Cache-Control", "no-cache")
                    append("Custom-Header", "custom-value")
             }
             method = HttpMethod.Get
 }
```

When I go to the network tab in Developers console, I see the
```
Request URL: http://my-url
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: ###.###.###.###:80
Referrer Policy: no-referrer-when-downgrade
```

is this a bug?

**Comment by andylamax** [comment]
I figured it's how the browser behaves when multiple headers are set. It first send a request with options method to validate if the custom headers are accepted by the servers then sends the actual get/post request to retrieve the required information. So, case closed

**Comment by JagadishaIncture** [comment]
How to avoid this from ktor?

**Comment by JagadishaIncture** [comment]
In my case I need to send multiple header for secuirty purpose how to avoid OPTIONS in this case?

**Comment by Stexxe** [comment]
The browser automatically sends the `OPTIONS` request, which is called a [preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#functional_overview).

**Comment by JagadishaIncture** [comment]
Looks like Preflight request is sent when we use header "Authorization" and it has to be handled explicitly from Backend servers. but is there any way to avoid from Browser end?

**Comment by Stexxe** [comment]
I don't think you can avoid that because it's a security mechanism built into modern web browsers.

**Comment by JagadishaIncture** [comment]
this link helped me

https://stackoverflow.com/a/42024918/10363408

**Comment by killin0415** [comment]
how to handle options requests, my api now give 405 neither 403 when an OPTIONS requests in sent to the server
