### ISSUE TITLE
How to bind server to localhost

### ISSUE THREAD

**Issue by fugithub** [ktorio/ktor#948]
### Ktor Version 
1.1.1

### Ktor Engine Used(client or server and name) 
Netty

### JVM Version, Operating System and Relevant Context 
1.8 Within Docker

### Feedback
How do I bind Ktor to a specific address, say localhost only?

**Comment by cy6erGn0m** [comment]
See https://ktor.io/servers/configuration

**Comment by cy6erGn0m** [comment]
What you need is `ktor.deployment.host` in HOCON config or `connector { host = ... }` to be set to `127.0.0.1`.

**Comment by fugithub** [comment]
Thanks, Sergey.

**Comment by e5l** [comment]
Answered
