### ISSUE TITLE
How do I handle exceptions with HttpClient?

### ISSUE THREAD

**Issue by andylamax** [ktorio/ktor#949]
I have written a common code in a common module as below and tested in JS environment 
```
val response = client.post<HttpResponse>(url) {
    body = TextContent("""{"a":1,"b":2}""", ContentType.Application.Json)
}
if (response.status != HttpStatusCode.OK) {
    logger.error("Error, this one failed bad?")
}

```
But my code ends at client.post with a canceled corutineException on no network. How do I handle this and any other exception? If there is an internet connection. Nothing fails, I want to be able to handle the exceptions. How?

**Comment by e5l** [comment]
Hi @andylamax, thanks for the report.
Could you try?
```kotlin
try {
    val response = client.post<HttpResponse>(url) {
         ...
    }
} catch (cause: Throwable) {
    println("Error: $cause")
}
```

Could you also provide the environment details?

**Comment by andylamax** [comment]
HI @e5l, thanks so much for your response. It works. 

instead of going for `catch(cause: Throwable)` I was going for `catch(e: Exception)` which apparently ddn't work. 

Question. Why is it Throwing a Throwable instead of a standard Exception? Is there a technical explanation?

**Comment by e5l** [comment]
If you catch `class Exception : kotlin.Throwable`, you miss `class Error : kotlin.Throwable`.
