### ISSUE TITLE
Memory leak by using of HttpClient(Apache)

### ISSUE THREAD

**Issue by eugeis** [ktorio/ktor#951]
### JVM Version, Operating System and Relevant Context: 
Java: jdk-11.0.2 Open JDK, Windows 10

### Feedback
How to reproduce:

1. Start the test http server Server.main()
2. Start a new process, the core main method  with -Xmx64M (or less)
After a bit more then 15 minutes, OutOfMemory

First log output:
14.02.2019 14:52:45.197+0100 INFO  [] [DevicePoller] [Memory] 
used: **7 MB**, committed: 30 MB, init: 64 MB, max: 64 MB

Last log output before OutOfMemory:
14.02.2019 15:07:45.374+0100 INFO  [] [DevicePoller] [Memory] 
used: **61 MB**, committed: 64 MB, init: 64 MB, max: 64 MB

See attached log file.

### Source Code
```
package mcr.dp

import io.ktor.application.call
import io.ktor.client.HttpClient
import io.ktor.client.call.call
import io.ktor.client.engine.apache.Apache
import io.ktor.client.response.readText
import io.ktor.http.HttpMethod
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.routing
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import org.slf4j.LoggerFactory
import java.lang.management.ManagementFactory
import kotlin.concurrent.fixedRateTimer


fun main() {
    val log = LoggerFactory.getLogger("DevicePoller")

    val poller = Poller()
    val devices = (1..50).map { "device$it" }

    fixedRateTimer(name = "DevicePoller", period = 1000) {
        for (device in devices) {
            GlobalScope.launch {
                val data = poller.poll(device)
                log.debug("$device: poll returns $data")
            }
        }
    }

    val memoryMXBean = ManagementFactory.getMemoryMXBean()
    fixedRateTimer(name = "Memory", period = 30000) {
        memoryMXBean.gc()
        log.info("used: {} MB, committed: {} MB, init: {} MB, max: {} MB",
                memoryMXBean.heapMemoryUsage.used.toMB(),
                memoryMXBean.heapMemoryUsage.committed.toMB(),
                memoryMXBean.heapMemoryUsage.init.toMB(),
                memoryMXBean.heapMemoryUsage.max.toMB())
    }

}

private fun Long.toMB(): Long = this / 1048576

class Poller(private val baseUrl: String = "http://localhost:8080",
             private val client: HttpClient = HttpClient(Apache)) {

    suspend fun poll(device: String): String {
        val urlString = "$baseUrl/poll?device=$device"
        val response = client.call(urlString) {
            method = HttpMethod.Get
        }.response
        val ret = response.readText()
        return ret
    }
}

class Server {
    private val log = LoggerFactory.getLogger(javaClass)

    private val server = embeddedServer(Netty, port = 8080) {
        routing {
            get("/poll") {
                val device = call.parameters["device"]
                log.info("$device: poll")
                call.respondText("$device polled")
            }
        }
    }

    fun start() {
        server.start(wait = true)
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            Server().start()
        }
    }
}
```

**Comment by eugeis** [comment]
[log-file.txt](https://github.com/ktorio/ktor/files/2865383/log-file.txt)

**Comment by eugeis** [comment]
14.02.2019 14:52:45.197+0100 INFO  [] [DevicePoller] [Memory] - used: 7 MB, committed: 30 MB, init: 64 MB, max: 64 MB
14.02.2019 14:53:15.194+0100 INFO  [] [DevicePoller] [Memory] - used: 11 MB, committed: 30 MB, init: 64 MB, max: 64 MB
14.02.2019 14:53:45.203+0100 INFO  [] [DevicePoller] [Memory] - used: 12 MB, committed: 30 MB, init: 64 MB, max: 64 MB
14.02.2019 14:54:15.202+0100 INFO  [] [DevicePoller] [Memory] - used: 14 MB, committed: 30 MB, init: 64 MB, max: 64 MB
14.02.2019 14:54:45.206+0100 INFO  [] [DevicePoller] [Memory] - used: 15 MB, committed: 30 MB, init: 64 MB, max: 64 MB
14.02.2019 14:55:15.206+0100 INFO  [] [DevicePoller] [Memory] - used: 17 MB, committed: 32 MB, init: 64 MB, max: 64 MB
14.02.2019 14:55:45.204+0100 INFO  [] [DevicePoller] [Memory] - used: 19 MB, committed: 34 MB, init: 64 MB, max: 64 MB
14.02.2019 14:56:15.212+0100 INFO  [] [DevicePoller] [Memory] - used: 20 MB, committed: 37 MB, init: 64 MB, max: 64 MB
14.02.2019 14:56:45.217+0100 INFO  [] [DevicePoller] [Memory] - used: 22 MB, committed: 40 MB, init: 64 MB, max: 64 MB
14.02.2019 14:57:15.200+0100 INFO  [] [DevicePoller] [Memory] - used: 24 MB, committed: 44 MB, init: 64 MB, max: 64 MB
14.02.2019 14:57:45.205+0100 INFO  [] [DevicePoller] [Memory] - used: 26 MB, committed: 45 MB, init: 64 MB, max: 64 MB
14.02.2019 14:58:15.207+0100 INFO  [] [DevicePoller] [Memory] - used: 27 MB, committed: 49 MB, init: 64 MB, max: 64 MB
14.02.2019 14:58:45.209+0100 INFO  [] [DevicePoller] [Memory] - used: 29 MB, committed: 52 MB, init: 64 MB, max: 64 MB
14.02.2019 14:59:15.220+0100 INFO  [] [DevicePoller] [Memory] - used: 31 MB, committed: 54 MB, init: 64 MB, max: 64 MB
14.02.2019 14:59:45.222+0100 INFO  [] [DevicePoller] [Memory] - used: 33 MB, committed: 59 MB, init: 64 MB, max: 64 MB
14.02.2019 15:00:15.229+0100 INFO  [] [DevicePoller] [Memory] - used: 34 MB, committed: 60 MB, init: 64 MB, max: 64 MB
14.02.2019 15:00:45.217+0100 INFO  [] [DevicePoller] [Memory] - used: 36 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:01:15.220+0100 INFO  [] [DevicePoller] [Memory] - used: 37 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:01:45.240+0100 INFO  [] [DevicePoller] [Memory] - used: 40 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:02:15.265+0100 INFO  [] [DevicePoller] [Memory] - used: 42 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:02:45.234+0100 INFO  [] [DevicePoller] [Memory] - used: 44 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:03:15.233+0100 INFO  [] [DevicePoller] [Memory] - used: 46 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:03:45.234+0100 INFO  [] [DevicePoller] [Memory] - used: 47 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:04:15.234+0100 INFO  [] [DevicePoller] [Memory] - used: 49 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:04:45.237+0100 INFO  [] [DevicePoller] [Memory] - used: 51 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:05:15.236+0100 INFO  [] [DevicePoller] [Memory] - used: 52 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:05:45.252+0100 INFO  [] [DevicePoller] [Memory] - used: 54 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:06:15.252+0100 INFO  [] [DevicePoller] [Memory] - used: 56 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:06:45.244+0100 INFO  [] [DevicePoller] [Memory] - used: 58 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:07:15.248+0100 INFO  [] [DevicePoller] [Memory] - used: 59 MB, committed: 64 MB, init: 64 MB, max: 64 MB
14.02.2019 15:07:45.374+0100 INFO  [] [DevicePoller] [Memory] - used: 61 MB, committed: 64 MB, init: 64 MB, max: 64 MB

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-Worker-ASYNCFILEINFO"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ktor-client-apache"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Memory"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ktor-client-apache"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncAppender-Worker-ASYNCFILE"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ktor-client-apache"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "DefaultDispatcher-worker-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "DevicePoller"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "DefaultDispatcher-worker-4"

**Comment by e5l** [comment]
Hi @eugeis, thanks for the report.
The `HttpResponse` class should be explicitly closed. Could you recheck it with the fix?

**Comment by eugeis** [comment]
Hi @e5l , thanks for fast response.
I changed the code like you suggested and it is fixed, thanks!

```
class Poller(private val baseUrl: String = "http://localhost:8080",
             private val client: HttpClient = HttpClient(Apache)) {

    suspend fun poll(device: String): String {
        val urlString = "$baseUrl/poll?device=$device"
        val call = client.call(urlString) {
            method = HttpMethod.Get
        }
        val ret = call.response.readText()
        call.close()
        return ret
    }
}
```

**Comment by e5l** [comment]
Resolved. Closed
