### ISSUE TITLE
Read entire HTTP response together

### ISSUE THREAD

**Issue by yzaoui** [ktorio/ktor#959]
### Ktor Version
1.1.2
### Ktor Engine Used
Apache client

Is there a way to get the entire raw response of a request? `HttpResponse` seems to offer a way to read the headers through `headers`, `status`, `version`, etc, and the body through `content`, but there doesn't seem to be a way to just get the entire response, without having to combine the individual properties. Even `readBytes()` only reads the content, which isn't implied by its name. 
What I'm looking for is the equivalent to `curl --include`, or IntelliJ's response when running standalone HTTP requests. I need the **exact** response from the server, character-for-character.
Thanks!

**Comment by e5l** [comment]
Hi @yzaoui, thanks for the report.
There is no way to access unparsed body bytes on any client.
HTTP is a text protocol, so if you want to read unparsed status line and headers you probably should open raw socket instead of using HTTP client(just as `curl --include` do).

**Comment by yzaoui** [comment]
Of course. I did end up going the socket route, but the HTTP client has a useful API that neatly organizes every part of the response into properties. I was hoping there was a way to get both of those in 1 request, the raw response for logging + the high-level object to actually use.
Thanks for your prompt response!

**Comment by OrangeDog** [comment]
The bigger benefit is having ktor construct the request for us, and then being able to pass the full response to another parser.
