### ISSUE TITLE
NativePRNGNonBlocking is not found, fallback to SHA1PRNG

### ISSUE THREAD

**Issue by PinkieSwirl** [ktorio/ktor#964]
### Ktor Version
1.1.2, 1.1.3
### Ktor Engine Used(client or server and name)
netty server
### JVM Version, Operating System and Relevant Context
JRE 11, Windows 10
### Feedback

I get the following warning:
```
io.ktor.util.random - NativePRNGNonBlocking is not found, fallback to SHA1PRNG
```
Is there anything I can do to fix that?

**Comment by PinkieSwirl** [comment]
I did some research and this `SecureRandom` instance is simply not available on windows.

A new option for all operating systems seems to be the DRBG-based implementations (http://openjdk.java.net/jeps/273), however these require java 9 or later.

Since I use java 11 I want to try it, but had no time yet.

But I guess it should be possible to use this new implementation through the system property that ktor checks, however it has some instantiation options (which I would like to change).

Another option would be to change the warning message to include the problem with windows.

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-668">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
