### ISSUE TITLE
ktor-client-jackson unused transitive dependencies on kotlinx-serialization

### ISSUE THREAD

**Issue by jvassbo** [ktorio/ktor#965]
### Ktor Version
1.1.2

### Ktor Engine Used(client or server and name)
`ktor-client-jackson`

### Feedback
`ktor-client-jackson` has (unused) transitive dependency on 2 kotlinx-serialization artifacts. 
From `mvn dependency:tree`:
```
+- io.ktor:ktor-client-jackson:jar:1.1.2:compile
|  +- io.ktor:ktor-client-json-jvm:jar:1.1.2:compile
|  |  +- org.jetbrains.kotlinx:kotlinx-serialization-runtime:jar:0.10.0:compile
|  |  \- org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:jar:0.10.0:compile
```

This causes build problems when using maven central as repository, as the kotlinx-serialization does not (yet?) exist there. Workaround is to exclude artifacts manually or add `https://kotlin.bintray.com/kotlinx` repository in addition to maven central.

Either way IMO these artifacts should not be transitive dependencies since they are unused.

**Comment by e5l** [comment]
Fixed in `master`.
