### ISSUE TITLE
Gradle Incompatability With Kotlinxserialization

### ISSUE THREAD

**Issue by MrThreepwood** [ktorio/ktor#966]
### Ktor Version
1.1.3
### Ktor Engine Used(client or server and name)
Client ios
### JVM Version, Operating System and Relevant Context
iOS
### Feedback
Currently with the ktor json feature, it appears I must enableFeaturePreview('GRADLE_METADATA')
in my gradle file in order to get the newest version (1.1.3). Unfortunately, the metadata for this publishing is v.4. This means that I cannot use gradle version 4.7. That's mostly fine, I can simply user gradle 4.10. Except that 4.10 does not support metadata of v.3 and the ktor json feature depends on kotlinx serialization 0.9, which publishes with metadata of v.3. I cannot figure out any way to get the dependencies to resolve for kotlin native at this time.

**Comment by e5l** [comment]
Hi @MrThreepwood, thanks for the report. 
We migrate to gradle 4.10 in our libraries, so you have to use gradle 4.10 if you want enable metadata.

**Comment by MrThreepwood** [comment]
It wasn't necessarily clear, are you saying you've upgraded your kotlinxserialization dependency to a version that is compatible with 4.10? If not, the problem is not resolvable by changing gradle version.

The problem is you can't use 4.10. Ktor requires 4.10, but gradle isn't backward compatible. Kotlinx serialization, a dependency of ktor, requires a version < 4.10. So Ktor requires at least 4.10, but it also requires that you be less than 4.10, making it unresolvable. 

If there's a way to import the libraries without enabling the meta feature I could try that, but I don't know how to write my imports to work without it as I get the error that gradle can't find the dependency without that feature on. I'm also having difficulty finding documentation on how to import libraries without that meta feature on when the library is using that feature themselves.

**Comment by e5l** [comment]
What version of serialization do you use?

**Comment by MrThreepwood** [comment]
I do not have kotlinx as a dependency directly, it is a dependency of Ktor's json feature.

**Comment by e5l** [comment]
Could you provide the error you've got?

**Comment by MrThreepwood** [comment]
Could not resolve all files for configuration 

```
':ios:klibsDebuglos_x64'
Could not resolve org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:0.9.0
Unsupported format version '0.3'
```

For some reason I can't copy from the xcode error window so I had to retype the pertinent bits. But long story short, ktor 1.1.3 depends on kotlinxserialization 0.9.0 which requires gradle 4.7. A newer version of kotlinxserialization might work, and I could likely just pull in a newer version manually, but ktor doesn't resolve on it's own.

**Comment by MrThreepwood** [comment]
I was assuming the kotlinx was related, but manually specifying a newer version of kotlinx removed that log. Looks like the io.ktor:ktor-client-json-ios:1.1.3 just can't be found. Seeing as I can't find the json feature documentation for native anymore, perhaps support has simply been dropped?

**Comment by MrThreepwood** [comment]
I just went ahead and closed the issue under the assumption that the Json feature does not support multiplatform at this time (makes sense, even the JVM feature is experimental) as I can't find any documentation for it anymore.
