### ISSUE TITLE
ALPN callback dropped: HTTP/2 is disabled

### ISSUE THREAD

**Issue by eiclu** [ktorio/ktor#967]
### Feedback

While running my app often this message appears in my log. I have not enabled HTTP/2 and also don't want to. How can I stop this message from appearing. It doesn't even adhere to Logback formatting.

```
okhttp3.internal.platform.Platform logINFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-667">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
