### ISSUE TITLE
Unable to register multiple lists 

### ISSUE THREAD

**Issue by santoshastagi** [ktorio/ktor#969]
### Feedback
While trying a post request as follows:
I get a list back from API call, so I have a kotlinxSerializer where I am registering two lists, as

val kotlinxSerializer = KotlinxSerializer()
kotlinxSerializer.register(FirstList.serializer().list)
kotlinxSerializer.register(SecondList.serializer().list)

However, when I make the call, only the last registered serializer is used. How can I register multiple lists to the serializer?

I tried:

kotlinxSerializer.registerList(FirstList.serializer())
kotlinxSerializer.registerList(SecondList.serializer())

too.

**Comment by jrocharodrigues** [comment]
I have the same problem.

**Comment by ScottPierce** [comment]
Is this going to be fixed for `1.2`?

**Comment by cy6erGn0m** [comment]
Unfortunately we can't fix it without [KT-28230](https://youtrack.jetbrains.com/issue/KT-28230) that is planned for 1.3.40.

**Comment by cy6erGn0m** [comment]
So the only solution is to get `ByteArray` and deserialize it manually using kotlinx.serialization API.

**Comment by ScottPierce** [comment]
@cy6erGn0m You could fix it with a `registerList` method, couldn't you? That method seems to already exist, it doesn't work though is the problem.

**Comment by ScottPierce** [comment]
@cy6erGn0m Could you provide an example of getting the byte array and deserializing it manually?

**Comment by santoshastagi** [comment]
@jrocharodrigues Sorry for the delayed response. One method is, you can write a wrapper and custom serializer for the the lists as described here: https://stackoverflow.com/a/54714777/4892045

**Comment by e5l** [comment]
Fixed with `typeOf` support in 1.3.0

**Comment by feresr** [comment]
@e5l could you expand a bit more on that? `typeOf` point to some docs perhaps? Thanks!
