### ISSUE TITLE
NetworkOnMainThread exception not thrown

### ISSUE THREAD

**Issue by feresr** [ktorio/ktor#973]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Default engine

### JVM Version, Operating System and Relevant Context
Android 

### Feedback
Thanks for the great library, this is not a bug but a question so I'll try to keep it short. I'm scheduling my http calls in the main thread like so:

```kotlin
@ImplicitReflectionSerializer
    suspend fun about(): List<Wallpaper> {
        return client.get { url("https://...") }
    }
```

And calling this method from a co-routine with the default `Main` dispatcher:

```kotlin

override val coroutineContext: CoroutineContext = Dispatchers.Main + job

@ImplicitReflectionSerializer
    fun downloadWallpapers() = launch(handler) {
            val w = vm.about()
            pushNewState(SUCCESS(w))
    }

```

I was expecting a `NetworkonMainThreadException` to occur in Android, but this was not the case, everything works as expected.

Might be related to https://github.com/ktorio/ktor/issues/764
It seems it was fixed but I still don't get why "not crashing" is the desired behaviour. 

Does ktor switches to a different thread for me? if so, should I worry about changing the dispatcher myself or can I just always use the main thread?

Thanks in advance

**Comment by e5l** [comment]
Hi @feresr, thanks for the question.
No, you shouldn't care about the dispatcher. The client selects the best one.
