### ISSUE TITLE
[WebSocket] 10x worse performance compared to OkHttp

### ISSUE THREAD

**Issue by avently** [ktorio/ktor#982]
### Ktor Version
1.2.0-SNAPSHOT ( build after commit https://github.com/ktorio/ktor/commit/ac90eb2e5c5e550ad26a09341d392d7fd608acaf)
### Ktor Engine Used(client or server and name)
OkHttp
### JVM Version, Operating System and Relevant Context
openjdk version "1.8.0_192", Manjaro (Linux)
### Feedback
I use Ktor with OkHttp engine for web sockets. I noticed that performance with Ktor and without Ktor (just OkHttp library) is so different. 
On test machine my Kotlin application (on JVM) uses <5% of one core of CPU with two web sockets with just OkHttp library. But with Ktor(OkHttp) CPU usage is 30-50% with the same configuration. I provided setup for both clients, you can just change what client you want to test.
Note that this provided percents of CPU is for my whole application, but web sockets use mostly all of the CPU power compared to other code of app.

As you will see, I even disabled parsing of the response from server in Ktor but parsing works in clean OkHttp (so Ktor in relaxing mode:) )

I hope you will find the source of the problem and will can reproduce it. 

The link with test classes:
https://gist.github.com/avently/7467164a6a926dfd25dc7607733edfc2

**Comment by e5l** [comment]
Hi @avently, thanks for the report. I'll try to investigate the problem.

**Comment by e5l** [comment]
Relates to:
https://github.com/Kotlin/kotlinx.coroutines/issues/1046

**Comment by avently** [comment]
@e5l , got another strange situation. Maybe it's related to my code, or to coroutines, or to ktor.
My app was running for about two days and then I checked heapdump in VisualVM.
VisualWM shows this info. As you can see, HttpClient on top of the list of allll classes. Only my custom implementation of it is higher (I didn't show it on screenshot because it just holds your HttpClient).
![screenshot-2019-03-25_165715_733689485](https://user-images.githubusercontent.com/7953703/54925808-f7f5f400-4f06-11e9-9ed8-efdd0ce9ffa4.png)

Tens of thousands objects related to coroutines. Is it something unusual:) Did you see something before or it's my fault somewhere?

Ktor was build from source, latest commit in local branch is https://github.com/ktorio/ktor/commit/453682ce1fbae2cab29bd1485eff365bf80e4306

I can create new issue if needed.

**Comment by e5l** [comment]
Workarounded in `master`.

**Comment by avently** [comment]
@e5l the issue is still unsolved. I updated all ktor libs to 1.2.0 from maven and checked CPU usage. It's still ~50-80% even without `frame.readText()`. Normal usage today is ~10-12% with plain OkHttp without Ktor.
Can you reproduce the problem?

**Comment by e5l** [comment]
Can you post the reproducer here?

**Comment by avently** [comment]
@e5l this is a sample project.

Run this command to use Ktor client with Okhttp as an engine:
```
./gradlew build runKtor
```
Check CPU usage.
Then second command to use plain Okhttp:
```
./gradlew build runOkhttp
```

You can also uncomment `println` inside `WebSocketClient.kt`  to ensure that the data is really the same. 
[sample.zip](https://github.com/ktorio/ktor/files/3223640/sample.zip)

**Comment by e5l** [comment]
Can you replace `CoroutineScope(Dispatchers.Default).launch { connect() }` with `client.launch { connect() }`?

**Comment by avently** [comment]
Checked multiple times, yes, now the result is the same. Where is the magic? Where is a bug?

**Comment by e5l** [comment]
The client is using a fixed thread pool now by default. 

The problem still here: https://github.com/Kotlin/kotlinx.coroutines/issues/1046

**Comment by avently** [comment]
Hm, I thought the problem was limited to GlobalScope() not CoroutineScope(). My bad. Thank you for your help, Leonid!
