### ISSUE TITLE
When returning a String, content negotiation is ignored

### ISSUE THREAD

**Issue by mjburghoffer** [ktorio/ktor#985]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Server - Jetty

### JVM Version, Operating System and Relevant Context
Azul 10, OSX / Debian Linux

### Feedback
Currently, when you respond with a string, even if you have a header of `Accept=application/json`, due to `fun ApplicationSendPipeline.installDefaultTransformations()`, `TextContent` is always returned.  This means you can't return a bare json string, ie `"foo"`.

The special case of `String` is handled here:

```kotlin
@KtorExperimentalAPI
fun PipelineContext<Any, ApplicationCall>.transformDefaultContent(value: Any): OutgoingContent? = when (value) {
    is OutgoingContent -> value
    is String -> {
        val contentType = call.defaultTextContentType(null)
        TextContent(value, contentType, null)
    }
    is ByteArray -> {
        ByteArrayContent(value)
    }
    is HttpStatusCode -> {
        HttpStatusCodeContent(value)
    }
    is URIFileContent -> {
        if (value.uri.scheme == "file")
            LocalFileContent(File(value.uri))
        else
            null
    }
    else -> null
}
```

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-662">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
You can use explicitly set `Content-Type` header to `application/json` and respond with a JSON:
```kt
val server = embeddedServer(Jetty, port = 7070) {
    routing {
        get("/") {
            call.respondText("\"foo\"", contentType = ContentType.Application.Json)
        }
    }
}
```
