### ISSUE TITLE
Duplicate code on CurlMultiApiHandler.kt ?

### ISSUE THREAD

**Issue by kikitux** [ktorio/ktor#987]
### Ktor Version
master

### Feedback
Is this code duplicate intentionally?

at ktor/ktor-client/ktor-client-curl/posix/src/io/ktor/client/engine/curl/internal/CurlMultiApiHandler.kt

https://github.com/ktorio/ktor/blob/06e3fdfd6f167294cf38df8005a53ca3a20eb135/ktor-client/ktor-client-curl/posix/src/io/ktor/client/engine/curl/internal/CurlMultiApiHandler.kt#L150-L162

Been looking at it, and I need to ask if thats intentional, if yes, as time permit, why?

Thanks!
Alvaro.

**Comment by e5l** [comment]
Hi @kikitux, thanks for the notice. The error message should be different.
