### ISSUE TITLE
SessionTransportTransformerEncrypt.kt throws java.security.InvalidAlgorithmParameterException: Wrong IV length: must be 16 bytes long when using AES 256

### ISSUE THREAD

**Issue by cyoderek** [ktorio/ktor#990]
### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Server

### JVM Version, Operating System and Relevant Context
Java 1.8.0_161, macOS Mojave (10.14.2)

### Feedback
When using AES 256 with `SessionTransportTransformerEncrypt.kt` it throws `java.security.InvalidAlgorithmParameterException: Wrong IV length: must be 16 bytes long`.

It appears that the IV generator uses the encoded key length which is 32 Bytes for AES 256, however, AES 256 requires a 16 byte IV.

Current work-around: 
```kotlin
transform(
    SessionTransportTransformerEncrypt(
        sessionSecretKey,
        sessionHmacKey,
        ivGenerator = {
            SecureRandom().generateSeed(16)
        }
    )
)
```

Proposed Solutions:
- Change the implementation to check if the key length is AES and greater than 16, default to 16
- Add a check in `init` block for AES 256 and check IV length prior to passing it to `encrypt` method. If IV length is greater than 16, throw an error that says user must provide their own IV Generator that generates a 16 byte IV when using AES 256.
- Add a comment to the class that warns users to provide their own ivGenerator if using AES 256.

Please let me know if you have any questions or if I missed something. 

Thanks for your help!

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-661">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by Stexxe** [comment]
Cannot reproduce using Ktor 1.6.1 and JDK 1.8.
