### ISSUE TITLE
Dead Link in Documentation for HttpRequestBuilder

### ISSUE THREAD

**Issue by Azoth128** [ktorio/ktor#991]
Ther's a dead link in the documentation.
https://ktor.io/clients/http-client/calls/requests.html#shortcut-methods

![grafik](https://user-images.githubusercontent.com/29049270/53654711-ad0df700-3c4e-11e9-962d-96bf2025d124.png)

**Comment by e5l** [comment]
Hi, @Azoth128. Could you reopen the issue here https://github.com/ktorio/ktorio.github.io ?

**Comment by e5l** [comment]
Fixed here `https://github.com/ktorio/ktorio.github.io/commit/20b820aa010cb7cccfd9f77315808e483e1732a3`
