### ISSUE TITLE
Ktor Client HTTP Cache

### ISSUE THREAD

**Issue by jrocharodrigues** [ktorio/ktor#992]
### Ktor Version
Ktor 1.1.3
### Ktor Engine Used(client or server and name)
Ktor Client iOS engine
### Feedback
I'm building a multi-platform (Android and iOS) kotlin project, using ktor client, and i want to have HTTP cache implemented.
For android i'm using the OKHTTP client, and configuring the Cache using the HttpConfig.

In iOS i was expecting to have the default caching policy, but in the code, https://github.com/ktorio/ktor/blob/0b3548afa30ff11d13c7496c0047465a6825682f/ktor-client/ktor-client-ios/darwin/src/io/ktor/client/engine/ios/IosClientEngine.kt#L86 it is being set to `NSURLRequestReloadIgnoringCacheData`

Since the config parameter in the constructor is currently not used for anything, is there other way i can change http cache policy for iOS?

Why is the cache being disabled on the iOS Client? Can it lead to problems?

Thanks in advance

**Comment by e5l** [comment]
Hi @jrocharodrigues, thanks for the report. 

We try to unify the client behavior with each engine. So we set `HttpCache` disabled by default.
Probably we should expose request configuration in engine config.

**Comment by davegough** [comment]
Hi @e5l has this fix been merged into master as I can't seem to see the changes. IosClientEngine.kt still seems to nativeRequest.setCachePolicy(NSURLRequestReloadIgnoringCacheData)
Which release is this fix available in?

**Comment by nikolaykasyanov** [comment]
To clarify, if I enable the `HttpCache` feature on iOS, would it do any caching or not?

**Comment by davegough** [comment]
@nikolaykasyanov I tried enabling HttpCache feature on iOS and I did not see any caching

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-660">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by jeanraymonddaher** [comment]
Hi ! 
Are there any updates regarding this ticket ?
I am also unable to enable caching for iOS.
Thanks

**Comment by Stexxe** [comment]
With the [HttpCache](https://api.ktor.io/1.5.1/io.ktor.client.features.cache/-http-cache/index.html) feature installed it works as expected on iOS:
```
GlobalScope.launch(Dispatchers.Main) {
    val client = HttpClient(Ios) {
        install(HttpCache)
    }

    client.get<HttpResponse>("https://httpbin.org/cache")
    client.get<HttpResponse>("https://httpbin.org/cache")
}
```
The sample project is attached [ios_cache.zip](https://github.com/ktorio/ktor/files/5931733/ios_cache.zip)

If you have a case where caching doesn't work as expected please describe it in the relevant [YouTrack issue](https://youtrack.jetbrains.com/issue/KTOR-660).

**Comment by e5l** [comment]
Closed

**Comment by rustamsmax** [comment]
But what about file caching. I tried to implement myself by I couldn't extend internal classes.
