### ISSUE TITLE
Js engine can't handle fetch response with undefined body

### ISSUE THREAD

**Issue by egoossens** [ktorio/ktor#996]
### Ktor Version
1.1.2

### Ktor Engine Used(client or server and name)
JsClientEngine

### JVM Version, Operating System and Relevant Context
React Native 0.56

### Feedback
I'm using the Ktor HTTP Client in a Kotlin Multiplatform project. The code is compiled to JS and packaged to be used as a Node package from a React Native app. 

React Native uses [the GitHub fetch polyfill](https://github.com/github/fetch) to expose the [Fetch API](https://facebook.github.io/react-native/docs/network), which is used by the JsClientEngine. However, as can be seen in [the source code](https://github.com/github/fetch/blob/master/fetch.js), the Response objects returned have no `body` property, which triggers the error `Fail to obtain native stream` [here](https://github.com/ktorio/ktor/blob/712e6119564c7cfb58529c9aaf64c554f1211a58/ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatible/browser/BrowserUtils.kt#L14). 

It seems the standard practice when using `fetch` in React Native is to use methods such as `.json()`, `.text()`, etc. to access the response body.

Is there a way to use these methods, instead of `ReadableStream` in the JsClientEngine that would be compatible with the rest of the API? A naive solution would be, when `resp.body` is null, to try and get the response as text and convert it to a `ByteReadChannel` to construct the `JsHttpResponse`. Would any problem arise from doing this?

Thanks for your help!

**Comment by e5l** [comment]
Fixed in `1.2.0`
