### ISSUE TITLE
ClassCastException when POSTing an object without explicitly setting a Content-Type

### ISSUE THREAD

**Issue by arnestockmans** [ktorio/ktor#997]
### Ktor Version

1.1.3

### Ktor Engine Used(client or server and name)

OkHttp with GsonSerializer

### JVM Version, Operating System and Relevant Context

Android 9.0

### Feedback

When I try to do a POST call with a body object, it gives me a ClassCastException:
```
java.lang.ClassCastException: be.gekrabbel.ktortest.MyCustomObject cannot be cast to io.ktor.client.call.HttpClientCall
        at io.ktor.client.HttpClient.execute(HttpClient.kt:151)
        at io.ktor.client.call.HttpClientCallKt.call(HttpClientCall.kt:80)
        at be.gekrabbel.ktortest.MainActivity.callDoesntWork(MainActivity.kt:63)
        at be.gekrabbel.ktortest.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:41)
```

It works if the body is a String instead of an object, and it also works after explicitly adding `contentType(ContentType.Application.Json)`.

Full sample app: https://github.com/Arne517/ktor-test/blob/master/app/src/main/java/be/gekrabbel/ktortest/MainActivity.kt

**Comment by Ribesg** [comment]
I have the same issue.

### Ktor Version
1.1.3

### Ktor Engine Used(client or server and name)
Android with KotlinxSerializer

### JVM Version, Operating System and Relevant Context
Android 8.0

### Feedback
Exact same issue, exact same fix working (thanks @Arne517).

My interceptors and `defaultRequest` also seem to be ignored but I need to investigate more on that.

**Comment by lamba92** [comment]
Even with @Arne517 advice I had to switch engine. Not a big matter but still bugged.

Ktor v1.1.3, plain JVM, Apache engine

**Comment by oleg-larshin** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/KTOR-659">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
